### ISSUE TITLE
Not finding any files

### ISSUE THREAD

**Issue by smartroad** [Rello/audioplayer#10]
I am so pleased to see this being maintained! So much better then the other MP3 player :grin: 

I have downloaded and got it installed on my owncloud service but when I click scan for new files it comes back empty. What have I got wrong?

**Comment by Rello** [comment]
Hold off for now. 
I think you got a version in the middle of the renaming from "audios" to "mp3_player". 
Wuite some files to change in sequence. 

I will respond later

**Comment by Rello** [comment]
if you loaded the current Master, it should work actually.
what file-types are you indexing/expecting?
anything in owncloud.log?

**Comment by Rello** [comment]
would you have time to support me with the testing of the new - rebranded version?
https://github.com/z000ao8q/audios/tree/rebranding

it should be possible to run it in parallel to the old one - but disabling the old version might be on the save side.

let me know & thank you!

**Comment by smartroad** [comment]
still getting the same problem, not finding any *.mp3 files. I removed the old tables from the MYSQL database just in case there was a conflict before I installed the new version, but nothing. It does come up briefly with 0/925 before saying finished with nothing found. I do have over 900 music tracks on my Owncloud install and they are visible/downloadable etc. Just that this app doesn't see them, weird :confused:

**Comment by Rello** [comment]
Strange!
- are the files local or external (e.g. SMB)?
- anything in owncloud.log?
- anything in php- or nginx/apache log?
- which OC Version?

**Comment by sbr9150** [comment]
branch:rebranding co-exsit with branch:master, cannot scan files. 
error log `{"reqId":"wKTtXWdPJZ0bOHK8xzkb","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE`oc_mp3_player_albums`SET`year`= ?,`genre_id`= ? WHERE`id`= ? AND`user_id`= ?' with params [\\\"\\\", 0, \\\"1\\\", \\\"sbr\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'year' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(174): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE`oc_mp3_...', Array)\n#2 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \\/var\\/www\\/html\\/owncloud\\/apps\\/mp3_player\\/controller\\/scannercontroller.php(641): OC_DB_StatementWrapper->execute(Array)\n#4 \\/var\\/www\\/html\\/owncloud\\/apps\\/mp3_player\\/controller\\/scannercontroller.php(509): OCA\\mp3_player\\Controller\\ScannerController->writeAlbumToDB('Various', '', 0)\n#5 [internal function]: OCA\\mp3_player\\Controller\\ScannerController->scanForAudios()\n#6 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\mp3_player\\Controller\\ScannerController), 'scanForAudios')\n#8 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\mp3_player\\Controller\\ScannerController), 'scanForAudios')\n#9 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/routing\\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/route\\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \\/var\\/www\\/html\\/owncloud\\/lib\\/base.php(882): OC\\Route\\Router->match('\\/apps\\/mp3_playe...')\n#13 \\/var\\/www\\/html\\/owncloud\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"July 12, 2016 20:14:36","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
disable branch:master, still cannot scan, same error.

**Comment by Rello** [comment]
Hello,
can you please get the modified scannercontroller from
https://github.com/z000ao8q/audios/blob/rebranding/controller/scannercontroller.php

and then set a config-parameter
`'mp3_player_debug' => true,`

this will enable a detail debugging for the first file to be scanned. please post the owncloud.log entries of 

> "app":"mp3_player","message":"mp3 detail

please also check the webserver-php log if there is anything.
thank you for your patience!

**Comment by sbr9150** [comment]
I git pull the new rebranding branch. I don't know how to post oc.log entries of "app":"mp3_player","message":"mp3 detail. so I just post the error messages which are 5 after I scan audio files.
`{"reqId":"l0idN9U6vft51NkUPTI8","remoteAddr":"::1","app":"PHP","message":"Undefined index: year at \/var\/www\/html\/owncloud\/apps\/mp3_player\/controller\/scannercontroller.php#499","level":3,"time":"July 14, 2016 19:01:51","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
`{"reqId":"l0idN9U6vft51NkUPTI8","remoteAddr":"::1","app":"PHP","message":"Undefined index: album at \/var\/www\/html\/owncloud\/apps\/mp3_player\/controller\/scannercontroller.php#500","level":3,"time":"July 14, 2016 19:01:51","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
`{"reqId":"l0idN9U6vft51NkUPTI8","remoteAddr":"::1","app":"PHP","message":"Undefined index: genre at \/var\/www\/html\/owncloud\/apps\/mp3_player\/controller\/scannercontroller.php#501","level":3,"time":"July 14, 2016 19:01:51","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
`{"reqId":"l0idN9U6vft51NkUPTI8","remoteAddr":"::1","app":"PHP","message":"Undefined index: artist at \/var\/www\/html\/owncloud\/apps\/mp3_player\/controller\/scannercontroller.php#502","level":3,"time":"July 14, 2016 19:01:51","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
`{"reqId":"l0idN9U6vft51NkUPTI8","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE`oc_mp3_player_albums`SET`year`= ?,`genre_id`= ? WHERE`id`= ? AND`user_id`= ?' with params [\\\"\\\", 0, \\\"4\\\", \\\"sbr\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'year' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(174): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE`oc_mp3_...', Array)\n#2 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \\/var\\/www\\/html\\/owncloud\\/apps\\/mp3_player\\/controller\\/scannercontroller.php(656): OC_DB_StatementWrapper->execute(Array)\n#4 \\/var\\/www\\/html\\/owncloud\\/apps\\/mp3_player\\/controller\\/scannercontroller.php(524): OCA\\mp3_player\\Controller\\ScannerController->writeAlbumToDB('Various', '', 0)\n#5 [internal function]: OCA\\mp3_player\\Controller\\ScannerController->scanForAudios()\n#6 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\mp3_player\\Controller\\ScannerController), 'scanForAudios')\n#8 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\mp3_player\\Controller\\ScannerController), 'scanForAudios')\n#9 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/appframework\\/routing\\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/route\\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \\/var\\/www\\/html\\/owncloud\\/lib\\/base.php(882): OC\\Route\\Router->match('\\/apps\\/mp3_playe...')\n#13 \\/var\\/www\\/html\\/owncloud\\/index.php(39): OC::handleRequest()\n#14 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"July 14, 2016 19:01:52","method":"POST","url":"\/owncloud\/index.php\/apps\/mp3_player\/scanforaudiofiles","user":"sbr"}`
There are no error messages in apache2 log.

**Comment by Rello** [comment]
Hello,

ok, 2 issues:
- your ID3 Tags are not recognized. either there is something wrong with the MP3-Files, or the library does not work in your case.
  can you check the log for the entry with "mp3 detail - track name:"? it should be the line before "Undefined index: year at "
  Do the ID3 tags show up correctly in iTunes or others?
- your database does not allow a NULL entry in the year column even so the table should be defined according to the setup.
  what Database are you using?
  are you able to insert a similar record manually into the DB?
  `INSERT INTO`owncloud`.`oc_mp3_player_albums`(`id`,`user_id`,`name`,`year`,`genre_id`,`cover`,`bgcolor`) VALUES (NULL, 'kind', NULL, NULL, NULL, NULL, NULL);`

let me know...

**Comment by sbr9150** [comment]
I found A audio file with error mp3 tag which is in the least expeted folder. I changed the file name. It can scan audio files now. Can we chose which folders we want to scan files rather than the whole database?

**Comment by Rello** [comment]
Hello,
Currently not - "music" app has this feature but it makes it so complex again. 
I will think about it. Perhaps a tag on a folder?
Lets see

**Comment by smartroad** [comment]
Apologies for the delay, I was having network issues with my owncloud box - turn out to be the network switch. So I downloaded the new scannercontroller.php and in the log I get:

`{"reqId":"zMjAspfdOUk58sNq+Obi","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Class 'OCA\\mp3_player\\Controller\\ScannerController' not found at \/var\/www\/owncloud\/apps\/mp3_player\/appinfo\/application.php#79","level":3`

**Comment by smartroad** [comment]
I tried using the 1.0 release and am having the same issue with it not finding any of the MP3s in my account :(

**Comment by Rello** [comment]
same as #14
