### ISSUE TITLE
use play count & popularitymeter and write to tag

### ISSUE THREAD

**Issue by john-2000** [Rello/audioplayer#103]
Hi

it would be great to also rate and play count tracks via their ID3v2 tag: [http://id3.org/id3v2.3.0](url) section 4.17 and 4.18 

this would allow a more complete online replacement of my music library 

thanks

**Comment by ghost** [comment]
Thanks for requesting this feature! There is not enough need for this feature at the moment.
We are looking forward to further feature requests.
