### ISSUE TITLE
Chrome CSS issue with only 1 title in album

### ISSUE THREAD

**Issue by andypl78** [Rello/audioplayer#104]
### Steps to reproduce the behavior
1. Install Nextcloud 11
2. Install plugin 1.4.0 or older
3. testing play on Chrome 55.0.2883.87 m (64-bit)

### Server configuration
**Operating system**:
Linux Debian Jessie

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.0.14

**ownCloud/Nextcloud version:** (see `/status.php`)
11.0.0

**Where did you install Audio Player from:**
Nextcloud App store

**Are you using encryption:** yes

### Client configuration
**Operating system:**
Win 10 14393.576

**Browser:**
Chrome 55.0.2883.87 m (64-bit)

#### Browser log (optional)
![nt3](https://cloud.githubusercontent.com/assets/7813646/21263337/7d93dc02-c396-11e6-8280-16f83f5d2f3c.jpg)

**Comment by Rello** [comment]
Hello,
thank you for reporting. I will search for the issue.

is it gone when you have more than 1 song for that album?

**Comment by NanoLook** [comment]
![image](https://cloud.githubusercontent.com/assets/15818381/21430398/bc6540f4-c86b-11e6-8e95-d13516b87091.png)
I thought I had one like that.
Chrome 53.0.2785.143

**Comment by rushsteve1** [comment]
@Rello I can confirm the bug exists, and that if there is more than one song in the album it does not happen.

Edit: This bug is also confirmed not to happen in Firefox 50.1.0.

**Comment by Rello** [comment]
finally, a fix is found for this issue
=> pending 1.4.1 release
