### ISSUE TITLE
Add support for Polish language

### ISSUE THREAD

**Issue by andypl78** [Rello/audioplayer#105]
As the topic

Regards

**Comment by Rello** [comment]
@andypl78 
my Polish skills are equal to 0.
could you help us?
basically its only about taking 2 files (de.js, de.json) and translating all the english words - and sending the file back.

the files can be found here:
https://github.com/Rello/audioplayer/tree/master/l10n

could you help?

**Comment by Rello** [comment]
@andypl78 
please let me know when you can support here.
without support i need to close this because we are not able to deliver this.

**Comment by Rello** [comment]
thank you @andypl78

**Comment by ghost** [comment]
@andypl78 May we ask again to complete and correct both files? We have changed some strings due to code changes. Thanks in advance!

**Comment by andypl78** [comment]
Done ;)

**Comment by ghost** [comment]
@andypl78 Thank you very much for your translation!
