### ISSUE TITLE
Scan new audio files not working with Audioplayer 1.3.x and 1.4.0

### ISSUE THREAD

**Issue by ummon29** [Rello/audioplayer#106]
### Expected behavior

"Scan new audio files" scans for new audiofiles. 

### Actual behavior

"Scan new audio files" doesn't work

### Steps to reproduce the behavior
1. Update to audioplayer >1.2.2
2. Click on the "Scan new audio files" Button
3. see log for Error (see ownCloud/Nextcloud log below)

### Possible solution (optional)

Downgrading to version 1.2.2 solves the problem.

### Server configuration
**Operating system**:

Raspbian (Jessie)

**Web server:**

nginx

**Database:**

mysql

**PHP version:**

5.6.28

**ownCloud/Nextcloud version:** (see `/status.php`)

ownCloud 8.2.9

**Updated from an older ownCloud/Nextcloud or fresh install:**

Updated from an older ownCloud

**Where did you install Audio Player from:**

From intrgrated Appstore and manually (Tried both).

**Are you using external storage, if yes which one:** `local/smb/sftp/...`

the owncloud data directory is mounted over nfs

**Are you using encryption:** yes/no

no

### Client configuration
**Operating system:**

Different ones (Win 10, Win 7, Linux)

**Browser:**

Recent Firefox 49.x and 50.x

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Error
index
Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCP\\L10N\\IFactory! Class can not be instantiated","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(106): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCP\\\\L10N\\\\IFacto...')\n#1 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(66): OC\\AppFramework\\Utility\\SimpleContainer->query('OCP\\\\L10N\\\\IFacto...')\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(85): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(106): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\audioplayer...')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\audioplayer...')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'getImportTpl', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(853): OC\\Route\\Router->match('\/apps\/audioplay...')\n#9 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":87} 
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
No Webserver Error log  found
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
No Browser Error log found
```
</details>

**Comment by Rello** [comment]
hello,
do you have any access to a newer OC-Version or are you planning on upgrading?
I can not find anything at the moment besides the remark in the API-Docu, that the iFactory class was enhanced with OC9.
if this would be the reason, we would add a min-version which I did not know of until now.

\OCP\L10N\IFactory was introduced in order to provide OCC scan capabilities

**Comment by ummon29** [comment]
Hello,
I plan to upgrade to a newer OC soon and audioplayer 1.2.2 is working fine for me at the moment. So no big problem for me.

Best Regards

**Comment by Rello** [comment]
Hello,
@ummon29 
thank you for your testing and sorry for the bad news: I installed a 8.2.9 and it is really the issue with iFactory from 9.0 that I am depending on.

the minimum version is changed in the info.xm. and in the app-store.

...happy to assist once you updated :-)
