### ISSUE TITLE
Cant Scan or reset

### ISSUE THREAD

**Issue by Bockwurst2** [Rello/audioplayer#107]
### Expected behavior
"Scan new audio files" scans for new audiofiles.

### Actual behavior
"Scan new audio files" doesn't work

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /www/owncloud/apps/audioplayer/appinfo/register_command.php on line 30

### Steps to reproduce the behavior
1. sudo -u www-data php occ audioplayer:scan --all

### Server configuration
**Operating system**:
Debian(Wheezy)

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
PHP 5.4.45-0+deb7u6 

**ownCloud/Nextcloud version:** (see `/status.php`)
ownCloud 9.1.3

**Updated from an older ownCloud/Nextcloud or fresh install:**
fresh

**Where did you install Audio Player from:**
From intrgrated Appstore 

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
yes local

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Win 10 / Win 7

**Browser:**
Firefox

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

Insert your webserver log here

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

Insert your browser log here

</details>

**Comment by Rello** [comment]
Hello,
thank you for the feedback.
It showed that AP is not available with PHP5.4 - I will update info.xml accordingly.

`::class` 
is introduced as of 5.5
http://php.net/manual/en/migration55.new-features.php
do you have any plans to upgrade? upcoming OC will also drop 5.4

**Comment by Bockwurst2** [comment]
Hallo Rello,
thank zou for the fast response.

I have plans to upgrade, but still have some dependencys to other programms that sadly use 5.4 :-(
