### ISSUE TITLE
allow to limit number of file requests

### ISSUE THREAD

**Issue by j-ed** [Rello/audioplayer#109]
## Expected behavior

It should be possible to limit the number of file requests during a directory scan to prevent heavy server load.

## Current behavior

If a directory scan has been requested the apps generates a heavy load in the webbrowser and also on a server which may cause problems with other applications. I've e.g. stored my audio files on an external drive which have been mounted via NFS and starting the file/directory scan within the audio player app 
are causing problems where the Linux server load increases or the network connection gets lost due to
the hight file scan activities.
All other file scan activities cause by Nextcloud are working without any problems.

### Steps to reproduce
1. Open the audio player app.
2. Start a file scan and monitor load on the server.

### Log files
No error messages can be found in the Nextcloud log file.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Audio Player version: 1.4.0

#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by Rello** [comment]
Hello @j-ed 
thank you for your comment. 
the ID3 process needs to load every audio file to extract the data.
if the data is mounted on an external storage, the file is copied into the local /tmp for being processed (and the tmp copy is removed afterwards).

This sets the Audio Player scanning speed to the limits of your webserver (php for processing the files) and the network (for delivering the files).
Luckily this will only occur once during a fill rescan. A workaround could be to plan this during off-times via OCC?

What would be your request? I can´t really think of something useful right now. Put in a delay-loop of x seconds after every file?
I think this would not be a proper solution because the Audio Player is expected to be as quick as possible and it would be a no-go for big libraries.

let me know your suggestions

**Comment by j-ed** [comment]
@Rello Wouldn't it be possible to allow to restrict the file scan to specific directory path? I would assume that this might reduce the risk of a heavy load condition a little bit. If you use the occ command to scan for Nextcloud files, you can add a file path but this is not possible if you use the `./occ audioplayer:scan` command.
Is there a special need for copying a file to a tmp directory instead of reading it directly from a remote share?

**Comment by Rello** [comment]
Hello,
Check the userdocu in git. You have the possibility to choose the scan folder in usersettings or exclude the folder with a .noaudio

The files need to be copied from external because its how NC/OC works here

**Comment by Rello** [comment]
By the way: AP only scanns valid mime types - not all of your files

**Comment by j-ed** [comment]
In my small environment around 160k file have been scanned by Nextcloud but only approximately 8k files are audio files. Nevertheless the generated traffic/load is enormously.

**Comment by Rello** [comment]
If you have all on external storage thats not optimal now. 
Problem is that getID3 needs the beginning of each file directly accessible.
One option would be to tweak xC&ID3 to work with streams. 
Second option would be to only transfer the first 500k of a file. 

Both options which i could not achieve yet. 
So for the moment you need to invest the little load. 
A rescan is only required with a major version change anyway. So for the moment a one-off...


Thank you...

**Comment by Rello** [comment]
@j-ed 
with the current setup I don´t have a chance to avoid that the complete file is transferred at least once during the scan.
So I can´t reduce the overall load right now.

what could be an option is to stretch the load by slowing down the scanner with e.g. a little delay between each song.
The scan would take significantly longer then - but the load would be more distributed and not at maximum all the time.

would this (quick fix) be something that would help you?
Or is only a reduction of the total MB transferred an option?

**Comment by j-ed** [comment]
@Rello I can give it a try if you will provide a modified app version or the code lines which need to be modified to me.

**Comment by j-ed** [comment]
@Rello After upgrading the app to v1.4.1 a heavy server load cannot be seen anymore, but a command line scan for new audio files on a SMB shares crashes regularly as described in the issue ticket https://github.com/Rello/audioplayer/issues/152 .

**Comment by ghost** [comment]
Version 1.5.0 brings significantly changes in handling this behavior, e.g. for big libraries. Please wait for the release or test the beta.
