### ISSUE TITLE
Add MPEG-4 MIME Types e.g. .m4a

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#11]
in Owncloud 9.0.2 & NextCloud 9.0.52, some mimetypes are missing.
add the following lines to :

> resources/config/mimetypemapping.dist.json

`"m4a": ["audio/mp4"],
"m4b": ["audio/m4b"],`

https://github.com/owncloud/core/commit/998da2acd37777c62091dc996d44241cb5f8cedd

**Comment by bassianotis** [comment]
Added the mimetypes and restarted nginx and php-fpm just to be save.  Not recognized in files browser or when re-indexing audioplayer.

**Comment by ghost** [comment]
@Rello: Don't edit the `/resources/config/mimetypemapping.dist.json`! Copy the file to `/config/mimetypemapping.json` and add the new MIME types.

**Comment by ghost** [comment]
@manisman: After adding the new MIME type(s) you have to update the database (MIME types and **existing files**) with OCC command `./occ maintenance:mimetype:update-db --repair-filecache` and the `mimetypelist.js` with command `./occ maintenance:mimetype:update-js`.

**Comment by bassianotis** [comment]
Very helpful @xraMsamohT .  Thanks.

Strange thing is that some m4a files display as audio tracks (and load into audio player), and some don't.  When I have some time I'll shoot to identify what the difference between the files is.

**Comment by ghost** [comment]
https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types

The formats `.m4a` and `.m4b` were added in ownCloud/Nextcloud 9.1.0.
