### ISSUE TITLE
Issues when sidebar open in Chrome

### ISSUE THREAD

**Issue by rushsteve1** [Rello/audioplayer#111]
### Expected behavior
When the left sidebar is open the slider should scrub the song to the location I clicked.
Also when the sidebar is open, the volume slider should change the volume.

### Actual behavior
The scrubbing works, but is offset to the right the width of the slider.
The volume controller does nothing when clicked, but sets the volume to 0 when right-clicked then clicked-away. I believe this may be issue #84. Right-click then clicking-away does the same thing with the sidebar closed as well.

### Steps to reproduce the behavior
1. Open Audio Player in chrome
2. Open sidebar and play song
3. Attempt to scan through song, or change volume

### Server configuration
**Operating system**:
Raspbian Lite 2016-11-25

**Web server:**
Apache 2

**Database:**
MariaDB

**PHP version:**
7.0.14-2

**ownCloud/Nextcloud version:** (see `/status.php`)
11.0.0

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh Install

**Audio Player version:** (see `/settings/apps`)
1.4.0

**Where did you install Audio Player from:**
Nextcloud App Store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
OpenSUSE Tumbleweed

**Browser:**
Google Chrome 53.0.2785.116 (64-bit)

I have confirmed this bug to not be present in Firefox 50.1.0 and Firefox Developer Edition 52.0a2 (2016-12-28) (64-bit)

#### ownCloud/Nextcloud log
None relevant, though will provide full logs if necessary (they are lengthy).

**Comment by Rello** [comment]
Hello,
thank you for the feedback. I could reproduce it and yes - there is something wrong with the offset of the sidebar.

when the sidebar is open and the progress-bar of the track is clicked, the bubble is moving with the offset of the sidebar
![screen shot 2017-01-03 at 22 21 44](https://cloud.githubusercontent.com/assets/13385119/21623535/23fe5732-d203-11e6-8b4e-e0026252c9bc.png)

**Comment by Rello** [comment]
@artemanufrij
as you supported already with an other pull, perhaps you could support here. any Idea on how to solve this css issue?

**Comment by ghost** [comment]
Want to add that this also happens with DPI Scaling or Zoom Level in Vivaldi. I have no sidebar open and slider has weird offset.

**Comment by artemanufrij** [comment]
@Rello sure... let me finish my #179 request :)

**Comment by artemanufrij** [comment]
@Rello Can you assign me this issue?

**Comment by artemanufrij** [comment]
@Rello 
1. Open Navigation Bar
2. Choose an element in the ComboBox
3. Click on any player control button (prev/play/next/volume/repeate/shuffel)
--> Selection (in the ComboBox) will be reseted... and the app throws an js 500 Error.

I guess it's an javascript bug.

![screenshot_20170504_192923](https://cloud.githubusercontent.com/assets/16517095/25716677/29ab825c-3100-11e7-86b2-b62e9b4cc41b.png)

**Comment by Rello** [comment]
somehow assignment does not work.
I will check the JS error. regarding the but itself it is reproducable (chrome) when trying the progress bar.

I think it is related to the combination of css position/display (absolute/relative; block/float) somehow

**Comment by Rello** [comment]
Hello @Faldon 
unfortunately the fix does not work :-(

by removing/adding 'full-width', you remove the` position=fixed`
This has 2 effects:
- the spacing between the the player and the playlists jumps
- when having the nav-bar open, and you have more than one page of files, the palybar scrolls out of sight. thats why `position fixed` is required

any other idea?

**Comment by Faldon** [comment]
Good morning @Rello,
I will fill my development environment with more music to look deeper into it. :-)
I guess there is more to adjust than the offset of the audios-audioscontainer.

**Comment by jancborchardt** [comment]
@artemanufrij @pixelipo @juliushaertl anyone of you has an idea here?

@Rello it might be because of your seemingly quite custom sidebar implementation. Like for example you hide it in the beginning, and you don’t use Snap.js as provided from core.

**Comment by Rello** [comment]
Hello,
I am using the "default" app-navigation but the idea is to hide it (with a `display: none !important`) in order to have a full-size player on demand. the show/hide status is stored in the user settings.

the issue is that I have to use the object `sm2-bar-ui` with the `position=fixed` to have it always on top of the `app-content`.

If I remove the `position` class, the "title-scroller" works correctly, but then it is scrolled out of the screen on long playlists.
When I put position in, it stays in place, but has the offset of the opened app-navigation-width.

any suggestion is welcome
thank you for looking at this

**Comment by juliusknorr** [comment]
@Rello I just had a quick look and it seems like the offset calculation (getOffX function) in bar-ui.js is always returning the same no matter if the sidebar is shown or not. 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent
> In compliance with the specification, this property will return null on Webkit if the element is hidden (the style.display of this element or any ancestor is "none") or if the style.position of the element itself is set to "fixed".

Maybe that might be the cause for your issue.

**Comment by Rello** [comment]
Issue was located; Testing in progress

**Comment by Rello** [comment]
Released with 2.2.2
