### ISSUE TITLE
Image as album cover not written to DB - just to file

### ISSUE THREAD

**Issue by artemanufrij** [Rello/audioplayer#113]
### Expected behavior
Edit a title -> Set album cover -> Save -> Done

### Actual behavior
Edit a title -> Set album cover -> Save -> Nothing happens

### Steps to reproduce the behavior
1. Open Edit Dialog
2. Set a cover
3. Choose "use as album cover"
4. Save

### Server configuration
**Operating system**:
Ubuntu Server 16.04

**Web server:**
Apache

**Database:**
SQLite

**PHP version:**
7

**ownCloud/Nextcloud version:** (see `/status.php`)
11 (Nextcoud)

**Updated from an older ownCloud/Nextcloud or fresh install:**
fresh install

**Audio Player version:** (see `/settings/apps`)
1.4.0

**Where did you install Audio Player from:**
'AppStore' (Nextcloud)

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Manjaro/Zorin/Solus

**Browser:**
Chrome / FireFox / IE11

**Comment by Rello** [comment]
Hello,
thank you for the feedback.
I had a look and there is a minor issue. Actually, the cover is written to the ID3-Tag of the file - but the display/database record is not updated correctly.

if you change a cover and would do a library reset&rescan, it would show.

I will have a look and fix it with the next release

**Comment by artemanufrij** [comment]
Hey Rello,

it works. But this takes a long time. I have > 1000 titles.

Maybe it would be useful to display "cover.jpg / Cover.jpg / folder.jpg / Folder.jpg" if the file exists.

**Comment by Rello** [comment]
hello,
as of 1.4.0 the cover/folder is being used during the scan when no ID3 image is found in the file.

for your issue: I will correct it, so the image is updated right away. does not make sense to trigger a rescan

**Comment by artemanufrij** [comment]
Thank you!

**Comment by Rello** [comment]
Hello,

fix is implemented and will be released with the next version.
an old, obsolete function call caused an error and so the cover was not stored into the DB

**Comment by artemanufrij** [comment]
Cool... Thank you! I use it every day
