### ISSUE TITLE
Auto play in Files app to next title

### ISSUE THREAD

**Issue by Huster-at-github** [Rello/audioplayer#115]
### Current situation
When playing a music title with app Files the playback stops after that file.

### Future situation
* Searching the next file in the list which is an audio file.
* Audioplayer will play that title ..... and so on.

### Features
* Automatic skip to the next audio file
* Zero time slot between 2 files   ;-)
* Endless repeat the hole file / audio list until stop is requested by user

**Comment by ghost** [comment]
To play all audio files in a folder use `Selection: Folders` in Audio Player and choose the desired folder.

**Comment by Huster-at-github** [comment]
No, this is not working for me:
* 32.000 audio files
* start of audioplayer app needs up to more minutes
* cannot direct jump to folders by Files Favorites

App Files is my main app inside Nextcloud and I want to use it as comfortable as I can. So I ask to reopen this issue.

**Comment by ghost** [comment]
No, after internal discussion we decided not to implement this or work on this enhancement in the near future. Sorry for this.
If we decide to work on it in the future, we will reopen the issue. See #39

**Comment by ghost** [comment]
@Huster-at-github The first scan of new files and the first start afterwards takes some time. But the selection of a playlist, an artist, a genre, or a folder will be remembered so the second start can be shortened. There's no need to start with the album view every time. So this may be a workaround until we have found and implemented a better and faster solution.

**Comment by Huster-at-github** [comment]
Half year ago [biosonic](https://apps.owncloud.com/usermanager/search.php?username=biosonic) developed exactly this function in [Folder Player](https://apps.owncloud.com/content/show.php?content=174740&forumpage=0). Perhaps he/she would like to participate your Audio Player project!?!?

:-)

**Comment by Huster-at-github** [comment]
Dear developers,

with your feature "One Click Play from Files app" you are still inside the Files App.

Why not change from "Exit" to "Play the next file"?   (y)    :)
