### ISSUE TITLE
Two column view - horizontal truncation issue for albums with 1 title

### ISSUE THREAD

**Issue by youphyun** [Rello/audioplayer#120]
### Expected behavior
Albums with just one song are displayed correct in Chrome and/or Opera

### Actual behavior
There is some strange truncation issue. The first column shows the upper part of the song title text and the 2nd column shows the lower part of the same song title. Note that I have not been able to reproduce this for albums with 2 or more songs,

### Steps to reproduce the behavior
1. Upload an album with just 1 m4a/mp3 file (single or incomplete album)
2. View the album in Nextcloud using Chrome and/or Opera.

### Possible solution (optional)
- Open the Nextcloud UI in Internet Explorer.
This leads me to the question: what is the preferred browser for Nextcloud and the audio player app?
Is there a specific browser that will always work best? 

### Server configuration
**Web server:** Apache 5.6.28
**Database:**  mysql
**PHP version:** 5.6.28
**ownCloud/Nextcloud version:** Nextcloud 11.0.0 (stable)
**Updated from an older ownCloud/Nextcloud or fresh install:** Updated from owncloud and since first nextCloud release
**Audio Player version:** 1.4.0
**Where did you install Audio Player from:** nextCloud release
**Are you using encryption:** yes (https)

### Client configuration
**Operating system:** Windows 8.1 with Opera

Repro in Chrome:
![000736_2017-01-16 20_10_06](https://cloud.githubusercontent.com/assets/12627719/21996351/20de9216-dc2a-11e6-9e40-1825e3e3d27f.png)

Repro in Opera:
![000737_2017-01-16 20_10_21](https://cloud.githubusercontent.com/assets/12627719/21996373/3a6e66ac-dc2a-11e6-82d2-d2b78f00d0d7.png)

Not Repro in IE (tried different zoom as well, all work fine):
![000738_2017-01-16 20_13_28](https://cloud.githubusercontent.com/assets/12627719/21996562/257417a0-dc2b-11e6-9575-a0702fa4ff38.png)

Some info from Inspect Element:
![000739_2017-01-16 20_17_26](https://cloud.githubusercontent.com/assets/12627719/21996418/70f5172a-dc2a-11e6-84dd-82243c282f7a.png)

**Comment by ghost** [comment]
> This leads me to the question: what is the preferred browser for Nextcloud and the audio player app?

RTFM! ;-)
https://github.com/rello/audioplayer#supported-browsers
https://github.com/rello/audioplayer/wiki/installation-instructions#known-issues

**Comment by xraMsamohT** [comment]
Duplicate of #104
