### ISSUE TITLE
Sorting of Selected List

### ISSUE THREAD

**Issue by SchoolGuy** [Rello/audioplayer#122]
Hi Rello,

I have some (well two) improvements to suggest. I would love to help, but my knowledge is limited to Android and Java.

1. Sorting ability in the filelist.
When opening a special artist, album, ... I would love to have the possibility to sort the playlist according to my needs.

~~2. Create playlists~~
When hearing my music I would love to have the ability to create a playlist with the songs I would like to hear. A suggestion from my point of view would be to export them to a folder the user specified when creating the playlist (as a file of course). I think this is clever, because you would not have to mess around with another database, you just need to read in another playlist like you are doing already.

Hope I was able to help you! Thx for your great work!
Regards, SchoolGuy

EDIT: Saw now your playlist feature. I would enjoy however an export function!

**Comment by Rello** [comment]
@SchoolGuy 
thanks for the Sorting-Part. makes sense. will put it on the roadmap.

but can you please explain why you would need the files which you include in a playlist being exported into a folder again? they are within your folder structure already and it would mean duplicating them.

let me know...

**Comment by SchoolGuy** [comment]
I would need the files e.g. when I sync my music to a computer and would like to execute the playlist (Is this the correct way in english to say this? I'm german.) in my media player (e.g. VLC, Windows Media Player, ...). When creating a playlist within your app I do not get a file for the playlist and so I won't get it also to work on my media player locally.

**Comment by ghost** [comment]
> When creating a playlist within your app I do not get a file for the playlist and so I won't get it also to work on my media player locally.

Playlists are app-specific and won't be saved as .m3u or .xspf files. They're not exportable.
External playlist support is not implemented yet, but on the roadmap. See #39 #31 

But you mixed up two different things in one issue. Please file one request in one issue.
Your first request is an alternate sorting of selected lists. Or do I have you misunderstood?

**Comment by Rello** [comment]
feature is implemented and will be part of the next 1.5 release

**Comment by SchoolGuy** [comment]
Thanks for implementing. Looks cool in nextcloud.
