### ISSUE TITLE
paging to album list

### ISSUE THREAD

**Issue by rseabra** [Rello/audioplayer#124]
### Expected behavior

A reasonably quick page load.

### Actual behavior

A slow page load, browser hangs for a little while.

### Steps to reproduce the behavior
1. have lots of music (I have 401 albums according to database)
2. go to audioplayer page

### Possible solution (optional)

Some sort of paging filter (for instance a [0-9 a-z] sort of filter ruler on top of the album listing page) would help tremendously.

**Comment by ghost** [comment]
@rseabra In the meantime, until we have a proper solution for the problem, you may set your own _start point_ in Audio Player. After the first start, scanning and listing of the full album view you may select a criteria from the left-handed selection. The selected view (playlist, artist, folder) will be remembered.

**Comment by rseabra** [comment]
Thanks. It helps a little :) It could also be useful to integrate with the search field in nextcloud as a search filter.

**Comment by Rello** [comment]
#130

**Comment by Deelight-fr** [comment]
Perhaps the most elegant solution would be to have the same behaviour as with the Gallery app: only load a few lines and add a few more each time the user reaches the end of the list.

**Comment by Rello** [comment]
Hello @rseabra 
I wanted to check back on your current status. with the last versions we did quite some performance tuning which should help a little.
Also the mentioned search field is working properly. 

The request for paging seems to be valid but would require some serious development on the Albums-View.
I think for bigger libraries like yours, the category filters will be more suitable

let me know if the current AP features are helping you here...

**Comment by FI5CHER** [comment]
Hi @Rello 

first : my THX to all developers ... cool App  🥇 .

I just did some test after your app scan's my music collection on my kodi server ( more then 100k songs via SMB ) .

From my point of view there is no other way then paging . As a first simple workaround it's maybe possible to just implement a counter in the "album view" program and "stop" after 100 albums. 

Also a really cool feature will be to have the nice "album view" after selecting an artist or genre . 

 .... but in any case ... stop or pause after 50-100 albums 😃

**Comment by Rello** [comment]
Hello @FI5CHER @rseabra 
the current beta has a pretty big rework of the js backend and the way the metadata is read in the Albums-View. 
Technically it was getting all titles for every album before. this is now changed to just the album names/covers and the details only on demand.

If you have a test-environment, I would be interested in a feedback on the current beta.
If not, we will inform you once the release is out.

**Comment by rseabra** [comment]
I don't have a test environment, but I'm eager to test the new release! Thanks a lot for letting us know, Rello! :)

**Comment by FI5CHER** [comment]
Hi @Rello , 

THX for the enhancements ! 

first i've to say it again ... i'm have with over :100: k mp3's not a usual mp3 collection size.

after changing the "php_value memory_limit" in .htaccess to  2048M and adding 
" ini_set('memory_limit', '2048M'); " 
to 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php

everything works perfect :+1: 

maybe you contact the developer of the db driver you use ... he should simply take the default memory_limit from nextclouds .htaccess

**Comment by Rello** [comment]
@rseabra @FI5CHER 
do you have an NC setup where you could test the current AP beta version?
we made a HUGE step forward. Cover-View for all and **BIG** UI  + scanner speedup

would like to hear some feedback from you guys with the big libraries if possible...

**Comment by rseabra** [comment]
Oh, that would be nice to try out! You'd like me to try a specific version or just git head? If it breaks how can I roll back, just restore a backup of the database and previous app version or is it fine to just reverse the app?

**Comment by Rello** [comment]
Hello,
Current git please. A lot of tuning in there. 
But no DB modification. An app rollback would be fine

Thank you!

**Comment by rseabra** [comment]
Cool, that makes it so much easier :) I'll try it out later on.

**Comment by Rello** [comment]
Hello,
I will close this issue for now as this is not on the roadmap anymore. the UI was made a lot quicker...
