### ISSUE TITLE
scanning external webDAV folders does not work

### ISSUE THREAD

**Issue by mtk64** [Rello/audioplayer#127]
### Expected behavior
Scanning of external storage should find files

### Actual behavior
Scanning does not find files

### Steps to reproduce the behavior
1. Mount external storage (Webdav) to folder mp3
2. select mp3 (double klick on path opens folder selection popup) for audio player start path 
(folders below are visible!)
3. Goto audio Player and start sync brings nothing found. 

made installation exactly from this: https://help.nextcloud.com/t/complete-nc-installation-on-debian-with-spreed-me-and-turn-step-by-step/2436

### Server configuration
**Operating system**:
Nextcloud 11.0
Debian jessie 3.16.39-1 (2016-12-30) x86_64
working as a virtual machine on XEN 6.5

**Web server:**
Apache2

**Database:**
Database Type: mysql
Version: 10.0.28
Size: 11.5 MB

**PHP version:**
PHP Version: 5.6.29
Memory Limit: 512.0 MB
Max Execution Time: 3600

**Nextcloud version:** (see `/status.php`)
version":"11.0.1.2","versionstring":"11.0.1

**Audio Player version:** (see `/settings/apps`)
1.4.0
**Where did you install Audio Player from:**
built in nc 11

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
WebDAV

**Are you using encryption:** yes

### Client configuration
**Operating system:**
Win 8.1

**Browser:**
Firefox

**Comment by Rello** [comment]
Hello,

did you start the filescan (via occ) or did you navigate inside the newly mapped folder at least once?
because Audio Player can only search what is known to Nextcloud. And new folders need to be indexed first.

did this happen?

**Comment by mtk64** [comment]
I tried both. Let me explain in detail.

1. Added a external WebDAV Folder in Webinterface of NC11.1, marker became green
2. Checked the existance of Folder in files app and found all folders and subfolders
(symbol showing as external Folder)
3. configured audio player start index folder
4. went to audio app and started scan
5. went into ssh /var/www/nectcloud/data/myname
checked folders files and files_external for existance of WEBDAV folder, but no external storage became visible there. seems to be managed in database only... I also tried ftp, but there is no NFS or smb support on nextcloud anymore for that.

On my OC9 its working with smb, allthough stopping indexing everytime somewhere in the middle, when there are too many mp3s or folders or what ever. but its working there.
at least i tried  

"**sudo -u www-data php /var/www/nextcloud/occ audioplayer:scan micha --debug"**

which did not work yesterday, but when writing this I checked that again and now the scanner is working!
But instead of taking the webdav folder, he is scanning an folder i connected via nfs to my nextcloud server and configured an external "local" folder within the webinterface. Lets see what happens.
will keep you updated.
 
kind regards

**Comment by Rello** [comment]
Hello,

correct - the mounts are handled by the application layer only. they are not visible in the data folder.

did you run a
`sudo -u www-data php occ files:scan --path="/micha/mp3"`
or so? because my assumption would still be, that the newly mapped folder was not completely indexed yet

let me know how it worked out

**Comment by mtk64** [comment]
no, just with user without path argument, means he will scan all folders in users directory.
Scan has finished successfully right now. 
But WebDAV was still ignored, that sync between filessystem and app layer information seems to be very slow :-(

**Comment by mtk64** [comment]
so here is my experience with that issue so far:
it seems htat external webDAV storage is provinding problems. A local mount via nfs (fstab) to /mnt/mp3 together with a external storage of type "local" on /mnt/mp3 is working well.

starting with a ` sudo -u www-data php /var/www/nextcloud/occ files:scan micha  -vvv` 
occ became notice of the new attached folders.
Remark: With webdav it was really slow, with nfs mount on local drive much faster.

Then a quick audio player scan: 
`sudo -u www-data php /var/www/nextcloud/occ audioplayer:scan micha --debug`

With a **external webdav storage** the result of a scan is none.
With a **external local storage** (nfs mount) the result is a complete scan with all subfolders.

**Comment by Rello** [comment]
Hello,
i was just testing with a WebDav connection and in fact there is an issue. it only randomly adds the files to the AP - one more every scan.

I assume it is a webdav issue because webdav is completely handled by application logic (e.g. when you call the webdav-url of NC/OC, its all done via php).
this is not a usefull setup because webdav has quite some slow performance - and during the scan process, every file needs to be transferred at least once temporarily.

I am not sure currently, if there is a fix at all and if WebDav can be supported at all

**Comment by mtk64** [comment]
so recommendation should be:
1. mount your mp3 library via nfs to server
2. use external storage of type "local" to connect to mp3 library

any better proposals?

**Comment by Rello** [comment]
Hello,
i personally use a SMB (from Nextcloud) mount to my Qnap where all audio files are on - this works.
your approach is to use a mount on OS level.

I try to think about advantage/disadvantage. the only thing I could think of is that going the Nextcloud way will produce more load because everything is handled via php application logic.
your approach is OS core.
might be interesting to do performance comparisons.

But thank you again for your feedback. we will add this to the know-issues.

**Comment by mtk64** [comment]
Made some performance comparison with dbench with nfs and cifs on my server, both performed on virtual machines. Fileserver is openMediaVault, running as a vm too.
cifs was mounted on os level, not via oc application level.
As expected nfs seems to be faster, also on os level (because of less overload)
If its is handled in addition via php application logic, it will not be faster ;-)

**NFS  Throughput 30.4514 MB/sec**

  **CIFS Throughput 19.5326 MB/sec**

Details: 

**NFS**
________
`dbench -D /mnt/mp3/ -t 10 2
dbench version 4.00 - Copyright Andrew Tridgell 1999-2004
Running for 10 seconds with load '/usr/share/dbench/client.txt' and minimum warmup 2 secs
0 of 2 processes prepared for launch   0 sec
2 of 2 processes prepared for launch   0 sec
releasing clients
   2       372    26.61 MB/sec  warmup   1 sec  latency 374.417 ms
   2      3960    34.34 MB/sec  execute   1 sec  latency 285.013 ms
   2      6874    31.59 MB/sec  execute   2 sec  latency 85.669 ms
   2      9437    28.78 MB/sec  execute   3 sec  latency 116.161 ms
   2     12108    30.24 MB/sec  execute   4 sec  latency 126.283 ms
   2     15262    30.59 MB/sec  execute   5 sec  latency 53.679 ms
   2     17903    30.79 MB/sec  execute   6 sec  latency 203.044 ms
   2     20536    29.92 MB/sec  execute   7 sec  latency 110.897 ms
   2     23336    29.60 MB/sec  execute   8 sec  latency 146.121 ms
   2     26327    30.45 MB/sec  execute   9 sec  latency 59.132 ms
   2  cleanup  10 sec
   0  cleanup  10 sec

 Operation      Count    AvgLat    MaxLat
 ----------------------------------------
 NTCreateX       9849     0.600   165.576
 Close           7241     0.480   146.110
 Rename           419     1.203     6.167
 Unlink          1985     1.757   203.033
 Qpathinfo       8962     0.184     3.100
 Qfileinfo       1555     0.928    53.673
 Qfsinfo         1635     0.203     0.916
 Sfileinfo        806     0.777    57.566
 Find            3443     0.429     1.718
 WriteX          4858     0.019     0.305
 ReadX          15440     0.009     1.181
 LockX             32     0.362     5.069
 UnlockX           32     0.216     0.314
 Flush            688     1.230     4.639

Throughput 30.4514 MB/sec  2 clients  2 procs  max_latency=285.013 ms
`
**CIFS** 
_________

` dbench -D /tmp/smb -t 10 2
dbench version 4.00 - Copyright Andrew Tridgell 1999-2004

Running for 10 seconds with load '/usr/share/dbench/client.txt' and minimum warmup 2 secs
0 of 2 processes prepared for launch   0 sec
2 of 2 processes prepared for launch   0 sec
releasing clients
   2      2131    54.22 MB/sec  warmup   1 sec  latency 31.595 ms
   2      5692    13.35 MB/sec  execute   1 sec  latency 31.703 ms
   2      7520    18.74 MB/sec  execute   2 sec  latency 4.796 ms
   2      9363    18.29 MB/sec  execute   3 sec  latency 12.913 ms
   2     11177    19.05 MB/sec  execute   4 sec  latency 3.490 ms
   2     12971    18.92 MB/sec  execute   5 sec  latency 30.667 ms
   2     14695    18.75 MB/sec  execute   6 sec  latency 15.071 ms
   2     16602    19.22 MB/sec  execute   7 sec  latency 16.273 ms
   2     18341    19.20 MB/sec  execute   8 sec  latency 3.196 ms
   2     20216    19.53 MB/sec  execute   9 sec  latency 16.284 ms
   2  cleanup  10 sec
   0  cleanup  10 sec

 
Operation      Count    AvgLat    MaxLat
 ----------------------------------------
 NTCreateX       6271     0.989    30.659
 Close           4605     0.523    15.063
 Rename           265     2.218    12.899
 Unlink          1272     1.084     3.733
 Qpathinfo       5680     0.576    10.491
 Qfileinfo        987     0.001     0.008
 Qfsinfo         1017     0.407     1.833
 Sfileinfo        534     0.486     1.765
 Find            2164     1.065    18.162
 WriteX          3077     0.017     0.577
 ReadX           9634     0.264    29.972
 LockX             20     0.398     0.511
 UnlockX           20     0.411     0.843
 Flush            452     0.811     2.846

Throughput 19.5326 MB/sec  2 clients  2 procs  max_latency=31.703 ms
`
