### ISSUE TITLE
wrong album artist shown when different track-artists available

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#13]
when scanning several files with different artists  - but of the same album - the last one is used as album artist.
in this case, the "Various" should be used

**Comment by Rello** [comment]
1st during scanner: 
- when an album-artist is maintained on a track, it is stored as album artist
- when no album-artist is maintained, the track-artist is stored as album artist

2nd during display:
- when all album-artists are the same, it is displayed in the Album display
- when there are different album-artists, "various" is displayed

**Comment by youphyun** [comment]
I am still able to repro this. I have two Artists with the same album named "Greatest Hits".
They did ended up in the same album in the web UI (the last artist in alphabetical order was used for the displayed cover art). I confirm both Artist + Album Artists fields do contain different names for these two albums. As a workaround I added the artist name between brackets to the 2nd Album name. Can this issue be re-opened?

**Comment by Rello** [comment]
The Album Artist is coming from ID3v2 TPE2 (band).
I can confirm your finding. not all combinations were caught correctly.

it is corrected now - part of next release
![screen shot 2017-03-17 at 06 31 16](https://cloud.githubusercontent.com/assets/13385119/24030117/294c0da4-0adb-11e7-84b9-0f7fb021f0a2.png)

@xraMsamohT
