### ISSUE TITLE
Preview controls/scrubber in Files app

### ISSUE THREAD

**Issue by bobapplemac** [Rello/audioplayer#131]
Hello,

I was wondering if it would be possible to implement a more detailed control bar for the files app when previewing a file (play/pause, scrubber to skip through the file, etc.)?

It could look identical to the top control bar in the Audio Player app, and simply show up at the bottom of the window in the files app while previewing a file (showing play/pause button, title, artist, album, time, and volume control)

Thanks!

**Comment by ghost** [comment]
After internal discussion we decided not to implement this or work on this enhancement in the near future. Sorry for this.
If we decide to work on it in the future, we will reopen the issue. See #39
