### ISSUE TITLE
Dynamically reduce high bitrate audio for playback over 3G

### ISSUE THREAD

**Issue by chris001** [Rello/audioplayer#134]
### Expected behavior
Audio should play, without disruptions for buffering, on all high speed internet connections, including 3G.

### Actual behavior
When playing high bitrate 192, 256, 320kpbs audio files, or flac/wav files, over 3G data connection, the audio often pauses to buffer, leading to a bad user experience.

### Steps to reproduce the behavior
1. Save some high bitrate 320kbps mp3, or flac, files to the owncloud server
2. Enable the Audioplayer.
3. Browse in the audio player, play the high bitrate audio file with Audioplayer over 3G data connection.
4. Experience unpleasant disruptions pauses and buffering, a bad user experience.  User expects smooth perfect stream like youtube soundcloud etc.

### Possible solution (optional)
Dynamically call a binary to decode the high bitrate mp3 and encode at reduced audio bitrate such as 128kbps or 64kbps, and stream that out to the web browser of the listener. This process will use some cpu yet is better than the alternative of totally unlistenable paused buffered choppy sounds.  The re-encoded mp3 files should be saved in a disk cache of size determined by a setting, or default to the minimum of 1GB or 10% of disk free space whichever is smaller.  The cache would eliminate cpu processing time for the next play.

### Server configuration
**Operating system**:
Debian 8 current

**Web server:**
Nginx current

**Database:**
MySQL current

**PHP version:**
7.0 current

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.4 stable

**Updated from an older ownCloud/Nextcloud or fresh install:**
Upgraded. Started with owncloud 6, 3 yrs ago, and upgraded regularly.

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
Installed inside owncloud on the apps page.

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Windows 10

**Browser:**
Firefox 52.0b2 (current).

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by Rello** [comment]
Hello @chris001 
thank you for your suggestion.
unfortunately I would not know how this could be achieved.

The Browser Audio API including our Soundmanager2 does not support this. To make it happen, we would need to implement a realtime (or batch) transcoding with e.g. ffmpeg.

This would be a completely new application and would create enormous efforts which can not be provided as part of AP.
Just think about rolling out a ffmpeg server inkl libraries for all possible server setups.

If anyone is willing to support here with a separate AP-Backand app, we are happy to share the backend. but for now I don´t see how this could happen.

Thank you
