### ISSUE TITLE
Legitmate mp3 filenames fail to playback

### ISSUE THREAD

**Issue by chris001** [Rello/audioplayer#135]
### Expected behavior
Play on any mp3 (or other supported audio file) and it plays in browser.

### Actual behavior
Some filenames with punctuation fail to play. It hangs at loading. You can click on another mp3 without the special characters and it'll play that one.

### Steps to reproduce the behavior
1.  Rename an mp3 file on your local machine to `(Artist name) Album name [1] First song (ABC remix).mp3`
2. Upload the file to owncloud
3. Go into Music audioplayer app.
4. Scan for new files.
5. Play the new file.
6. See it hang.

### Possible solution (optional)
Examine code.
See if it's treating special characters differently.
See if the code should quote or escape the filename characters before passing them to the process which opens the file and streams it to the browser.

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.4

**Updated from an older ownCloud/Nextcloud or fresh install:**
Installed 6 and upgraded regularly to current version.

**Audio Player version:** (see `/settings/apps`)
1.4.1 latest

**Where did you install Audio Player from:**
Inside owncloud on apps page

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Windows 10

**Browser:**
Firefox 52.0b3 latest

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by Rello** [comment]
Hello @chris001 
I can not reproduce your error. I uploaded a file with your suggested name.
the generated player-URL is perfectly escaped and the song is playing as expected.

can you please retry and see if you find any log in your browser console which could provide more insights?

`https://.../owncloud/apps/audioplayer/getaudiostream?file=%2F%28Artist%20name%29%20Album%20name%20%5B1%5D%20First%20song%20%28ABC%20remix%29.mp3`

**Comment by chris001** [comment]
@Rello 
My mistake, I reported this issue under your audioplayer app, when I should've reported it under the owncloud Music app.  So I reported it there now.  Sorry!  https://github.com/owncloud/music/issues/562

**Comment by chris001** [comment]
One more thing, I have 6100 music files on the nextcloud 11 (latest version) server.  Most are "shared files" uploaded by another person.  Audioplayer shows 54 audio files when it first starts.  The "scan for new audio files" is stuck at 0/6100   0%  for about 30 minutes.  Is it accurate to say this is a known bug?

**Comment by ghost** [comment]
@chris001 Don't mix different issues and open a new one, please.
It's a known problem with many possible causes. Please provide detailed information.
Have you tried a verbose [scan with occ](https://github.com/rello/audioplayer/wiki/occ-command-line) (debug option)?

**Comment by chris001** [comment]
Thanks @xraMsamohT new issue opened #150
