### ISSUE TITLE
Cannot update to 1.4.1

### ISSUE THREAD

**Issue by Huster-at-github** [Rello/audioplayer#136]
* ND 11.0.1
* Audioplayer 1.4.0

![bildschirmfoto vom 2017-02-04 16-04-18](https://cloud.githubusercontent.com/assets/3857906/22619392/1b61875c-eaf4-11e6-9d74-37605f991e4d.png)

Rights:

> root@owncloud:/var/www/nextcloud/apps# ll audioplayer/
> total 108
> drwxr-xr-x 14 www-data www-data  4096 Jan 19 22:08 ./
> drwxr-xr-x 57 www-data www-data  4096 Jan 24 10:56 ../
> drwxr-xr-x  3 www-data www-data  4096 Jan 19 22:08 3rdparty/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 appinfo/
> -rw-r--r--  1 www-data www-data   281 Jan 19 22:08 AUTHORS.md
> -rw-r--r--  1 www-data www-data  5529 Jan 19 22:08 CHANGELOG.md
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 command/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 controller/
> drwxr-xr-x  3 www-data www-data  4096 Jan 19 22:08 css/
> drwxr-xr-x  4 www-data www-data  4096 Jan 19 22:08 img/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 js/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 l10n/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 lib/
> -rw-r--r--  1 www-data www-data 34279 Jan 19 22:08 LICENSE.md
> -rw-r--r--  1 www-data www-data  3487 Jan 19 22:08 README.md
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 search/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 settings/
> drwxr-xr-x  2 www-data www-data  4096 Jan 19 22:08 templates/
>

**Comment by Rello** [comment]
hello,
you need to have something in the nextcloud.log

please post your error from there

**Comment by Huster-at-github** [comment]
Krass: I'm for sure not in the maintenance mode!     :-(

> Fatal	webdav	Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 System in maintenance mode.

    [internal function] OCA\DAV\Connector\Sabre\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

	2017-02-04T16:22:55+0100
Fatal	webdav	Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 System in maintenance mode.

    [internal function] OCA\DAV\Connector\Sabre\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

	2017-02-04T16:22:45+0100
Fatal	webdav	Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 System in maintenance mode.

    [internal function] OCA\DAV\Connector\Sabre\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

	2017-02-04T16:22:40+0100
Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2017-02-04T16:21:10+0100

**Comment by Rello** [comment]
your installation has some kind of issue - and its not Audio Player :-(

**Comment by Huster-at-github** [comment]
Yes. Created another issue: https://github.com/nextcloud/server/issues/3374
