### ISSUE TITLE
Not playing from shared subfolders

### ISSUE THREAD

**Issue by kknishev** [Rello/audioplayer#139]
### Expected behavior
Play audio files from shared subfolders.

### Actual behavior
Audio files (mp3) not playing from shared subfolders with permanent link:
SHARED_FOLDER\name.mp3 - OK
SHARED_FOLDER\folder\name.mp3 - NOK

From my admin account playing well in all case. But for users with shared link, playing from shared-root folder only. Help please.

### Steps to reproduce the behavior
1. 
2. 
3. 

### Server configuration
**Operating system**:
UBUNTU 16

**Web server:**
11.0.1

**Database:**
MSQL

**PHP version:**
7.0

**ownCloud/Nextcloud version:** (see `/status.php`)
NC 11.0.1

**Updated from an older ownCloud/Nextcloud or fresh install:**

**Audio Player version:** (see `/settings/apps`)
1.4.1 

**Where did you install Audio Player from:**

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Windows10

**Browser:**
all

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser error log
</summary>
JQMIGRATE: Migrate is installed, version 1.4.0
jquery-migrate.min.js (2,495)
Missing plural form in language file
_generatePluralFunction @ l10n.js:(99,4)
publicpreview.php Failed to load resource: the server responded with a status of 404 (Not Found)
5DOgoitEpeUdSUc:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
</details>

**Comment by Rello** [comment]
Hello,
issue is located.
the problem is that the subfolder is parsed with a "/" and this breaks the URL-scheme.

I will fix this...

https://.../owncloud/apps/audioplayer/getpublicaudiostreamSUBFOLDER/TITLE.mp3?token=vTKP1RJWNJXcG0d

**Comment by Rello** [comment]
the url scheme was corrected to a proper ?file= &token=

...next release.
thank you for reporting the finding!

**Comment by kknishev** [comment]
Thanks a lot.
Try to fix my NC (correct 3 files), at list only two browser playing good:
Chrome - OK
Opera - OK

Firefox - NOK
IE - NOK
EDGE - NOK
:(

**Comment by ghost** [comment]
We take a look at this. IE and Edge are not supported (see README.md and wiki).

**Comment by Rello** [comment]
@KKnishev can you send me the sharing link to audioplayer(at)scherello(dot)de for debugging?

Thank you

**Comment by kknishev** [comment]
Here it is:
https://nextcloud.kknishev.ru/index.php/s/5DOgoitEpeUdSUc

пн, 27 февр. 2017 г., 5:39 Rello <notifications@github.com>:

**Comment by Rello** [comment]
Hello @KKnishev 

I tested with FF 51.0.1 (64-Bit) and Chrome 56.0.2924.87 (64-bit) and the files in both folders are working for me.

do you have any error-code in FF?

**Comment by kknishev** [comment]
FF 51.0.1 (32-bit)

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
Missing plural form in language file  l10n.js:99:4
HTTP “Content-Type” of “text/html” is not supported. Load of media resource https://nextcloud.kknishev.ru/index.php/apps/audioplayer/getpublicaudiostream%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F%20%D0%9E%D0%A1%D0%98%D0%A1/2011%20%D0%A3%20%D1%81%D0%B0%D0%BC%D0%BE%D0%B3%D0%BE%20%D1%81%D0%B8%D0%BD%D0%B5%D0%B3%D0%BE%20%D0%BC%D0%BE%D1%80%D1%8F/00_00_Osis.mp3?token=5DOgoitEpeUdSUc failed.  5DOgoitEpeUdSUc
Cannot play media. No decoders for requested formats: text/html

**Comment by Rello** [comment]
Please clear the cache of FF

Ist is still using the old url from the old JS file

**Comment by kknishev** [comment]
Yep, thanks a lot, FF playing super good ;)
Is it anyways for IE/EDGE, in future may be?

**Comment by ghost** [comment]
@KKnishev Once again: We will not work on the compatibility with IE or Edge. Neither now nor in the near future!
