### ISSUE TITLE
Mobile Browser Support

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#141]
### Expected behavior
The documentation doesn't explicitly state if mobile versions of firefox, chrome, safari are supported.
I tested on Linux with firefox and chrome works great on desktop browser. Tested Safari on os x el capitan (desktop / macbook) works great.

On iOS firefox, chrome, safari assumed to work.
Play music from album after pressing / clicking play

### Actual behavior
Pressing play (iOS) in all three browsers (firefox, chrome, safari) simply advances the play cursor (next arrow) through each song without stopping to play music. The advancement stops after the end of list is reached without any songs played.

### Steps to reproduce the behavior
1. Login to web interface of nextcloud (not the iOS client app) on iOS device.
2. Show the albums
3. Tap album to show songs
4. Press play button at top of album listing (or press play on first song)
Note: Javascript is "enabled" on iOS devices (both ipad and iphone)

### Server configuration
**Operating system**: 
Debian 8.6 Linux Kernel 3.16.04-amd64 

**Web server:**
Apache 2 

**Database:**
PostgreSQL 9.4.9

**PHP version:**
Version: 5.6.27

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 11.0.1 (stable)

**Updated from an older ownCloud/Nextcloud or fresh install:**
Updated from Nextcloud 9 to 10, then upgraded to 11
Note: Audio play was not added until after the upgrade to 11.

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
App Store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
 iOS 10.2.1

**Browser:**
iOS Firefox, iOS Chrome, iOS Safari

**Comment by Rello** [comment]
Hello,
it should work - I used it on my iPad with standard Safari.
I will check and let you know

**Comment by Rello** [comment]
Hello,
I sometimes have these kind of issues on my various test-PIs when the certificate is not clean (e.g. URLs don´t match because its a cloned instance).

The desktop browsers are more flexible and habe the "always trust" option to overwrite. its not that simple in iOS.
Could this potentially apply to your setup?

**Comment by ghost** [comment]
I can confirm this with version 1.4.1 and Samsung Browser. The problem is fixed with version 1.5.0-beta.2, which can be tested.

**Comment by ghost** [comment]
During the tests of the beta version I had the behavior again. Clearing the browser cache solved the problem.
