### ISSUE TITLE
MP3 Tag Edit

### ISSUE THREAD

**Issue by Jano69** [Rello/audioplayer#142]
Hi Rollo,

wenn ich einen MP3 TAG editiere, dann klappt das Abspeichern auch wunderbar.
Doch leider wird danach das MP3 Stück nur 20 sekunden abgespielt und bricht ab.
Danach wird der nächste Titel des Albums abgespielt.

Alles andere funktioniert Perfekt. Irgendwie eine Idee woran es liegen könnte?

**Comment by ghost** [comment]
Thanks for reporting this issue! Please fill in the [issue template](https://github.com/rello/audioplayer/blob/master/.github/ISSUE_TEMPLATE.md) as complete as possible.

**Comment by Rello** [comment]
Hello,
was tested locally and no issue was found.
please report back with the issue template (especially the log files) if the error comes up again.

thank you

**Comment by ghost** [comment]
I asked him for details more than a week ago but no response, unfortunately.
