### ISSUE TITLE
Dokumentation OCC Kommandos Fehlerhaft!

### ISSUE THREAD

**Issue by Jano69** [Rello/audioplayer#143]
Folgender Befehl funktioniert nicht, da er anscheinend falsch dokumentiert ist.

Laut Doku für ein Scan ALL Users schreibst Du:
sudo -u www-data php occ audioplayer:scan all

Das gibt dann aber folgenden Error: User all does not exist

Es müsste doch richtig lauten:
sudo -u www-data php occ audioplayer:scan --all

oder ?

**Comment by ghost** [comment]
It was a c&p error in the examples and my fault. The description of the commands above the examples was/is correct.
Thanks for reporting.
