### ISSUE TITLE
Separate scrolling for app-navigation & app-content

### ISSUE THREAD

**Issue by Deelight-fr** [Rello/audioplayer#144]
### Expected behavior
For example, when the artist list is displayed in the app-navigation section (left side of the window) and when that list is a few screens long, clicking on a artist name down in the list loads the corresponding tracks in the app-content section (right side of the window). We should immediately see the beginning of the tracks listing without any scrolling.

### Actual behavior
You have to scroll back to the top of the windows to see the tracks corresponding to the artist which was selected.

### Steps to reproduce the behavior
1. Select "Artists" from the dropdown menu
2. Click on an artist at the end of the list
3. Scroll back to the top of the window to see the corresponding tracks

### Possible solution (optional)
Have separate vertical scrollbars for the app-navigation and the app-content sections. This can probably be done with CSS.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.0.29

**PHP version:**
PHP 7.0.13

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 11.0.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh install

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
Apps menu

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
HTTPS

### Client configuration
**Operating system:**
Ubuntu 16.04

**Browser:**
Chrome  56.0.2924.87

**Comment by xraMsamohT** [comment]
See #39  It's already on the roadmap.

**Comment by Rello** [comment]
Hello,
Correct, this definately makes sense. 
Should be simple task for a CSS Pro. Any volunteers? ;-)

**Comment by ghost** [comment]
> Should be simple task for a CSS Pro.

@Rello You're the Pro! Absolutely! 👍
