### ISSUE TITLE
Scan stuck due to artist field being too long

### ISSUE THREAD

**Issue by kudev** [Rello/audioplayer#145]
I am trying to scan my files. One of these files is an MP3 with an artist field that's around 300 characters.

### Expected behavior
The file is scanned without any issues.

### Actual behavior
The scan simply hangs indefinitely. Checking the nextcloud logs revealed that the column's length is limited to 256 in the database.

### Steps to reproduce the behavior
1. Have a song with an artist field longer than 256 characters
2. Try to scan it

### Possible solution (optional)
Basic ideas:
- Remove character limit
- Trim artist
- Handle the error so the user can react

### Server configuration
**Operating system**:
Linux

**Web server:**
Nginx

**Database:**
PostgreSQL 9.6.1

**PHP version:**
7.1.2

**ownCloud/Nextcloud version:** (see `/status.php`)
11.0.1.2

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh install

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
The NextCloud apps page

**Are you using external storage, if yes which one:** `local`

**Are you using encryption:** no

### Client configuration
**Operating system:**
Linux

**Browser:**
Firefox 51

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_audioplayer_artists" ("user_id","name") SELECT ?,? FROM "oc_audioplayer_artists" WHERE "user_id" = ? AND "name" = ? HAVING COUNT(*) = 0' with params ["ori", "<Really long artist name here>"]: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(256)
```

</details>

**Comment by Rello** [comment]
scanner was adjusted

- values for year & tracknumber are normalized to a positive integer
- strings for e.g. titles, artist, genre are truncated to DB size

#137
