### ISSUE TITLE
Show Progress and Control Buttons in Files app

### ISSUE THREAD

**Issue by Huster-at-github** [Rello/audioplayer#147]
I have tons of internet radio recordings, some up to 5 hours per "track".

When browsing through that stuff with Files App (Audio Player is too slow) it would be great not only to play a track.

So I friendly ask for this enhancement:

Open **Progress and Control Buttons View** on top when playing from **Files App**.

**Comment by xraMsamohT** [comment]
Duplicate of #131

**Comment by xraMsamohT** [comment]
Duplicate of #131
