### ISSUE TITLE
Scan for audio files hangs at 0/6100.

### ISSUE THREAD

**Issue by chris001** [Rello/audioplayer#150]
### Expected behavior
Scan should increment the counter maybe 1 per second until it reads the necessary data from each audio file's mp3 id3 tags etc.

### Actual behavior
Audioplayer shows 54 audio files when it first starts. The "scan for new audio files" is stuck at 0/6100 0% for about 30 minutes.

### Steps to reproduce the behavior
1. Upload 6100 files to owncloud 9 using sqlite, then upgrade to mysql database when it recommends your to upgrade because number of files is large.  Then upgrade to Nextcloud 11, to try some other new apps on nextcloud app store.
2. Go into the Audioplayer app.  See it is showing only 54 audio files.
3. Scan for new audio files.  Stuck at 0/6100 for 30 minutes.
4. Note,  Most of the audio files are "shared files" uploaded by another person onto their own account, if this is possible a factor in the hang at 0/6100.

### Server configuration
**Operating system**:
Linux Debian 8

**Web server:**
Nginx latest version.

**Database:**
Mysql from debian 9 distro

**PHP version:**
PHP 7.0 latest

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 11.0.1.2 latest

**Updated from an older ownCloud/Nextcloud or fresh install:**
Upgraded starting with owncloud 6, 7, 8, 9, to nextcloud 11.

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
From owncloud app store, the upgraded from nextcloud app store.

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Windows 10

**Browser:**
Firefox latest 52.0b9

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

#### OCC SHELL COMMAND OUPUT
<details>
<summary> output from running an occ command</summary>

```
# sudo -u www-data php occ audioplayer:scan chris --debug
Start scan for chris
Scanned Folder: /chris/files
Total audio files: 6154
Checking all files whether they can be skipped
   7 - /chris/files/music/projektava-bozotrain.mp3  => already indexed
   92 - /chris/files//Shared/music/Devil_Whole_-True_Butts/Devil Whole - 01 - A Bad
Day to Live.mp3  => already indexed

(.... the 54 files which it says it has already indexed ...)

Final audio files to be processed: 6100
Start processing of ID3s
   /chris/files//Shared/music/Music Folder X/Red Storm Top - Imagination Waits For No One/earthlanguage - Imagination Waits For No One - 01 Fairytale.mp3

  [OCP\Files\NotPermittedException]

```

</details>

**Comment by chris001** [comment]
Added: occ shell command output.

```

# sudo -u www-data php occ audioplayer:scan chris --debug
Start scan for chris
Scanned Folder: /chris/files
Total audio files: 6154
Checking all files whether they can be skipped
   7 - /chris/files/music/projektava-bozotrain.mp3  => already indexed
   92 - /chris/files//Shared/music/Devil_Whole_-True_Butts/Devil Whole - 01 - A Bad
Day to Live.mp3  => already indexed

(.... the 54 files which it says it has already indexed ...)

Final audio files to be processed: 6100
Start processing of ID3s
   /chris/files//Shared/music/Music Folder X/Red Storm Top - Imagination Waits For No One/earthlanguage - Imagination Waits For No One - 01 Fairytale.mp3

  [OCP\Files\NotPermittedException]

```

**Comment by Rello** [comment]
@chris001
Can you tell me whar occ is showing below this NotPermitted? Is there another line?

In general sharing is not an issue - my whole setup is based on this. Also at least one file is working above already. 
Could there be an authorization issue in the one folder?

Let me know

**Comment by chris001** [comment]
```
  [OCP\Files\NotPermittedException]

audioplayer:scan [--all] [--debug] [--] [<user_id>]...
```
It seems my "Shared" folder is empty.  I'm not sharing any files.   Isn't the "Shared" supposed to represent files shared by others?

**Comment by ghost** [comment]
@chris001 Files and folders shared by other users of your cloud are located in the folder that is defined in `config.php`.
```
/**
 * Define a default folder for shared files and folders other than root.
 */
'share_folder' => '/Shared',
```
Without this option in the config file, `/` (root) is used.

**Comment by chris001** [comment]
That option `share_folder` is missing from `/var/www/owncloud/config/config.php`.
Is it because it was updated from owncloud to nextcloud?
First time running into this missing optoin in the config file.

**Comment by ghost** [comment]
@chris001 This setting is optional. I don't remember if this was a default setting in old versions or not.
As I wrote above, without this setting all incoming shared files and folders are located in the root folder. This setting is for all users of your cloud instance and cannot be overridden in the personal settings.

https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-configuration-options

**Comment by chris001** [comment]
Sorry if this is a dumb question: How is the sharing implemented, when a user on the cloud shares a file with you? Does the cloud create a new symlink, in your `Shared` folder, to the real file in their `data/files` folder?

**Comment by Rello** [comment]
Hello,
The origin user has a folder calles "shared" with all the files in there. 
Now he shared the folder with you and you will see "shared" with the same name in you root directory. 

No files are copied or symlinked. They are "mapped" in NC via the *share* tables. 

But in your case: 
in the files app can you navigate to the files with the error (...Red Storm...) and see if you can open or play it from the files app?

There seems to be some access right issue and I cant imagine how AP would cause this

Another try is to trigger a occ file:scan for your user to clean up the filecache table.

**Comment by ghost** [comment]
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#file-operations-label

**Comment by chris001** [comment]
```
# sudo -u www-data php occ file:scan chris
# sudo -u www-data php occ audioplayer:scan chris --debug
```
@Rello @xraMsamohT 
These two commands seem to have done the trick.
The first command completed, now the 2nd command is still running, steadily going thru the 6100 audio files.
It would be good to update audioplayer to detect this state and either tell the user an error message to run the command line, or better, just automatically run the command line to do the `occ file:scan` and automatically fix the data itself without any user intervention, because most users cannot login to the shell to run the command anyway.

**Comment by Rello** [comment]
Hello,
thats not really an option for an application. We have to assume that the server is running correctly and rely on its data. 
Also a web app can not trigger an occ command. thats 2 different worlds (on purpose).

I don´t know what caused your inconsistencies - issues during the upgrade; broken cron; broken setup; I cant tell

but good that its working now.

**Comment by chris001** [comment]
OK but is there no way at all for the scanner to detect that it's hanging probably due to bad data and notify the user with an alert box that they might want to run a scan especially if their system has experienced major changes recently such as an upgrade or migration.

**Comment by Blisk** [comment]
Today I scanned files and have the same problem. Is this still not solved???
After I did occ file:scan, than scaning files in audioplayer still doesn't work.
It is stuck on some file
