### ISSUE TITLE
command-line scan crashes on SMB shares

### ISSUE THREAD

**Issue by j-ed** [Rello/audioplayer#152]
## Expected behavior
I should be possible to scan for new audio files on e.g. an SMB share from the command line without running into any exception.

## Current behavior
It isn't possible to scan for new audio files on a SMB share without running into an exception after exactly 198 scanned files.
```
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"proc_open(): unable to create pipe Too many open files at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#58","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"include(\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/ConnectionException.php): failed to open stream: Too many open files at \/var\/www\/htdocs\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#440","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"include(): Failed opening '\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/ConnectionException.php' for inclusion (include_path='\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/console_getopt:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/pear_exception:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/archive_tar:\/var\/www\/htdocs\/nextcloud\/apps:\/var\/www\/htdocs\/nextcloud\/apps2:\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src') at \/var\/www\/htdocs\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#440","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
PHP Fatal error:  Class 'Icewind\SMB\Exception\ConnectionException' not found in /var/www/htdocs/nextcloud/apps/files_external/3rdparty/icewind/smb/src/RawConnection.php on line 60
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"Class 'Icewind\\SMB\\Exception\\ConnectionException' not found at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#60","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
```
After this exception is is possible to re-initiate the scan process. Usually the number of unscanned files
will be displayed at the beginning, which shows that it crashes exactly after the same number of scanned files.
```
Final audio files to be processed: 2730
...
Final audio files to be processed: 2532
...
Final audio files to be processed: 2334
...
```
After the crash an instance of the smbclient program is still running and an additional instance will
be started each time the scan process is initiated again. Right after the running instances of the smbclient program have been killed manually the server load returns to normal.

### Steps to reproduce
1. Open a console window and switch to the user under which the web server is running.
2. Start a file scan by executing the following command: `./occ audioplayer:scan --debug <user>`

#### Server Configuration
OS: Linux 3.2.84
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 11.0.2
Audio Player version: 1.4.1

#### Client Configuration
Browser: Mozilla Firefox 51.0.1
Operating system: Windows 7

**Comment by ghost** [comment]
This is not an Audio Player problem. `/apps/files_external/3rdparty/icewind/smb`
Please report a bug in the [appropriate bug tracker](https://github.com/nextcloud/server/issues). Thanks.

**Comment by Rello** [comment]
Hello,
just as an idea, I had positive experience with using a separate php-library.
If I remember correctly, I used it additionally (because the smbclient is used for other stuff also)

https://github.com/Rello/audioplayer/issues/7

**Comment by Rello** [comment]
@j-ed 
another idea: can you check the server/php logs? the exact repeating number sounds really strange.
perhaps some kind of timeout or memory issue in php?

**Comment by j-ed** [comment]
@Rello FYI, the memory limit for the command line php binary is currently set to **128M** which should be sufficient.
Unfortunately I couldn't find any logged memory error etc. in the apache2 log file. As far as I understood an audio file is copied to a local cache directory to read the MP3 header. After that activity has been finished I would expect that all allocated resources are freed again.
Due to the fact that a `failed to open stream: Too many open files` is shown it might be possible that a problem exists in the used icewind/smb library which might not release allocated resources after some tasks have been executed.

**Comment by Rello** [comment]
Hello,
Do you have a possibility to test the current beta of AP from GIT locally?
We changed the scanner so no files need to be copied anymore to tempFile. 

Perhaps this resoves the issue?

**Comment by j-ed** [comment]
@Rello Today, I've installed a current snapshot from GIT but it turned the result to the worse. If the scan process is started from the command line the files cannot be read and the following errors are displayed, although the mentioned audio file can be accessed via the Files app and played from the GUI without any problem (FYI: `/Musik_Familie` represents the mounted SMB share).
```
..."app":"PHP","message":"fseek(): stream does not support seeking at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","level":3,"time":"2017-03-02 10:28:33+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
..."app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/carmen\/files\/\/Musik_Familie\/Vaya Con Dios\/Vaya Con Dios\/04-Vaya Con Dios - Lay Your Hands.mp3","level":0,"time":"2017-03-02 10:28:33+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
```

**Comment by Rello** [comment]
Hello,
Thank you for the feedback. It is linked to our new scanner concept. 

Does this error come up for every of your files?
So no file works at all?

**Comment by j-ed** [comment]
@Rello Yes, the messages are shown immediately after executing the scan process.

**Comment by Rello** [comment]
Hello,
Just to clarify: you have 100s of these messages, right?

Because only some would indicate broken single files.

**Comment by j-ed** [comment]
@Rello I hope this make the picture a little bit sharper. I've restarted the can process and the following messages are written to the console. It seems that an ls-command is executed with an incomplete file path:
```
> ./occ audioplayer:scan --debug carmen
Start scan for carmen
Scanned Folder: /carmen/files
Total audio files: 7056
Checking all files whether they can be skipped
   373466 - /carmen/files//Musik_Familie/... => already indexed
   373529 - /carmen/files//Musik_Familie/... => already indexed
   373720 - /carmen/files//Musik_Familie/... => already indexed
   373721 - /carmen/files//Musik_Familie/... => already indexed
   373722 - /carmen/files//Musik_Familie/... => already indexed
   ...
Final audio files to be processed: 6859
Start processing of ID3s
   /carmen/files//Musik_Familie/Wir_sind_Helden/Die Reklamation/04-Wir sind Helden-Denkmal.mp3
ls: cannot access '/04-Wir sind Helden-Denkmal.mp3': No such file or directory
       Error with getID3. Does not seem to be a valid audio file
   /carmen/files//Musik_Familie/Wir_sind_Helden/Die Reklamation/07-Wir sind Helden-Monster.mp3
ls: cannot access '/07-Wir sind Helden-Monster.mp3': No such file or directory
       Error with getID3. Does not seem to be a valid audio file
   /carmen/files//Musik_Familie/Wir_sind_Helden/Die Reklamation/09-Wir sind Helden-Aurelie.mp3
ls: cannot access '/09-Wir sind Helden-Aurelie.mp3': No such file or directory
       Error with getID3. Does not seem to be a valid audio file
...
[aborted by pressing CTRL-C]
```
In parallel the following messages are written to the log file:
```
...,"app":"PHP","message":"fseek(): stream does not support seeking at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/
3rdparty\/icewind\/streams\/src\/Wrapper.php#74","level":3,"time":"2017-03-02 10:28:09+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
...,"app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/carmen\/files\/\/Musik_Famil
ie\/Wir_sind_Helden\/Die Reklamation\/04-Wir sind Helden-Denkmal.mp3","level":0,"time":"2017-03-02 10:28:09+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","v
ersion":"11.0.2.7"}
...,"app":"PHP","message":"fseek(): stream does not support seeking at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/
3rdparty\/icewind\/streams\/src\/Wrapper.php#74","level":3,"time":"2017-03-02 10:28:09+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
...,"app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/carmen\/files\/\/Musik_Famil
ie\/Wir_sind_Helden\/Die Reklamation\/07-Wir sind Helden-Monster.mp3","level":0,"time":"2017-03-02 10:28:09+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","v
ersion":"11.0.2.7"}
...,"app":"PHP","message":"fseek(): stream does not support seeking at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/
3rdparty\/icewind\/streams\/src\/Wrapper.php#74","level":3,"time":"2017-03-02 10:28:09+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
...,"app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/carmen\/files\/\/Musik_Famil
ie\/Wir_sind_Helden\/Die Reklamation\/09-Wir sind Helden-Aurelie.mp3","level":0,"time":"2017-03-02 10:28:10+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","v
ersion":"11.0.2.7"}
```

**Comment by Rello** [comment]
ok, could reproduce it.
I am working on it

**Comment by Rello** [comment]
https://github.com/nextcloud/server/issues/3691

**Comment by Rello** [comment]
Hello,
after further testing it all comes down to libsmbclient-php which needs to be installed for NC to work properly.

I am testing if a check is required for this. if it is not installed, the old way of scanning could be performed (but your 198 could still not be solved).
if it is installed, the newer and faster scan would be performed

**Comment by j-ed** [comment]
@Rello That sounds good. Does that requirement need to be installed manually or will it be added to the server's 3rdparty components or added to the audioplayer lib directory?

**Comment by xraMsamohT** [comment]
It's neither part of Nextcloud nor part of Audio Player. You have to install [libsmbclient-php](https://github.com/eduardok/libsmbclient-php) on your server.

**Comment by Rello** [comment]
on Debian, I used: `sudo apt-get install php-smbclient`

**Comment by j-ed** [comment]
Ok, understood. Until now I never had to install any PHP specific files as a prerequisite of the Nextcloud server and its apps, that was the reason why I asked how you're planning to handle this requirement.

**Comment by Rello** [comment]
I know. Still investigating...

**Comment by j-ed** [comment]
@Rello FYI: I just installed the smbclient v0.9.0 extension on my server and was successfully able to run the provided example scripts (https://github.com/eduardok/libsmbclient-php) using the PHP CLI. Unfortunately I'm not able to run the `> ./occ audioplayer:scan --debug <useer>` command because it terminates with a segmentation fault error:
```
...
Final audio files to be processed: 6859
Start processing of ID3s
   /carmen/files//Musik_Familie/Wir_sind_Helden/Die Reklamation/04-Wir sind Helden-Denkmal.mp3
Segmentation fault
```

**Comment by Rello** [comment]
hello @j-ed 
can you get in contact with me at audioplayer(at)scherello(dot)de for some detail analysis on how to help with your case?

**Comment by Rello** [comment]
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html?highlight=smb
regarding the recommendation to install this. nevertheless the app needs to be able to handle both cases...

**Comment by j-ed** [comment]
@Rello you have new mail :-)

**Comment by Rello** [comment]
Hello @j-ed 
I wanted to follow up on the status here.
did you manage to update the smb-config and got it working?

**Comment by j-ed** [comment]
@Rello Unfortunately I'm unable to run tests with a SMB shares at the moment because there seems to be a problem with external storages due to lack of SMB v3 support in the app (see https://github.com/nextcloud/server/issues/5195). Due to this issue I switched to WebDAV for the moment and an audio scan runs without any exceptions:
```
Audios found: 7108
Duplicates found: 1
Written to music library: 7103
Albums found: 469
```

**Comment by Rello** [comment]
ok, closing it for now.
...impressive Library by the way...
