### ISSUE TITLE
Add column "File Date" on top of playlist

### ISSUE THREAD

**Issue by nc2017** [Rello/audioplayer#160]
Would be nice to have an additional column with the "File Date" on top of "Title", "Artist", "Album", "Length" (sortable), which is helpful for identifying recent recordings.

**Comment by ghost** [comment]
@nc2017 We discussed this internally and think that a playlist with the most _Recently Added_ tracks (25 tracks, newest on top) is a technically and optically better solution. This **Smart Playlists** feature will be extended in future versions.

@Rello

**Comment by Rello** [comment]
Development for all smart playlists will be documented in #164
