### ISSUE TITLE
on Nextcloud 11.0.2 no mp4 support

### ISSUE THREAD

**Issue by osaddambinbush** [Rello/audioplayer#163]
### Expected behavior

scan folder for existing mp4 files to list in the playlist

### Actual behavior
filescan doesnt find mp4 files. these files are in the same folder where my mp3s are

### Steps to reproduce the behavior
1. open audioplayer
2. choose the folder you want to listen (where mp3 /mp4 /m4a files inside) which is the same in my personal settings of my control panel
3. will only list the m4a and mp3 audio files no chance to get the mp4 files

### Possible solution (optional)
propper mp4 support (the quicktime module of getid3 should do this but it doesnt work...). maybe the module is not added correctly into your search function. I can play the mp4 files in my datamanager of nextcloud without having any problems. but it seems that audioplayer dont even support the playback. if i mark an mp3 file and click the 3 dots for detailed actions i have an "play" option listed below. 
if i mark up an mp4 file and click the 3 dots for detailed action there is no "play" function listed. 

### Server configuration
**Operating system**:
bananian (debian jessie based distro)  Linux Kernel 4.47 ARM71

**Web server:**
Apache2 

**Database:**
sqlite 3.16.2

**PHP version:**
PHP 7.0.16

**ownCloud/Nextcloud version:** (see `/status.php`)
11.0.2 stable

**Updated from an older ownCloud/Nextcloud or fresh install:**
update with occ command from 11.0.1.2

**Audio Player version:** (see `/settings/apps`)
1.4.1

**Where did you install Audio Player from:**
nextcloud apps

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
yes and i already got some kind of error

 "[OC\Encryption\Exceptions\DecryptionFailedException]
  Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you." 

but there is no filename listed just that message

### Client configuration
**Operating system:**
win10 x64

**Browser:**
firefox

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
its lager than 16mb impossible to add it here....
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by ghost** [comment]
Probably your MP4 audio files are mapped to the wrong MIME type in the `*PREFIX*filecache` table. Audio Player supports MP4 audio with the appropriate audio MIME types. MPEG-4 is a container format for audio, video, and text ([RFC 4337](http://www.rfc-editor.org/rfc/rfc4337.txt)). Feel free to change the mapping of the extension [in your instance](https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types) according to your requirements.

In Nextcloud the `.mp4` extension is mapped with MP4 video.
https://github.com/nextcloud/server/blob/stable11/resources/config/mimetypemapping.dist.json#L97
