### ISSUE TITLE
Graphical view selectable for all categories

### ISSUE THREAD

**Issue by PhieF** [Rello/audioplayer#165]
Hi,

I've just improved the artist view, here is the result 
http://pix.toile-libre.org/upload/original/1491067626.png

so after selecting an artist, I now have a view with albums only from this artist

Here are the two files I've modified
http://phoenamandre.fr/shared/audioplayerimprovement.tar.gz
Just sharing in case you'd like to merge it

Thanks for your great app !

**Comment by Rello** [comment]
Hello @Phoenamandre 
thank you for your suggestion.
what you are trying is to get a filter on the artist and show this in the layout of the "albums view".

The categories on the dropdown are on purpose without any graphical output because we have users with 10.000s of titles and they depend on a list-view.
So in this case, the views can not be mixed.

What you want to have would be a filter within the existing "Albums" because there we remain purely within the graphical display

We will keep it in the backlog, but at the moment it is not the main focus because we want to extend features like flac or streams due to frequent requests.


thank you again for your input

**Comment by Rello** [comment]
one remark for your code suggestion:

` $SQL .=" AND id in (SELECT album_id from *PREFIX*audioplayer_tracks WHERE artist_id = ".$artist_id.")";`

- the "id" needs to be properly described for DB compatibility `('AA'.'id')`
- don´t concatenate variable values into a SQL-string for injection risks. always use the "?" and parse it via `$result = $stmt->execute(array($this->userId, $artist_id))`

**Comment by PhieF** [comment]
Thanks for the tip !
Indeed, flac would be a great improvement !

**Comment by PhieF** [comment]
I've just added that to fasten songs loading with the album view by artist, sharing it for those who would like to use it 

```
public function loadSongs(){
    $artist_id = $this->params('artist_id');

        //		$SQL="SELECT  `AT`.`id`,`AT`.`title`,`AT`.`number`,`AT`.`album_id`,`AT`.`artist_id`,`AT`.`length`,`AT`.`file_id`,`AT`.`bitrate`,`AT`.`mimetype`,`AA`.`name` AS `artistname` FROM `*PREFIX*audioplayer_tracks` `AT`
		$SQL="SELECT  `AT`.`id`,`AT`.`title`,`AT`.`number`,`AT`.`album_id`,`AT`.`length`,`AT`.`file_id`,`AT`.`mimetype`,`AA`.`name` AS `artistname` FROM `*PREFIX*audioplayer_tracks` `AT`
						LEFT JOIN `*PREFIX*audioplayer_artists` `AA` ON `AT`.`artist_id` = `AA`.`id`
			 			WHERE  `AT`.`user_id` = ?";
	    //to add			
		if(!empty($artist_id)){
			$SQL .="AND artist_id = ? ";
		}
		$SQL.="ORDER BY `AT`.`album_id` ASC,`AT`.`number` ASC";
		
		...
		
		if(!empty($artist_id))
			$result = $stmt->execute(array($this->userId,$artist_id));
		else
			$result = $stmt->execute(array($this->userId));
		
```

**Comment by WhiteBahamut** [comment]
Actually this would be one of the main changes for me. I really like the app (it just works! :) ). But I am used to group the graphical view by artist with all the albums/titles grouped to the artist. And not group by album (as it is right now).
So it would be nice to be able to change the graphical view to either Artists or Albums.

**Comment by Rello** [comment]
Hello,
thank you for your inquiry. this feature is already on the backlog.
https://github.com/Rello/audioplayer/issues/39

actuall, the background coding is undergoing a major redesign and modularization at the moment.
the plan ist to enable a list & graphical view for several categories. similar to the files app, where the display can be triggered.

just hold on a little...

**Comment by Rello** [comment]
@WhiteBahamut 
I want to come back to your question: do you want to sort the Albums-View differently (currently alphabetic on album name)? only a diffent sorting?

or you want to use the category drilldown at the left and select an artist - and then only see the albums (grafical) for this artist?

**Comment by WhiteBahamut** [comment]
I would love to have an Album view which will show 
a) an artist image
b) or a thumbnail of the albums for this artits

Like http://cdn.arstechnica.net/wp-content/uploads/2015/07/music-artists-980x592.png

**Comment by Rello** [comment]
Hello,
i am preparing a kind of "filtered album view".
so if you select a Genre or an artist, all albums in this category will be shown - so a partial amount of the total albums view.

An artist-image is not possible because thats not part of ID3, so it can not be extracted from your metadata.

**Comment by WhiteBahamut** [comment]
ahh true.. totally forgot. A good alternative would be something like

**A**
ABBA  AC/DC
**B**
Beatles  Blondie
...
**W**
White Stripes   WithinTtemptation

For me, the grouping is the important part. And to have a more prominent Artist view.

**Comment by Rello** [comment]
fyi: work in progress for next release...

**Comment by Rello** [comment]
@PhieF @WhiteBahamut 
do you have an NC setup where you could test the current AP beta version?
we made a HUGE step forward. Cover-View for all + big UI speedup

would like to hear some feedback if possible...

**Comment by WhiteBahamut** [comment]
I could setup a basic env in a vm to make a very basic review

**Comment by WhiteBahamut** [comment]
Sorry for my late response. The new version runs smoother on my setup. The cover view works also good if I switch to Album Artist view. 
Nice work!
