### ISSUE TITLE
missing tags for wav files

### ISSUE THREAD

**Issue by kanasta01** [Rello/audioplayer#166]
Hi,
All my wav files are tag in UTF8 ID3V2, but still I do not have album and all tracks information in audioplayer. Album is always unknown and artists are always various,
![2017-04-02_18-56-12](https://cloud.githubusercontent.com/assets/26856023/24589172/3c82a01a-17d6-11e7-886d-53a9f6dd48e7.jpg)

**Comment by Rello** [comment]
Hello @kanasta01 
thank you for reporting this back to us.

we looked at the code and found an issue in the external getID3 library.
https://github.com/Rello/audioplayer/commit/6aeb7028226227d45b566e6ecb00cab110d1a741

If you need this urgently - or if you are willing to support us with testing, feel free to implement this fix locally and let us know.
We have to perform some more tests before we can push the bug fix release.
