### ISSUE TITLE
Drag & Drop complete album/artist to playlist

### ISSUE THREAD

**Issue by cuthulino** [Rello/audioplayer#168]
Just an enhancement for better usability.

It would be great if we could drag and drop not only one title.
A complete album or maybe a complete artist would be great to create some bigger playlists.

**Comment by daniu-de** [comment]
strongly support that ... takes forewer to create a reasonable playlist the way it works now ...

**Comment by Rello** [comment]
Hello,
we also have the point on our backlog, to add titles from other lists to a playlist - not only from the album.
This should speed up things already.

We will also think about a possible solution for a multi-select and let you know

**Comment by ghost** [comment]
@daniu-de Support the development of Audio Player and create a pull request! 😜

**Comment by Rello** [comment]
Drag&Drop was activated for all dynamic lists - not only for the album view.

this still requires single file dragging, but makes finding them in the first place much quicker.
for selecting a whole album or artist, no intuitive way was found yet
