### ISSUE TITLE
same artwork on different albums

### ISSUE THREAD

**Issue by kanasta01** [Rello/audioplayer#169]
Seems that there is bug with artwork preview on music libary page, same artwork for different albums.
![2017-04-03_18-15-41](https://cloud.githubusercontent.com/assets/26856023/24619464/5a4f4c82-189a-11e7-862a-8347d6bad2f0.jpg)

**Comment by Rello** [comment]
Hello,
can you please check that the files are not within the same folder and that the folder does not have a folder picture?

See the details here
https://github.com/rello/audioplayer/wiki/how-are-id3-tags-processed#cover-art

**Comment by kanasta01** [comment]
Every album have folder with folder artwork, when I remove everything from libary and do the rescan everything goes fine. Problem occurs after log off Nextcloud and log on again then I have same artwork on different albums.

**Comment by Rello** [comment]
Hello,
Just to check back: 
Is it a display issue with wrong results after re-logon to NC?
Or is it an issue with the scanner reading wrong covers?

Any hint welcome

**Comment by kanasta01** [comment]
Hi,
Display issue is after re-logon to NC.
Cheers!

**Comment by Rello** [comment]
hello @kanasta01 
can you please verify, if this issue still exists with the new AP version?

thank you

**Comment by ghost** [comment]
Closed due to lack of info.
