### ISSUE TITLE
easy use interface

### ISSUE THREAD

**Issue by mind22** [Rello/audioplayer#170]
Hi, i wanted to ask for the possibility of a second interface like itunes or other have it. With three tables for selection (Genres/Interprets/Albums) and beneath the titles. I think it is a fast way to scroll through a lot of music titles.

<img width="1182" alt="bild" src="https://cloud.githubusercontent.com/assets/26789520/24738620/2420f62a-1a97-11e7-98bb-67795e86d0df.png">

**Comment by Rello** [comment]
Hello,
Did you use the category dropdown on the left already?
Because this should do pretty much the same - and in a faster was as not all Categories are displayed the same time. 

This becomes especially important for users with many 1000 titles

**Comment by mind22** [comment]
Yes, i used it. But the problem is, you can fast scroll through interprets, but then if you have 4-7 albums of one interpret, you have no possibility to limit it to an album. This would be probably less a problem if the titles wouldn't be unsorted like it is now. I mean you can sort it then by albums, but the Track number is not in a right order per album. Hmm or maybe a slight break between the sorted albums would do it.

(With the above three tables i normally use first the interpret like you have now and in the right album table, the albums get automatically limited.)

**Comment by ghost** [comment]
> This would be probably less a problem if the titles wouldn't be unsorted like it is now.

Titles are sorted alphabetically at the moment, but not unsorted (by `fileid`).

> but the Track number is not in a right order per album.

List(s) with `DISCNUMBER` and `TRACK` will be a later stage of Smart Playlists. First we will implement a better sorting for _one_ album, selected in the sidebar. But the development goes on.

Perhaps we will change appearance and handling in v2 but in v1 it will remain as it is.

**Comment by Rello** [comment]
Hello,
One additional comment: did you see that the lists are sortable by pressing the header?
It was introduced in 1.5
