### ISSUE TITLE
Repeat single track

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#172]
I would like to be able to repeat just a single song. I realize you can make a playlist with just one song and putting that on repeat, but that becomes quickly combersome.

**Comment by Rello** [comment]
requested with the Soundmanager2 creator
https://github.com/scottschiller/SoundManager2/issues/189

**Comment by Rello** [comment]
Hello,
the player backend is being rewritten for the next release. this will then also enable the single-repeat.
finally :-)

**Comment by Rello** [comment]
The repeat can be toggled with `Single File => Playlist => None`
![Screenshot 2020-07-16 at 14 30 07](https://user-images.githubusercontent.com/13385119/87670969-e2968000-c770-11ea-9ae3-17445d13c6bf.png)

![Screenshot 2020-07-16 at 14 30 01](https://user-images.githubusercontent.com/13385119/87670967-e1655300-c770-11ea-9877-7d07426134dd.png)


...
coming via 
drop soundmanager2 and bar-ui for HTML5 audio #481

**Comment by Rello** [comment]
Version 2.11.0 was released
