### ISSUE TITLE
localization for zh_TW

### ISSUE THREAD

**Issue by sbr9150** [Rello/audioplayer#173]
@Rello New localization for zh_TW. By the way, flac support works perfectly. Good jobs.
[zh_TW.zip](https://github.com/Rello/audioplayer/files/925869/zh_TW.zip)

**Comment by ghost** [comment]
Thanks @sbr9150 !

May we ask again before the next release?
We plan to switch to Transifex soon.

**Comment by sbr9150** [comment]
update zh_TW.json
[zh_TW.json.txt](https://github.com/Rello/audioplayer/files/927203/zh_TW.json.txt)

**Comment by ghost** [comment]
@sbr9150 May we ask again to complete **and** correct both files? We have changed some strings due to code changes. Thanks in advance!

**Comment by sbr9150** [comment]
update zh_TW.json & zh_TW.js
[zh_TW.tar.gz](https://github.com/Rello/audioplayer/files/1028995/zh_TW.tar.gz)

**Comment by ghost** [comment]
@sbr9150 Thank you very much for your translation!
