### ISSUE TITLE
Sort tracks by track number

### ISSUE THREAD

**Issue by shockdude** [Rello/audioplayer#174]
Could you add the ability to sort tracks by track number? This would be great for listening to albums track by track.

Great music player, thanks for your hard work!

**Comment by ghost** [comment]
We will add a better handling of tracks in playlists as part of #88 .

**Comment by hkparker** [comment]
This doesn't appear to be addressed in #88 or #186, it still appears to be impossible to sort by track number in 2.0.1.  I suggest we re-open this.

**Comment by ghost** [comment]
Sorting by `DISC-TRACK` was implemented with v2.0.0. It works properly with the _graphical album view_ and with the _selection by album_ – and **only there**. Sorting by track number in other views is not provided.

**Comment by hkparker** [comment]
Oh I see that now, I wanted to view all songs sorted by artist, then album, and lastly track.  In the end I think it would make more sense for my desires to just host smaller transcodings of my music and sync those, then use local music players.

**Comment by ghost** [comment]
@hkparker We changed the default sort order for _all playlists_, taking `DISC-TRACK` into account – except the Smart Playlists and the own playlists. If you want to test this improvement, you can either clone the current beta version or download and install the ZIP file manually.

**Comment by hkparker** [comment]
Awesome, thank you!  I'll check it out in the next release.

**Comment by ghost** [comment]
@hkparker Version 2.0.2 was released a day ago. ;-)
