### ISSUE TITLE
Not available for nextcloud 12 beta

### ISSUE THREAD

**Issue by simonbuehler** [Rello/audioplayer#185]
hi,

would like to test it with the beta, how can i install it there?

**Comment by ghost** [comment]
[Clone](https://github.com/rello/audioplayer.git) the Git `master` repo or [download](https://github.com/rello/audioplayer/archive/master.zip) the ZIP archive. You have to install AP in Nextcloud manually.
Be aware that 1.6.0 is an alpha version yet!

**Comment by simonbuehler** [comment]
thanks, 

unzipped but when trying to enable it in the web inteface i got "unableto download ..." fixed it by renaming the folder audioplayer-master to audioplayer,
