### ISSUE TITLE
Undefined variable: SQL at controller/categorycontroller.php

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#187]
Currently I see several undefined variable-error reports in my next cloud logs when activating the audioplayer app.

### Steps to reproduce the behavior
1. Activate audioplayer
2. Check logs

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache2

**Database:**
MySQL-5.7.18

**PHP version:**
PHP-7.0.15

**Nextcloud version:**
Nextcloud v11.0.3

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Audio Player version:**
1.5.1

**Where did you install Audio Player from:**
Nextcloud menu

**Are you using encryption:** yes/no
yes

#### Nextcloud log
<details>
Error	PHP	Undefined variable: SQL at /var/www/html/nextcloud.*.de/apps/audioplayer/controller/categorycontroller.php#124
</details>

**Comment by Rello** [comment]
Hello,
thank you for the report.
I found the section causing this. But this should only occur once after a clean install.
can you please navigate to one of the categories in the drop down and confirm that the log is not showing up anymore?

thank you

**Comment by ghost** [comment]
Yes it does happen only once whenever the app gets activated so if I turn it off and on again I will see it in the log again.
