### ISSUE TITLE
NC 12 support

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#190]
Hello Rello.

I guess you working already on NC 12 support? The lack of it prevents me from switching to NC 12 right now. Love the audioplayer.

thanks and cheers
t.

**Comment by Rello** [comment]
correct.
the next version will be a bigger one inkl NC12/oC10, Flac, smart playlists....
see here: https://github.com/Rello/audioplayer/blob/master/CHANGELOG.md

we are in final testing so it should be released soon
give us some more days

**Comment by ghost** [comment]
Thanks.

**Comment by Wikinaut** [comment]
I think you better should 
* reopen this issue; and 
* remove the flag "inappropriate"

because this appears to be an active issue: the App is not ready for NC 12.0.0. and cannot be activated for users and admins like me who upgraded NC.

**Comment by ghost** [comment]
@Wikinaut You can do a git clone and use that. I know thats an ugly workaround.

**Comment by ghost** [comment]
Another option: download the [master](https://github.com/rello/audioplayer/archive/master.zip), upload the files manually, and rename the `audioplayer-master` to `audioplayer`.

A change during the NC 12 betas needs to be fixed in Audio Player. A partially functioning app does not help anyone.

**Comment by Rello** [comment]
Hello,
Please keep in mind that we did not release the app on purpose yet. There is even a bug in NC which we have to work around. 

We have known issues with the share-player. If you dpend on this, you dont need to try the current git clone

**Comment by Wikinaut** [comment]
Dear all, thanks for "improving" the issue, so that the "work in progress" is now clearly visible to everyone.

**Comment by Wikinaut** [comment]
Well done, it works.
