### ISSUE TITLE
DISCNUMBER tag ignored in VorbisComment

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#196]
### Expected behavior
For albums with multiple discs, tracks should first be sorted by disc number.

### Actual behavior
For ID3 (`.mp3`) it works, but not for VorbisComment (`.flac`, `.ogg`).

### Steps to reproduce the behavior
1. Tag an audio file with `DISCNUMBER` greater than `1`.
2. Scan for new audio files.
3. Take a look into graphical album view or selected playlist. All discs have number `1` and sorted wrong.

### Possible solution (optional)
Detect the `DISCNUMBER` tag correctly in `fLaC` and `OggS`.

### Server configuration
**Audio Player version:** (see `/settings/apps`)
2.0.0

**Comment by Rello** [comment]
corrected
