### ISSUE TITLE
Playback stops after playing a track on artist list

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Rello/audioplayer#199]
### Expected behavior

The player will play the next song after the currently played track has ended.

### Actual behavior

Playback stops.

### Steps to reproduce the behavior
1. Select tracks by artist
2. Play a song
3. Wait

### Possible solution (optional)

Probably due to JS error:

```
app-min.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:93 Uncaught TypeError: album.substring is not a function
    at Audios.soundmanager_callback (app-min.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:93)
    at N.onfinish (bar-ui-min.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:62)
    at soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:51
    at la (soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:55)
    at N._onfinish (soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:51)
    at HTMLAudioElement.<anonymous> (soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:58)
    at HTMLAudioElement.<anonymous> (soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:13)
Audios.soundmanager_callback @ app-min.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:93
onfinish @ bar-ui-min.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:62
(anonymous) @ soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:51
la @ soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:55
N._onfinish @ soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:51
(anonymous) @ soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:58
(anonymous) @ soundmanager2-nodebug-jsmin.js?v=a38d576b9ea1806ddd6fb526b2b1ad0f:13
```

### Server configuration
**Operating system**: Ubuntu 16.04
**Web server:** nginx
**Database:** MariaDB
**PHP version:** 7.1
**ownCloud/Nextcloud version:** 11.0.3.2
**Updated from an older ownCloud/Nextcloud or fresh install:** yes
**Audio Player version:** 2.0.1
**Where did you install Audio Player from:** via Apps-App
**Are you using encryption:** no

### Client configuration
**Operating system:** Windows 10 (x64)
**Browser:** Google Chrome 58.0.3029.110 (64-bit)

**Comment by Kaliumhexacyanoferrat** [comment]
Seems the `data` attributes are not set as expected:

![image](https://cloud.githubusercontent.com/assets/4992119/26553353/85e3c568-448b-11e7-8744-5c4f860890c7.png)

![image](https://cloud.githubusercontent.com/assets/4992119/26553318/5a0854ea-448b-11e7-804d-d1626b07fc1a.png)

Display columns are configured as expected:

![image](https://cloud.githubusercontent.com/assets/4992119/26553399/b57858ac-448b-11e7-802b-9306085352c9.png)

**Comment by Rello** [comment]
hello,
thank you for this finding.

It is a rare combination of several facts that is causing this
- Artist View (because only this is showing the year)
- title without album cover
- 2 of them being next to each other

in this case it is trying to use a string function on an integer value - which will not work.
we will provide a solution
