### ISSUE TITLE
Progress bar of 360° player does not work

### ISSUE THREAD

**Issue by puntorosso** [Rello/audioplayer#201]
### Expected behavior
In previous releases, the inner circle of the player had a different color than the background, and was turning while the audio has been played

### Actual behavior
After the last update only the numeric clock in the middle indicate that the song is playing.

### Server configuration
**Nextcloud/ownCloud version:**
11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Audio Player version:**
2.0.1

**Are you using encryption:**
yes

### Client configuration
**Operating system:**
Mac Os 10.12.5

**Browser:**
Safari, Chrome

**Comment by xraMsamohT** [comment]
Thanks for reporting this issue! Please fill in the [issue template](https://github.com/rello/audioplayer/blob/master/.github/ISSUE_TEMPLATE.md) at least with the details of the Nextcloud/ownCloud version, the Audio Player version, and the browser used.

**Comment by puntorosso** [comment]
### Expected behavior
In previous releases, the inner circle of the player had a different color than the background, and was turning while the audio has been played

### Actual behavior
After the last update only the numeric clock in the middle indicate that the song is playing.

### Steps to reproduce the behavior
1. 
2. 
3. 

### Possible solution (optional)


### Additional information (optional)


### Server configuration
**Operating system**:


**Web server:**


**Database:**


**PHP version:**


**Nextcloud/ownCloud version:** 11.0.3


**Updated from an older Nextcloud/ownCloud or fresh install:** Updated


**Audio Player version:**  2.0.1


**Where did you install Audio Player from:**


**Are you using external storage, if yes which one:** `local/smb/sftp/...`


**Are you using encryption:** yes


### Client configuration
**Operating system:**Mac Os 10.12.5


**Browser:** Safari, Chrome


### Logs
#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>
