### ISSUE TITLE
Offset in progress bar in Safari

### ISSUE THREAD

**Issue by mind22** [Rello/audioplayer#206]
When i want to fast forward a track in the progress bar, there is an offset of about 45 seconds.
It only occurs in Safari. Firefox is doing as usual.

nextcloud 12
nginx 1.12
php 7.0.18

**Comment by ghost** [comment]
Thanks for reporting this issue! Please fill in the [issue template](https://github.com/rello/audioplayer/blob/master/.github/ISSUE_TEMPLATE.md) as complete as possible.

- Progress bar of 360° player (Share Player) or on playlists?
- Is the sidebar opened?
- Audio Player version?
- Which MIME type?

**Comment by mind22** [comment]
### Steps to reproduce the behavior
I marked it in the picture below. When i click at this position, the progess bar jumps with an offset to 2:05 as shown. 

After testing more tracks, i found out that the offset is increasing and decreasing with the track length. So it is not static.

<img width="1180" alt="bildschirmfoto 2017-06-17 um 19 35 25" src="https://user-images.githubusercontent.com/26789520/27255000-c88f725a-5394-11e7-8aae-d39ce7b632b5.png">

### Additional information (optional)
- Yes the sidebar is open and artists is selected.
- Audioplayer 2.0.2
- MIME: m4a, mp3

### Server configuration
- nextcloud 12
- nginx 1.12
- php 7.0.18


**Updated from an older Nextcloud/ownCloud or fresh install:** from 11


**Audio Player version:** (see `/settings/apps`) 2.0.2


**Where did you install Audio Player from:** app store


**Are you using encryption:** no


### Client configuration
- Safari/Mac (latest)

**Comment by xraMsamohT** [comment]
It is the same problem with both Safari and Chrome. So I close this issue as a duplicate of #111.

**Comment by xraMsamohT** [comment]
Duplicate of #111
