### ISSUE TITLE
Missing "center" audio

### ISSUE THREAD

**Issue by spiffzilla** [Rello/audioplayer#207]
### Expected behavior
When i play mp3:s i expect to hear the singing

### Actual behavior
I hear no singing

### Steps to reproduce the behavior
1. Play for example ACDDC, Back in black
2. Listen

### Possible solution (optional)
??

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
5.6.30

**Nextcloud/ownCloud version:** (see `/status.php`)
    [needsDbUpgrade] =>
    [version] => 12.0.0.29
    [versionstring] => 12.0.0
    [edition] =>

**Updated from an older Nextcloud/ownCloud or fresh install:**
from older nextcloud (a couple of versions ago)

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
Store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Yes, smb

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Windows 7

**Browser:**
Chrome (newest)

**Comment by ghost** [comment]
What is the color of the volume slider, gray or black?
With or without an open sidebar?
See #111 

Without the sidebar I can move the volume slider. Unfortunately, it is a known issue but the Audio Player generally works with Chrome.

Remark: _Newest_ means v59? In four weeks with _newest_ no one can start anything.

**Comment by spiffzilla** [comment]
I get sound, it's only (a channel?) thats missing. Sound in both ears with headphones but it sounds as the "center" is gone I'm no audio genius so bear with me :-)

@xraMsamohT Seems like if the sidebar is expanded, you need to drag with an offset as big as the sidebar

![audio](https://user-images.githubusercontent.com/3751145/27175479-9dab9932-51bf-11e7-805f-8cfbfe0d37c1.png)

**Comment by ghost** [comment]
@spiffzilla The offset is also a known issue and is also discussed in #111, that I linked above.

The other issue does not seem to be a problem with the Audio Player so I close this issue and mark it as a duplicate of #111.

You can send us a link to one of your affected audio files and we will check this file with our instances.

**Comment by spiffzilla** [comment]
Please do. I have tried quite a lot of differnt  MP3 Files, problem is constant.
The ticket you marked s duplicate is not the problem i reported, I only added the info regarding offset to be of help.

**Comment by ghost** [comment]
@spiffzilla Due to missing of an audio file to investigate **your** problem I let this issue closed. I see no problem with the Audio Player in general. At least one of the thousands of users of Audio Player would have reported otherwise.

**Comment by spiffzilla** [comment]
Please ignore, faulty hardware :-/

**Comment by Rello** [comment]
A little note on the technical background: Audio Player does not process any audio content. It is obly delivering it to the browser's API which is then responsible for any playback

**Comment by spiffzilla** [comment]
Perfectly  ok. I Think it's hw relaterad. Thanx
