### ISSUE TITLE
Player fails with console exception

### ISSUE THREAD

**Issue by dhowe** [Rello/audioplayer#211]
### Expected behavior
Play a track or give an error/warning in interface

### Actual behavior
Skips to next track, outputs error to console

### Error
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

### Versions
Server: Nextcloud 12.0.0 (Ubuntu 16.04)
Browser: Chrome Version 58.0.3029.110 (64-bit) on OSX 10.10.5

**Comment by Rello** [comment]
Hello,
can you please provide proper logs here? in which log do you see an error?
are you sure you are playing a track with a supported mimetype of your browser? Is the track shown in italic letters?

please provide more details here

**Comment by dhowe** [comment]
The error above shows in the client browser console. I can't seem to recreate it at moment, but again the browser's console log is filled with warnings/errors (see below). I will keep trying to recreate the issue above.

```
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
soundmanager2-nodebug-jsmin.js:48 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
/nextcloud/index.php/apps/audioplayer/#:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
/nextcloud/index.php/apps/audioplayer/#:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
```

Also several of these:

```

core.js?v=6a9be61…-2:3 Uncaught TypeError: soundObject.togglePause is not a function
    at Object.play (bar-ui-min.js:90)
    at HTMLSpanElement.<anonymous> (app-min.js:37)
    at HTMLSpanElement.dispatch (core.js?v=6a9be61…-2:3)
    at HTMLSpanElement.r.handle (core.js?v=6a9be61…-2:3)
```

**Comment by Rello** [comment]
Hello,
the above log indicates e.g. that a title was Paused before it actually managed to start (transfer of file to browser API)
The next version - in final testing - has some corrections in the player js coding. I hope your exception should not occur anymore. 
if you have the possibilities, you could test the current git-master


thank you

**Comment by Rello** [comment]
Hello,
please try the new 2.1.0 which was released and let us know.

thank you
