### ISSUE TITLE
Log full of errors after installing audio-player

### ISSUE THREAD

**Issue by dhowe** [Rello/audioplayer#212]
### Versions
Server: NextCloud 12.0.0 (Ubuntu 16.04)
Browser: Chrome Version 58.0.3029.110 (64-bit) on OSX 10.10.5

![image](https://user-images.githubusercontent.com/737638/27344561-4ab324e4-5619-11e7-8971-1b247a8e2f19.png)

**Comment by Rello** [comment]
Hello,
thank you for reporting this back to us.
the "Undefined Variable/Index" are notice messages. they are reported as errors due to some configuration in your php.ini

nevertheless we will take care of them with the next release wherever possible include proper isset() validations

**Comment by Rello** [comment]
the issue with the categorycontroller is corrected.
the other occurrences are within an external library which we don´t modify. as this is only called during the scanner process and not in normal operation, it should be ok
