### ISSUE TITLE
Audio Player is not compatible with Nextcloud 12

### ISSUE THREAD

**Issue by m4j** [Rello/audioplayer#213]
### Expected behavior

Audio Player to work with Nextcloud 12

### Actual behavior

After upgrading from Nextcloud 11 to 12, Audio Player is disabled. Tried to enable it using admin interface and received the following message:

> App "Audio Player" cannot be installed because it is not compatible with this version of the server.

### Steps to reproduce the behavior
1. Login to Nextcloud
2. Go to Settings -> Apps -> Multimedia
3. Find Audio Player and click "Enable" button

### Server configuration
**Operating system:** Ubuntu 16.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0.x

**Nextcloud/ownCloud version:** (see `/status.php`) 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.3

**Audio Player version:** (see `/settings/apps`) 1.5.1

**Where did you install Audio Player from:** Nextcloud App Store

**Are you using external storage, if yes which one:** n/a

**Are you using encryption:** no

### Client configuration
**Operating system:** OS X El Capitan v10.11.6

**Browser:** Safari

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by ghost** [comment]
Audio Player 1.5.1 is not compatible with Nextcloud 12 and above. You have to upgrade the app to version 2.0 or newer.
https://apps.nextcloud.com/apps/audioplayer
https://github.com/rello/audioplayer/blob/master/CHANGELOG.md

**Comment by m4j** [comment]
Thanks!
