### ISSUE TITLE
Artist "Unknown" requests huge amount of data without displaying it

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Rello/audioplayer#214]
When requesting the playlist (GET /apps/audioplayer/getcategoryitems?category=Artist&id=18), the (album?) covers will be serialized into the JSON response, causing a huge amount of data being downloaded by the client.

### Expected behavior
The playlist will show immediately after clicking on "Unknown".

### Actual behavior
The client will download several MB (31 in my case) of song covers without actually showing them, causing the playlist to load quite a while (depending on the speed of the internet connection).

### Steps to reproduce the behavior
1. Select "Artists" in the dropdown in the upper-left corner of the player app
2. Select "Unknown" (in my example, there are 218 songs in this category)

### Possible solution (optional)
Either:

- Add a query parameter to prevent covers from being returned if they are actually not shown (?covers=false)
- Return the cover URL within the response, leveraging the capabilities of the browser to load resources in parallel when needed 

### Server configuration

**Nextcloud/ownCloud version:** 11.0.3.2
**Audio Player version:** 2.0.2

### Screenshots

![image](https://user-images.githubusercontent.com/4992119/27429722-62855dd4-5746-11e7-9b52-1f78bd1e66f4.png)

**Comment by Rello** [comment]
Hello,
thank you for the finding - here is indeed a problem.
the cover is only required internally during the select and should not be transferred as part of the json at all. It is working correctly within the "Album" selection e.g.

I am testing the correction locally already and will give an update soon

**Comment by Rello** [comment]
@Kaliumhexacyanoferrat if you have the possibility, feel free to locally test the commit upfront already.
https://github.com/Rello/audioplayer/commit/5cd44fa0ab09f149388482f5b7e43e6a9f9c7b36
