### ISSUE TITLE
Message on scan in debug mode

### ISSUE THREAD

**Issue by ddanielww** [Rello/audioplayer#219]
Trying to index using `sudo -u www-data php occ audioplayer:scan "user" --debug` but its displaying the below error ...

Attention: Only slow indexing due to server config. See Audio Player wiki on GitHub for details.

Can not find anything to do with this? Can someone send a link.

**Comment by Rello** [comment]
Hello,

thank you for the hint.
the wiki was enhanced

https://github.com/Rello/audioplayer/wiki/External-storage
