### ISSUE TITLE
fileaction not working

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#22]
the following features are not working correctly:
- when an audiofile is clicked in the file overview, it can be played right away
- when a audiofile is shared via link, it can be played within the sharing screen via the js player

new feature:
- introduce the play-entry in the file-options-dropdown

**Comment by Ark74** [comment]
Hi!
Maybe I need to open a new ticket, please let me know.

On Nextcloud 15.0.1
AudioPlayer 2.5.1
php-7.3.1

When clicking on a shared link with music, the audio is not played as stated on the opening description,

>  - when a audiofile is shared via link, it can be played within the sharing screen via the js player

Console shows,

```
GET https://cloud.domain.com/apps/audioplayer/getpublicaudiostream?token=nrTRrodAykwBiNB&file=The%20song%20file.ogg net::ERR_ABORTED 500
nrTRrodAykwBiNB:1 Uncaught (in promise) DOMException
```
Seems that the requested stream requires js which can't be loaded thus the 500 error and no sound.
Cheers!
