### ISSUE TITLE
Add Network Indicator

### ISSUE THREAD

**Issue by joewashear007** [Rello/audioplayer#220]
### Load Panel
Click on the Artist in the dropdown will load the artist. A nice little indicator (or spinner) shows that the list is being loaded

### Actual behavior
Click on the Artist in the dropdown will load the artist. With a fair large collection, it take a bit. there is no indicator that the request is taking place.

### Steps to reproduce the behavior
1. Add a large collection to the app
2. Click on Artist
3. No indication that 

### Possible solution (optional)
Add a indicator to show the status of the HTTP request 

### Server configuration
**Operating system**:
Ubuntu Core

**Web server:**
Apache

**Database:**
MySql

**PHP version:**
7

**Nextcloud/ownCloud version:** (see `/status.php`)
11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Installed using the nextcloud snap

**Audio Player version:** (see `/settings/apps`)

**Where did you install Audio Player from:**
Nextcloud Apps page

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local hard drive

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Windows 7

**Browser:**
Firefox developer

**Comment by Rello** [comment]
Hello,
you are only seeing longer response times because the current release has a little bug and is transferring too much data
#214
this is already fixed and currently in testing.
Afterwards there should not be the need for a spinner.

nevertheless we will look at it. its enabled in the Albums-View already and could also be done in the categories for consistency reasons.

**Comment by joewashear007** [comment]
Awesome. Thanks for the update!

Joseph Livecchi

**Comment by Rello** [comment]
Hello,
with 2.2.0 also the database indexes have been reworked.
we will focus on the backend performance and save the coding overhead of a spinner which is only required in very rare conditions

thank you
