### ISSUE TITLE
Audio Player 2.x compatibility to oC 9.0

### ISSUE THREAD

**Issue by alars** [Rello/audioplayer#222]
### Actual behavior
ownCloud silently aborts; a browser presents an empty page.
Even the command-line tool 'occ' just silently exits, no output at all.

### Steps to reproduce the behavior
1. upgrade audioplayer from 1.4.1 to 2.0.2

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.1.25

**PHP version:**
7.0.18

**Nextcloud/ownCloud version:** (see `/status.php`)
ownCloud 9.0.8

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
Upgrade from within ownCloud

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
yes

#### ownCloud log
<details>
<summary>ownCloud log (`/data/owncloud.log`)</summary>

```json
{"reqId":"K7cIyHLe2n66dQHBdXFk","remoteAddr":"","app":"PHP","message":"Error: Class 'OCA\\audioplayer\\AppInfo\\Application' not found at \/var\/www\/owncloud\/apps\/audioplayer\/appinfo\/app.php#32","level":3,"time":"2017-07-12T15:55:49+02:00","method":"--","url":"--","user":"--"}
```

</details>

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.
It seems like the Audio Player is not compatible with the outdated autoloader within OC 9.0.x.
I could reproduce the issue with a test-install.

we will adjust the min-version flag in the index.xml to avoid any issues.
For your case, I recommend to upgrade your OC instance as we can't invest much effort here to make it backward compatible to this old version.
