### ISSUE TITLE
Safari (iPad with iOS 10) does not play songs

### ISSUE THREAD

**Issue by prsnbrg** [Rello/audioplayer#223]
### Expected behavior
Play the songs one at a time.

### Actual behavior
The songs are loaded one after the other without being played.

### Steps to reproduce the behavior
1. Open the Audioplayer in Safari (iOS)
2. 
3. 

### Server configuration
**Operating system**:
Raspbian

**Web server:**
Apache2

**Database:**

**PHP version:**
PHP5

**Nextcloud/ownCloud version:** (see `/status.php`)
Owncloud Community 10.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
Marketplace Owncloud

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
iOS 10.3.2

**Browser:**
Safari

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
can you please try from your desktop if it is working?

- Are you using ssl on your PI? 
- Are you accessing via the same URL as the certificate?
- is this a self-signed certificate?

I have the same issue with iOS when accessing the PI within local WLAN with its local DNS. iOS policy seems very strict on the certificate validation there.

let me know...

**Comment by prsnbrg** [comment]
Yes I am use a self signed certificate.

I can play music with windows 10 and Mozilla Firefox.

**Comment by Rello** [comment]
Hello,

I am afraid we can not solve this issue as it is related to the iOS browser.
There is nothing AP can do about this
