### ISSUE TITLE
Audio Player doesn't play any MP3 file

### ISSUE THREAD

**Issue by adi2k5** [Rello/audioplayer#224]
### Expected behavior

Play audio files in audioplayer

### Actual behavior

Audio failes are loaded into player, but no audio is being played after hitting play button. 

### Steps to reproduce the behavior
1. Upload any mp3 file to nextcloud
2. Go to audioplayer app
3. Go to playlists
4. Mark any file from playlist
5. Try to play the file

### Server configuration
**Operating system**:
Fedora 25

**Web server:**
Lighttpd 1.4.45

**Database:**
mariadb 10.1.24

**PHP version:**
7.0.21

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 11

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
nextcloud app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Fedora 25

**Browser:**
Firefox 54

#### Nextcloud/ownCloud log
<details>
<summary>nextcloud log</summary>

```json
{"reqId":"cmd31s1190hCJcQXn8aw","level":3,"time":"2017-07-21T12:39:37+00:00","remoteAddr":"*.*.*.*","user":"*****","app":"index","method":"GET","url":"\/index.php\/apps\/audioplayer\/setstatistics","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\NotNullConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_audioplayer_statistics` (`user_id`,`track_id`,`playtime`,`playcount`) VALUES(?,?,?,?)' with params [\\\"main\\\", null, 1500640777, 1]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'track_id' cannot be null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/audioplayer\\\/lib\\\/Controller\\\/CategoryController.php(413): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 [internal function]: OCA\\\\audioplayer\\\\Controller\\\\CategoryController->setStatistics()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\audioplayer\\\\Controller\\\\CategoryController), 'setStatistics')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\audioplayer\\\\Controller\\\\CategoryController), 'setStatistics')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\audioplayer...', 'setStatistics', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/audioplay...')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":113}","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```
</details>

If I'll try to use anything else than playlist (i.e Albums, Titles or anything else), I'm getting following error:

<details>
<summary>nextcloud log</summary>

```json
{"reqId":"6WIuEDAkNyoQGkkH3oyt","level":3,"time":"2017-07-21T13:15:13+00:00","remoteAddr":"*.*.*.*","user":"***","app":"PHP","method":"GET","url":"\/index.php\/apps\/audioplayer\/getcategory?category=play","message":"Undefined variable: SQL at \/var\/www\/nextcloud\/apps\/audioplayer\/lib\/Controller\/CategoryController.php#129","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```
</details>

#### Web server error log (optional)
no errors

#### Browser log (optional)
n/a

**Comment by Rello** [comment]
Hello,
it looks like something is wrong with the status of your library.
Can you clean and rescan the library via the 2 icons in the left menu?

please let me know

**Comment by adi2k5** [comment]
Hello,

yes, I have done that already, with the very same effect. Tried either with icons on left menu, as well ac with occ (I've replaced real userid with $myuserid)
```
php occ audioplayer:reset $myuserid
php occ audioplayer:scan $myuserid
```
I've tried to use different audio files, different accounts - always the same result.
It's finding audio file without any errors, but still I can't play it:

```
$ php occ files:scan $myuserid           
Starting scan for user 1 out of 1 ($myuserid)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 7       | 7     | 00:00:00     |
+---------+-------+--------------+
$ php occ audioplayer:reset $myuserid
Reset library for $myuserid
Reset finished
$ php occ audioplayer:scan $myuserid
Start scan for $myuserid
Audios found: 1
Duplicates found: 0
Written to music library: 1
Albums found: 1
Errors: 0
```
In nextcloud log I'm getting this during scan via browser (no errors in log while using php occ method):
```
{"reqId":"iTTlFiYcq01Rj96SfxtF","level":1,"time":"2017-07-26T07:16:23+00:00","remoteAddr":"*.*.*.*","user":"$myuserid","app":"admin_audit","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","message":"File accessed: \"\/01 The Trail.mp3\"","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"uqV3es5AGq4AMe1UAasv","level":3,"time":"2017-07-26T07:16:24+00:00","remoteAddr":"*.*.*.*","user":"$myuserid","app":"PHP","method":"GET","url":"\/index.php\/apps\/audioplayer\/getcategory?category=play","message":"Undefined variable: SQL at \/var\/www\/nextcloud\/apps\/audioplayer\/lib\/Controller\/CategoryController.php#129","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```


Edit:
I just tried and changed oc_audioplayer_statistics to allow NULL in track_id column, and now I see that  track has been added into above table when I've tried to play the file (no 'INSERT INTO `oc_audioplayer_statistics' error anymore)
```
MariaDB [myndb]> select * from  oc_audioplayer_statistics;
+----+---------+----------+------------+-----------+
| id | user_id | track_id | playtime   | playcount |
+----+---------+----------+------------+-----------+
|  6 | $myuserid    |     NULL | 1501058132 |         1 |
|  7 | $myuserid    |     NULL | 1501058169 |         1 |
```
but 'Undefined variable: SQL' error still prevent file to be played.

Other thing that may be worth to note is, that when I'm hitting play button, left menu is cleared from my previous choice, i.e if I'll choose 'playlist' from drop down menu, then i.e 'favorites', and then I'll hit 'play' on a file, playlist with favorites will be reset to blank fields.

Edit2: 
More things from browser; while clicked play button, I'm getting this:
```
TypeError: soundObject.togglePause is not a function[More info]  bar-ui-min.js:90:1
	play https://***/apps/audioplayer/js/bar-ui-min.js:90:1
	handleClick https://***/apps/audioplayer/js/bar-ui-min.js:73:296
```
More info redirects to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

**Comment by adi2k5** [comment]
Ok, figured that out finally. Stupid reason - firefox on one of my computers used for testing doesn't support mp3 for some reason (although gstreamer plugins are installed). For some unknown reason on that computer I couldn't see neither supported nor not supported file formats as well... But as strange as it is, it's error on client side, so I think issue can be closed. One suggestion though... it would be good to have some check if given format is supported (mp3 in this case), and eventually return some error to log that file format is not supported by browser.

**Comment by ghost** [comment]
> it would be good to have some check if given format is supported

This has been implemented long time ago. ;-)

https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types#browser-support
_To evaluate your browser capabilities, go to the personal settings of your cloud and select the Audio Player section. …_

`Formats [NOT] supported by your current browser: …`
