### ISSUE TITLE
Audio Player is stuck playing the same track forever

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#226]
When you play a song two times, then change the album and select a song there, it will still play the old song and you can't change it anymore. The only way to recover from this state is a page reload.

### Expected behavior
1. Select "Artists" in Dropdown
2. Select an artist which has only one song
3. Click on the track and let it finish playing
4. Then press the "Play" button to play it again and let it finish playing
-> No JS errors occur
5. Change to another album with multiple songs
6. Click the "Play" button
-> The song from the new artist plays
-> No JS errors occur
7. Click on another song to play it
-> The new song plays

### Actual behavior
1. Select "Artists" in Dropdown
2. Select an artist which has only one song
3. Click on the track and let it finish playing
4. Then press the "Play" button to play it again and let it finish playing
-> JS error occurs: Cannot play media. No decoders for requested formats: [object Object]
5. Change to another album with multiple songs
6. Click the "Play" button -> The song from the old artist plays
-> JS error occurs: Cannot play media. No decoders for requested formats: [object Object]
7. Click on another song to play it
-> JS error occurs:
```
TypeError: item.getElementsByTagName is not a function[Learn More]  bar-ui-min.js:48:102
	playItemByOffset https://cloud.hello.me/apps/audioplayer/js/bar-ui-min.js:48:102
	play https://cloud.hello.me/apps/audioplayer/js/bar-ui-min.js:86:225
	success/</< https://cloud.hello.me/apps/audioplayer/js/app-min.js:37:203
	dispatch https://cloud.hello.me/core/vendor/core.js:3:6414
	add/r.handle https://cloud.hello.me/core/vendor/core.js:3:3224
```
8. Try to play ANY other track. It will always play the track from the old artist (with only one song) You can also try to switch the artist. The audio player is now stuck playing this only track forever. Until you reload the page with F5. Everytime you try to select a track you will see a JS TypeError.

### Possible solution (optional)
Reload the page (not really a solution)

### Server configuration
**Operating system**:
Windows 10 x64

**Web server:**
Apache2 as web server for nextcloud
NGINX as a reverse proxy

**Database:**
 mysql Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using EditLine wrapper

**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud/ownCloud version:** (see `/status.php`)
 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
 Fresh install of NC 12

**Audio Player version:** (see `/settings/apps`)
 2.0.2

**Where did you install Audio Player from:**
 NC Apps

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
 Tested with Windows 10 x64

**Browser:**
 Windows 10: Firefox Developer Edition (55.0b14)

#### Nextcloud/ownCloud log
The only log entry that has to do with audio player:
<details>
Error | PHP | Undefined variable: SQL at /var/www/html/nextcloud/apps/audioplayer/lib/Controller/CategoryController.php#129 | 2017-08-09T12:20:34+0200
</details>

</details>

**Comment by Rello** [comment]
Hello,
Issue located. I am working on it
