### ISSUE TITLE
Can not read audio files in external storage?

### ISSUE THREAD

**Issue by jimmy5670** [Rello/audioplayer#227]
### Expected behavior
when I set scan audio scan folder as an external folder, the message shows "find new music" on the top of page, should scan and list music files in the album on the left.

### Actual behavior
Scan folder just for few secend. and no any files show on the left column.

### Steps to reproduce the behavior
1. setup an external storage as local folder, where is collect music files
2. setup audio player app search location index to the external storage path
3. scan for now music files, but nothing new files can be find.

### Server configuration
**Operating system**:
ubuntu 16.04.3

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
php7

**Nextcloud/ownCloud version:** (see `/status.php`)
nextcloud 12+

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from owncloud 9,and switch to nextcloud 11, then follow stable updates.

**Audio Player version:** (see `/settings/apps`)
2.02

**Where did you install Audio Player from:**
2.0

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
'local'

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
win7 x64

**Browser:**
chrome,firefox

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
nothing error log on audio app
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by ghost** [comment]
1. Did you see the files in the Files app?
2. Did you made a scan of the external storage?

https://github.com/rello/audioplayer/wiki/specific-media-folder#external-storage

**Comment by Rello** [comment]
Hello,
a little reminder here.

1. Did you see the files in the Files app?
2. Did you made a scan of the external storage?

Audio Player will only see whatever is "known" to Nextcloud. it will not do a file level scan

**Comment by jimmy5670** [comment]
Yes, I can browse all files in external storage, and use command line to scan all user's files.
But still can't see the media files, I try to use original storage the music files, looks Audio Player can scan these files as usual.

I'm using the external storage location is mount by linux and set to readonly, is that the reason why Audio Player can't see any music files in this external storage?

**Comment by Rello** [comment]
Hello,
if Nc can access the files, Audio Player should also.
can you run a scan `occ audioplayer:scan username --debug` and let uns know what is being shown there?

**Comment by jimmy5670** [comment]
Hello:
after I run audioplayer:scan command, it shows all music files,
and show following begging message below:

```
Start scan for guest
Scanned Folder: /guest/files/Music
Total audio files: 19635
Checking all files whether they can be skipped

list all music file..... *.mp3 => already indexed
(many files route has chinese folder name or chinese filename. for example:
1142639 - /guest/files/Music/純演奏表演音樂/心靈音樂館═閒情聽茶系列═香飄水雲間/8  雲間幽徑香~峨嵋蛾蕊茶.mp3  => already indexed)

Final audio files to be processed: 17543
Start processing of ID3s
```

but in the web interface still shows zero files found.

![default](https://user-images.githubusercontent.com/30663643/29697132-dabc5602-897f-11e7-9690-14b55e3c5585.png)

**Comment by Rello** [comment]
Hello,
can you please get in contact with me via email?
audioplayer -at- scherello -dot- de

**Comment by jimmy5670** [comment]
Yes, I send a message via mail already.

**Comment by Rello** [comment]
Issue was related to a corrupt file
