### ISSUE TITLE
support multimedia keys on my keyboard

### ISSUE THREAD

**Issue by MichaelSp** [Rello/audioplayer#228]
### Expected behavior
When I press on my keyboard the multimedia keys for
Starts/Stops Playback 
Next/Prev song

The Nextcloud-Player should perform the requested action

### Actual behavior
iTunes opens... (on mac)

### Steps to reproduce the behavior
1. open music 
2. start playback
3. press "next song" key on your keyboard

### Possible solution (optional)
http://www.streamkeys.com

**Comment by Rello** [comment]
Hello,
Audio Player supports keyboard keys:

Space = play/pause
arrow right/left = forward/backwards
shift arrow up/down = volume up/down

if you manage to remap your keys via streamkeys to these, it should work.
any other user specific solution would technically not really make sense.

thank you for your request

**Comment by ghost** [comment]
> Streamkeys is a Chrome extension only.

Another reason to not invest work in this.

**Comment by MichaelSp** [comment]
Streamkeys is only a possible solution! Just to show how it works...
Please reconsider this feature.

**Comment by MichaelSp** [comment]
additionally the keyboard keys are only supported, if tab is open and focused. The global multimedia keys works always

**Comment by Rello** [comment]
Hello,
this would require specific add-ins for Chrome, Firefox and so on. This complexity can not be handled and maintained by Audio Player.
Feel fee to offer the functionality as an Audio Player plugin
