### ISSUE TITLE
Doesn't play the selected track

### ISSUE THREAD

**Issue by jasonbayton** [Rello/audioplayer#229]
### Expected behavior
Clicking on a track plays that track

### Actual behavior
It will usually play another track in the list or just repeat the current track when clicking elsewhere.

### Steps to reproduce the behavior
1. Select an album
2. Click a track to play

### Additional information (optional)
AudioPlayer 2.1.0

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Audio Player version:** (see `/settings/apps`)
2.1.0

**Where did you install Audio Player from:**
Store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Win10/Ubuntu

**Browser:**
Chrome

#### Nextcloud/ownCloud log

The only error entry I see:
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_audioplayer_statistics` (`user_id`,`track_id`,`playtime`,`playcount`) VALUES(?,?,?,?)' with params ["jason", null, 1504307505, 1]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'track_id' cannot be null/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)/var/www/html/apps/audioplayer/lib/Controller/CategoryController.php - line 461: Doctrine\DBAL\Statement->execute(Array)[internal function] OCA\audioplayer\Controller\CategoryController->setStatistics(NULL)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\audioplayer\Controller\CategoryController), 'setStatistics')/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\audioplayer\Controller\CategoryController), 'setStatistics')/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\audioplayer...', 'setStatistics', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/lib/base.php - line 1004: OC\Route\Router->match('/apps/audioplay...')/var/www/html/index.php - line 48: OC handleRequest(){main}
--
```

</details>

![weirdaudioplayer](https://user-images.githubusercontent.com/3178412/29990690-075d382a-8f75-11e7-8275-8bf02aacd7b2.gif)

**Comment by Rello** [comment]
@jasonbayton 
thank you for reporting your issue.

is the error reproducible? I expect that when changing the category or selecting another folder, the playlist is reset and working again?

I am seing your issue from time to time and the player coding gets more stable with every release. but it seems that there is some exception, which is still not caught.

every hint to reproduce it, is very welcome

**Comment by jasonbayton** [comment]
I too can't reproduce it reliably. Logs are clean and it appears to otherwise work fine.
