### ISSUE TITLE
Support non ascii filenames

### ISSUE THREAD

**Issue by pythonimus** [Rello/audioplayer#23]
Every non ascii character get displayed as an "?".
Most of my filenames are only displayed as "???????????".

**Comment by Rello** [comment]
can you please give me more details - or provide a testfile for debugging?
I did some tries (Thai letters here) and everything is working. is the file correclty displayed in the file-app?
![screen shot 2016-08-01 at 20 48 50](https://cloud.githubusercontent.com/assets/13385119/17305175/87ab1166-5829-11e6-91fc-cbc37f0f77a7.png)

**Comment by pythonimus** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1097383/17310485/0ed958da-5845-11e6-8eeb-a0b70ee65dc3.PNG)

Title is: 脳内シナプスの叛逆, album is: アシンメトリーカラーズ in UTF-16

**Comment by Rello** [comment]
Hey,
I successfully tested it with the current version and can not reproduce the problem.
1.0.2 will be released the next days. please retry then and let me know.

I will reply to this issue when its available in the app-store

![screen shot 2016-08-02 at 17 44 55](https://cloud.githubusercontent.com/assets/13385119/17335096/0b857e68-58d9-11e6-84db-904a124f6594.png)

**Comment by Rello** [comment]
1.0.2 was pushed to the app-store
please give it a retry

**Comment by pythonimus** [comment]
Updated to 1.0.2.
Deleted Database and re-scanned.
Some get displayed correctly, some as gibberish and some with question marks.
Here are some samples: https://www.dropbox.com/s/rk50eetlxtzhx54/nw.zip?dl=0

**Comment by pythonimus** [comment]
Anything new on that issue?
Still the same for 1.0.3.

**Comment by Rello** [comment]
Hey,
Is this your tweet?

**Comment by Rello** [comment]
Hello,
I fixed an error with the getID3 Library.
it was still refering to an outdated version in CORE.
now the most recent version within audioplayer is used

Does this look ok?
=> Version 1.1.0
![screen shot 2016-08-15 at 20 21 16](https://cloud.githubusercontent.com/assets/13385119/17674480/fa4e3020-6325-11e6-8e99-f39a0d9b0c68.png)

**Comment by pythonimus** [comment]
Thanks! Works on 1.1.0.
