### ISSUE TITLE
Error while Scanning

### ISSUE THREAD

**Issue by Dani22m** [Rello/audioplayer#230]
### Expected behavior
Audioplayer can search for new songs

### Actual behavior
scan for new songs run into an error

### Steps to reproduce the behavior
execute: `sudo -u wwwrun php occ audioplayer:scan --all`

### Server configuration
**Operating system**:
Openseuse 42.1 Linux 4.1.36-44-default on x86_64

**Web server:**
Apache version 2.4.16

**Database:**
MySQL version 10.0.29

**PHP version:**
7.1.7

**Nextcloud/ownCloud version:** (see `/status.php`)
13.0.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Audio Player version:** (see `/settings/apps`)
2.1.0

**Where did you install Audio Player from:**
From integrated Nextcloud "App-Store"

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
local /home/medien/Musik

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**

**Browser:**

#### Nextcloud/ownCloud log
Nothing in the Logfile.
But error message on the console:
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
An unhandled exception has been thrown:                                                                                                     
ArgumentCountError: Too few arguments to function OCA\audioplayer\Controller\ScannerController::scanForAudios(), 3 passed in /srv/www/htdocs
/nextcloud/apps/audioplayer/lib/Command/Scan.php on line 77 and exactly 5 expected in /srv/www/htdocs/nextcloud/apps/audioplayer/lib/Control
ler/ScannerController.php:439                                                                                                               
Stack trace:                                                                                                                                
#0 /srv/www/htdocs/nextcloud/apps/audioplayer/lib/Command/Scan.php(77): OCA\audioplayer\Controller\ScannerController->scanForAudios('Javakur
s', Object(Symfony\Component\Console\Output\ConsoleOutput), false)                                                                          
#1 /srv/www/htdocs/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\audioplayer\Command\Scan->execute(Object(Symfony\Compone
nt\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                        
#2 /srv/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Co
mponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                   
#3 /srv/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\a
udioplayer\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))        
#4 /srv/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Comp
onent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                     
#5 /srv/www/htdocs/nextcloud/lib/private/Console/Application.php(170): Symfony\Component\Console\Application->run(Object(Symfony\Component\C
onsole\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                            
#6 /srv/www/htdocs/nextcloud/console.php(92): OC\Console\Application->run()                                                                 
#7 /srv/www/htdocs/nextcloud/occ(11): require_once('/srv/www/htdocs...')   
```

</details>

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. we did the first tests with NC13 already, but this one we did not recognize.
basically a function has additional parameters due to NC13 compatibility. Here the occ also needs to be taken care off.

https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L439

I will take care of it...

**Comment by Rello** [comment]
one addition: the scan via the web interface should work

**Comment by Dani22m** [comment]
No. The Webscan also doesn't work. The Webscan stop everytime at one file. Without any errormessage on screen or in the error log.

**Comment by ghost** [comment]
> The Webscan also doesn't work.

At _your_ instance. Generally it works.

> The Webscan stop everytime at one file.

Then it is _mostly_ a problem with the _file_, not with the Audio Player.

Remark: Nextcloud 13 is in an early alpha state. The current version is **13.0.0.3** (`13.0.0 alpha Build:2017-09-14T22:01:19+00:00`). We're looking forward to the feedback after a beta version was released.

**Comment by Rello** [comment]
a quick test with the current NC13 tested the scanner successfully.
please report back if you still have the issue with the upcoming AP 2.2.0 and a NC beta release.

thank you
