### ISSUE TITLE
? icon by missing artwork tag

### ISSUE THREAD

**Issue by puntorosso** [Rello/audioplayer#232]
### Expected behavior
When the mp3 doesn't have an artwork the mp3 player should display an empty space

### Actual behavior
If the mp3 doesn't have an artwork an error icon "?" appears

### Steps to reproduce the behavior
1. Upload an mp3 without embedded artwork
2. Share it
3. Open the shared link

### Additional information (optional)
This old problem has been corrected in the previous AudioPlayer version, but the actual release shows again the error icon.

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0.2 to 12.0.3

**Audio Player version:** (see `/settings/apps`)
2.1.0

</details>

**Comment by Rello** [comment]
Hello,
can you please post a screenshot of your issue?
you are referring to the share-screen. 
The cover art on the share screen is generated by Nextcloud server - not the AP. We don´t have any influence there.

**Comment by ghost** [comment]
Closed due to lack of info.
