### ISSUE TITLE
syntax error in /audioplayer/lib/Controller/ScannerController.php ?

### ISSUE THREAD

**Issue by Patlol** [Rello/audioplayer#235]
### Expected behavior
execution of the command occ

### Actual behavior
php syntax error message in audioplayer lib

### Steps to reproduce the behavior
```
sudo -u www-data /var/www/owncloud/occ -V
PHP Parse error:  syntax error, unexpected ';', expecting ')' in /var/www/owncloud/apps/audioplayer/lib/Controller/ScannerController.php on line 539
```

### Possible solution (optional)
in source i see on line 539:
```
for ($i = 0; $c < count($keys); $i < $c; $i++) {
                                        if (isset($ThisFileInfo['comments'][$keys[$i]][0]) and rawurlencode($ThisFileInfo['comments'][$keys[$i]][0]) !== '%FF%FE') {
                                                $year = $ThisFileInfo['comments'][$keys[$i]][0];
                                                break;
                                        }
```
i don't know this syntax: `( $i = 0; $c < count($keys); $i < $c; $i++)`

But I could be wrong

### Server configuration
**Operating system**:
debian 8

**Web server:**
apache2

**Database:**
mariadb

**PHP version:**
5

**Nextcloud/ownCloud version:** (see `/status.php`)
oc 10.02

**Updated from an older Nextcloud/ownCloud or fresh install:**
 fresh install

**Audio Player version:** (see `/settings/apps`)
2.2.0-alpha2

**Where did you install Audio Player from:**
https://github.com/Rello/audioplayer/archive/master.zip

**Comment by Rello** [comment]
Hello,
Thank you for the hint. This is known but not yet fixed. 
Please dont open tickets for alpha releases. They have frequent changes and are not stable.
Please wait at least for the beta.

Thank you
