### ISSUE TITLE
Audio Player does not scan for new files

### ISSUE THREAD

**Issue by pieter-groeneweg** [Rello/audioplayer#238]
When I run a cron job to scan all audio files, nothing happens.
When I scan for new audio with the scan button in the app, nothing happens.

Both ways it says it found new audio files. (top of sceen) but I can't see any new in the list.

Checking through "files" shows all audio files allright.

### Expected behavior
scan all user accounts for music files

### Actual behavior
scans only a few users. 
but shows no new audio

### Steps to reproduce the behavior
1. setup cron job - sudo -u www-data php occ audioplayer:scan --all
2. run cron job
3. see the output

1. click scan button and start scan.
2. see the progress bar appear
3. progress bar is stuck to 0%

### Server configuration
Debian 9
Apache
MySQL
PHP7
Nextcloud 12 upgraDed from 11
latest version of Audio Player
Installed from app store
local /mnt/nas/data
No encryption

Nothing in the logs

**Comment by Rello** [comment]
Hello,
please run the command with the --debug option in the console and let us know what the output is.
`sudo -u www-data php occ audioplayer:scan --all --debug`

Thank you for your support

**Comment by pieter-groeneweg** [comment]
Running with --debug:
At first it got stuck at an mp3 named "07 - At Arthur's court.mp3".
I figured it could maybe have something to do with the '. Though there were previous scanned mp3's with the same name. Anyway....
So I renamed to "07 - At Arthurs court.mp3"

Ran with --debug again.

Now it surprisingly scanned all audio files remaining even beyond the above file that still was considered having the name "07 - At Arthur's court.mp3".
Which was now tagged with: Error with getID3. Does not seem to be a valid audio file.
At least it continued.

I have several files now tagged with: Error with getID3. Does not seem to be a valid audio file but the most surprising, with another user that has the same audio files shared, it was scanned as "07 - At Arthur's court.mp3"  with the '. No errors... 

any thoughts?

**Comment by Rello** [comment]
Hello,
thank you for the feedback.
first, the " ´ " should not make any difference because this does not matter during the scan. we only check the ID3 and this is unicode compatible

in your case that very file caused the scanner to stop (or wait). if the file could not be read, the "error with getID3" should be shown and then continued.
did erything complete now or did you have any other issues?

**Comment by pieter-groeneweg** [comment]
Yes it did but for the nunch of ID3 errors.
Though I can play the mp3's and m4u's that errored out in the "files" app.

**Comment by Rello** [comment]
Hello,
Do you have the file several times shared/reshared? Why would you correct one and still find others?
If they would be the same file, they should not even be scanned as they are dublicates.

Any other hint to narrow down the issue?
I dont really have an answer yet

**Comment by ghost** [comment]
Closed due to lack of info.

**Comment by pieter-groeneweg** [comment]
plse reopen. No the files are not reshared.
They are on an external storage though, but the files app shows everything.
It continues to stop at the same file.
I do have all these Id3 errors but the files are still playable and tags look ok in any other mp3 player or editor...

**Comment by pieter-groeneweg** [comment]
I did "repair" all audio files. Still there are some that show this id3 tag error. But these are skipped in the scan... don't know why as the tags look fine in any other player.. 

but still the scan halts at the file I mentioned above.
Though I can play this same file from the "files" app. (Listening to it now. :D )

Even if it is a faulty file, shouldn't it not just give a warning and then continue with the rest?

**Comment by Rello** [comment]
Hello,
when the scanner breaks completely, you should have entries in the nextcloud.log
please check there.

if you would send/share the file to `audioplayer*at*scherello*dot*de` I could check the details.
in general you are correct - a faulty file should be skipped and not break everything

**Comment by ghost** [comment]
Closed due to lack of info.
