### ISSUE TITLE
Search for cover in album folder

### ISSUE THREAD

**Issue by pythonimus** [Rello/audioplayer#24]
It would be nice if the player would search for a cover/folder.jpg/png in the album folder, and use this as the cover.

**Comment by microcreators** [comment]
+1
a lot of cover art is missing (although I'm pretty sure it's in tags). considering any external JPG / PNG files would do the trick!

**Comment by Rello** [comment]
followup in Roadmap,
will be reopened when work is started

**Comment by Rello** [comment]
Implementation was started...

**Comment by Rello** [comment]
#97

**Comment by Rello** [comment]
the following search sequence is being used:

1. folder.jpg
2. folder.png
3. cover.jpg
4. cover.png

# Tests to be performed:
- [x] single file of 1-4 in one folder => file is chosen
- [x] folder & cover in one folder => folder is chosen
- [x] single file in folder and audio title with ID3 cover => ID3 is chosen
- [x] other image in folder => none chosen
- [x] folder.jpg with defect image date => error is caught
- [x] info in occ --debug => "Alternative album art: file..."
