### ISSUE TITLE
Support for WebM audio files

### ISSUE THREAD

**Issue by Victorsueca** [Rello/audioplayer#240]
This is a feature request to support .webm audio files. WebM is a open, lightweigh and quality format for video and audio which is quickly spreading all across the internet since it is easy to insert in web pages and is supported by most of the modern browsers.

You can read more at [https://www.webmproject.org/](https://www.webmproject.org/)

**Comment by ghost** [comment]
Thanks for requesting this feature! The limited resources and the low demand for this feature at the moment force us to decide against an implementation.
If we decide to work on it in the future, we will reopen the issue. See #39
