### ISSUE TITLE
Error in displaying "&" special characters

### ISSUE THREAD

**Issue by Larsene** [Rello/audioplayer#244]
### Expected behavior
Display the & character normally

### Actual behavior
1 character is replaced by his html code :  &amp; 

### Steps to reproduce the behavior
1. add an album that contain the & character in his title
2. open it AP

### Additional information (optional)

![audioplayer-bug](https://user-images.githubusercontent.com/8544729/31297091-fef8e3a6-aae4-11e7-979c-cc191d101eaa.jpg)

**Comment by Rello** [comment]
Hello,
I can not reproduce the error
![screen shot 2017-10-07 at 22 06 38](https://user-images.githubusercontent.com/13385119/31311413-e5f7eb6e-abab-11e7-9653-00f36145d7a6.png)

can you check the file itself with a metadata-editor if there is something special in the Album Title?

**Comment by ghost** [comment]
Closed due to lack of info.
