### ISSUE TITLE
Audio Player doesn't add music files from local external storage

### ISSUE THREAD

**Issue by roukydesbois** [Rello/audioplayer#245]
### Expected behavior
I set up an external storage in the administration of Nextcloud, of type local, I added myself as a user who can access it, still in the administration, and it works fine in the Files app as I see everything. I set up in the Personal page this very folder in the Audio Plater settings. I start scanning for music files, be it in the GUI or via the occ command, and my music files are recognised.

### Actual behavior
Everything mentioned above, except that my music files are not recognized by Audio Player

### Steps to reproduce the behavior
1. Add a local external storage in the admin
2. Give access to user
3. Set up this folder in the Audio Player settings
4. Scan the library in the GUI or via occ

### Server configuration
**Operating system**:
Debian Jessie (arm) (Nextcloud install via Yunohost)

**Web server:**
nginx

**Database:**
mySQL

**PHP version:**
5.6.30-0+deb8u1

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Audio Player version:** (see `/settings/apps`)
2.1.0

**Where did you install Audio Player from:**
Nextcloud app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
yes, local

**Are you using encryption:**
no

### Client configuration
**Operating system:**
Debian Stretch

**Browser:**
Firefox

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
can you please do an occ scan with the --debug parameter and post the output here?
thank you

**Comment by roukydesbois** [comment]
There you go:

legolas@ynh:/var/www/nextcloud$ sudo -u nextcloud php occ audioplayer:scan thomas --debug
[sudo] password for legolas: 
Start scan for thomas
Scanned Folder: /thomas/files/Musique Partagée
Total audio files: 0
Checking all files whether they can be skipped
Final audio files to be processed: 0
Start processing of ID3s
Audios found: 0
Duplicates found: 0
Written to music library: 0
Albums found: 0
Errors: 0

Could it be the space or the special character in the folder name? (Nope, just tested SharedMusic as folder name and it didn't work either)

**Comment by ghost** [comment]
@roukydesbois Does your audio files on the external storage accessible in the Files app without any problems?

**Comment by roukydesbois** [comment]
Yes, I can browse them, see them all, download them, no problem at all!

**Comment by Rello** [comment]
Hello,
could there be a mimetype issue?
what are those files? mp3? are they recognized with a tone (note) symbol in the files app?
when you press the 3 "..." to open the context menu, do you see the audioplayer icon including the "Play/Abspielen" link?

**Comment by roukydesbois** [comment]
That was it! I did a maintenance:update-db --repair-filecache and everything is working now! Thanks @Rello you rock!
