### ISSUE TITLE
CSS issue - X looks clipped off

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#247]
### Expected behavior
The close X on the rescan popup looks nice.

### Actual behavior
The close X on the rescan popup is clipped off.

### Steps to reproduce the behavior
Press the rescan button and look at the X.

### Possible solution
Remove these 2 tags from the .ui-button-icon-only / .ui-icon CSS:
left: 50%;
margin-left: -8px;

This is the original:
![original](https://user-images.githubusercontent.com/15927695/31862393-84bd644e-b73d-11e7-863f-555cc0e6bcce.png)

This is the corrected version by me:
![corrected](https://user-images.githubusercontent.com/15927695/31862396-87eb3e8e-b73d-11e7-9c39-bee3499fe279.png)

### Server configuration
**Nextcloud/ownCloud version:**
12.0.3

**Audio Player version:**
2.1.0

**Where did you install Audio Player from:**
Nextcloud apps

**Are you using external storage:**
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Ubuntu 17.10, Windows 10

**Browser:**
Firefox

**Comment by ghost** [comment]
The same with the reset popup. ;-)

**Comment by Rello** [comment]
hello,
thank you for the input!

I will search for the details. Issue is, that this is a core css which can not be changed by audio player. 
But we will find a solution...
