### ISSUE TITLE
purge nextcloud from entries of music files

### ISSUE THREAD

**Issue by pieter-groeneweg** [Rello/audioplayer#248]
I want to start a new with a complete new set of mp3 files.
Is there a way to purge nextcloud and completely scan from scratch?

**Comment by Rello** [comment]
Hello,

please use the trash-Icon in the first row of the sidebar (next to Albums).
this will completely empty all AP-Tables.
Afterwards, use the rescan.

alternatively please check the wiki here for occ
https://github.com/rello/audioplayer/wiki/occ-command-line

please let us know if you need more information
