### ISSUE TITLE
Music-Progressbar is shifted to the right

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#249]
### Expected behavior

To skip to the desired position on the Music-Track. clicking the Slider and sliding over the timeline to the desired position and letting it go where is needed.

### Actual behavior

On clicking on the Slider, the Slider put itself like 100-pixel off to the right from the mouse-position and use this position to navigate trough the musik-track.

### Steps to reproduce the behavior
1. Open Music-Player with any music-title
2. click the Timeline-Slider with your mouse
3. profit ... ehm ... the slider positions itself off to the right.

### Possible solution (optional)

faulty calculations within the JS-Code -> Recalculating where the Pointer should actually be?
It's definitely a Frontend-Problem and only for the slider in the JS-Code.

### Server configuration
**Operating system**: Linux - Ubuntu 16.04

**Web server:** Apache2

**Database:** PostgreSQL

**PHP version:** ~ 7.2

**Nextcloud/ownCloud version:** Nextcloud

**Updated from an older Nextcloud/ownCloud or fresh install:** Freshly Installed, but updated via Updater

**Audio Player version:** 2.1.0

**Where did you install Audio Player from:** NextCloud's "Apps"-section

**Are you using external storage, if yes which one:** Nope

**Are you using encryption:** Nope

### Client configuration
**Operating system:** Windows 10 x64

**Browser:** Opera vers. 48.0 Stable

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by xraMsamohT** [comment]
Duplicate of #111

**Comment by ghost** [comment]
It's not 100 px, but 250 px – the width of the sidebar. It also affects Opera.

**Comment by ghost** [comment]
Oh, Sorry. Didn't knew this was called sidebar ... :-/

**Comment by ghost** [comment]
No problem. Until we fixed this bug hide the sidebar while playing. It should occur only when the sidebar is open.

**Comment by ghost** [comment]
Ah, Thanks!
