### ISSUE TITLE
Cannot control play/stop action when scolling down

### ISSUE THREAD

**Issue by sbr9150** [Rello/audioplayer#25]
# Cannot contorl play/stop action when scolling down, Could you keep the control section always on the top position and won't scorll up with files.

![ncaudioplayer-2](https://cloud.githubusercontent.com/assets/11934046/17280514/14f18f16-57c4-11e6-9557-166560eb9d7c.png)

**Comment by Rello** [comment]
various CSS modifications

**Comment by Rello** [comment]
1.0.2 was pushed to the app-store
