### ISSUE TITLE
Can't read Arabic and can't update the metadata

### ISSUE THREAD

**Issue by alahwany** [Rello/audioplayer#250]
#
![capture](https://user-images.githubusercontent.com/14204438/32172852-bdc9a682-bd85-11e7-9b90-c78748f41905.JPG)
Hello,

i have a problem with audio player for reading arabic language and can't update the metadata with new info. in english or others language.

**Comment by ghost** [comment]
Thanks for reporting this issue! Please fill in the [issue template](https://github.com/rello/audioplayer/blob/master/.github/ISSUE_TEMPLATE.md) as complete as possible.

**Comment by ghost** [comment]
Please note that no support is provided for the Metadata editor. The editor will probably be removed from the app in a future version.

**Comment by alahwany** [comment]
thank you very much for your reply.
anyway it's not important to fix it if the app in a future will be removed but i hop in future can reading arabic language.

**Comment by ghost** [comment]
I wrote about the editor part of the Audio Player app, not the whole app! We prefer to use an external metadata editor instead of the embedded very limited ID3 editor without VorbisComment support.
For an investigation of your problem please fill out the template and provide an example audio file.

**Comment by Rello** [comment]
Hello,

could you please send or share one of these titles to `audioplayer*at*scherello*dot*de`
you definitely have a codepage issue there which I would double check

**Comment by alahwany** [comment]
sorry bro.  for my late.

my server
OS: Centos 7 with CPanel Latest version 
PHP7 with Apache2
nextcloud 12

i don't see any error in logging under admin page 

about your question 
"could you please send or share one of these titles to audioplayer*at*scherello*dot*de"
you want to know the arabic word for title in my mp3 ?

**Comment by Rello** [comment]
Hey,
I meant, please send the file with the error to my via email to audioplayer_at_scherello_dot_de

**Comment by ghost** [comment]
Closed due to lack of info.
