### ISSUE TITLE
Show mouse-over descriptions for buttons

### ISSUE THREAD

**Issue by tflidd** [Rello/audioplayer#252]
### Expected behavior

When I move the mouse on the shuffle, repeat, play, ... button, I'd like to show a text with a description. Play and pause are quite obvious, but the '>>' button it is not clear if you just fast-forward in the current song or if you skip this song.
Also shuffle and repeat, could be clear and are quite similar, but a nice mouse-over description would be better.

### Actual behavior
You have to click and see what happens. Not everybody has so much courage ;-)

version from current master: 49a17609202087adb477f94303637f3952742f80

**Comment by ghost** [comment]
> but the '>>' button it is not clear if you just fast-forward in the current song or if you skip this song

I'm with you with the media player buttons, because &#9193; is usually `FFWD` and &#9197; is usually `SKIP/NEXT`.
It looks like this is still a bug from the former _MP3 Player_ app.

We think on replace SoundManager 2 in a future version.

**Comment by Rello** [comment]
Hello,
thank you for reporting this issue.
Actually there are tooltips available for the buttons - but they don´t seem wo work right now.
Good finding...

I will have a look at this

**Comment by Rello** [comment]
icons were cleaned up and tooltip was corrected
![screen shot 2017-11-06 at 11 32 04](https://user-images.githubusercontent.com/13385119/32575261-c9997082-c4d3-11e7-947f-d2434253bb9b.png)

**Comment by Rello** [comment]
due to compatibility issues with the implementation of jquery tooltips on mobile devices, the tooltips were deactivated for the moment. we will investigate later
