### ISSUE TITLE
Scanbar freeze

### ISSUE THREAD

**Issue by olinox14** [Rello/audioplayer#254]
First of all: thanks for this app, it's a very good work!

I would like to report a bug with the progress bar of the scanner, it occasionnally freeze while scanning large number of files (cf. picture)
![nextcloud_audiop_prog_freeze](https://user-images.githubusercontent.com/15560057/32746949-87260fc0-c8b7-11e7-9fc3-3bbfcd56428f.PNG)

### Expected behavior
Progress bar keep going to 100%

### Actual behavior
Progress bar randomly stop while scanning.

### Steps to reproduce the behavior
1. Not sure how, but scan a large library of audio (only mp3) files)
2. Wait...

### Additional information (optional)
Here is an error I get from the console:
"Content Security Policy: Page's parameters prevented the load of a resource to self (« script-src 'nonce-dHl0Uk4xVjV1OHdraERDZDRuWlRCbU16djFIdXEwYzd4SWNkNVc0cjVSND06KzFnb1J4TUkrZWQzelg3MW8wRm5UeGNDMUNXQy9DMEpnTFYzdERrWTFrdz0=' 'unsafe-eval' »). Source: onsubmit attribute on FORM element."

AH! And cancelling and restarting works.

### Server configuration
**Operating system**:
Raspbian (Debian 9)

**Web server:**

**Database:**
Pgsql

**PHP version:**
7.0

**Nextcloud/ownCloud version:** (see `/status.php`)
nextcloud 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Audio Player version:** (see `/settings/apps`)
?

**Where did you install Audio Player from:**
from store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
ntfs extrnal drive

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
windows 10, x64

**Browser:**
Firefox

#### Nextcloud/ownCloud log
nothing relevant

**Comment by Rello** [comment]
Hello,
thank you for contacting us. do you not have anything in nextcloud.log?
if it freezes 
* it could be an indication, of a faulty audio file (which is not caught correctly)
* a performance/buffer issue when working on smb

nothing there?
what happens if you stop and restart?

**Comment by olinox14** [comment]
Yes, I got that from the nextcloud.log, but it was logged after the first crash (so after I post the issue):

{"reqId":"Zu6GRk6c1lOwu277wr65","level":3,"time":"2017-11-13T21:29:34+01:00","remoteAddr":"192.168.0.10","user":"olinox14","app":"PHP","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","message":"filesize(){"reqI$
{"reqId":"Zu6GRk6c1lOwu277wr65","level":3,"time":"2017-11-13T21:29:34+01:00","remoteAddr":"192.168.0.10","user":"olinox14","app":"PHP","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","message":"Undefined index:$
{"reqId":"7iHv9M3r7OXHQfSilyae","level":3,"time":"2017-11-13T21:30:41+01:00","remoteAddr":"192.168.0.10","user":"olinox14","app":"index","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","message":"Exception: {\"$
{"reqId":"jQzKuLYRYrXfDnnJSbD2","level":3,"time":"2017-11-13T21:37:29+01:00","remoteAddr":"192.168.0.10","user":"olinox14","app":"PHP","method":"POST","url":"\/index.php\/apps\/audioplayer\/getprogress","message":"file_get_contents(\/me$

**Comment by olinox14** [comment]
And I edited (too late) the issue to precise that it worked when cancelled/restarted... So not a big deal :)

**Comment by olinox14** [comment]
A last thing: the freeze thing happened 2 more times before I could scan the entire library. So it is not just one problematic file, and that were files from different origins / albums / date...etc.

**Comment by Rello** [comment]
Hello,
unfortunately I can´t see much we can do here.
when the scanner continues the next time, its not a faulty file and I expect some runtime/memory/buffer/open-file-pointer issue or something like that.

if you have any more findings, let us know
