### ISSUE TITLE
Delete File

### ISSUE THREAD

**Issue by drolex2** [Rello/audioplayer#255]
I would like to be able to delete a file from the Audio Player page. Then I can easily delete music that I no longer want as I listed to it.

**Comment by Rello** [comment]
Hello,
can you please give us more information?

* you can delete a music file within the file explorer completely. then it will also be removed in AP
* you can exclude whole folders with `.noaudio` files (see wiki)
* if you have a custom playlist, you can add/remove files

removing a title only from AP library would mean that with the next scan, it would be re-added.

please let us know some more background

**Comment by drolex2** [comment]
I think it would be convenient to completely delete music files from AP while listening to the music. Then if I don't like a song while I'm listening I can easily delete it for good and move on to listening to the next song. Otherwise, it is inconvenient to go find the file, delete it, and then rescan the files.

**Comment by Rello** [comment]
hello,

adding a deletion option to AP, which at the end also deletes the physical file is not a good idea as a misuse would be fatal.

The only workaround for your specific case I could think about is marking the title as favorite (one click) and then using the favorites-section in the files app to clean up if really required.

upon deletion of a file, it will be automatically removed from the AP library in the background.
what do you think?

**Comment by Rello** [comment]
closing this request.
please let us know if the workaround worked for you

**Comment by drolex2** [comment]
No it doesn't work. To bad you're not willing to communicate more.

**Comment by Rello** [comment]
we are :-)
the only thing is, that AP can not touch server-files functionality. so the only thing left is to give hints for workarounds
