### ISSUE TITLE
Support for shared audio folder

### ISSUE THREAD

**Issue by dhowe** [Rello/audioplayer#259]
I'm trying to setup a shared music folder for all nextcloud users on my server, and I'm not sure how to proceed -- the expected symlinks don't work

I get the following error in the log (NC 12.0.4, Ubuntu 16.04.3 LTS) : 

```
Error | core | Following  symlinks is not allowed ('/var/www/nextcloud/data/user/files/music'  -> '/music/' not inside '/var/www/nextcloud/data/user/')
-- | -- | --
```

Is this supported, and if so, are there docs?

**Comment by Rello** [comment]
Hello,
even so this ist not really an AP question - let me try. I am using something similar for my kids:

- all Files are available in one folder for one user - e.g. Admin or your normal user
- Then you share this folder with a group (e.g. "everyone") or every user
- Now every user can see this folder including all subsequent audio files
- After that, every user can scan within AP
- alternatively you can do an `occ audioplayer:scan --all ` for all users
- the key message is, that every user needs to see the files in his files app. everything that is visible there, is visible for AP


does this help you?
symlinks will create chaos on your backend structure...

**Comment by dhowe** [comment]
Yes, that is helpful as a workaround, thanks. But is there really no way to include items outside the nextcloud root? This is such a standard thing to do with web-folders, either by way of an alias or a sym-link

**Comment by Rello** [comment]
Hey,
not with symlinks. NC does not handle them.
I suggest you use the "external storage" app to enable these settings in the NC admin. then you can properly include local paths also (similar to SMB e.g.)

**Comment by ghost** [comment]
> are there docs?

A little hint in the Audio Player wiki:

https://github.com/rello/audioplayer/wiki/specific-media-folder#external-storage

**Comment by Rello** [comment]
closing this support request.
let us know if it worked out as expected...

**Comment by dhowe** [comment]
Thanks for the tips @Rello... I will try the "external storage" app with a local path
