### ISSUE TITLE
Volume slider not operable until file is being played

### ISSUE THREAD

**Issue by phlnx** [Rello/audioplayer#260]
Hi, this is a minor thing that has been bugging me for a while, although overall I really love audioplayer, thank you so much for your effort.

In essence, when I open audioplayer I can click play and it works but I can't lower the volume before I play anything.

It could be something that depends on bad configuration on my part, if so please ruthlessly tell me off and close the ticket.

It would also be awesome (but this is a distinct request) if audioplayer could remember the last volume setting just like it remembers the last song I played, so that I can find an adequate volume when I open the tab.

Thank you.

### Expected behavior
I can lower the volume by operating on the volume slider when I first open the player and no file is being played yet.

### Actual behavior
The value/position of the volume slider cannot be changed until a file is being played.

### Steps to reproduce the behavior
1. Open AudioPlayer
2. Do not click Play
3. Try to lower the volume

### Server configuration
**Operating system**: Debian Stretch

**Web server:** Apache 2.4.25

**Database:** mysql 15.1

**PHP version:** PHP 7.0.19-1

**Nextcloud/ownCloud version:** (see `/status.php`) Nextcloud "12.0.4.3"

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Audio Player version:** (see `/settings/apps`) 2.2.1

**Where did you install Audio Player from:** Nextcloud app store

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Not sure

### Client configuration
**Operating system:** Windows 10

**Browser:** Firefox 57.0.2

**Comment by Rello** [comment]
Hello,
thank you for the request. we will look into it

**Comment by Rello** [comment]
Released with 2.2.2

**Comment by phlnx** [comment]
Hi, I am very sorry to bother you again. I just updated to 2.2.2 (checked the status page) and my issue persists. When I open audioplayer, before I click on any file to start playing it, the volume slider is inoperable. I tried cleaning the browser cache, with no result. Am I doing something wrong?

Thanks.

**Comment by Rello** [comment]
Hello,
sorry, we commented this enhancement a little incomplete :-)
the volume button is part of the player backend, which is only initialised once a title is playing (changing this requires more change than a bugfix release).

What is did is the last sentence of your request: whatever volume you set will be remembered across AP restarts. I hope this helps your use-case also?

**Comment by phlnx** [comment]
Oh okay, that's unexpected, as 97% of this issue, including the title, describe a different problem. I have seen other members of your staff updating the title, howevever only to remove a "minor" tag I had attached. I am then confused to why this hasn't been renamed properly while you were at it...

Having said that, I can confirm that now the volume slider remembers its last position. I think this helps my situation in most cases, so thank you. I hope in time you can also implement the rest.
