### ISSUE TITLE
Nextcloud 14 compliance

### ISSUE THREAD

**Issue by MorrisJobke** [Rello/audioplayer#266]
We are dropping some constants that are deprecated for 3 years now. One of them is still used in here: https://github.com/rello/audioplayer/blob/fbf532377a07a205163e27248ad14da831b2121b/lib/Controller/EditorController.php#L73

PR: https://github.com/nextcloud/server/pull/7844

@Rello Please update your code to run it on NC 14+ too.

Please also have a look at https://github.com/nextcloud/server/issues/7827 for other dropped methods or use the app:code-check to highlight deprecated methods in the current code.

**Comment by Rello** [comment]
Hallo @MorrisJobke ,

thank you for the hint!
interestingly, I got the same warning yesterday after scruitinizer was switched to the new validator.
I will check again and we will include this in the next release
