### ISSUE TITLE
Ratings support

### ISSUE THREAD

**Issue by RedKage** [Rello/audioplayer#267]
Hello,

Saw a few tickets with this request as well.

But there will be a more general issue: owncloud enables sharing files with other users, including musics. So as a single user implementation using the POPM meta may work.
But if we are many, I don't want to see the rating of another user... right?

Which means saving the rating inside the music file is a no-go.
The ratings have to be stored per user and on a separate space, like the database.

I'd like this feature, but really it is low priority. I posted this issue more to expose my concerns than anything else!
Cheers.

**Comment by Rello** [comment]
I can not follow this request due to very limited time available at the moment.
sorry
