### ISSUE TITLE
Gapless audio playback (FLAC)

### ISSUE THREAD

**Issue by eleksnell** [Rello/audioplayer#272]
### Expected behavior
Songs from the playlist should play after one another without any noticeable silence in-between.

### Actual behavior
There is a silent gap between tracks played in the playlist.

### Steps to reproduce the behavior
1. Play songs in the playlist that are supposed to be played gapless (e.g., classical operas or similar)
2. Jump to the end of one song to experience the silent gap between this and the next song

### Possible solution
Pre-load the next song in the playlist before the current song ends and provide it to the player without interruption.

### Server configuration
**Operating system**:
Debian 9

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
5.6.30-0+deb8u1

**Nextcloud/ownCloud version:** (see `/status.php`)
installed	true
maintenance	false
needsDbUpgrade	false
version	"12.0.4.3"
versionstring	"12.0.4"
edition	""

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Audio Player version:** (see `/settings/apps`)
2.2.4

**Where did you install Audio Player from:**
App store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Arch Linux

**Browser:**
Firefox 57

**Comment by Maikewng** [comment]
+1 for this

**Comment by xraMsamohT** [comment]
@Maikewng Please use [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of posting a comment with +1 only.

**Comment by Rello** [comment]
I can not follow this request due to very limited time available at the moment.
This involves frontend buffering where I do not have any insights.
sorry
