### ISSUE TITLE
Show file path of found duplicate audio files

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#273]
### Expected behavior
It would be convenient to be able to look up the file path of the duplicate files that were found by the audio file scanner. This could be done via a collapsable list in the result popup.

### Actual behavior
Currently the scanner only shows the number of duplicates that were found.

**Comment by Rello** [comment]
makes sense. I will look at it

**Comment by efelon** [comment]
It would be sufficient for me, if the occ audioplayer:scan would output the duplicates' paths. Maybe only by providing a command line option like "-v".

Other than that I'm very happy with the audioplayer.

**Comment by Rello** [comment]
@efelon @AmonBune 
Duplicates are now shown within the scanner results

Web:
![screen shot 2018-04-11 at 22 15 13](https://user-images.githubusercontent.com/13385119/38640905-e32b119c-3dd5-11e8-9bba-c7c50b1eb349.png)

occ:
![screen shot 2018-04-11 at 22 18 05](https://user-images.githubusercontent.com/13385119/38641025-3d59cca8-3dd6-11e8-98c6-2647aff0ab70.png)
