### ISSUE TITLE
Integrity check failed on NC 13 RC2

### ISSUE THREAD

**Issue by Ark74** [Rello/audioplayer#274]
### Expected behavior
No issue with code integrity scan.

### Actual behavior
HI I'm testing NC 13R2 and i'm getting this flag about integrity code,
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- audioplayer
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [audioplayer] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
```
### Steps to reproduce the behavior
1. Install AudioPlayer on NC 12 stable
2. Change repo to Beta (NC 13 rc2)
3. Run upgrade and initial integrity code scan

### Possible solution (optional)
Update signature(?)

### Server configuration
**Operating system**:
*buntu 16.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
7.0 (os-stack) <br/>
_PHP 7.0.22-0ubuntu0.16.04.1_

**Nextcloud/ownCloud version:** (see `/status.php`)
13.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.4

**Audio Player version:** (see `/settings/apps`)
2.2.3

**Where did you install Audio Player from:**
Appstore

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
None

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Trisquel 8

**Browser:**
Abrowser 57.0.4

**Comment by Ark74** [comment]
No way!
Just right after I submitted this issue, there was already an update available. 2.2.4 which fixed this issue.
Thanks.

**Comment by ghost** [comment]
@Ark74 Version 2.2.4 was released [3 days ago](https://github.com/Rello/audioplayer/releases/tag/2.2.4). ;-)

**Comment by Ark74** [comment]
I see that, don't know why my nc is lazy in checking that stuff. xD
Also I just upgraded to nc 13 yesterday.

**Comment by Ark74** [comment]
Thanks

**Comment by ghost** [comment]
> Also I just upgraded to nc 13 yesterday.

Please note that the playlist issue (#270) may not be resolved until the release of Nextcloud 13.
