### ISSUE TITLE
No metadata information shown

### ISSUE THREAD

**Issue by saspol** [Rello/audioplayer#275]
### Expected behavior
After update Nextcloud to 12.0.5 metadata information not shows when player on single file share.

### Actual behavior
On 

### Steps to reproduce the behavior
1. Share mp3/flac file
2. Go to the link
3. 

### Additional information (optional)
https://monosnap.com/file/UQ1IZNgIaAk66SNt1fyoMm0pDZiePr.png

### Server configuration
**Operating system**:
Ubintu 16.04 MIPS

**Web server:**
Apache 2.4

**Database:**
MYSQL

**PHP version:**
7.0

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Audio Player version:** (see `/settings/apps`)
2.2.5

**Where did you install Audio Player from:**
From Nextcloud app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
OSX Sierra

**Browser:**
Firefox 57

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
is this title part of your scanned library in AP?
because the ID3 information shown in the share player is being read from the AP tables - not the file itself every time

**Comment by saspol** [comment]
Hi,
When player playing file i suppose it show me some metadata. Why it cannot be taken on the fly? 
Actually i do file upload and share by NextCloud API, and get share URL directly to my clipboard. How i must update this AP 'library' and 'tables'?

**Comment by Rello** [comment]
Hello,
the shareplayer does only access audio player tables.
the shareplayer was adjusted that ID3 information (including headlines) is only shown if data is actually available.
on-the-fly ID3 extraction is not planned.

this avoids that empty lines are being generated
