### ISSUE TITLE
PHP 7.2 Support

### ISSUE THREAD

**Issue by janarzz** [Rello/audioplayer#277]
Hey,
when coming PHP 7.2 support ?

**Comment by janarzz** [comment]
Hey, can anybody tell me..when coming PHP 7.2 support ?

**Comment by Rello** [comment]
will be added in the next release

**Comment by szzr** [comment]
Hey, when coming new release ?

**Comment by Rello** [comment]
hey,
still need some time. working on the open issues & the new sidebar (right side)

**Comment by janarzz** [comment]
I still waiting php 7.2 support :(
I cannot use this plugin while i using PHP 7.2 :(

**Comment by ghost** [comment]
Use the GitHub repo where PHP 7.2 is activated.

**Comment by janarzz** [comment]
Hey,
i downloading audioplayer GitHub version, but still not work.
audiopayer 2.3.0-beta.4
App "Audio Player" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 7.1 is required.
