### ISSUE TITLE
Optimizations for large collections

### ISSUE THREAD

**Issue by psy-q** [Rello/audioplayer#279]
### Expected behavior

The music list loads in under 5 seconds.

### Actual behavior

The music list loads in 20 - 30 seconds.

### Steps to reproduce the behavior
1. Index a large collection (e.g. 90000 songs)
2. Log out and back in, just to be sure
3. View the audio player. The initial load will take perhaps 20, 30, 40 seconds while a rotating icon is shown on the right. The browser may think the page has stalled and ask whether the page should be terminated.

### Server configuration
**Operating system**:
Debian GNU/Linux 9.

**Web server:**
Apache 2.4.25.

**Database:**
MariaDB 10.1.26.

**PHP version:**
PHP 7.2.2.

**Nextcloud/ownCloud version:** (see `/status.php`)
13.0.

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh.

**Audio Player version:** (see `/settings/apps`)
2.2.5.

**Where did you install Audio Player from:**
Store.

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No.

**Are you using encryption:** yes/no
Not on this machine (it's a test).

### Client configuration
**Operating system:**
Debian GNU/Linux 9.

**Browser:**
Firefox 58.0.2.

Nothing useful in the logs, so not attached.

**Comment by ghost** [comment]
Audio Player is not designed for such a large music collection. There's no solution atm.
After initial scan use a category from the selection within the sidebar instead of the graphical album view.

**Comment by xraMsamohT** [comment]
Duplicate of #237

**Comment by Rello** [comment]
Hello @psy-q 
to check back on your issue: the graphical Albums-View will not work with such a big library as the metadata transferred in the back is quite big. We don´t habe page-loading implemented (yet).

I would like to know how AP acts when you use the category filter from the drop down on the left.
are the lists coming up in a reasonable time?

please let us know...

**Comment by Rello** [comment]
#124

**Comment by psy-q** [comment]
Hi @rello, sorry that I didn't see that previous ticket yet.
With the filter pull-down on the left everything performs nicely, usually 30 - 50 ms per request, sometimes 600 (e.g. when fetching artist list initially, further requests for the artist list are 100ms). 
I might actually be able to make it work this way, although the long rotating arrows initially might be confusing for users.

**Comment by Rello** [comment]
@psy-q 
do you have an NC setup where you could test the current AP beta version?
we made a HUGE step forward. Cover-View for all and **BIG** UI  + scanner speedup

would like to hear some feedback from you guys with the big libraries if possible...

**Comment by psy-q** [comment]
Thank you, a collection of about 9700 tracks can now be indexed fine :)  The artist list (on the left side) works too, it loads in just a few seconds.

The page itself seems to load in about 2.44s for me according to the Network tab of developer tools in Firefox, but there is nothing actually displaying on the right-hand side. No album thumbnails but there is a rotating loading indicator.

![image](https://user-images.githubusercontent.com/87557/63585114-a8435380-c59e-11e9-9100-534da73ea917.png)

This was because 128 MB memory_limit is not enough in this situation, it fails with:

```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) at /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#182
```

Increasing to 512 MB makes it work fine. I haven't found the sweet spot for memory size but I can leave it at this. Thanks for the great work!

**Comment by Rello** [comment]
Ok, thank you. The memory thing has room for improvement - but there I need to touch the DB

Do you have comparison old/new values (seconds) between the AP versions?

**Comment by psy-q** [comment]
No, unfortunately my old setup is long gone. But I remember it being so slow that it was basically unusable. Now it's zippy with 9000 songs and I expect it might also scale to 90000. I will see if I can set it up to scan 90000 songs overnight.

**Comment by Rello** [comment]
@psy-q 
I just tested a tweak of the SQL selects which should reduce the memory consumption drastically by processing the cover-evaluation right in the DB.

Could you do me a favour and set back the memory limit - and then try navigation in the UI again?
I would really appreciate the support here

**Comment by psy-q** [comment]
I stopped scanning at about 26000 tracks so I could try this. At 128 MB it would hit this:

```
[PHP] Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) at /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#182

POST /index.php/apps/audioplayer/checknewtracks
```

But at 256 MB it's a different part:

```
[PHP] Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 2097160 bytes) at /home/nextcloud/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php#484

POST /index.php/apps/audioplayer/checknewtracks
```

Then I managed to get the web interface to be unresponsive when selecting "Titles" -> "All Titles", which produced this:

```
[PHP] Error: Undefined index: Title at /home/nextcloud/nextcloud/apps/audioplayer/lib/Controller/CategoryController.php#194

GET /index.php/apps/audioplayer/getcategoryitemcovers?category=Title&categoryId=1156
```

```
[index] Error: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT  `AB`.`id` , `AB`.`name`, LOWER(`AB`.`name`) AS `lower` , `AA`.`id` AS `art`, (CASE  WHEN `AB`.`cover` IS NOT NULL THEN `AB`.`id` ELSE "" END) AS `cid` FROM `oc_audioplayer_tracks` `AT` LEFT JOIN `oc_audioplayer_artists` `AA` ON `AT`.`artist_id` = `AA`.`id` LEFT JOIN `oc_audioplayer_albums` `AB` ON `AT`.`album_id` = `AB`.`id` WHERE `AT`.`user_id` = ? AND = ? GROUP BY `AB`.`id` ORDER BY LOWER(`AB`.`name`) ASC' with params ["rca", "1156"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '1156' GROUP BY `AB`.`id` ORDER BY LOWER(`AB`.`name`) ASC' at line 1 at <<closure>>

 0. /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 184
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... 1", Doctrine\DBAL\Dr ... ]})
 1. /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 158
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... 1")
 2. /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 178
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT  `AB`.`i ... C", {1: "rca",2: "1156"})
 3. /home/nextcloud/nextcloud/apps/audioplayer/lib/Controller/CategoryController.php line 200
    Doctrine\DBAL\Statement->execute(["rca","1156"])
 4. /home/nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\audioplayer\Controller\CategoryController->getCategoryItemCovers("Title", "1156")
 5. /home/nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 6. /home/nextcloud/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 7. /home/nextcloud/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\audioplaye ... r", "getCategoryItemCovers", OC\AppFramework\ ... {}, {_route: "audiop ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
 9. /home/nextcloud/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
10. /home/nextcloud/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/audioplayer/getcategoryitemcovers")
11. /home/nextcloud/nextcloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/audioplayer/getcategoryitemcovers?category=Title&categoryId=1156
```

The shown query works when leaving off `AND = 1156`:

```
SELECT  `AB`.`id` , `AB`.`name`, LOWER(`AB`.`name`) AS `lower` , `AA`.`id` AS `art`, (CASE  WHEN `AB`.`cover` IS NOT NULL THEN `AB`.`id` ELSE "" END) AS `cid` FROM `oc_audioplayer_tracks` `AT` LEFT JOIN `oc_audioplayer_artists` `AA` ON `AT`.`artist_id` = `AA`.`id` LEFT JOIN `oc_audioplayer_albums` `AB` ON `AT`.`album_id` = `AB`.`id` WHERE `AT`.`user_id` = 'rca' GROUP BY `AB`.`id` ORDER BY LOWER(`AB`.`name`) ASC;
```

And returns 7828 rows at the moment in 1.65s (while a scan process is also running against the same DB!)

I will increase memory to 1024 and let it scan so that I have a nice representative collection to test with tomorrow. Should be between 70000 and 90000 tracks :)

**Comment by Rello** [comment]
Ui
Let me check the logs
I just touched the display part - not the Scanner

I will get back to you...

**Comment by Rello** [comment]
@psy-q 
some strange things: 

---
**"Titles" -> "All Titles"**
The corresponding url=>error should never be possible. I don´t know where your 1156 is coming from. because the "all tiltles" should always be `data-id 0`. can you check your HTML?

> getcategoryitemcovers?category=Title&categoryId=1156

![Screenshot 2019-08-23 at 23 25 49](https://user-images.githubusercontent.com/13385119/63624670-7f05e000-c5fd-11e9-90e0-49cd13ff18a9.png)

can you try with a smaller selection in the GUI like a Genre? in your case the "all titles" is the last test to go for :-)

---
**POST /index.php/apps/audioplayer/checknewtracks**
this is not the error of the scanner itself - even so it might break at the same part.
his call is done at every AP first start to check if there are unindexed files. 

> ScannerController.php#484

there, a big array with all valid audio titles is being built. It took list of all files (probably failing in your first error), looping them, and then storing the final list in a second array - failing on your second error.
I changed the coding to use just one array. this will avoid doubling the amount of memory here. please try again

---
I am including @mmatous in here.
He had the idea of batching DB-writes which brought the major performance part here #419
We have an open question whether we need to commit the work in junks in case the scanner fails - to at least be able to scan in packages.
The test of @psy-q will be very valuable here

**Comment by psy-q** [comment]
Yes, the data-id is 0 for All Titles. I don't know where that snuck in. I did click around the dropdown to figure out where I can find the list of all albums so I can get a huge cover list, not sure what went wrong while doing that.

Anyhow, I found a separate issue:

![image](https://user-images.githubusercontent.com/87557/63635337-e6557b80-c661-11e9-88bd-873520808816.png)

It should say something like 26000, so the last digit is getting cut off there. I could not get it to index the entire 80000+ set of titles so far, even letting it run overnight. At one point it stopped. I didn't see anything too suspicious in the logs.

Now when I go to "Albums" or "Artists", the list in the left column shows correctly. When I go to "Titles" and click "All Titles", a loading spinner spins for two seconds or so, then the spinner disappears, the right part of the page turns blank and the JavaScript console reports:

```
TypeError: album.name is null
```

However, the request for `/index.php/apps/audioplayer/getcategoryitemcovers?category=Title&categoryId=0` seems fine, it returns a 516 KB array of 7827 items in cover mode. In list mode I get a 6.14 MB (!!!) array which displays correctly as a list.

I could try to get it to index all items somehow and then perhaps give you access to the instance if you want to test with humongous collections? 

However, I'm not using Nextcloud for this anymore (I use mpd with a native mpd client) so I'm not sure how many other people would have this use case. Maybe it can't be done efficiently within the boundaries of Nextcloud and maybe no one's even interested in having it supported, so it could just be a waste of time. It seems to work for "smaller" collections (up to 3000ish items).

**Comment by Rello** [comment]
Ok,
In general AP seems to be capable to handle enormous libraries. Thank you very much for your testing efforts. 

I will search the type error

And the sizes also make sense because the cover view just returns the albums(tracks are loaded later)
The list has to fetch all titles and thats a lot of rows for you

**Comment by mmatous** [comment]
One thing that would make the returned JSON smaller is omitting the path and requesting song from server by its ID. Because currently server sends the client info it does not need which is used only for sending it to server that already knows it. Sending just ID + SELECT server-side would help.
I commented out the $row['lin'] append to JSON response as an experiment right now, and the difference is huge. For ~7k tracks it's 239KB/1.57MB vs 141KB/887KB (gzip/unpacked).

Another reason why I don't like the file location sent back and forth is that the client has no bussiness knowing how files are stored on the server. It's OKish for client's own files but especially bad when shared. If Alice shares music library to Bob and Alice has her music in folder called "ILOVEPINKPONIES", AP just leaked Alice's private info to Bob. It also leaks info when posting logs somewhere.

In case it does not help enough then infinite scrolling or streaming the list to client would offer very scalable solution.

As for further PHP memory optimizations [this answer](https://stackoverflow.com/questions/2008866/unsetting-array-values-in-a-foreach-loop/2008893#2008893) has an applicable suggestion for improvement.

**Comment by Rello** [comment]
i was thinking about the same with the link already. But it has implications on the player in the files app and on the (previously available) share-player. 
I will check the references 

The link with the loop is what i applied today already by using just one audios-array in the scanner.

**Comment by mmatous** [comment]
If you mean 003e7e0ed41b9ea97ff8c4c6d6f7bb4b15282539 that's not what the link says. The array is still accessed as a copy `foreach ($audios as $key => $audio)` not using a reference `foreach ($audios as $key => &$audio)`. Notice the ampersand.

**Comment by Rello** [comment]
Ah,
Ok. One more. So my fix got rid of 1 out of 3 - not 1/2 ;-)

**Comment by psy-q** [comment]
I've grabbed the newest scanner code and am rerunning a scan (with 1024 MB RAM limit). It correctly lists that it has ~50000 tracks to go, 27000 already scanned. What I have seen a bunch of times is:

```
[index] Error: Doctrine\DBAL\ConnectionException: There is no active transaction. at <<closure>>

 0. /home/nextcloud/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1360
    Doctrine\DBAL\ConnectionException::noActiveTransaction()
 1. /home/nextcloud/nextcloud/apps/audioplayer/lib/Controller/DbController.php line 392
    Doctrine\DBAL\Connection->rollBack()
 2. /home/nextcloud/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php line 201
    OCA\audioplayer\Controller\DbController->rollBack()
 3. /home/nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\audioplayer\Controller\ScannerController->scanForAudios(null, Symfony\Componen ... {}, null)
 4. /home/nextcloud/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\audioplayer\ ... {}, "scanForAudios")
 5. /home/nextcloud/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "scanForAudios")
 6. /home/nextcloud/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\audioplaye ... r", "scanForAudios", OC\AppFramework\ ... {}, {_route: "audiop ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
 8. /home/nextcloud/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
 9. /home/nextcloud/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/audioplayer/scanforaudiofiles")
10. /home/nextcloud/nextcloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/audioplayer/scanforaudiofiles?requesttoken=7zcV%2BvN6a2DSC3OpqpdhLlWsvWx3CHplFW4mDAKSMWw%3D%3Aml9esqcULS%2BwQ1zjy9IyagD7yjQ9UTEjdiB8OjPXZhQ%3D
```

This is new, with 92a3cecae6b7fca1f5f754902328a098d17bb0dc I never saw that particular message.

**Comment by psy-q** [comment]
Another weirdness: In the end dialog once it thinks it finished scanning, it says it's added something like 15 songs, but the count went up from 27000 to 34400 :smirk:

**Comment by Rello** [comment]
@mmatous wrote me about my mistake in the Scanner. Will fix it when at home. It was supposed to be a safety net - not a break

**Comment by psy-q** [comment]
Ah, sorry about that, I didn't realize those things were related. I'll keep the collection online so I can test more scanner stuff later, then.
