### ISSUE TITLE
Double player in sharing screen

### ISSUE THREAD

**Issue by puntorosso** [Rello/audioplayer#280]
Hi, since the NextCloud 13 update I have 2 players displayed (see screenshot).

<img width="538" alt="screen shot 2018-02-14 at 12 34 39" src="https://user-images.githubusercontent.com/7838163/36202302-8b5328ca-1183-11e8-85df-95f94f3c6faa.png">

I would like to hide the standard audio player and keep only your 360° player but couldn't find a solution.

Thanks for any advice

**Comment by Rello** [comment]
The player was introduced with NC13
https://github.com/nextcloud/server/pull/7246

we are evaluating a streamlining of the functionality.

thank you for this finding.

**Comment by puntorosso** [comment]
Hi, thanks a lot for the update.
To be honest I was expecting the ugly standard player would be removed instead of the nice round one.
Or at least that we could have the chance to decide which one to keep.

**Comment by ghost** [comment]
We have decided to respect the standards (new slogan: Audio Player – Back to Standard). So we removed the buggy external 360 Player.
The SoundManager 2 will be replaced by HTML5 in the future, too.

**Comment by puntorosso** [comment]
Ok, thanks.
I thought a bit of "originality" wouldn't be bad in a world full of "standards" ;)
In this case I had to disable the app completely, as it was enabled **just** because of the 360 player.
Thanks anyway for your great work and support.
