### ISSUE TITLE
Highlight current song in album view

### ISSUE THREAD

**Issue by Maikewng** [Rello/audioplayer#282]
### Expected behavior
Currently played song should be highlighted in bold in the album view 

### Actual behavior
The selected song stays in bold even if the player moved on playing the next one. Look at the screenshot below.
![image](https://user-images.githubusercontent.com/36565143/36341690-564a345e-13f2-11e8-928a-4d465ea9018d.png)

### Steps to reproduce the behavior
1. Select a song to be played in the album view
2. Wait until the following one is played. The bold highlighting in the album view does not move to the current song.

### Possible solution (optional)
Update the album view when payed song changes

### Server configuration
**Operating system**: Raspbian Stretch

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7

**Nextcloud/ownCloud version:** (see `/status.php`) 13

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Audio Player version:** (see `/settings/apps`) 2.2.5

**Where did you install Audio Player from:** App store

**Are you using external storage, if yes which one:** Local HD

**Are you using encryption:** No

### Client configuration
**Operating system:** Windows 10

**Browser:** Firefox 58

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
thank you for this finding!
Issue is re-producable and work in progress...
