### ISSUE TITLE
display unique folder names

### ISSUE THREAD

**Issue by richri** [Rello/audioplayer#283]
### Expected behavior
Display unique folder names

### Actual behavior
Only the last part of the path to the folder ist displayed:

/Media/Audio/Top100/2018-01
/Media/Audio/Top50 Dance/2018-01

are both displayed as 2018-01

### Steps to reproduce the behavior
1.  Create folder structure like this:

/Media/Audio/Top100/2018-01
/Media/Audio/Top50 Dance/2018-01

2. Set Libraray Start folder to /Media/Audio
3. Scan for files

### Possible solution (optional)
Display a full path (or maybe a full path relatiove to the start folder) maybe as tooltip (mouseover)

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2

**Database:**
MariaDB

**PHP version:**
7.3

**Nextcloud/ownCloud version:** (see `/status.php`)
13

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Audio Player version:** (see `/settings/apps`)
13.0.0

**Where did you install Audio Player from:**
App-Store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
external - CIFS Mount

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Windows 10

**Browser:**
Firefox

**Comment by Rello** [comment]
#271

**Comment by Rello** [comment]
ready for testing

the scan will recognise different folders and save the album separately. separate cover art files will be processed accordingly.
the full path is not shown yet in the AP. This will perhaps be implemented later

**Comment by ghost** [comment]
> the full path is not shown yet in the AP. This will perhaps be implemented later

The full path is now displayed in the new sidebar below the cover.
