### ISSUE TITLE
Scanner doesn't detect changed audio metadata

### ISSUE THREAD

**Issue by Maikewng** [Rello/audioplayer#284]
### Expected behavior
Scanner should detect when an audio file metadata (for example album name) has been changed through an external tag editor.

### Actual behavior
If you change a song's metadata through an external tag editor (for example MusicBrainz Picard) and then rescan the database, the changes are not detected.

### Steps to reproduce the behavior
1. Pick an album in your database
2. Change the album name with an external tag editor (eg Musicbrainz Picard)
3. Rescan the library
4. The changes are not detected

### Possible solution (optional)
I don't know how the scanner works, but if it relies on file hashes for identification it should be easy to detect changes and rescan the file.
Also look at issues [271](https://github.com/Rello/audioplayer/issues/271) and [239](https://github.com/Rello/audioplayer/issues/239) as they might be related to a general scanner improvement

**Comment by Rello** [comment]
hello,
yes, this is how AP works. we are detecting new audio files and adding these to the database.
technically everything in Nextcloud depends on the file_cache table. whenever a new file is posted there, it will be recognised.

we would need to evaluate if the file_cache also tracks a timestamp for file updates. 
but this leaves you with another issue: working on files with an external editor ist not being recognised by Nextcloud until you do a `occ file:scan` if I am not wrong.

AP (nor does any other app) does not scan the filesystem itself for changes. file_cache is the core setup in Nextcloud for this.

**Comment by Maikewng** [comment]
Even if I edit the files via an external editor, I still reupload them via Nextcloud. Somehow Nextcloud is aware of the change, I believe there should be a way to communicate that to AP.
Unfortunately I am not an experienced programmer in PHP, I wish I could help more.

**Comment by Rello** [comment]
functionality is being beta-tested and will be included in the next release
