### ISSUE TITLE
New Category "Album Artists"

### ISSUE THREAD

**Issue by kpalczewski** [Rello/audioplayer#286]
It would be great if there was "Album Artist" option. Album Artist is often used for albums with various artists.

There is a selection "Titles" that should be named "All". It's great btw. You can shuffle all your songs (only way to do this).
Alternatively, "Artists", "Albums", "Genres" and "Years" could have an "All" option at the top of the list.

![screenshot from 2018-03-06 10-49-46](https://user-images.githubusercontent.com/16464271/37025519-3c452874-212c-11e8-83a5-55d15d67c49a.png)
![screenshot from 2018-03-06 10-50-19](https://user-images.githubusercontent.com/16464271/37025521-3c6095f0-212c-11e8-9daa-666df5b0d76d.png)

**Comment by ghost** [comment]
> There is a selection "Titles" that should be named "All".

The sub-selection `Titles` has been renamed from `All` to `Titles` to name the headline of the playlist, sorted by title, a little better than `All`. We may rename it to `All Titles`.

**Comment by ghost** [comment]
> Alternatively, "Artists", "Albums", "Genres" and "Years" could have an "All" option at the top of the list.

You can sort the playlist of all titles at least by `Title`, `Artist`, and `Album` by clicking or tapping the column header.
[Default sorting](https://github.com/rello/audioplayer/wiki/basic-usage-of-audio-player#navigation--selection) of this playlist is by `Album`->`Disc`->`Track`.

**Comment by kpalczewski** [comment]
`All Titles` seems best choice.
It may vary from person to person, but my audio library is best sorted with `Album Artist` field in ID3 tag, so having such sorting there would make sense.

**Comment by Rello** [comment]
- "Titles" was renamed to "All Titles"
- New category "Album Artists" was introduced

**Comment by kpalczewski** [comment]
Awesome! Thank you very much!
