### ISSUE TITLE
Edited id3 tags on external storage (SMB) are not saved

### ISSUE THREAD

**Issue by efelon** [Rello/audioplayer#287]
### Expected behavior

ID3 tags changed after clicking "save" on the metadata editor on files scanned from external storage (SMB in my case).

### Actual behavior

Metadata stays unchanged; No warning or error message displayed.

### Steps to reproduce the behavior
1. Click on "edit metadata" on any file from external storage
2. Enter/Change any data you like
3. Save
4. Reopen metadata editor and examine result (no changes made)

Copied some files to the local nc filesystem and repeated those steps with success. Even with a user whom i shared the folder with. (btw. i need to reset and scan the library to make the changes in the sidebar visible, which were correctly shown in the metadata editor without reset/scan)

### Additional information (optional)

I'm happy to provide anything else that could help. Just tell me what you need.

### Server configuration
**Operating system**:
Raspbian Stretch

**Web server:**
Nginx 1.10.3

**Database:**
mysql Ver 15.1 Distrib 10.1.23-MariaDB

**PHP version:**
7.0
php-smbclient installed

**Nextcloud/ownCloud version:** (see `/status.php`)
installed | true
maintenance | false
needsDbUpgrade | false
version | "13.0.0.14"
versionstring | "13.0.0"

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Audio Player version:** (see `/settings/apps`)
2.2.5

**Where did you install Audio Player from:**
appstore

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
smb

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
doesn't matter

**Browser:**
Firefox / Chrome

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
{"reqId":"VWPCmvTIyWOKOBvsV897","level":0,"time":"2018-03-06T13:34:31+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"martin","app":"audioplayer","method":"GET","url":"\/oc\/apps\/audioplayer\/editaudiofile?songFileId=2757","message":"songFileId: 2757","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```

No other messages with leglevel 0. (This is always written whenever the metadata editor launches for a file; regardless of success or fail)

</details>

**Comment by Rello** [comment]
Hello,
due to the complexity and efforts required, the ID3 editor war removed from Audio Player.
There is a plug-in planned - but no feature or release planning being done at the moment.
Please use an external ID3 editor if required.

https://github.com/Rello/audioplayer_editor
