### ISSUE TITLE
Separation of ID3 tag editor into separate App

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#290]
The ID3 editor will not be part of the core Audio Player anymore.

Due to the resources required, it will be developed and rolled out separately.
Please follow
https://github.com/Rello/audioplayer_editor

**Comment by ghost** [comment]
#287

**Comment by Rello** [comment]
Editor-Install-Check is currently disabled until officially released
https://github.com/Rello/audioplayer/blob/master/lib/Controller/PageController.php#L71
