### ISSUE TITLE
Question from IRC tonight?

### ISSUE THREAD

**Issue by nickvergessen** [Rello/audioplayer#292]
```
<Rello> hello....
<NextcloudBot> hi Rello, please go ahead and ask your question and be patient, most people do not actively monitor the chat and will only check the chatlog periodically
<-- michag86 (~michael@200116b840fbf800640226ff0c6249a9.dip.versatel-1u1.de) hat das Netzwerk verlassen (Quit: Leaving.)
<Guest83866> Hi guys I try to understand why i can't activate or use the catpions settings, subtitles, resolutions (quality) with videojs. I use the Ubuntu 16.04 OVA: Pre-installed Nextcloud, Version: 13.0.1 Is it a choice made by the team nextcloud ? Thank you for your help
<-- don-isle (~don@AAnnecy-651-1-243-145.w86-209.abo.wanadoo.fr) hat das Netzwerk verlassen (Ping timeout: 276 seconds)
<Rello> can anyone suggest a better way (perhaps even 1-liner) for: \OC\Files\Filesystem::getPath($row['fid'])
<enoq> Rello: isnt there a getPath() method on each node?
<enoq> Rello: https://github.com/nextcloud/server/blob/master/lib/public/Files/Node.php#L95
<NextcloudBot> Title: server/Node.php at master · nextcloud/server · GitHub (at github.com)
<jsc144> oops wrong chatroo
<enoq> Rello: https://github.com/nextcloud/server/blob/master/lib/public/Files/Folder.php#L155
<NextcloudBot> Title: server/Folder.php at master · nextcloud/server · GitHub (at github.com)
<enoq> IRootFolder extends Folder
<enoq> inject IRootFolder
<enoq> call getById($id)->getPath()
<Rello> I tried $this->rootFolder->getUserFolder($this -> userId)->getById($row['fid'])->getPath() but this did not work that straight forwards
<enoq> $this->rootFolder->getById($row['fid'])->getPath()
<Rello> ...want to get rid of the last OC calls to make scruitinizer happy :-)
<Rello> oha "Call to a member function getPath() on array" exception. thats strange
<enoq>          * @return \OCP\Files\Node[]
<enoq> ok?
<enoq> dont ask me
<enoq> This method could return multiple entries. For example once the file/folder is shared or mounted (files_external) to the user multiple times.
<enoq> someone butchered apis again
<Rello> h...
<Rello> thank you anyway. will keep the old OC - at least its working....
```

is it solved?

All information was basically there.
The only thing missing was that you only want one result, instead of all, correct?
If you want just one path to the file:
```php
$nodes = $this->rootFolder->getUserFolder($this -> userId)->getById($row['fid']);
$file = array_shift($nodes);
$path = $file->getPath();
```

Why is this necessary. Just assume you have the structure `/level1/level2/level3` and you share `level1` and `level2` with user2. Now when user2 `getById('level3')`, there should be `<share for level2>/level3` and `<share for level1>/level2/level3`. (I think we sort by path length, so the shortest path is the first one). `array_shift` returns you the first `OCP\Files\File` and then you can proceed and call `getPath`

Just for the record, `$row` makes me assume you run this in a loop from teh database. In that case you should assign `$this->rootFolder->getUserFolder($this->userId)` to a variable instead of calling it everytime again.

PS: In case you don't get replies on IRC feel free to create issues and mention people (or me ;) )

**Comment by Rello** [comment]
hello @nickvergessen 
thank you for the followup!

...I am using the OC here - straight forward. 2 lines
https://github.com/Rello/audioplayer/blob/master/lib/Controller/CategoryController.php#L398-L399

Result is `/audio_tests/test-long strings.mp3` - the relative path to the users home

your approach would get me
`/Admin/files/audio_tests/test-long strings.mp3`

any suggestion to get the path related to the users root?

problem is, that in this area I need to initialize the user view with the userId from a variabel in case of occ-scan-all
https://github.com/Rello/audioplayer/blob/master/lib/Http/AudioStream.php#L32-L37

So coming with the full path on the initialized user-view has the first 2 levels doubled

you know what I mean?
or to confusing :-)
at the end its all about getting rid of \OC\Files\. is it actually so bad to keep it?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/9222/files#diff-15983d90aa67710cbe2e93d8a7341ae5R66

**Comment by Rello** [comment]
thank you @nickvergessen 
my drop-in-replacement is
 ```
           $nodes = $this->rootFolder->getUserFolder($this -> userId)->getById($row['fid']);
            $file = array_shift($nodes);
            $path = $file->getPath();
            $segments = explode('/', trim($path, '/'), 3);
            $row['lin'] = rawurlencode($segments[2]);
```

***

I am not sure for this one:
https://github.com/Rello/audioplayer/blob/master/lib/Hooks/FileHooks.php#L32-L33
```
		$view = \OC\Files\Filesystem::getView();
		$node = $view->getFileInfo($params['path']);
```

I think it should be something like this - but do I have the $user available in the fileHook in this place?
```
        $view = new View('/' . $user->getUID() . '/uploads');
        $rootInfo = $view->getFileInfo($params['path']);
```

**Comment by nickvergessen** [comment]
You can get the user with `\OC::$server->getUserSession()->getUser()` (check for null (guest))

But then again, instead of the View, you can use the getUserFolder() too?
