### ISSUE TITLE
uk Translation

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#295]
@BODYA7979 Would you like to add the missing translations in `uk.js` and `uk.json` please?
Feel free to add the files to this issue or make a pull request.
Thanks in advance!

**Comment by BODYA7979** [comment]
@xraMsamohT 
Hi, sure. Here is a patch:
[uk-locale-2.3.0.patch.zip](https://github.com/Rello/audioplayer/files/1954780/uk-locale-2.3.0.patch.zip)

**Comment by Rello** [comment]
Thank you @BODYA7979
