### ISSUE TITLE
Support "Limit to groups"

### ISSUE THREAD

**Issue by monreal** [Rello/audioplayer#303]
### Expected behavior
The audioplayer app should support "Limit to groups"

### Actual behavior
It does not support "Limit to groups"

### Steps to reproduce the behavior
1. Go to apps
2. Compare to "Calendar" app for exmaple

### Server configuration
**Operating system**: Linux / Docker
**Web server:** NGINX
**Database:** MYSQL
**PHP version:** 7
**Nextcloud/ownCloud version:** 13.0.2.1
**Audio Player version:** 2.3.0
**Where did you install Audio Player from:** built-in app downloader
**Are you using external storage, if yes which one:** none
**Are you using encryption:** no

### Client configuration
**Operating system:** Fedora Linux 28
**Browser:** Firefox 59

**Comment by ghost** [comment]
Audio Player does not support this feature because the app provide public access without login like the public sharing page with the metadata collected by Audio Player.
This is a limitation of Nextcloud, not of the Audio Player app.
