### ISSUE TITLE
Playback does not continue to next song after the current song ends.

### ISSUE THREAD

**Issue by wincak** [Rello/audioplayer#305]
### Expected behavior
Playback continues to play all the songs in the album one after one till the end.

### Actual behavior
Only the started song plays to the end. Next one has to be started manually.

### Steps to reproduce the behavior
1. Open Audio Player, select an album
2. Select a song, click play.
3. Wait for the song to finish. Playback does not continue with next song.

This used to work well before, so step 0. might be installing Audio Player version 2.3.0

### Server configuration
**Operating system:** Ubuntu server 16.04

**Nextcloud/ownCloud version:** Nextcloud 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated, originally Nextcloud 12

**Audio Player version:** 2.3.0

**Where did you install Audio Player from?** NC App Store

**Are you using external storage? If yes, which one:** Yes, local.

**Are you using encryption?** No

**Have you activated other multimedia apps?** No

**Audio Player media folder:** /HDD-ext/hudba/

### Client configuration
**Operating system:** Manjaro Linux

**Browser:** Firefox 59.0.2 (64-bit)

#### Nextcloud/ownCloud log
Nextcloud web interface log mentions only "Trusted domain" errors.

**Comment by Rello** [comment]
@wincak can you please confirm that this error only occurs on every Album which does not have a cover? I found an issue there - it should not be related to the external storage itself.

If the playback does not continue, you should see a JS error in your browser console.

**Comment by wincak** [comment]
You are right, this happens only on albums without covers.
In that case it gives following error (copied from Firefox console)
`TypeError: activeLi.data(...) is undefined  app-min.js:34:666`

**Comment by Rello** [comment]
ok, yes.
its fixed already. we will test another issue and hope to release 2.3.1 shortly. thank you for the finding
