### ISSUE TITLE
non-Admin user has empty library maybe related to external shared storage

### ISSUE THREAD

**Issue by jauling** [Rello/audioplayer#307]
### Expected behavior
A normal user should be able to select a folder (that's been shared with him/her), and scan that location for audio files. The selected folder was shared with that user by an admin, via an external storage source (local storage).

### Actual behavior
Normal User scanning for audio files in selected folder results in zero audio files. 
Audios found: 0
Written to library: 0
Albums found: 0

Admin can see and play files in AP just fine.

### Steps to reproduce the behavior
1. Admin creates external storage location, from a local folder (outside of Nextcloud data folder)
2. Admin shares this external storage location with group Users
3. Admin can scan external storage location and can see and play audio files in Audio Player 
4. Normal User sees the shared folder in Nextcloud Files
5. Normal User selects the shared folder, and attempts to scan for audio files

### Server configuration
**Operating system:**
Asustor NAS ADM 3.0.4.RCQ1
Linux 4.4.24 #1 SMP Mon Dec 25 21:03:46 CST 2017 x86_64 GNU/Linux

**Web server:**
Apache/2.4.25 (Unix)

**Database:**
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for Linux () using readline 5.1

**PHP version:**
PHP 5.6.30 (cli) (built: Dec 25 2017 22:58:55) 

**Nextcloud/ownCloud version:** (see `/status.php`)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"13.0.2.1","versionstring":"13.0.2","edition":"","productname":"Nextcloud 4pack"}

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 11 -> Nextcloud 12

**Audio Player version:** (see `/settings/apps`)
2.3.0

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
Yes, Local

**Are you using encryption?** yes/no
No

**Have you activated other multimedia apps?** `Music/Folder Player/...`
No

**Audio Player media folder:** (see Settings) `root/Music/...`
/Music/

### Client configuration
**Operating system:**
Mac OSX 10.12.6 (16G1314)

**Browser:**
Google Chrome Version 66.0.3359.117 (Official Build) beta (64-bit)

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
hello,

we tested the given information in several setups but could not reproduce your issue.
could you please do a scan in occ with the debug option?

`sudo -u www-data php occ audioplayer:scan username --debug`

**Comment by jauling** [comment]
Not much to go on here:
```
$ ./occ audioplayer:scan jauling --debug
Start scan for jauling
Scanned Folder: /jauling/files/Music
Total audio files: 0
Checking audio files to be skipped
Final audio files to be processed: 0
Total stream files: 0
Checking stream files to be skipped
Final stream files to be processed: 0
Start processing of audio files
Start processing of stream files
Audios found: 0
Duplicates found: 0
Written to library: 0
Albums found: 0
Errors: 0
```
Here is the list of my external storages
```
$ ./occ files_external:list
+----------+-----------------+---------+---------------------+-------------------------------------------+----------------------+------------------+-------------------+
| Mount ID | Mount Point     | Storage | Authentication Type | Configuration                             | Options              | Applicable Users | Applicable Groups |
+----------+-----------------+---------+---------------------+-------------------------------------------+----------------------+------------------+-------------------+
| 1        | /Jau Italy 2017 | Local   | None                | datadir: "\/volume1\/Media\/201709 italy" | enable_sharing: true |                  | admin             |
| 2        | /Media          | Local   | None                | datadir: "\/volume1\/Media"               | enable_sharing: true |                  | admin             |
| 3        | /Music          | Local   | None                | datadir: "\/volume1\/Music\/jau"          | enable_sharing: true |                  | admin             |
| 4        | /TV Movies      | Local   | None                | datadir: "\/volume1\/TV & Movies"         | enable_sharing: true |                  | admin             |
+----------+-----------------+---------+---------------------+-------------------------------------------+----------------------+------------------+-------------------+
$ ./occ files_external:verify 3
  - status: ok
  - code: 0
  - message
```

Not sure how to list shares for my users, but that might be helpful? FWIW, the `/volume1/Music/jau` location isn't owned by admin (user for Nextcloud), but everything under that folder is rw to everyone.

**Comment by jauling** [comment]
Even if I search for audio files in / for the user jauling, it shows me zero audio files. I can see the audio files if browsing by the Files tab, but scanning with audioplayer comes up zero. For whatever reason, audioplayer isn't traversing the locations shared with this user.

```
 $ ./occ audioplayer:scan jauling --debug
Start scan for jauling
Scanned Folder: /jauling/files
Total audio files: 0
Checking audio files to be skipped
Final audio files to be processed: 0
Total stream files: 0
Checking stream files to be skipped
Final stream files to be processed: 0
Start processing of audio files
Start processing of stream files
Audios found: 0
Duplicates found: 0
Written to library: 0
Albums found: 0
Errors: 0
```

Please let me know if I can provide additional troubleshooting data, thanks.

**Comment by jauling** [comment]
Hi @Rello is there anything else I can check?

I confirmed the audio player works for my user. I deposited an mp3 file into the home directory, and it scanned and found it and played it no problem. Its just the external storage that's shared that still registers as no files thats the issue. 

Since the time I posted this issue, I've upgraded my Nextcloud instance to 13.0.5, and audioplayer is now at 2.3.2 Unfortunately, no change fro the behavior I originally reported.

Would any additional Nextcloud apps possibly interfere?

**Comment by jauling** [comment]
Not sure what changed, but I upgraded to nextcloud `13.0.8` recently, and my shared external storage seems to work fine with audioplayer now. It might be because some apps were disabled in the process. I guess this issue can be closed now.

Here's a list of my apps for no real reason:
```
$ ./occ app:list
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.4.1
  - bruteforcesettings: 1.2.0
  - camerarawpreviews: 0.6.1
  - checksum: 0.4.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.9.2
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.1.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - sociallogin
  - systemtags
  - user_ldap
  - user_saml
```
