### ISSUE TITLE
occ scan failes with id3v1 Tags with a Special character

### ISSUE THREAD

**Issue by myndbreaker** [Rello/audioplayer#308]
### Expected behavior
scan runs as expected

### Actual behavior
scan failes

### Steps to reproduce the behavior
1. take an mp3 file with an ' as title in id3v1 ( "It's" in my case) and run the scan
2. scan fails 
3. removal of ' fixed the issue for me. 

### Additional information (optional)
With another file which contained an "&" conversion to id3v2 tags fixed the issue as well
Problem seems to only appear with id3v1 tags

### Server configuration
FreeBSD11

**Web server:**
Apache 2.4

**Database:**
mysql56-server-5.6.40

**PHP version:**
php7.1

**Nextcloud/ownCloud version:** (see `/status.php`)
13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
update all the way from owncloud 3

**Audio Player version:** (see `/settings/apps`)
2.3.0

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
no

**Are you using encryption?** yes/no
no

**Have you activated other multimedia apps?** `Music/Folder Player/...`
Video Player 1.2.0

**Audio Player media folder:** (see Settings) `root/Music/...`
not defined

### Client configuration
**Operating system:**
not relevant, server side issue

**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
Audio Player is dependent on id3v2
https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L136-L137

I don´t know at the moment why it processes your id3v2 at all. I assume some fallback in the exxternsl getID3 library

In this case you should convert to id3v2
