### ISSUE TITLE
Can't list all titles. PHP exhausts memory

### ISSUE THREAD

**Issue by pmetras** [Rello/audioplayer#310]
### Expected behavior

List all titles in music collection.

### Actual behavior

I have >5000 FLAC titles in my music collection, all with covers. I'm unable to browse by "All Titles". Timer icon keeps turning and the list of titles does not display.

When doing so, PHP raises a memory exhausted error in Nextcloud logs.
```
Allowed memory size of 536870912 bytes exhausted (tried to allocate 98304 bytes) at /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#105
```
I've increased PHP `memory_limit` up to 1 GB with always the same error. Nextcloud is running on a small box and I can't give more memory dedicated to PHP.

All other media views seems to work.

### Steps to reproduce the behavior
1. In Selection combobox, select "Titles"
2. Select "All Titles"
3. 

### Possible solution (optional)
Break SQL query to retrieve covers after querying the titles. Many titles will share the same album cover and memory use should decrease by ten fold.

### Additional information (optional)
I suspect that the player tries to load all titles with their cover. I think that the size of the pictures exhausts memory.
Query in MySQL retrieves MBs of data:
```SQL
SELECT  `AT`.`id`, `AT`.`title`  AS `cl1`, `AA`.`name` AS `cl2`, `AB`.`name` AS `cl3`, `AT`.`length` AS `len`, `AT`.`file_id` AS `fid`, `AT`.`mimetype` AS `mim`, `AB`.`id` AS `cid`, `AB`.`cover`, LOWER(`AB`.`name`) AS `lower` FROM `oc_audioplayer_tracks` `AT`                           
              LEFT JOIN `oc_audioplayer_artists` `AA` ON `AT`.`artist_id` = `AA`.`id`                                         LEFT JOIN `oc_audioplayer_albums` `AB` ON `AT`.`album_id` = `AB`.`id`WHERE `AT`.`id` > '0' AND `AT`.`user_id` = 'alfonse' ORDER BY LOWER(`AB`.`name`) ASC, `AT`.`
disc` ASC, `AT`.`number` ASC limit 1;
```

This seems related to #124.

### Server configuration
**Operating system:**
Debian 9.4

**Web server:**
Apache 2.4.25

**Database:**
MariaDB 10.1.26

**PHP version:**
7.0.27

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Audio Player version:** (see `/settings/apps`)
2.3.0

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
Nextcloud App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
local

**Are you using encryption?** yes/no
No

**Have you activated other multimedia apps?** `Music/Folder Player/...`
No

**Audio Player media folder:** (see Settings) `root/Music/...`

### Client configuration
**Operating system:**
Linux Ubuntu 16.04

**Browser:**
FireFox 60.0.1

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
{"reqId":"Wv7vj38AAQEAAE8EYPQAAAAA","level":3,"time":"2018-05-18T15:22:40+00:00","remoteAddr":"99.184.62.126","user":"alfonse","app":"PHP","method":"GET","url":"\/cloud\/index.php\/apps\/audioplayer\/getcategoryitems?category=Title&categoryId=0","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 49152 bytes) at \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"Wv7wRX8AAQEAAE-q-b0AAAAB","level":3,"time":"2018-05-18T15:25:23+00:00","remoteAddr":"99.184.62.126","user":"alfonse","app":"PHP","method":"GET","url":"\/cloud\/index.php\/apps\/audioplayer\/getcategoryitems?category=Title&categoryId=0","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 49152 bytes) at \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"Wv7yLH8AAQEAAFCmhQsAAAAA","level":3,"time":"2018-05-18T15:33:27+00:00","remoteAddr":"99.184.62.126","user":"alfonse","app":"PHP","method":"GET","url":"\/cloud\/index.php\/apps\/audioplayer\/getcategoryitems?category=Title&categoryId=0","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 98304 bytes) at \/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,

it is correct, that the select also ready the covers because we need this information (yes/no - not the data itself) for later processing.
There is no quick fix around this at the moment. we don´t support paging in audioplayer yet.

But as displaying a list of 5000 items (every item has Metadata + the link information) might not even work with a better cover select.

So for this special usecase, there is unfortunately not fix. I am sorry
