### ISSUE TITLE
delete playlist

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#312]
I see no way to do it

**Comment by ghost** [comment]
Smart Playlist, Playlist File with Stream URL, or Standard Playlist?

- Smart Playlists are not deletable.
- Playlist Files with Stream URLs are deletable in the Files app only.
- Standard Playlists has an icon right to the name to delete them.

**Comment by ghost** [comment]
There are a few play lists below what I believe are the smart play lists, below "Most Played".
I didn't add them. They are names of artists in my library. No icon to the right

**Comment by ghost** [comment]
From `Favorites` to `Most Played` are the [Smart Playlists](https://github.com/rello/audioplayer/wiki/basic-usage-of-audio-player#smart-playlists). Below them are the _playlist files_, found by a scan through the specified _media folder_.
You have to delete these **local files** (filenames with extensions `.m3u`, `.pls`, and `xspf`) in the Files app as I wrote above. Audio Player itself does not create _playlist files_ and can not delete, move, or rename files.
It is a [known issue](https://github.com/rello/audioplayer/wiki/installation-instructions#known-issues) that Audio Player does not work with local playlist files yet.

> They are names of artists in my library.

This indicates, that these _playlist files_ created by another app or program und have synchronized to your cloud, especially your _media folder_.
What file extension do the files have?

**Comment by Rello** [comment]
Hello,
is this problem still existing? can you please provide a screenshot?
