### ISSUE TITLE
Volume control widget appears to adjust linearly instead of logarithmically

### ISSUE THREAD

**Issue by 48kRAM** [Rello/audioplayer#313]
### Expected behavior

Adjusting the volume to the visual half point reduces the volume to a level that sounds half-way between silence and full-volume.

### Actual behavior

Adjusting the volume to the visual half point reduces the volume only slightly.

### Steps to reproduce the behavior
1. Play any audio file
2. Adjust the volume widget
3. Notice that most of the level adjustment occurs in the lower-third of the triangle.

### Possible solution (optional)

Switch to logarithmic volume scaling.

https://ocw.mit.edu/high-school/engineering/guitar-building/physics-of-the-guitar/logarithmic-audio/

### Server configuration

**Audio Player version:** (see `/settings/apps`)

2.2.5

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`

NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

No

**Are you using encryption?** yes/no

No

**Have you activated other multimedia apps?** `Music/Folder Player/...`

No

### Client configuration
**Operating system:**

macOS 10.12

**Browser:**

Chrome one back from latest.

**Comment by ghost** [comment]
There is no _widget_ in use. At the moment we still using [SoundManager 2](http://www.schillmania.com/projects/soundmanager2/) of Scott Schiller in the main window of Audio Player. Please ask in the [issue tracker of SM2](https://github.com/scottschiller/soundmanager2/issues) for solving your problem.

Be aware, that the SoundManager 2 will be replaced by the HTML5 `audio` tag in the future. The volume control is then browser-dependent.
