### ISSUE TITLE
smbclient hangs with 100% cpu on scan for audio files

### ISSUE THREAD

**Issue by shadowlord017** [Rello/audioplayer#315]
### Expected behavior
Scan all new files

### Actual behavior
Scan starts and then hangs on 166 files (i have more files added, so 166 / 4000 is seen).
Top shows 100% cpu on smbclient process.
Each scan restart new smbclient is started and hangs on 100% cpu
After reboot page, smbclient stays on 100% cpu state
smbclient shows 100% cpu only after counter hangs on 166 files

### Steps to reproduce the behavior
1. Add some files to smb/cifs connected external storage
2. Run "scan for audio files"
3. Wait for counter stops on 166 files
4. Watch top utility

### Additional information (optional)
smbclient 4.5.12-Debian

### Server configuration
**Operating system:**
OS Debian 9.4

**Web server:**
nginx version: nginx/1.10.3

**Database:**
mysql  Ver 15.1 Distrib 10.1.26-MariaDB

**PHP version:**
php-fpm PHP 7.0.27-0+deb9u1 (fpm-fcgi) (built: Jan  5 2018 13:51:52)

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Audio Player version:** (see `/settings/apps`)
Audio player 2.3.0

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
yes - smb

**Are you using encryption?** yes/no
no

**Have you activated other multimedia apps?** `Music/Folder Player/...`
no

**Audio Player media folder:** (see Settings) `root/Music/...`
/music/

### Client configuration
**Operating system:**
Ubuntu 16.04

**Browser:**
Chrome 66.0.3359.181

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
did you see the note regarding the special requirement for the libsmb libary?
https://github.com/rello/audioplayer/wiki/external-storage

**Comment by shadowlord017** [comment]
Yes, after installing additional library it became more stable. But sometimes it still hangs (maybe 300+ files), but not every time, so i can't set dependencies
1. If libsmbclient-php is absolutely required (no plans to checks on standard library), mayde it must be checked automatically on module install?
2. Needs more stability on libsmbclient-php library

**Comment by Rello** [comment]
Hello,
unfortunately I can not support here.
libsmbclient is a tweak I use on all my instances. why NC does not declare it as mandatory, and what the development part ist, I cant tell. Sorry
