### ISSUE TITLE
Enhancement:   Surface play controls in File App

### ISSUE THREAD

**Issue by rebecca-cook** [Rello/audioplayer#317]
This is not a bug so much as an enhancement request:

It would be really nice if when you select an audio file in the file app, if play controls surface to allow the user to pause, scrub through the track, or skip to the next track.  Right now when the user selects an audio file it begins to play automatically, but there are no controls.   It is a way better user experience to have the controls in the file app where the user may want to preview the file.

### Steps to reproduce the behavior
1. 
2. 
3. 

### Server configuration
**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud/ownCloud version:** (see `/status.php`)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Audio Player version:** (see `/settings/apps`)

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

**Are you using encryption?** yes/no

**Have you activated other multimedia apps?** `Music/Folder Player/...`

**Audio Player media folder:** (see Settings) `root/Music/...`

### Client configuration
**Operating system:**

**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,

we went another way here because we introduced the file preview sidebar within audio player. I don´t know if you recognised this one already?
To implement the playbar within the files-app involves a lot of overhead for every user and every navigation + hacking of the stock NC setup. As this is very unreliable during every version update, we can not provide the resources here at the moment.

**Comment by rebecca-cook** [comment]
It's sad because the way that the video preview works by creating a modal window is so user-friendly.  I just wish there was an experience like that for Audio
