### ISSUE TITLE
Cannot select/play track

### ISSUE THREAD

**Issue by k1rb** [Rello/audioplayer#318]
### Expected behavior
Select track, track title becomes bold, audio icon is displayed to the left of the text, audio begins playing.

### Actual behavior
Selecting the track has no effect. Text is not bold, no audio icon, no audio.

### Steps to reproduce the behavior
1. Enter "Audio Player"
2. Select album (album organization may be a local configuration)
3. Select track

### Server configuration
**Operating system:** Debian 9 Stretch, Stable amd64
**Web server:** Nginx 1.10.3
**Database:** MariaDB 10.1.26
**PHP version:** 7.0.27
**Nextcloud/ownCloud version:** 13.0.4.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Not a fresh install.
**Audio Player version:** 2.3.0
**Where did you install Audio Player from?** NC App Store (95% sure)
**Are you using external storage:** No
**Are you using encryption:** No
**Have you activated other multimedia apps:* No
**Audio Player media folder:** `/Music/Library`

### Client configuration
**Operating system:** Windows 10 Professional x64, 1803
**Browser:**
- Firefox 60.x, 61.0
- Internet Explorer 11
- Microsoft Edge 42.17134.1.0

### Logs
**Nginx Access/Errors:** Nothing unusual, access shows expected access, no errors.
**Nextcloud.log:** Nothing is generated while attempting to play audio.

#### Browser log (optional)
Using debugger in FF there is no GET request when clicking any track title.

From chrome the GET is to:
`/apps/audioplayer/getaudiostream?file=Music%2FLibrary...`

### Other Information
I have uninstalled and reinstalled Firefox, no Add-ins or extensions are installed. 
Chrome 67.0.3396.99 does work as expected...
Firefox 52.8 on Debian 9 also works as expected...

**Comment by Rello** [comment]
Hello,
I just published the 2.3.1 which had some fixes especially for FF in it.
can you please have a try and come back if the issue still persists?

Thank you for your support
