### ISSUE TITLE
Play button on album cover

### ISSUE THREAD

**Issue by byteturtle** [Rello/audioplayer#319]
Would it be possible to add a small play/pause button to the album cover view (on hover)?
This is how it looks in the album view of iTunes - and i think it's a quite nice feature to start playing an albumg starting with the first track right away.
![image](https://user-images.githubusercontent.com/6249273/42598534-c0742b7e-855c-11e8-96ee-9e06e04791b5.png)

**Comment by Rello** [comment]
Hello,
this is an interesting idea, but not that simple.
because the way the player works is, that it needs to have the playlist of all files to start. So this click would need to what "click album + click first song" does in one go.

I need to think about this...

**Comment by Rello** [comment]
Hello,
just to let you know that I am working on it.
I am just figuring out how to handle mobile devices because they don´t have `:hover`

**Comment by Rello** [comment]
Testing in progress
![screen shot 2018-09-09 at 22 31 08](https://user-images.githubusercontent.com/13385119/45268659-12431580-b480-11e8-9221-bc6ffa3848b3.png)
