### ISSUE TITLE
Feature Request: Download Playlists to Mobile Device

### ISSUE THREAD

**Issue by Schmunzelhummel** [Rello/audioplayer#321]
Feature request:
I would like to have the option to download a selected playlist including it's tracks - like Microsoft Groove does. That way I would be able to listen to my songs offline without downloading every single file.

**Comment by Rello** [comment]
Hello,
this feature is not foreseen in the near future because it would require huge efforts. Basically a native app would be required for this.
This is far beyond this App`s purpose.

sorry...
