### ISSUE TITLE
Feature request: retry failed cover load attempts

### ISSUE THREAD

**Issue by babolivier** [Rello/audioplayer#322]
I currently have 309 albums in Audioplayer. When Audioplayer's album view loads, it tries to download covers for all albums simultaneously, which, due to some system limitations on my end, a lot of these requests end up with my web server responding with an error, and many albums end up with having blank covers.

It would be great if the app could detect failed attempts at loading album covers, and retry each of them after a short wait (I'm thinking of something around ~200ms).

**Comment by Rello** [comment]
Hello,

do you have any indication on what is failing? any messages?

because normally the browser should only load the covers in the visual area first and then load the others when required. This was the purpose of the change to the current rendering mode (before, all covers were transferred once in a big string) to let the browser do the thinking.

any hint?

**Comment by babolivier** [comment]
Hey,

Nope, no error message in the console. I confirm it does try to load every cover at once, including the ones that aren't in the visual area.

Also, I seem to have forgotten to mention I'm talking about the grid "Album" view, and I'm running Firefox 61.0.1. If you can think of any additional info that could help find out where the problem comes from, please tell me.

**Comment by Rello** [comment]
Hello @babolivier 
do you still have this issue or could you solve the webserver setup?
I don´t really have an idea how to fix this from AP side. It would need some delayed looping of all images again and again to check if they are shown.

this would create load on every AP user but you are the only one I heard about having this issue.
Unfortunately I can not solve this for now
