### ISSUE TITLE
Add new tracks causes php memory_limit error

### ISSUE THREAD

**Issue by GitGobo** [Rello/audioplayer#326]
Hi,
I installed successfully the Audioplayer app via the Nextcloud appstore. But everytime I click on the "Add new tracks to library" only the popup "Scan for audio files 0% (0/0)" appears and nothing happens. I waited serveral times up to 15min. My library is empty. Same behaviour when I change the Music folder, for example to a single Album with only 5 Songs.

### Expected behavior
library contains tracks, progress bar starts

### Actual behavior
Nothing happens in the browser.
On the Server in the Apache error.log an entry is written, everytime i clicked the add tracks button: "PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 166"

### Steps to reproduce the behavior
1. Install audioplayer via appstore
2. click Add new tracks to library
3. wait

### Additional information (optional)
Everytime I click on the "Add new tracks to library" only the popup "Scan for audio files 0% (0/0)" appears and nothing happens. I waited serveral times up to 15min. My library is empty. Same behaviour when I change the Music folder, for example to a single Album with only 5 Songs.

### Server configuration
**Operating system:**
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
MariaDB 10.0

**PHP version:**
7.0

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 12.0.4

**Audio Player version:** (see `/settings/apps`)
2.3.1

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
no

**Are you using encryption?** yes/no
no

**Have you activated other multimedia apps?** `Music/Folder Player/...`
no

**Audio Player media folder:** (see Settings) `root/Music/...`
doesnt matter

### Client configuration
**Operating system:**
Windwos 10

**Browser:**
Firefox, Opera, Chrome

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
{"reqId":"7w2Sz60tm1uctlBwEGPT","level":3,"time":"2018-08-12T13:27:10+02:00","remoteAddr":"94.22.23.227","user":"user","app":"PHP","method":"POST","url":"\/nextcloud\/apps\/audioplayer\/checknewtracks","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/nextcloud\/lib\/private\/Files\/Cache\/Cache.php#166","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.87 Safari\/537.36 OPR\/54.0.2952.64","version":"12.0.6.1"}

```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
are these normal files of several-hour-mp3 or FLACs? something fills up 500MB.

I only head similar issues when using SMB external shares without the proper library installed
https://github.com/Rello/audioplayer/wiki/External-Storage

**Comment by GitGobo** [comment]
I have a lot of mp3 files and only a few flac files. But when I change the music folder to a single folder with only 5 mp3 files the problem still exists.
I do not use external shares, all files are on the internal hdd.
Is there a way to increase the 500MB limit? I tried to change it in the php.ini but this doesn't change anything.

**Comment by Rello** [comment]
Hello,
the strange thing is, that this error comes up in checknewtracks, which is not even accessing the files itself.
it is only checking the NC cache (which is based on the filecache table). don´t know whats wrong in the backend. sorry.

I would recommend to give a current NC version a try to see if it performs better.
