### ISSUE TITLE
how to get rid of it ???

### ISSUE THREAD

**Issue by krrkrr** [Rello/audioplayer#327]
Hi.

I've added audioplayer several months ago. Then recently I tried to update my nextcloud and it failed because of audioplayer which cannot be updated.. and I was stuck. After several hours, I managed to "bypass" the problem and make my nextcloud update. 
I've deleted audioplayer from the app folder, I've deactivated it in my nextcloud administration... but it's still there. And so, everytime I want to update, Nextcloud tries to update audioplayer... and so, it fails and I'm stuck... and again, I spend hours trying to bypass that.

I think the reason is that audioplayer instances are still in my databases. How can I get rid of that ???

php is 7.1.3, mysql is 5.7.21, nextcloud is 13.0.x

thanks

**Comment by Rello** [comment]
Hello,
It would be interesting to see the error of the upgrade issue to have it fixed. do you get any message?

When deactivating an external app, you should then get a "remove" in the NC admin console. this takes care of everything.
to get rid of an NC app you need to remove the app in the app folder and remove the rows in the appconfig table.

but if you could give me a hint what the issue is?
the compatibility settings are fine
https://github.com/Rello/audioplayer/blob/master/appinfo/info.xml#L36-L37

**Comment by krrkrr** [comment]
in the update page, NextCloud only says that's it failed... just while trying to update audioplayer. after that, the nextcloud goes into maintenance mode and stay that way. 
If I try to update only audioplayer, in the app page, the button goes OK and then, maintenance mode, stuck again.
I deactivated audioplayer (I got no "remove" button) but nothing is changed in my databases...

**Comment by Rello** [comment]
did you try an `occ upgrade` already if there is more detail?
or check the `nextcloud.log` ?

**Comment by krrkrr** [comment]
nothing is shown in the nextcloud.log... nor in the journal...

I've tried several things since yesterday... it seems I got issues with any 3rd party apps, in fact... Audioplayer was mainly the first one that shows errors because, I guess, it begins with an A .... I don't get it: I can't activate nor update any 3rd party apps ????

**Comment by Rello** [comment]
on the one hand it sounds good - that AP is not messing it up.
on the other hand it sounds like a major chaos in your installation. I guess something went terribly wrong during an upgrade and the database/filesystem are out of sync.

do you have your data separated? 
did you think already about a fresh setup?

- backup the data/config dir
- delete the whole NC-Folder
- download the latest one from scratch
- copy back
- start the instance

**Comment by krrkrr** [comment]
I already did that.... twice. backuped the NC folder, just in case, dl-ed a fresh one... copied the config... start again... I did that using both download and web install.... same results. 

and it starts to have effect on the rest of the install.... after a moment, the instance just crashes... no warning, nothing in logs, etc... I don't know what to do....

**Comment by Rello** [comment]
Hey,
sorry to hear. but you seem to have a serious issue with your NC installation.
I recommend to ask https://help.nextcloud.com for support
