### ISSUE TITLE
Option Hide / Show left panel

### ISSUE THREAD

**Issue by hitam4450** [Rello/audioplayer#33]
Hi,

The left panel in Version 1.01 was selectable **show or hide**.
Unfortunately, this feature was deleted in Version 1.02 and the left panel covers now a fixed portion of the display, which makes it not nice, during "Music play".

Please revert to the "**old and former style**" of making it user selectable and **not** fixed proportion!

 I am sure, many other user feel the same way....... of using your great audioplayer!

regards, hitam4450

**Comment by Rello** [comment]
Hello,
Please empty your browser cache as the updated .js files might not be loaded.
next to the reverse/play/forward icons in the soundbar, the icon for show/hide of the navigation pane should be displayed.

can you please evaluate if this is the case?
or provide a screenshot?
che funktionality of show/hide was not changed. the only change was to keep the soundbar always visible (not scrolling when many albums are displayed) and to show it initially when there was no library-scan yet.

let me know...

**Comment by hitam4450** [comment]
Hi, 
i use ff47.0 on UBUNTU 14.04 LTS. NextCloud 9.0.51 
I emptied the browser cache, reload the page and nothing can be see of the icon show/hide (taken after reload of the page ,see enclosed screen shot)!
![audioplayer1](https://cloud.githubusercontent.com/assets/9738727/17430330/d5bb81c0-5af3-11e6-9bbd-e564a30b9f6b.png)

**Comment by Rello** [comment]
ah, ok.
in this case the bar is not hidden because you don´t have anything scanned.
when the bar would go to hide, the "rescan" icon would be gone and you would be "locked out".

rescan your library and everything will work as before

**Comment by hitam4450** [comment]
Ok, it works as mentioned!

In Version 1.01 the show / hide icon was present, even there were "no media files " available!
Thanks for your quick support!

regards, hitam4450

**Comment by Rello** [comment]
> In Version 1.01 the show / hide icon was present, even there were "no media files " available!

I know.
the current change is related to #25 
I could not find a way around until now. if I do, I will re-enable it :-)
