### ISSUE TITLE
update of Audio Player language files for 2.4.0

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#333]
- [X] @r4sas may I ask you for an update of `l10n/ru.json`
- [x] @447937 may I ask you for an update of `l10n/cs.json`
- [x] @limingqi  may I ask you for an update of `l10n/zh_CN.json`
- [x] @andypl78  may I ask you for an update of `l10n/pl.json`
- [x] @sbr9150  may I ask you for an update of `l10n/zh_TW.json`
- [x] @mzeyrek  may I ask you for an update of `l10n/tr.json`
- [ ] @BODYA7979  may I ask you for an update of `l10n/uk.json`

there were some minor additions for the new SONOS plugin to be released
Thank you all!

**Comment by Rello** [comment]
#331

**Comment by r4sas** [comment]
Only json?

add:
`All titles will be played on your SONOS speaker`
Here `titles` means `tracks`?

**Comment by Rello** [comment]
hello,

yes. just the json with 4 lines at the bottom.
and yes - titles means tracks/audio files/

thank you!

**Comment by Rello** [comment]
#342

**Comment by Rello** [comment]
a little reminder to  @sbr9150 @mzeyrek @BODYA7979

**Comment by Rello** [comment]
#344

**Comment by Rello** [comment]
#346

**Comment by r4sas** [comment]
Hafl of `settings/user/audioplayer` is not translated idk why.  14.0.1.
![image](https://user-images.githubusercontent.com/7023612/46440392-de4fcd00-c76b-11e8-941d-7566194787db.png)
upd: Can you create full english lang file with all translable strings?

upd2: 
https://github.com/Rello/audioplayer/blob/f174b92621c2ebea33103f672d7501a9438bf0d8/templates/settings-personal.php#L30
Better to change to
```        <label for="cyrillic_user"><?php p($l->t('Cyrillic support')); ?>:</label>```
to use that line and prevent duplicating of translation strings:
https://github.com/Rello/audioplayer/blob/f174b92621c2ebea33103f672d7501a9438bf0d8/l10n/ru.json#L63
