### ISSUE TITLE
Uncaught Error: Access to undeclared static property - NC 9

### ISSUE THREAD

**Issue by alphamat** [Rello/audioplayer#34]
I have at ussage of the audioplayer app the following errors in admin log:

`Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/htdocs/lib/private/files/filesystem.php:798 Stack trace: #0 /var/www/htdocs/lib/private/files/view.php(2011): OC\Files\Filesystem::normalizePath('/MaT/files/Musi...') #1 /var/www/htdocs/lib/private/files/view.php(1129): OC\Files\View->unlockFile('/Music - World/...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/htdocs/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/htdocs/lib/private/files/filesystem.php#798`

My config:  Debian 8, NC 9.0.53, PHP 7, Apache 2.4

Thx for feedback & resolve :-)

**Comment by Rello** [comment]
Can you please retry the current 1.1.0
It was trsted with NC

**Comment by alphamat** [comment]
i have upgraded today - but still error reports when i use the app - in frontend it works perfect - but the logfile is full with this errors:

`Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/htdocs/lib/private/files/filesystem.php:798 Stack trace: #0 /var/www/htdocs/lib/private/files/view.php(2011): OC\Files\Filesystem::normalizePath('/MaT/files/Musi...') #1 /var/www/htdocs/lib/private/files/view.php(1129): OC\Files\View->unlockFile('/Music - World/...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/htdocs/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/htdocs/lib/private/files/filesystem.php#798`

thanks in advance for your feedback ;-)

**Comment by Rello** [comment]
Hello,
just got the same in my error log for the first time.
...trying to reproduce it....

**Comment by Rello** [comment]
Hello,
it seems to be an issue in some core functionality in relation to PHP7.
it is discussed here
https://github.com/owncloud/core/issues/22370

Unfortunately I cant help you from audioplayer perspective :-(

**Comment by ghost** [comment]
No problems here with NC 9.0.53 and PHP 7.0.10. Neither with the player itself nor with a publicly shared file or with an audio file in the Files app.

No problems with oC 9.1.0 and NC 9.1.0 too.

**Comment by alphamat** [comment]
Upgrade to nc 9.1.0.16 resolve the issue 
Thx for your work ;-)

**Comment by alphamat** [comment]
@Rello 
The error is now back again also in NC 9.1.0.16 (10) - always at every song at the app ... in other parts of NC / other apps it does not happen curiously ... 

Is there any different in OC or NC cloud regarding this problem?  Because you postet the owncloud issue tracker

**Comment by Rello** [comment]
Its an issue in the core - and tahts the same in NC/OC

Still searching. But the app is working - correct?
Only the log is spammed

**Comment by alphamat** [comment]
yes the good thing is the app is working :+1:  - only the log file is full within seconds with this spam - i found the problem now also when i click normal inside the folders with short clicks - same issue

**Comment by Rello** [comment]
look at the OC-Issue - quite some deep debugging ongoing :-)

if you have any additional observations, it might help them

**Comment by alphamat** [comment]
looks good ;-)
i hope NC team get the info too when OC has resolved the issue
