### ISSUE TITLE
new version of getID3 to recognize Ogg Flac (oga) files

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#340]
### Expected behavior

Adds oga (Ogg Flac) data to database

### Actual behavior

Rejects files with "Error with getID3. Does not seem to be a valid audio file"

### Steps to reproduce the behavior

1. generate ogg flac (oga) file using `flac --ogg`
2. add it to folder of user
3. (add some useful tags via musicbrainz picard)
4. run `php occ audioplayer:scan --all --debug`

### Possible solution (optional)

Fix getID3 support for OGG Flac files

### Server configuration
**Operating system:**

Debian stretch amd64

**Web server:**

apache2

**Database:**

Postgresql

**PHP version:**

PHP7.0

**Nextcloud/ownCloud version:** (see `/status.php`)

Nextcloud 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from Nextcloud 13.0.4

**Audio Player version:** (see `/settings/apps`)

2.3.2

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`

NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

smb

**Are you using encryption?** yes/no

no

**Have you activated other multimedia apps?** `Music/Folder Player/...`

Video Player (preinstalled?)

**Audio Player media folder:** (see Settings) `root/Music/...`

Music

### Client configuration
**Operating system:**

Debian Stretch amd64

**Browser:**

Chromium 69.0.3497.81

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Nope
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
```

</details>

**Comment by Rello** [comment]
hello, 
i am not sure what the issue is here.
can you please send the file to audioplayer<at>scherello<dot>de ?

**Comment by ghost** [comment]
I have thousands of these files but these are all copyrighted material. But I've just created an 1s silent wav file, converted it to OGG Flac via:

    flac --best  --ogg test.wav -f

and then tagged it with musicbrainz picard as schweigeminute from knorkator.  The resulting file is attached (don't forget to uncompress - had to compress it because github didn't allow to upload the file without being in a ZIP container): [test.zip](https://github.com/Rello/audioplayer/files/2391456/test.zip)

The ouput of the audioplayer:scan is:

    /foobar/files/musik/test.oga
        Error with getID3. Does not seem to be a valid audio file

So the same message I get for every OGG Flac file on my system.

**Comment by Rello** [comment]
i will check if getID3 can handle it...

**Comment by Rello** [comment]
Hello,
i am using the getID3 library and this does not know this format
https://github.com/JamesHeinrich/getID3

Error: 
`Expecting either "Speex ", "OpusHead" or "vorbis" identifier strings, found "FLAC"`

So there is nothing I can do unless the maintainer knows what this file format is

**Comment by ghost** [comment]
This is no reason to close this bug. You ship this library and thus it is a bug in your App. Why don't you ask the getID3 library for the support?

**Comment by Rello** [comment]
Hello,
I am offering this app for free in my freetime. This time has to be invested wisely.
And when one user out of >20.000 has an issue with a strange file format which is not even recognised by one of the most commonly used library, I have to prioritise.

Sorry for this...

**Comment by ghost** [comment]
But getID3 supports it. Check their list of supported files:

* Ogg (Vorbis, OggFLAC, Speex, Opus)

And it is generated by the official flac tool. So don't say that it is a strange file format.

**Comment by Rello** [comment]
Hello, 
again: not supporting your combination for some reason. the mentioned error message is from the latest getID3 version. Audioplayer has no involvement here

Feel free to try yourself: download getID3, put it on a server, put your file into the demos folder and open the browse.php

if you get James to fix whatever this is, it will be included in the next version

**Comment by ghost** [comment]
And again to you: don't close tickets which are not yet fixed.

Also see https://github.com/JamesHeinrich/getID3/commit/17461949907103a68d0390103c50962618d318a4

**Comment by ghost** [comment]
Btw. it works fine with the getID3 library

    $ php7.0 ../demos/demo.simple.php
    <html><head><title>getID3() - /demo/demo.simple.php (sample script)</title><style type="text/css">BODY,TD,TH { font-family: sans-serif; font-size: 9pt; }</style></head><body><table border="1" cellspacing="0" cellpadding="3"><tr><th>Filename</th><th>Artist</th><th>Title</th><th>Bitrate</th><th>Playtime</th></tr><tr><td>/tmp/test/test.oga</td><td>Knorkator</td><td>Schweigeminute</td><td align="right">226 kbps</td><td align="right">0:01</td></tr></table></body></html>
    $ php7.0 demo.browse.php
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>getID3() - /demo/demo.browse.php (sample script)</title><link rel="stylesheet" href="getid3.css" type="text/css"><meta http-equiv="Content-Type" content="text/html;charset=UTF-8" /></head><body>                                                                                                                                                                                                                                                                                                            Processing <span title="index.php">.</span> <span title="getid3.css">.</span> <span title="demo.simple.php">.</span> <span title="demo.mimeonly.php">.</span> <span title="demo.cache.mysql.php">.</span> <span title="demo.write.php">.</span> <span title="demo.audioinfo.class.php">.</span> <span title="demo.mp3header.php">.</span> <span title="demo.simple.write.php">.</span> <span title="demo.cache.dbm.php">.</span> <span title="demo.browse.php">.</span> <span title="test.oga">.</span> <span title="demo.zip.php">.</span> <span title="demo.joinmp3.php">.</span> <span title="demo.mysql.php">.</span> <span title="demo.basic.php">.</span> <span title="demo.dirscan.php">.</span> <span title=".">.</span> <span title="..">.</span>done<br>Directory scanned in 0.06 seconds.<br><table class="table" cellspacing="0" cellpadding="3"><tr bgcolor="#CCCCDD"><th colspan="14">Files in /var/www/html/nextcloud/getID3/demos/</th></tr><tr bgcolor="#EEBBBB"><td colspan="14"><form action="demo.browse.php" method="get">Parent directory: <input type="text" name="listdirectory" size="50" style="background-color: EEBBBB;" value="/var/www/html/nextcloud/getID3"> <input type="submit" value="Go"></form></td></tr><tr bgcolor="#CCCCDD"><th>Filename</th><th>File Size</th><th>Format</th><th>Playtime</th><th>Bitrate</th><th>Artist</th><th>Title</th><th colspan="3">MD5&nbsp;Data</th><th>Tags</th><th>Errors &amp; Warnings</th></tr><tr bgcolor="#DDDDDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Ftest.oga" title="View detailed analysis">test.oga</a></td><td align="right">&nbsp;36,657</td><td align="right">&nbsp;ogg.flac</td><td align="right">&nbsp;0:01</td><td align="right">&nbsp;<span style="color: #6b0094; font-weight: bold;">226 kbps</span></td><td align="left">&nbsp;Knorkator</td><td align="left">&nbsp;Schweigeminute</td><td align="center" colspan="3">-</td><td align="left">&nbsp;vorbiscomment</td><td align="left">&nbsp;<a href="#" onClick="alert('METADATA_BLOCK_HEADER.BLOCK_TYPE (reserved) at offset 1280 extends beyond end of file'); return false;" title="METADATA_BLOCK_HEADER.BLOCK_TYPE (reserved) at offset 1280 extends beyond end of file">warning</a><br></td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.audioinfo.class.php"><i>demo.audioinfo.class.php</i></a></td><td align="right">&nbsp;8,364</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.basic.php"><i>demo.basic.php</i></a></td><td align="right">&nbsp;2,561</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.browse.php"><i>demo.browse.php</i></a></td><td align="right">&nbsp;30,472</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.cache.dbm.php"><i>demo.cache.dbm.php</i></a></td><td align="right">&nbsp;1,315</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.cache.mysql.php"><i>demo.cache.mysql.php</i></a></td><td align="right">&nbsp;1,351</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.dirscan.php"><i>demo.dirscan.php</i></a></td><td align="right">&nbsp;7,422</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.joinmp3.php"><i>demo.joinmp3.php</i></a></td><td align="right">&nbsp;5,455</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.mimeonly.php"><i>demo.mimeonly.php</i></a></td><td align="right">&nbsp;2,985</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.mp3header.php"><i>demo.mp3header.php</i></a></td><td align="right">&nbsp;121,049</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.mysql.php"><i>demo.mysql.php</i></a></td><td align="right">&nbsp;108,905</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.simple.php"><i>demo.simple.php</i></a></td><td align="right">&nbsp;2,805</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.simple.write.php"><i>demo.simple.write.php</i></a></td><td align="right">&nbsp;2,754</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.write.php"><i>demo.write.php</i></a></td><td align="right">&nbsp;11,558</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fdemo.zip.php"><i>demo.zip.php</i></a></td><td align="right">&nbsp;4,166</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCFF"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Fgetid3.css"><i>getid3.css</i></a></td><td align="right">&nbsp;2,380</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#BBBBDD"><td><a href="demo.browse.php?filename=%2Fvar%2Fwww%2Fhtml%2Fnextcloud%2FgetID3%2Fdemos%2Findex.php"><i>index.php</i></a></td><td align="right">&nbsp;718</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="right">&nbsp;-</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td><td align="left" colspan="3">&nbsp;</td><td align="left">&nbsp;</td><td align="left">&nbsp;</td></tr><tr bgcolor="#CCCCDD"><td><b>Average:</b></td><td align="right">350,917</td><td>&nbsp;</td><td align="right">0:01</td><td align="right"><span style="color: #6b0094">226 kbps</span></td><td rowspan="2" colspan="9"><table class="table" border="0" cellspacing="0" cellpadding="2"><tr><th align="right">Identified Files:</th><td align="right">1</td><td>&nbsp;&nbsp;&nbsp;</td><th align="right">Errors:</th><td align="right">0</td></tr><tr><th align="right">Unknown Files:</th><td align="right">16</td><td>&nbsp;&nbsp;&nbsp;</td><th align="right">Warnings:</th><td align="right">1</td></tr></table></tr><tr bgcolor="#CCCCDD"><td><b>Total:</b></td><td align="right">350,917</td><td>&nbsp;</td><td align="right">0:01</td><td>&nbsp;</td></tr></table><div style="border: 1px #CCCCCC solid; padding: 5px; margin: 5px 0; float: left; background-color: #EEEEEE; font-size: 8pt; font-family: sans-serif;">Powered by <a href="https://www.getid3.org/"><b>getID3() v1.9.15-201809221240</b><br>https://www.getid3.org/</a><br>Running on PHP v7.0.30-0+deb9u1 (64-bit, Linux)</div><br clear="all"></body></html>


but not when copied to your audioplayer to nextcloud/apps/audioplayer/3rdparty/getid3/:

    Error with getID3. Does not seem to be a valid audio file

**Comment by Rello** [comment]
fine with me if it was fixed.
will include the next official release of getID3 in 2.5.
Testing and modification is more complex here. copying into 3rdparty will not work due to tweaks required

**Comment by Rello** [comment]
getID3 updated;
testfile successfully indexed
