### ISSUE TITLE
Play button not displayed due to png format

### ISSUE THREAD

**Issue by YannuX06** [Rello/audioplayer#345]
Since I upgrade to version 2.4 (via webgui in https) I get a boken image instead of the play button in front of the cover.

My configuration : 
Debian 9 (Apache2,PHP7,MariaDB)
Nextcloud 14
Audio player 2.4

PS : Installing php7-gd didn't solve my problem

Thanks in advance,
Regards.

**Comment by Rello** [comment]
Hello,
does it not look like this?
![screen shot 2018-09-26 at 22 05 24](https://user-images.githubusercontent.com/13385119/46106180-4fc1d580-c1d8-11e8-9a0d-17e380f8614b.png)

can you check with a web inspector of your browser, please?
it should point here:
![screen shot 2018-09-26 at 22 06 47](https://user-images.githubusercontent.com/13385119/46106232-813aa100-c1d8-11e8-8ac6-7f94c8b0506e.png)

**Comment by YannuX06** [comment]
Hello,

It looks like this:
![image](https://user-images.githubusercontent.com/28445079/46107505-ce6c4200-c1db-11e8-9c57-eec677e8d549.png)

and the source code:
![image](https://user-images.githubusercontent.com/28445079/46107527-dfb54e80-c1db-11e8-912b-01e2c9ebcfd6.png)

Thanks a lot for your support !

**Comment by Rello** [comment]
can you check if the file is actually in the `apps/audioplayer/img/ folder`?
which browser?

**Comment by YannuX06** [comment]
Yes it is:
![image](https://user-images.githubusercontent.com/28445079/46128585-3babc180-c234-11e8-92b3-e053c3ef40e6.png)
Same issue with Firefox,Chrome/Opera and Edge (with purge of cache & history before)

**Comment by ghost** [comment]
Nextcloud 14.0.0
![_20180927153029](https://user-images.githubusercontent.com/16513529/46129802-59941900-c26a-11e8-8437-d19ef60b139f.png)
![_20180927153336](https://user-images.githubusercontent.com/16513529/46129977-bb548300-c26a-11e8-87f3-ffded82ab428.png)

**Comment by Rello** [comment]
Hello, could one of you send me a guest account to your installations to audioplayer(at)scherello.de ?
I can not reproduce it in my test setups

thank you!

**Comment by craig24x** [comment]
Same here, using Owncloud 
![screenshot from 2018-09-28 21-54-22](https://user-images.githubusercontent.com/37234175/46239671-b4f90080-c369-11e8-8fec-641b34203637.png)
![screenshot from 2018-09-28 22-00-48](https://user-images.githubusercontent.com/37234175/46239700-14efa700-c36a-11e8-8225-62e98d8bc034.png)

**Comment by Rello** [comment]
@craig24x @YannuX06 @PYGC 
can one of you please create a guest account and send it via email to audioplayer(at)scherello.de

On my test instances on oC, NC13, NC14 this issues does not come up

**Comment by Rello** [comment]
thank you @PYGC for the account. it seems there is an issue with the file itself due to the .png extension.
I will correct this and push a bugfix as soon as possible

**Comment by Rello** [comment]
issue is fixed. this issue will be closed as soon as the v.2.4.1 is released

thank you for your support!

**Comment by YannuX06** [comment]
Thanks a lot for the corrections made in 2.4.1 , it solve the problem for me too !

Especially thank you very much for this great job that is media player

Yann

**Comment by Rello** [comment]
I am glad that it worked out and that you like the app.

always happy to get some sponsoring for some motivation drinks :-)
https://github.com/Rello/audioplayer/wiki/Donate
