### ISSUE TITLE
ID3 tags aren't all read

### ISSUE THREAD

**Issue by jimbolaya** [Rello/audioplayer#347]
### Expected behavior
I am hoping to see each song with an Artist and Album pulled from the ID3 tags.

### Actual behavior
I see the Artist and Album for some of my files, but around 2900 out of 3200 say Unknown for the Artist and Album. 

### Steps to reproduce the behavior
1. Scan (or Rescan) for audio files that are on "external" storage (just a directory that's local to the server mounted in Nextcloud)
2. I've spot checked a number of the files using "`exiftool -json <filename>`" to see what's listed for the file and all the ones I've checked have both of those fields filled.

### Server configuration
**Operating system:**
Debian Jessie v9 

**Web server:**
Apache 2.4.10

**Database:**
MySQL 5.5

**PHP version:**
PHP 5.6.38

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.10
Initial install was Owncloud 6 or 8 or something and upgraded over time

**Audio Player version:** (see `/settings/apps`)
2.4.0

**Where did you install Audio Player from?** `NC App Store/oC Marketplace/GitHub`
NC App Store

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
Yes: local

**Are you using encryption?** yes/no
Yes

**Have you activated other multimedia apps?** `Music/Folder Player/...`
No

**Audio Player media folder:** (see Settings) `root/Music/...`
/media/md1/music

### Client configuration
Linux/Windows/etc

**Browser:**
Firefox/Chrome

**Comment by jimbolaya** [comment]
After reading some more detail, especially about the ID3 scanner you seem to be using, I used "eyeD3" to convert the ID3 tags from v1 to v2 (v2.3 specifically). Now the ID3 information shows up correctly.

**Comment by Rello** [comment]
yes, thats correct.
for compatibility issues we are dependent on V2
https://github.com/rello/audioplayer/wiki/how-are-id3-tags-processed

thank you for reporting back
