### ISSUE TITLE
SONOS socket backend error handling

### ISSUE THREAD

**Issue by monreal** [Rello/audioplayer#348]
### Expected behavior
Audio playback with latest release

### Actual behavior
No audio playback with latest release

### Steps to reproduce the behavior
1. try to play a song

### Additional information (optional)

  | Error: Call to undefined function OCA\audioplayer\Controller\socket_create()/var/www/html/custom_apps/audioplayer/lib/Controller/SonosController.php - line 169: OCA\audioplayer\Controller\SonosController->discoverDevices()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\audioplayer\Controller\SonosController->getDeviceList()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\audiopla ... {}, "getDeviceList")/var/www/html/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\audiopla ... {}, "getDeviceList")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\audiop ... r", "getDeviceList", OC\AppFramew ... {}, { _route: "a ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "a ... "})/var/www/html/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "a ... "})/var/www/html/lib/base.php - line 989: OC\Route\Router->match("/apps/audio ... s")/var/www/html/index.php - line 42: OC::handleRequest()
-- | --

### Server configuration
**Operating system:** using the latest official Nextcloud docker image
**Nextcloud/ownCloud version:** 14.0.0
**Audio Player version:** 2.4.0 (playback used to work fine)
**Where did you install Audio Player from?** NC App Store
**Are you using external storage? no
**Are you using encryption?** no
**Have you activated other multimedia apps?**  no
**Audio Player media folder:** (see Settings) `/Music/`

### Client configuration
**Operating system:** Fedora 28
**Browser:** Firefox 63

**Comment by Rello** [comment]
Hello,
this error comes up when you open the user-settings. is this correct?
this function is used to scan for available sonos devices. Did your players show up within the dropdown?

If you don´t have a valid player selected, you should not enable the Sonos-Feature (some error handling there still missing).

please let me know when this issue showed up

**Comment by monreal** [comment]
Thanks for pointing out the Sonos thing! I don't own one and in fact the setting was showing as "off". I then switched it on and off and now the player works fine again.

**Comment by monreal** [comment]
Actually, it still doesn't work on my laptop... will have to look deeper tomorrow
