### ISSUE TITLE
NC14.0.1 & Audio Player 2.4.1: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [Rello/audioplayer#349]
`occ app:check-code audioplayer`

```
Invalid appinfo.xml file found: Element 'owncloud': This element is not expected.

Invalid appinfo.xml file found: Element 'types': This element is not expected. Expected is one of ( background-jobs, repair-steps, two-factor-providers, commands, settings, activity, navigations, contactsmenu, collaboration, sabre ).

App is not compliant
```

What does this mean?
Thank you!

**Comment by Rello** [comment]
Hello,
thank you, I will take care.
its actually not an issue - it seems that the code-checker does not like the sequence of the elements in .xml
I will try to find out how which sequence will make it happy

**Comment by Rello** [comment]
https://github.com/nextcloud/server/issues/12942

**Comment by Rello** [comment]
hello,
this issue is cosmetic as the tags are required (types) or irrelevant for NC (owncloud).
As the app is working on both releases, it has to be kept like that

**Comment by Rello** [comment]
The `types` for instances has to follow the `namespace` tag. https://apps.nextcloud.com/schema/apps/info.xsd

**Comment by Rello** [comment]
types was rearanged.

2 findings remaining
```
Invalid appinfo.xml file found: Element 'owncloud': 
Invalid appinfo.xml file found: Element 'settings-sections': 
```
These are OC dependencies and can not be removed
