### ISSUE TITLE
Closing tracklist on album jumps to top

### ISSUE THREAD

**Issue by MrManor** [Rello/audioplayer#351]
### Expected behavior
When I close the track list popup, from a album in the main window I expect to remain in the same position on the page.

### Actual behavior
Jumps to top page

### Steps to reproduce the behavior
1. open the audio player with a list of records bigger that web page
2. scroll down somewhat 
3. open track list for an album
4. close tracklist using X in upper left cornor

### Server configuration
**Operating system:**
openSUSE Leap 42.3

**Web server:**
apache2-prefork-2.4.23

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
nextcloud-14.0.1

**Audio Player version:** (see `/settings/apps`)
2.4.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
yes /shared/musik/ is "external" on the nexcloud host, mounted as
/dev/vdb1 on /shared type xfs (rw,relatime,attr2,inode64,noquota)

### Client configuration
**Operating system:**
openSUSE Leap 42.3

**Browser:**
Firefox 60.2.1esr (64-bit) and Google-Chrome 

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
nothing logged on playlist view on page
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
nothing logged on playlist view on page
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
thank you for the report. I will check

**Comment by Rello** [comment]
coming with v2.5
