### ISSUE TITLE
switch from --debug to verbosity levels in occ

### ISSUE THREAD

**Issue by mmattel** [Rello/audioplayer#352]
### Expected behavior
Show scanning details

### Actual behavior
Nothing shown, htop shows load and audioplayer activity

### Steps to reproduce the behavior
1.  sudo -uwww-data ./occ audioplayer:scan -v (or -vv)

### Server configuration
**Operating system:** Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**Nextcloud/ownCloud version:** (see `/status.php`) oC 10.0.10

**Audio Player version:** (see `/settings/apps`) 2.4.1

**Are you using external storage? If yes, which one:** `smb`

**Comment by Rello** [comment]
Hello,

AP is using the --debug option for the detailed output
https://github.com/rello/audioplayer/wiki/occ-command-line

please let me know if you have further questions.

thank you

**Comment by mmattel** [comment]
``--debug`` & ``-v`` should do the same... or ``-v`` should print a note to use ``--debug`` instead
Current behaviour is imho inconsistent
```
 sudo -uwww-data ./occ audioplayer:scan --help

Usage:
  audioplayer:scan [options] [--] [<user_id>]...

Arguments:
  user_id               scan all audio files of the given user(s)

Options:
      --all             scan all audio files of all known users
      --debug           current processed audio file will be written for detailed analysis
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by Rello** [comment]
hmmm
good point actually. I will have a look. at least -v/vv/vvv should show the same as debug

**Comment by Rello** [comment]
Testing results:
- [x] NC 15
- [x] oC 10
