### ISSUE TITLE
Feature request: Resize left pane

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#354]
It would be nice to be able to drag the the album pane left and right so one can see long names.

![image](https://user-images.githubusercontent.com/15927695/47002581-b5e1ae80-d12d-11e8-868d-15ddecc0da23.png)

**Comment by Rello** [comment]
Hello,

the sidebar is a stock item of Nextcloud which can not be tweaked to my knowledge.
But I will have a look. for longer records, the mouseover titles should actually be shown. does this work on your side?

**Comment by AmonBune** [comment]
Oh well, I hope there is a way to change it anyways somehow.

And mouseover does not work on my end. It doesn't shows any tooltip messages or anything if I hover over it.

I use Firefox Developer Edition (the latest one)

**Comment by Rello** [comment]
Hello,

the sidebar will not be adjustable, as it is NC standard. Changing would mean efforts for every release due to incompatibilities.
The "title" tag was fixed instead so the rollover/hover is working correctly
