### ISSUE TITLE
Feature Request: Seamless Playback

### ISSUE THREAD

**Issue by newhinton** [Rello/audioplayer#360]
Currently while playing an album, the switch to the next song is not seamless and there is a noticable gap. Maybe, this could prevented with preoloading the next audiostream so that there is no loading phase between the two songs.

This was tested on Opera and Firefox 63, with Nextcloud 14.0.3 and Audioplayer 2.4.1

**Comment by Rello** [comment]
I can not follow this request due to very limited time available at the moment.
This involves frontend buffering where I do not have any insights. AP is dependent on the Soundmanager2 at the moment and I don´t know how this could be done there.

#272
