### ISSUE TITLE
Feature: APIs for external music apps (Android, iOS

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#365]
With this Issue, I want to keep track of the current support for external apps, accessing the AP APIs.

ToDos:
- [ ] API for current version of AP to ensure compatibility of external app
- [ ] API for titles with webdav links

Existing APIs
- [ ] to be done....

**Comment by Rello** [comment]
@newhinton
@waltercool

**Comment by jakobroehrl** [comment]
@newhinton @waltercool
Is there still a beta version for testing? Would love to do this. 
Chromcast support would be awesome!

**Comment by newhinton** [comment]
I have modified an open source player for my needs, but the code is very hard to maintain. Expanding it to talk to nextcloud would be possible, but hard. I did not forget about this, but i also do not have enough time to get it done anytime soon, sorry :(

**Comment by memen45** [comment]
What is the status on this? And also, where can i find documentation on the API?

**Comment by waltercool** [comment]
> What is the status on this? And also, where can i find documentation on the API?

I started to work some progress into an opensource project (Timber https://github.com/naman14/Timber), but has too much problems, doesn't work at Android 10 and main developer dropped the project. Haven't tried to modify another Android project right now.

Also tried to start a new project, but there are already too many music players already on (don't reinvent the wheel). Do you know some good opensource music player to suggest and I can start working on it.

**Comment by memen45** [comment]
I am not familiar with open source audio players for Android in general. I found some that might be useful

- Exoplayer (enables streaming media as a replacement for Android MediaPlayer API) could be used internally
- Veezee seems quite nice and cross platform (Android and iOS)
- UltraSonic (works with subsonic API) has an old UI 

However, whichever you want to start from, you need an API on the nextcloud audio player in order to load playlists and access the streams etc. That is why I am interested to know how this API is defined, so we can access it from external apps.

**Comment by memen45** [comment]
@waltercool I found that the other nextcloud music app ([here](https://GitHub.com/owncloud/music)) has a well defined API, including subsonic and ampache endpoints. Both have several compatible apps already on Android and iOS (see [wiki](https://github.com/owncloud/music/wiki/Subsonic)), so you could contribute to one of those.

Best regards,

**Comment by Rello** [comment]
Hello,

thats correct. music included the ampache backend.
I thought about this for AP also - but then as an add-on to separate the development cycles.
it would be "just" the endpoints based on the existing AP tables.

Problem here: the use case
- Its private project and the time is limited. also due to my second app (Analytics)
- I would estimate 1-2 weeks of evening work here
- there are only very little number of users requiring this
- there is no funding of this requirement to motivate developments

on the other hand, I think it would be a nice task vor any other developer to start this app (I can support here for sure).
Its about understanding the ampache idea and connecting it to the existing tables

anyone wants to give it a try? :-)

**Comment by Rello** [comment]
for documentation:
this is the ampachecontroller with the core logic in the music app.
this would require some adaption to AP
https://github.com/owncloud/music/blob/master/controller/ampachecontroller.php

**Comment by Rello** [comment]
no further priority

**Comment by DatNoHand** [comment]
well actually... 😉 

I have tested both the Music App and Audioplayer and I have to say I prefer the Audioplayer Webinterface. The only drawback for me is the lack of Ampache / Subsonic support which enables mobile apps in Audioplayer

And I don't really like having to maintain two apps, libraries, keep them updated, etc.. so I cannot switch to Audioplayer yet.

Maybe someday I can look into developing a plugin, if I manage to get some free time. But the need for mobile support is definitely existent!
