### ISSUE TITLE
Dark Design and theming compatibility

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#367]
As you see, the dark design doesn't really look good within the audioplayer app.

![image](https://user-images.githubusercontent.com/15927695/49872012-0ae12e80-fe18-11e8-85e8-0963b4082649.png)

As the dark design is still in preview, it could be that it's nextcloud-server's "fault", but I'm not sure. I thought I'll let you know that it looks a bit off so you could fix it, if you have time :)

**Comment by Rello** [comment]
thank you for this.
this is correct, that AP does not work correctly with the dynamic background variables in the css files yet.
the issue is not the background, but all the icons, which need to be redesigned.
a to do...

**Comment by Rello** [comment]
Compatibility corrected
![screen shot 2018-12-15 at 11 10 59](https://user-images.githubusercontent.com/13385119/50041754-2c315d00-005a-11e9-9df4-8d53a81fde55.png)

**Comment by Rello** [comment]
Note:
**This is only working in Nextcloud**
ownCloud does not have this feature

**Comment by AmonBune** [comment]
NC version 15.0.0/15.0.1 seem to have a new mobile mode when resizing the window. If you have a small window, you'll get theme errors again.

![image](https://user-images.githubusercontent.com/15927695/51022943-ea76d200-1585-11e9-8ba0-01f0e29e6030.png)

**Comment by Rello** [comment]
hey,
you are correct. thank you for the finding!
there was something leftover...
