### ISSUE TITLE
php 7.3 support

### ISSUE THREAD

**Issue by sealionking** [Rello/audioplayer#368]
just update server to php 7.3 and this amazing app stopped work as it not support php 7.3.

Would you please port it to support php 7.3

**Comment by luntik2012** [comment]
+1

**Comment by Rello** [comment]
Hello,
thank you for the report. I will fix this with an update this weekend.
in the meantime you could edit /apps/audioplayer/appinfo/info.xml manually from 7.2 to 7.3
my local tests seem to be ok

let me know...

**Comment by Rello** [comment]
v 2.5.1 released

**Comment by sealionking** [comment]
test on php7.3 and works fine! thanks very much!
