### ISSUE TITLE
Player not loaded on shared folder

### ISSUE THREAD

**Issue by Ark74** [Rello/audioplayer#371]
When an audio file is shared via link, it can't be played within the sharing page.

On Nextcloud 15.0.1
AudioPlayer 2.5.1
php-7.3.1

When clicking on a shared link with music, the audio is not played.

Console shows,

```
GET https://cloud.domain.com/apps/audioplayer/getpublicaudiostream?token=nrTRrodAykwBiNB&file=The%20song%20file.ogg net::ERR_ABORTED 500
nrTRrodAykwBiNB:1 Uncaught (in promise) DOMException
```
Seems that the requested stream requires js which can't be loaded thus the 500 error and no sound.
Cheers!

**Comment by Rello** [comment]
Hello,

do you mean this player?
![screen shot 2019-01-16 at 21 27 27](https://user-images.githubusercontent.com/13385119/51276648-93ce2580-19d5-11e9-89b4-4292e1f8d5c3.png)

There is no audio-player-specific link anymore. It is using the stock-NC file link like `https://testserver/nextcloud/s/S5X6xzGf8QoWWQs/download`

can you please give some more information?

**Comment by Ark74** [comment]
No, I don't seem to have that.
Let me check closer, seems to be a SONOS player disable in my instance.

**Comment by Ark74** [comment]
No, the SONOS player doesn't allowme to pick any.
I only get this one when sharing a folder with music.
![ap_shared](https://user-images.githubusercontent.com/7444518/51282983-4f7a5f80-19ac-11e9-973a-d211a7f31d49.png)

**Comment by Ark74** [comment]
Seems to work on individual files but not on folder shares. :headphones:

**Comment by Rello** [comment]
I will check. thank you for the sonos hint...

**Comment by Rello** [comment]
Issue was located doe to a depreciated api
https://github.com/nextcloud/server/pull/8853

**Comment by Ark74** [comment]
Are these the changes to test,
https://github.com/Rello/audioplayer/commit/e36a004f8f56a949ba4f90529cb7c9f9e0a626c7

**Comment by Rello** [comment]
yes.
I want to fix another minor thing and release 2.5.2 this weekend.
any pretest is appreciated...

**Comment by Ark74** [comment]
Tested on 
- Firefox @ latest
- Google Chrome @ stable

both working.

**Comment by Rello** [comment]
thank you for the quick reply!

**Comment by Rello** [comment]
update released

**Comment by C0rn3j** [comment]
Confirming fixed, thanks a lot.
