### ISSUE TITLE
some album covers on albums page are from other album

### ISSUE THREAD

**Issue by kpalczewski** [Rello/audioplayer#372]
### Expected behavior
proper album cover for the album in albums page

### Actual behavior
some albums have wrong album covers from other albums in library
This is the case for a long time (several months minimum).

### Steps to reproduce the behavior
1. reset library
2. scan for audio files
3. refresh page

### Server configuration
**Operating system:**
ubuntu 16.04.5 LTS

**Web server:**
Apache2 2.4.18

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
15.02

**Audio Player version:** (see `/settings/apps`)
2.5.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
no

### Client configuration
**Operating system:**   **Browser:**
macOS high sierra 10.13.6 Chrome 71.0.3578.98
ubuntu 18.10 chromium 71.0.3578.98

NOT affected:
firefox 64.0 on ubuntu 18.10
safari on macOS high sierra 10.13.6

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hallo @kpalczewski 

covers are coming from 2 locations. There is no double usage

> The cover from the folder of the audio file is searched in the following sequence:
> cover.jpg –> cover.png –> folder.jpg –> folder.png
> If no folder image is found, ID3 tags are searched for included cover arts.

So please check if the titles in question are in the same folder perhaps?

**Comment by kpalczewski** [comment]
there are no images in the folders. 1 album in 1 folder. no mixes.
this issue seems to be related to chromium and some cashing issue.

**Comment by Rello** [comment]
ok, thank you for the update
in the scanner, the cover is cleared for every folder so I don´t think it can sneak in there.
https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L635

Regards...
