### ISSUE TITLE
Feature: share music library via public url

### ISSUE THREAD

**Issue by Chillstice** [Rello/audioplayer#373]
Similarly to how urls can be generated for folders, a user's music library or playlist can be given a url and a simplified version of the Audio Player app. 

Users that request that url (whether they have an account for that NextCloud instance or not) will have read access to the simplified version of the Audio Player interface, populated with the files that are part of that folder/playlist that the url was assigned to.

Sharing a folder with audio files almost works. Users can access the folder and see the content, but clicking on the audio files (without being logged in) does not play the audio like it normally would. Even though the speaker icon appears.

**Comment by Rello** [comment]
Hello,
thank you for the suggestion. But this would mean to develop an own sharing application. Now I am plugging in to the original one.
Unfortunately I don´t have resources to pull of such a big new feature. Despite >10.000 users, the support for the app is almost 0 in any direction.

I would like to focus on the issue why your shareplayer is not working.
do you have any browser logs?

**Comment by Rello** [comment]
#371

**Comment by Rello** [comment]
> Sharing a folder with audio files almost works. Users can access the folder and see the content, but clicking on the audio files (without being logged in) does not play the audio like it normally would. Even though the speaker icon appears.

Hello,
there was an issue being reported with #371 and I think this is also your issue here.
Fix will be released shortly

**Comment by Rello** [comment]
update of AP with the player fix released
