### ISSUE TITLE
cover album stored in database

### ISSUE THREAD

**Issue by daniu-de** [Rello/audioplayer#375]
i checked my databases for Nextcloud and found that audioplayer uses a lot of data in `oc_audioplayer_albums`. I got 45 albums on my NC. Why does that require 9MB database? It seems like the database covers are stored in the database.

Database storage is much more expensive than normal storage. From my point of view it makes little sense to store pictures like this in the database

**Comment by Rello** [comment]
Hello,
thank you for your feedback.
the album cover is stored into the database during the scanner to have it available during normal AP-usage more efficiently.

the cover can be either a `cover.* `file in the album folder or like in most cases coded into the ID3 tags of the audio file.
So when showing the `Albums`-View, reading all mp3 titles from the database to extract their cover from ID3 is the last thing you want to do.
Even worse when the cover is derived from one title out of 10 in an album for example.

Extracting the cover during the scanner and storing as files in the users-file-tree would be too complex for this.
As the whole Nextcloud performance is dependent on the database, proper selection speeds need to be taken as granted.

Additionally, the images are transferred via separate requests from the browser. this enables parallelisation on the first startup and browser caching on subsequent openings.

Of a cover, just a 250x250px resize is stored. They should be around 45kb. I have 4.4MB for 93 images so I am not sure how your DB is calculating the sizes...

I hope this answers your questions.
Regards ....

**Comment by daniu-de** [comment]
Hi,

well ... I don't know either. it is mysql and I see the size in phpmyadmin.

Do you see another way to confirm the size?

would be happy to be ably to verify that. Could even send you the table if you tell me which format and which email address

regards

**Comment by Rello** [comment]
I think this does not make a difference at the end. 
the key question is, if the app works for you

**Comment by daniu-de** [comment]
well ... it does make quite a difference that this app uses about 1/3 of database space of my complete Nextcloud database ...

**Comment by Rello** [comment]
ok.
but there is nothing I could do here.
switching to realtime file read might work for a very small instance but not for everyone else.
