### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [Rello/audioplayer#376]
Hi, I'm a logo designer, I saw your project and I can make a free logo for your project. So, what do you think?

**Comment by Rello** [comment]
Hey,
interesting. what do you think about? what kind of logo?
for the github? because the app itself does not have a logo.
let me know - sounds interesting

**Comment by tebriz159** [comment]
Hi again. You can use it for both, I've made design for you project. If you like the design, I'll send you all the files for using it.
![ap2](https://user-images.githubusercontent.com/31902754/51935834-a8d68b80-23bb-11e9-9977-09d49f723dd7.png)
I don't know which color you want, because of that I've made a few color variations of the logo. Which color do you prefer?
![ap pr](https://user-images.githubusercontent.com/31902754/51935922-e5a28280-23bb-11e9-91a7-00cb5d5dbe08.png)

**Comment by Rello** [comment]
hello @tebriz159 
can you get in contact with me via audioplayer-at-scherello.de ?

**Comment by jospoortvliet** [comment]
I like it ;-) @Rello what do you think?

**Comment by Rello** [comment]
@jospoortvliet which one? :-)
