### ISSUE TITLE
Albums below the selected one are relocated

### ISSUE THREAD

**Issue by Moerfi666** [Rello/audioplayer#377]
### Expected behavior
The albums should stay in place.

### Actual behavior
If the last album of a row is selected and the song container is displayed, the first album in the next row is relocated below the currently selected one.

### Steps to reproduce the behavior
1. Go to the album view
2. Select the last album in a row
3. See the albums of the rows below relocating

This occurs with **Nextcloud 15.0.2** and the **current master** branch of Audio Player (12bafc356deac1f0dc3a58553ea728056c9e557a)

**Comment by Rello** [comment]
Hello @Moerfi666 
sorry for the delay and thank you for the report.
is fixed with next v.2.6.2

**Comment by Rello** [comment]
2.7.0 released
