### ISSUE TITLE
.noaudio files are ignored

### ISSUE THREAD

**Issue by UDZGuru** [Rello/audioplayer#378]
### Expected behavior
When scanning for an audio library according to the documentation folders containing a .noaudio file are ignored and not added to the library

### Actual behavior
Folders containing a .noaudio file are scanned and added to the library.

### Steps to reproduce the behavior
1. Have your music on a CIFS/SMB share in a folder structure. Add .noaudio files to several folders to prevent them being added to the library.
2. Reset your library and let Audio Player scan the library
3. Find all the files from the .noaudio folders in your library again.

### Server configuration
**Operating system:**
Ubuntu 18.10
Kernel 4.18.0-13-generic

**Web server:**
Apache 2.4.34

**Database:**
MariaDB 10.1.34

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 15.0.2

**Audio Player version:** (see `/settings/apps`)
2.6.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
SMB

### Client configuration
**Operating system:**
Ubuntu 18.10

**Browser:**
Chromium 72.0

**Comment by Rello** [comment]
thank you. I will check and let you know

**Comment by Rello** [comment]
hello,
this seems to be a SMB related bug in Nextcloud.
.noaudio on normal folders works. when creating on smb shares, they are created on the file level. But as they are not shown in NC, they are not indexed in the filecache and so AP can not use them

https://github.com/nextcloud/server/issues/9663

**Comment by mmatous** [comment]
https://github.com/nextcloud/server/issues/9663#issuecomment-505958689 describes a solution.
