### ISSUE TITLE
Playing file from shared folder take down server

### ISSUE THREAD

**Issue by NilsGriebner** [Rello/audioplayer#379]
### Expected behavior
Hear music and enjoy happy user :)

### Actual behavior
Playing files from shared folders produces heavy load on server and takes it down.

### Steps to reproduce the behavior
1. Install AudioPlayer app
2. Upload .mp3 file to shared folder
3. Start playing the file
4. Monitor your server CPU/Ram

### Possible solution (optional)
Not found so far ...

### Server configuration
**Operating system:**
Debian 9

**Web server:**
nextcloud:14.0.4-apache Docker-Image

**Database:**
Postgres 9.6.8

**Nextcloud/ownCloud version:** (see `/status.php`)
14.0.4

**Audio Player version:** (see `/settings/apps`)
2.6.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
local

### Client configuration
**Operating system:**
Linux/Android/IOS

**Browser:**
Firefox/The one IOS uses (dont know the name)

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Error: Call to undefined method OCP\Share::resolveReShare()

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\audioplayer\Controller\MusicController->getPublicAudioStream("<removed>", "<filename>.mp3")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\audiopla ... {}, "getPublicAudioStream")

    /var/www/html/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audiopla ... {}, "getPublicAudioStream")

    /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\audiop ... r", "getPublicAudioStream", OC\AppFramew ... {}, { _route: "a ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "a ... "})

    /var/www/html/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "a ... "})

    /var/www/html/lib/base.php - line 987:

    OC\Route\Router->match("/apps/audio ... m")

    /var/www/html/index.php - line 42:

    OC::handleRequest()

```
</details>

**Comment by Rello** [comment]
Hello,
Can you please update the Audio Player to the latest version?
The mentioned Class in the log was removed in NC and AP was adjusted accordingly

Let me know...

**Comment by Rello** [comment]
You say you are on 2.6 already. But this code is not there anymore. 
https://github.com/Rello/audioplayer/commit/e36a004f8f56a949ba4f90529cb7c9f9e0a626c7#diff-875ebc65b7a8e8b917c8ffaa80ed6fad

Can you remove and reinstall AP? Something seems odd

**Comment by NilsGriebner** [comment]
Thanks for your quick response. Errors went away after reinstall. Player is working fine
now :)
Load is still high, but maybe it's related to shared folders.

**Comment by Rello** [comment]
Hello,
What happens when you play the same file inside normal AP - not on share screen?

Same load?

**Comment by NilsGriebner** [comment]
Hi, playing the file inside normal AP without sharing seems OK. Load stays normal.
