### ISSUE TITLE
9.1 support

### ISSUE THREAD

**Issue by bitking** [Rello/audioplayer#38]
Hi there,

Can you make this work for owncloud 9.1?

Thanks.

**Comment by Rello** [comment]
hello,
I still need my 9.1 testserver finished.
can you help me for the moment with some information on what is not working?
any errors in the frontend?
any errors in owncloud.log?

**Comment by bitking** [comment]
It seems like its working fine, my assumption was it wouldnt.

I am gonna test some more, i like the UI btw.

Ill come back to this in some time.

**Comment by Rello** [comment]
Hello,
no issues known

**Comment by ghost** [comment]
Works with ownCloud 9.1.0.
