### ISSUE TITLE
Artist search not working correctly

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#380]
when the search result is showing artists, "artist" and "album artist" are mixed. when clicking the result, AP is not jumping to the correct category

https://help.nextcloud.com/t/audioplayer-search-does-not-add-album-artist/46119

This fix also introduces the AP-icon in front of search results

![screen shot 2019-02-12 at 22 17 21](https://user-images.githubusercontent.com/13385119/52668501-04545d80-2f14-11e9-9857-e45e668af53d.png)

**Comment by Rello** [comment]
2.6.1 released

**Comment by Micdu70** [comment]
I updated to 2.6.1 and I don't see the "AP-icon" in front of search results...

**Comment by Rello** [comment]
did you clear the browser cache?
could you send me how the web inspector looks for your result rows?

**Comment by Micdu70** [comment]
yes browser cache cleared or other browser. (Chrome/Firefox)
http://puu.sh/CYvrx/1fc14ece48.png

EDIT: I use the search function when I'm already in "Audio Player" tab, that's why... But the icon is displayed when using search function in "Files" tab. ;)

**Comment by Rello** [comment]
ah, ok. correct.
the icon thing is a stock-NC-File-App-Feature
