### ISSUE TITLE
Adding french to translations

### ISSUE THREAD

**Issue by ewidance** [Rello/audioplayer#383]
French was not integrated in Audio Player. The attached file integrates a working french translation. Instructions : Unzip and copy files as is to l10n directory.

[fr.zip](https://github.com/Rello/audioplayer/files/2918170/fr.zip)

**Comment by r4sas** [comment]
Hello, @ewidance!
Can you open pull request with your translation? Thanks!

**Comment by Rello** [comment]
I will do it later
thank you for adding another language

**Comment by Rello** [comment]
Thank you @ewidance !
will do some testing and try to push 2.6.1 this weekend

**Comment by ewidance** [comment]
Thanks! Hope you'll push 2.6.1 quickly :)...

**Comment by Rello** [comment]
2.6.1 released

**Comment by ewidance** [comment]
Thanks a lot!
