### ISSUE TITLE
Database user_id format issue

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#384]
Hello there,
Scan always stuck on same file, here is the error log line:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_audioplayer_tracks` (`user_id`,`title`,`number`,`artist_id`,`album_id`,`length`,`file_id`,`bitrate`,`mimetype`,`genre_id`,`year`,`folder_id`,`disc`,`composer`,`subtitle`,`isrc`,`copyright`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' with params ["username", "\x41\x6d\x6f\x75\x72\x65\x75\x78\x20\x44\x65\x73\x20\x52\xea\x76\x65\x73", 1, 556, 642, "3:47", 9047, 1038688, "audio\/flac", 84, 2018, 2189, 1, "", "", "", ""]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xEAves' for column `username`.`oc_audioplayer_tracks`.`title` at row 1
--
```
Anyway, thanks for this nice app! 👍

_Originally posted by @Micdu70 in https://github.com/Rello/audioplayer/issues/362#issuecomment-470620263_

**Comment by Rello** [comment]
Hello @Micdu70 
I will have a look. this looks strange

thank you for reporting

**Comment by Micdu70** [comment]
The problem was a bad 'title' tag encoding => "Amoureux des R�ves" (should be "Amoureux des Rêves", displayed on Windows)
Using mp3tag software, displayed "Amoureux des R" so I edited this tag and it's okay now.

**Comment by Rello** [comment]
ok. thank you
