### ISSUE TITLE
Scan freeze and PHP error "fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/audioplayer/3rdparty/getid3/getid3.php#1996"

### ISSUE THREAD

**Issue by Micdu70** [Rello/audioplayer#385]
Got multiple lines of this following line in nextcloud.log file:

`fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/audioplayer/3rdparty/getid3/getid3.php#1996`

Happening during scan (and freeze at 96% but don't think it's related; all files have been scanned anyway...).

### Server configuration
**Operating system:**
Debian 9

**Web server:**
Nginx 1.15.9

**Database:**
MariaDB 10.3

**Nextcloud/ownCloud version:** (see `/status.php`)
15.0.5.3

**Audio Player version:** (see `/settings/apps`)
2.6.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

**Comment by Rello** [comment]
hmmm
hard to tell.
any more info with the log? in indicates that there was some issue with the fileaccess or the file itself.
normally this occurs when using SMB or any other external storage

**Comment by Rello** [comment]
any more input?

**Comment by Micdu70** [comment]
Nope nothing... :(

**Comment by Rello** [comment]
Hey,
but did the scan actually finish?
or is it showing a "new audio files exist" message at startup and it finds some files again after a second scan?

**Comment by Micdu70** [comment]
I re-scanned all my library and scan was stuck at 96% (6685 / 6899).
Refreshed the nextcloud page and started a new scan, it returned 0 audio file found.
In the end, AudioPlayer library has 6691 titles/files... (so 208 files missing?)
And the following error written in nextcloud.log (102 times):
`{"reqId":"MktChwotJHZyvu5rN026","level":3,"time":"2019-04-02T21:18:19+02:00","remoteAddr":"x.x.x.x","user":"y","app":"PHP","method":"POST","url":"\/apps\/audioplayer\/scanforaudiofiles","message":"fread(): Length parameter must be greater than 0 at \/var\/www\/nextcloud\/apps\/audioplayer\/3rdparty\/getid3\/getid3.php#1996","userAgent":"Mozilla\/5.0 (Windows)","version":"15.0.5.3"}`

**Comment by Rello** [comment]
here is the problem: the ID3 can not read/open some of your files. thats one part.
and the other part is, where does the difference come from!?

do you have the chance try do a scan with `occ audioplayer:scan [< user_id >] -v`
without resetting. would be interesting if the numbers are correct there

**Comment by Micdu70** [comment]
`occ audioplayer:scan [< user_id >] -v`

> Start scan for y
> Start processing of audio files
> Scanned Folder: /y/files
> Total audio files: 6691
> Checking audio files to be skipped
> Final audio files to be processed: 0
> Total stream files: 208
> Checking stream files to be skipped
> Final stream files to be processed: 0
> Start processing of audio files
> Start processing of stream files
> Audios found: 0
> Duplicates found: 0
> Written to library: 0
> Albums found: 0
> Errors: 0

Seems okay. ^^

EDIT: stream files are playlist files I think?

**Comment by Rello** [comment]
ok! so the numbers are correct!

the 208 are playlists (either local playlists or streams). they are in the separate category in the dropdown and not shown at the tile-count. happy for this at least :-)

for the initial issue: `$part = fread($this->getid3->fp, $bytes);`
it seems that ID3 is not able to get the requested byte sizes. as it has several occurrences in the external code, I don´t know where it got triggered.
As all files are scanned I have to assume that this is some "try if it is available" testing without a proper catch of the error

I think we have to leave it there for now

**Comment by Rello** [comment]
I am closing for now. if you find any information that might give further hints, let me know...
