### ISSUE TITLE
iconv error for cyrillic symbols

### ISSUE THREAD

**Issue by r4sas** [Rello/audioplayer#386]
Scaning tracks with cyrillic symbols in tags excepting PHP error:

```
[PHP] Error: iconv(): Detected an illegal character in input string at /apps/audioplayer/lib/Controller/ScannerController.php#572

POST /apps/audioplayer/scanforaudiofiles
from X.X.X.X by r4sas at 2019-03-10T21:49:25+00:00
```

### Expected behavior
Scan must proceed without errors.

### Actual behavior
PHP returns error for each track with cyrillic symbols

### Steps to reproduce the behavior
1. Upload track with cyrillic symbols in tags
2. Start library scan in audioplayer

### Possible solution (optional)
```diff
- if (preg_match('#[\\xA8\\B8\\x80-\\xFF]{4,}#', iconv('UTF-8', 'ISO-8859-1', $ThisFileInfo['tags'][$ttype][$tkey][0]))) {
+ if (preg_match('#[\\xA8\\B8\\x80-\\xFF]{4,}#', iconv('UTF-8', 'ISO-8859-1//TRANSLIT', $ThisFileInfo['tags'][$ttype][$tkey][0]))) {
```

**Comment by Rello** [comment]
hello,
did not have any issues here for long.

"If you append the string //TRANSLIT to out_charset transliteration is activated. This means that when a character can't be represented in the target charset, it can be approximated through one or several similarly looking characters"
seems to catch the errors - but I don´t know how the database will behave then.

could you send me a testfile with this issue?

**Comment by r4sas** [comment]
Sent track to mail.

**Comment by Rello** [comment]
Hello,
thank you for the suggestion. I had to replace it in 2 places and the error logs are also gone on my side

**Comment by Rello** [comment]
2.7.0 released
