### ISSUE TITLE
open_basedir restriction in effect: ScannerController.php#545

### ISSUE THREAD

**Issue by Sanookmakmak** [Rello/audioplayer#388]
NC 15.05, Audio Player 2.6.1, Ubuntu 18.04.2

![audio_player_error](https://user-images.githubusercontent.com/24833757/55242620-ea5da880-523d-11e9-9704-a64f80abca55.png)

I have definitively set up the path for open_basedir as you can see in the screenshot of the error message.

I have added an external Samba share to the NC account, in the root directory of the Samba server is a folder for mp3 files, and only here are the mp3 files which generate the error. During music scan with NC they are recognized as broken. Subfolders in there are working well. 

![samba](https://user-images.githubusercontent.com/24833757/55243426-86d47a80-523f-11e9-947a-0758afcc298b.png)

**Comment by Rello** [comment]
Hello,
i am not sure what to do here because this is a server config thing.
Can you access the files with the files-app and open them from there?

because AP is just using whatever you also can access in the files-app. its using the same filecache table.

can you check?

**Comment by Sanookmakmak** [comment]
> Can you access the files with the files-app and open them from there?

Yes. I can play them with the audio player, they are NOT broken.
But the audio player can't scan them.

![scan_for_audio_files](https://user-images.githubusercontent.com/24833757/55426443-1900b980-5585-11e9-856d-0600e39847d2.png)

**Comment by Rello** [comment]
it is somehow related to
   ```
             $fileName = $audio->getStorage()->getLocalFile($audio->getInternalPath());
                $ThisFileInfo = $getID3->analyze($fileName);
                if (!$audio->getStorage()->isLocal($audio->getInternalPath())) {
                    unlink($fileName);
                }
```
This area creates a local temp file of your audio during scanner to read the data. afterwards, this file is then removed again.
The location should be in the temp-folder as defined by your php-settings. it seems that php is not happy with something NC does there

But why it has an issue with one file - and not with others? no clue. sorry

**Comment by Sanookmakmak** [comment]
> But why it has an issue with one file

It happens with **every** file in the root directory of that folder.

![player1](https://user-images.githubusercontent.com/24833757/55662446-7316ae80-5813-11e9-9205-664bc29094a2.png)

![player2](https://user-images.githubusercontent.com/24833757/55662455-888bd880-5813-11e9-93ba-dfdb7c09899e.png)

What logfile can i look else to debug?

**Comment by Rello** [comment]
Hello
can you check your php.ini setting for this value?

```
; Directory where the temporary files should be placed.
; Defaults to the system default (see sys_get_temp_dir)
;sys_temp_dir = "/tmp"
```

second, did you add/change anything in nextcloud/config.php regarding to
`'tempdirectory' => '....',`

because what happens is, that for external files, a local temporary copy will be created. in your case, php does not allow this. some config issues somewhere

**Comment by Sanookmakmak** [comment]
Hello Rello,

after adding

`'tempdirectory' => '/tmp',`

to  nextcloud/config.php it is working.

Thank you!

**Comment by Rello** [comment]
Hello,

nice to hear that you got your setup sorted out.
enjoy the audio player...
