### ISSUE TITLE
Albuns are hidden behind the songs of the select album

### ISSUE THREAD

**Issue by riparise** [Rello/audioplayer#391]
First of all, thank you for your amazing app, I use it a lot!

This is not a bug, it is a design request. I believe that the display of the songs on the album view could be improved: when I click on an album, the albuns below get blocked by the expanded album. I think it would be better to move the albuns to make room for the the selected album to expand.

### Expected behavior
When I click on an album, the albuns below the selected one should move to make room for the songs to be displayed. (See picture 3)

### Actual behavior
When I click on an album, a pop up windows appears and it blocks the view of the albuns below. (See pictures 1 and 2).

### Steps to reproduce the behavior
1. Open the albuns view of the Audio Player
2. Click on any album

Picture 1 - Album view
![1](https://user-images.githubusercontent.com/33234089/56189543-818d7300-6028-11e9-9a7c-1308485446eb.PNG)

Picture 2 - Some albuns get hidden behind the songs of the selected album
![2](https://user-images.githubusercontent.com/33234089/56189544-818d7300-6028-11e9-87f8-c93226af23a9.PNG)

Picture 3 - Possible solution, no albuns are hidden
![3](https://user-images.githubusercontent.com/33234089/56189545-82260980-6028-11e9-9634-ba774cf60b4b.jpg)

Another minor suggestion would be to remove the (x) button to close the album, since you can simply click on the album again to close it

**Comment by riparise** [comment]
Another minor suggestion would be to remove the (X) button to close the album view, since you can already click on the album again to close it.

**Comment by Rello** [comment]
Hello,
thank you for your input.
let me check the history. the feature was available, but there was some technical reason, why I had to remove it. Some compatibility if I remember correctly.

I will come back to you...

btw: nice to see that someone is actually using the dark design mode :-)

**Comment by Rello** [comment]
Hello,

X-Button is removed.

The reason for removing this slide-down of all albums was the complex calculation.
Now, all covers are presented in 1 long row and the browser das a.) the line-brakes automatically and b.) the priorization (load visible content first).

Before, every line-width and the number of displayed covers was recalculated after **every** window move/resize or Navigation-/Side-bar show/hide. For big libraries with several 100 albums, this was a pain. Now the browser does it automatically.

So it is a matter of UI performance, that this feature is not available anymore.

thank you for getting in contact...
