### ISSUE TITLE
Scanner issue with Music app active

### ISSUE THREAD

**Issue by JosefAschauer** [Rello/audioplayer#394]
### Expected behavior
scans files

### Actual behavior
occ scan error:  Error with getID3. Does not seem to be a valid audio file

it does this for all of my files. nothing is being added to the DB but I can play each of my audio files from the nextcloud web interface or client -> smb share works just fine

### Steps to reproduce the behavior
1. sudo -u www-data php occ audioplayer:scan jo -vv
.  

### Additional information (optional)

php7.3

### Server configuration
**Operating system:**
ubuntu 18.04

**Web server:**
Apache/2.4.39 

**Database:**
mysql 5

**Nextcloud/ownCloud version:** (see `/status.php`)
15.07

**Audio Player version:** (see `/settings/apps`)
2.7.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
smb

### Client configuration
**Operating system:**
MAC, Windows 10, Android

**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>
{"reqId":"F5YFeHtpWnGA6BWjhD8T","level":0,"time":"2019-05-11T14:24:08+00:00","remoteAddr":"","user":"--","app":"audioplayer","method":                   "","url":"--","message":"Error with getID3. Does not seem to be a valid audio file: \/jo\/files\/sound\/Bluus2\/26.-.leonard.cohen.-.t                   he.future.mp3","userAgent":"--","version":"15.0.7.0"}

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by r4sas** [comment]
Can you attach compressed (in zip) audiofile?

**Comment by JosefAschauer** [comment]
[01 - Titel und Motto.zip](https://github.com/Rello/audioplayer/files/3169828/01.-.Titel.und.Motto.zip)

**Comment by JosefAschauer** [comment]
I've just tested with local storage and its the same:
   /jo/files/music/<sample_used>.mp3
       Error with getID3. Does not seem to be a valid audio file

I've updated the codepage used in nextcloud to utf8mb4, cant tell for sure whether this was working with utf8 before

currently, no title can be scaned, this error is thrown regardless which file and if external smb or local storage

**Comment by JosefAschauer** [comment]
Hi, I'll close this. The problem was that I had still enabled the music app...

**Comment by Rello** [comment]
Hello,
I will look at the cause because this should not happen.
Both apps were modified some time ago to avoid exactly this...

**Comment by Rello** [comment]
issue could not be replicated locally...
