### ISSUE TITLE
Any chance to support squeezebox?

### ISSUE THREAD

**Issue by mr-gosh** [Rello/audioplayer#396]
### Steps to reproduce the behavior
1. 
2. 
3. 

### Server configuration
**Operating system:**

**Web server:**

**Database:**

**Nextcloud/ownCloud version:** (see `/status.php`)

**Audio Player version:** (see `/settings/apps`)

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

### Client configuration
**Operating system:**

**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by r4sas** [comment]
Can you provide more info about that service/device/etc. ?

**Comment by mr-gosh** [comment]
Yes of course - will update thebissue - seems that not my whole text got posted...

**Comment by mr-gosh** [comment]
duplicate of #397
