### ISSUE TITLE
Sonos getting bad - Squeeze an alternative?

### ISSUE THREAD

**Issue by mr-gosh** [Rello/audioplayer#397]
### Expected behavior

As Sonos is getting more and more [problematic](https://www.heise.de/newsticker/meldung/Sonos-fordert-mehr-Daten-sonst-droht-Sendeschluss-3810249.html) an alternative would be helpfull.
Squeezebox or MPD Support instead if the closed Source Sonos Stuff.

### Actual behavior

Only Proprietary Sonos Player are supported.

### Possible solution (optional)

The Sonos Player Support could be modulized, so more player platforms could be added as the open source MPD services, the open source multi room sync server squeezeserver or simple pnp support?

### Additional information (optional)
https://github.com/Logitech/slimserver
https://github.com/MusicPlayerDaemon/MPD

**Comment by Rello** [comment]
Hello,
I am happy to assist any developer who wants to develop a separate app thats depends on the AP-tables to reuse the indexed ID3 data.

As I am not using any of these players (besides the SONOS module) I have no need for this.
As this is a free-time project, I don´t have any capacities for this.

thank you
