### ISSUE TITLE
Integrate Audio Player with Viewer

### ISSUE THREAD

**Issue by jtagcat** [Rello/audioplayer#398]
Hey, [Viewer](https://github.com/nextcloud/viewer) is efforts in making previews universal and solving the problem of having tens of preview apps being available (while having similar functions, inconsistent UI). Would be much appreciated if you'd take a look at [this](
https://github.com/nextcloud/viewer/issues/126).

**Comment by Rello** [comment]
Hello,
as discussed in the NC thread:

- NC is thinking about a generic player within the files viewer
- Music & Audio Player exist on top as proper library apps with additional features
