### ISSUE TITLE
/setfavorite request flood

### ISSUE THREAD

**Issue by mmatous** [Rello/audioplayer#399]
Clicking star icon in the sidebar works about half the time. The reason for this is a request flood dependent on certain conditions.

### Expected behavior
Only one favorite request /setfavorite GET request gets sent and a song is (un)favorited appropriately.

### Actual behavior
Multiple /setfavorite GET requests get sent dependent on how many options were selected beforehand and the result is (un)favoriting a song or nop dependent whether this number is odd or even. Refreshing the tab resets this counter.

### Steps to reproduce the behavior
1. Select options of a song (three dots)
2. Select options of a different song
3. Click a star in sidebar

### Possible solution (optional)
I will have fix ready (hopefully) soon.

### Server configuration
**Operating system:**
Arch Linux

**Web server:**
NGinx 1.17.0

**Database:**
MariaDB 10.3.15

**Nextcloud/ownCloud version:** (see `/status.php`)
16.0.1

**Audio Player version:** (see `/settings/apps`)
2.7.0, tried even master

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Operating system:**
Arch Linux

**Browser:**
Firefox Nightly 69 and Brave 0.65.118

#### Nextcloud/ownCloud log
Irrelevant

**Comment by Rello** [comment]
thank you for the finding.
its merged already
https://github.com/rello/audioplayer/pull/400
