### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by marcelklehr** [Rello/audioplayer#402]
Hey @Rello 
I don't seem to be able to catch you on IRC, so I'm responding to your question here :)

It is possible to add custom hooks like you described. The bookmarks app uses them for example to [expose CRUD events].(https://github.com/nextcloud/bookmarks/blob/master/lib/Bookmarks.php#L681)

**Comment by Rello** [comment]
thank you @marcelklehr

**Comment by Rello** [comment]
Hello @marcelklehr 

Is this way of defining namespace/object/functions the "correct" one?
what is the difference/do/don´t if I would not go for an object but for a class?
https://github.com/Rello/audioplayer/blob/master/js/sidebar.js#L27

my issue is, that I have to use the long function calls here because `this` or `_self `does not seem to work.
would a class solve this?
https://github.com/Rello/audioplayer/blob/master/js/sidebar.js#L36

thank you for your support

**Comment by marcelklehr** [comment]
> 20:31 <Rello>  https://docs.nextcloud.com/server/15/developer_manual/general/codingguidelines.html?highlight=app%20php
20:32 <Rello>  the "DONT" section is describing what I am doing - or not?

Generally, this is good advice, I think. Keeping your imperative code wrapped in a top-level closure is usually a good idea, because it prevents you from unintentionally leaking variables. This only applies if you don't use a module system, though, which might be worth the hassle depending on how complex your app is. (js development nowadays favors module bundlers that assemble multiple files into one large bundle that is wrapped in a closure. If you then want to expose a variable globally, you'll need to assign it to `window`).
In the specific case of your Sidebar object you actually do want to expose that globally, so as long as you make sure to not leak anything else, I'd wager your approach is fine. Having your whole app in the global namespace is probably not a good idea, though. It's usually best to only expose those parts that are intended for public consumption. (Like nextcloud core does on the server with the OCP namespace for example).
As to whether to use a module bundler: Usually with nextcloud apps you have a certain amount of functionality, which warrants using a module bundler, IMO. The downside of this is increased complexity for you to grasp. The upside, however, is cleaner code and newer js features that make coding much more fun.

**Comment by marcelklehr** [comment]
Yay, I saw you've published the addons. Great work! :)
