### ISSUE TITLE
Create lint configuration

### ISSUE THREAD

**Issue by mmatous** [Rello/audioplayer#405]
Just like #404 lints would serve to make code clearer with less bugs. In addition configuration centralized in repo would give clear guidelines to potential contributors.
I could share .eslintrc.js configuration I've been using with AP privately as a base.
Once this configuration is agreed upon, merged and majority of lints cleared, it would be nice to [include it in your CI](https://scrutinizer-ci.com/docs/tools/javascript/eslint/).

**Comment by Rello** [comment]
https://github.com/Rello/audioplayer/pull/406

**Comment by Rello** [comment]
thank you for this.
I am using phpStorm and I will try it.

**Comment by mmatous** [comment]
I use IntelliJ-based IDEs for C++ or Rust, so in case it does not deal with JS or eslint well, VS Code works nicely with those. I also tried Atom, but it was too heavy-weight for my taste.
