### ISSUE TITLE
Nextcloud16版本还是不可用

### ISSUE THREAD

**Issue by CF673** [Rello/audioplayer#407]
我的报错问题截图
![QQ截图20190628022538](https://user-images.githubusercontent.com/49812153/60290854-3bb82980-994c-11e9-9ac3-f20108145897.jpg)
![Uploading QQ截图20190628022549.jpg…]()

**Comment by CF673** [comment]
也许是我 环境的问题

**Comment by r4sas** [comment]
That is not AP error, it attached to "Folder Player".

**Comment by Rello** [comment]
for your Information: "Folder Play" is only compatible to NC 14
It does not have anything to do with Audio Player

**Comment by CF673** [comment]
我重新安装一遍 居然可以了 
现在完美
目前就找个方式 把数据迁移过去
