### ISSUE TITLE
NC 16.0.2 appearance wrong / CSS not loading correctly

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#410]
After upgrading from NC 16.0.1 to 16.0.2 the appearance of the audio player app looks crippled. Probably because of some internal changes of NC.

![image](https://user-images.githubusercontent.com/15927695/60741419-97486f80-9f69-11e9-8c37-09923a38d444.png)

**Comment by Rello** [comment]
Hey,
which browser? any issues in the inspector?
I tested without any findings in Chrome & Safari

**Comment by AmonBune** [comment]
> 
> 
> Hey,
> which browser? any issues in the inspector?
> I tested without any findings in Chrome & Safari

I just found out that my cache was the problem. Closing.
