### ISSUE TITLE
In Nextcloud 16.0.1 tracks sort inappropriately for multi CD collections.

### ISSUE THREAD

**Issue by WNYmathGuy** [Rello/audioplayer#412]
### Expected behavior
Individual sound files within a named artists folder and collections subfolder should be in the order that they would play if the CD-ROM's were played in disc number order.

### Actual behavior
The first track of each CD-ROM plays first in the order of the disc number, then the second track of each CD-ROM plays in the order of disc number and so on.

### Steps to reproduce the behavior
1. Use the Sound Juicer program to duplicate a multi disc collection to a fixed-drive in a Linux Workstation system.
2. Transfer the files to Nextcloud.
3. Have Audio Player find new sound files.
4. Try playing the new collection with the Audio Player app in Nextcloud.

### Possible solution (optional)
Look for other metadata in the file for the primary and secondary sorting of tracks.

### Additional information (optional)
When the standard Nextcloud android app is used to put a local copy of the same files onto the mobile device, the standard Google Play Music app will play them in the correct order. 

Also the CloudBeats app for Android works correctly with the same set of files but they don't need to be downloaded locally.

### Server configuration
_Apparently, the new Nextcloud way isn't to produce a copy/paste report, but instead to produce a link to the actively generated report. This might be better._
Link: [https://cloud.ruppssites.com/index.php/s/G79yjqtWgjzEaXc](https://cloud.ruppssites.com/index.php/s/G79yjqtWgjzEaXc)
Password: ...removed...(Rello) 
**This is good for 2 weeks from the date of this posting.**

**Comment by Rello** [comment]
hello,
sorry for the late reply.

which view are you talking about? Albums (graphical) or the list view?

because both views actually take the disc-track numbering into account when sorting
![Screenshot 2019-07-18 at 21 04 41](https://user-images.githubusercontent.com/13385119/61484805-f1045d00-a99f-11e9-9693-86ec84e2aa1c.png)

![Screenshot 2019-07-18 at 21 06 06](https://user-images.githubusercontent.com/13385119/61484814-f497e400-a99f-11e9-8744-92c424af5b4f.png)

**Comment by WNYmathGuy** [comment]
@Rello 
Okay, so you fixed it? When I was writing the initial post it was still working wrong. Here are some screenshots of things now to prove it's working correctly. Note that the third screenshot is of a mobile app that still does it wrong.




### Nextcloud Android App

![Screenshot_20190718-154554](https://user-images.githubusercontent.com/28640985/61487509-15e2db00-a974-11e9-8f81-f537575efd99.png)

### Audio Player app in Nextcloud web interface

![Screenshot from 2019-07-18 15-46-38](https://user-images.githubusercontent.com/28640985/61487523-21360680-a974-11e9-89b5-7a1712078482.png)




### Cloudbeats Android app

![Screenshot_20190718-154302](https://user-images.githubusercontent.com/28640985/61487605-517da500-a974-11e9-80c6-a7ef129de1ce.png)

**Comment by Rello** [comment]
hey,
actually I did not fix anything - yet.
the new version 2.8.0 is still not rolled out so you should still be on 2.7.2 since quite some time.
but ok, when its working now :-)
