### ISSUE TITLE
Audio Player not working on Desktop or mobile on Chrome Firefox or Safari - July 2019

### ISSUE THREAD

**Issue by sambenito** [Rello/audioplayer#414]
### Expected behavior
play the mp3

### Actual behavior
a message of "Loading" is the only thing that happens

### Steps to reproduce the behavior
1. upload an mp3
2. try to play
3. 

### Server configuration
**Operating system:**
mac high sierra

**Web server:**
Apache, CentOS

**Database:**
Sql Lite

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud 16.0.3

**Audio Player version:** (see `/settings/apps`)
2.7.2

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
online http

### Client configuration
**Operating system:**
mac high sierra
iphone ios 12.3

**Browser:**
chrome, firefox, safari

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
there needs to be some log indicating a local setup issue.
please provide more info

**Comment by sambenito** [comment]
Server configuration detail

Operating system: Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64

Webserver: Apache (fpm-fcgi)

Database: sqlite3 3.20.1

PHP version: 7.2.19

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, exif, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, imagick, mcrypt, ionCube Loader, Zend OPcache

Nextcloud version: 16.0.3 - 16.0.3.0

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - audioplayer: 2.7.2
 - bookmarks: 1.0.6
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - cospend: 0.1.0
 - dashboard: 6.0.0
 - dav: 1.9.2
 - dicomviewer: 1.2.0
 - drawio: 0.9.3
 - external: 3.3.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_ebookreader: 0.0.1
 - files_external: 1.7.0
 - files_external_gdrive: 0.4.0
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_photospheres: 1.0.3
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - onlyoffice: 2.4.0
 - ownbackup: 19.5.0
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - radio: 0.6.5
 - rainloop: 6.0.2
 - recommendations: 0.4.0
 - richdocuments: 3.3.13
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - smb_test: 0.2.2
 - socialsharing_email: 1.0.5
 - spreed: 6.0.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - weather: 1.6.1
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "drup.com.ar"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "16.0.3.0",
    "overwrite.cli.url": "http:\/\/drup.com.ar\/disco",
    "installed": true
}


</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by sambenito** [comment]
Server configuration detail

Operating system: Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64

Webserver: Apache (fpm-fcgi)

Database: sqlite3 3.20.1

PHP version: 7.2.19

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, exif, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, imagick, mcrypt, ionCube Loader, Zend OPcache

Nextcloud version: 16.0.3 - 16.0.3.0

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - audioplayer: 2.7.2
 - bookmarks: 1.0.6
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - cospend: 0.1.0
 - dashboard: 6.0.0
 - dav: 1.9.2
 - dicomviewer: 1.2.0
 - drawio: 0.9.3
 - external: 3.3.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_ebookreader: 0.0.1
 - files_external: 1.7.0
 - files_external_gdrive: 0.4.0
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_photospheres: 1.0.3
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - onlyoffice: 2.4.0
 - ownbackup: 19.5.0
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - radio: 0.6.5
 - rainloop: 6.0.2
 - recommendations: 0.4.0
 - richdocuments: 3.3.13
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - smb_test: 0.2.2
 - socialsharing_email: 1.0.5
 - spreed: 6.0.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - weather: 1.6.1
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "drup.com.ar"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "16.0.3.0",
    "overwrite.cli.url": "http:\/\/drup.com.ar\/disco",
    "installed": true
}


</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by sambenito** [comment]
Error | index | Icewind\SMB\Exception\DependencyException: No valid backend available, ensure smbclient is in the path or php-smbclient is installed |   | 2019-07-19T15:09:41-0300
-- | -- | -- | -- | --
Error | PHP | exec() has been disabled for security reasons at /home/lab01/public_html/disco/apps/files_external/3rdparty/icewind/smb/src/System.php#60 |   | 2019-07-19T15:09:41-0300
Error | jsresourceloader | Could not find resource core/js/placeholder.js to load |   | 2019-07-19T14:29:31-0300

**Comment by mmatous** [comment]
According to [known issues](https://github.com/rello/audioplayer/wiki/installation-instructions#known-issues), the Music app may cause AP to misbehave. Try disabling it.
Is this a fresh setup that does not work or did it work before and stopped suddenly?

**Comment by Rello** [comment]
Hello,
do the files work in the normal files-app?
because it looks like an issue with your SMB mounts and the according php libraries

**Comment by Rello** [comment]
hello,
any more information here?
