### ISSUE TITLE
jQuery .tooltip usage

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#415]
@juliushaertl 
can you help me out on this question?
i am trying to get rid of several jQuery dependencies and use quicker vanilla JS for DOM operations. I read several post that you are also cleaning something up related to .tooltip but I am not sure what this means for me.

What would I need to do for these cases?
https://github.com/Rello/audioplayer/blob/master/js/app.js#L362
`$('.toolTip').tooltip('hide');`

is this still required or do I need to do it different in vanilla JS?

thank you for your help!

**Comment by juliusknorr** [comment]
The current server tooltips are either using the jQuery plugin from bootstrap or are using https://github.com/Akryum/v-tooltip if they are already migrated to vue. I fear that there is no easy way to get this done in plain javascript, so unless you are doing Vue js and can reuse the styled v-tooltip from https://github.com/nextcloud/nextcloud-vue you probably need to stick with the jQuery variant.

**Comment by Rello** [comment]
Ok thank you. 

Perhaps I am not even clear about the need for the mentioned lines. 
Do I really need it in my app if I am not doing anything anywhere else?
What is the purpose then?

**Comment by juliusknorr** [comment]
It makes sure that tooltips are properly rendered for elements that the `toolTip` class is assinged to, like https://github.com/Rello/audioplayer/blob/master/js/app.js#L1083

**Comment by Rello** [comment]
Got it. 
Thank you for your support
