### ISSUE TITLE
home screen simpler

### ISSUE THREAD

**Issue by microcreators** [Rello/audioplayer#42]
with dozens of albums scanned it takes time to load Audio Player 1st screen and render all covers. especially on RPi ;) it'd be great to have some kind of a welcome / home screen with less data presented. ideas:
- 10 random albums
- 10 recently added albums
- 10 recently played albums
- etc.
  thanks.

**Comment by ghost** [comment]
Many users will then ignore the "see all" button, imho.

The new version 1.1.0 will be remember the setting of the sidebar (visibility and new selection). This could be extended to the main screen. All albums then will be displayed at first start of the app only or after a rebuild of the music library. @Rello

**Comment by xraMsamohT** [comment]
From now on Audio Player remembers the last settings as described above. So there is no need for additional start screens at the moment.

Changes are possible.

**Comment by Rello** [comment]
Hello,
the new 1.2.0 was significantly changed in the underlaying code.
when you are now within a selected category, it will remember your choice and go directly into the same list after reopening the app - without rendering the albums.
this should increase performance a lot
