### ISSUE TITLE
Deduplicate CSS files

### ISSUE THREAD

**Issue by mmatous** [Rello/audioplayer#420]
The .css and .scss bar-ui and styles files are basically duplicates. Since NC 14 the .scss file has priority over the .css. NC 14 was last supported by AP 2.4.1 so the styles.css and bar-ui.css can be removed from the app entirely. 
OC might be a problem because docs don't mention SCSS at all and I don't have an instance set up, so I can't try. 
Could you confirm whether the .scss file can be used with OC?

**Comment by Rello** [comment]
Yes,
Its about OC

I have a testinstance and will retry...

**Comment by Rello** [comment]
yes, it looks like scss is only coming with Phoenix in OC.
But when Phoenix is out, AP will not work anymore due to the completely new approach on OC.
at that point of time we can ditch it.

**Comment by Rello** [comment]
closing for now
