### ISSUE TITLE
Audio Player locks up when playbacking long music files

### ISSUE THREAD

**Issue by AmonBune** [Rello/audioplayer#426]
I have issues with some music files that are longer than 7 minutes.

The music starts to play, everything is fine, and then all of a sudden (always at the same point in the seek bar for this song) the playback stops. No JS errors occur. If I move the cursor in the seek bar, nothing happens. A JS error appears at this time (AbortError: The operation was aborted). But this happens all the time, even when the seek is working so I think that's another story.

Weird is, after some time, like 1-3 minutes, the situation recovers and the music plays further.
On some files, there are multiple lockup "positions".

Also, if I move the cursor in the seek bar after this "kill point", playback stops for a short time (5 seconds or so) and plays fine after that. But if the player hits the point by playing through it, it locks up. Very weird.

![image](https://user-images.githubusercontent.com/15927695/63001491-0328cc80-be74-11e9-8871-6490fa08f22e.png)

**Comment by Rello** [comment]
thats strange. seems like either the webserver or the browser cancelled the connection or transfer.
I will try on my side...

**Comment by mmatous** [comment]
I think I know what you're talking about. I keep encountering the same, but it did not have high enough priority for me to debug thoroughly. No suspicious JS console entries or NC log entries as well. To be sure, could you try any Chromium-based browser, @AmonBune? This only happens in FF for me, Brave works OK.
I want to use FF so it's definitely bothering me.
Additional info:
- I think this has been always happening, but I'm reasonably sure about >2.6.0 and higher.
- I'm not sure about the >7 minute mark. Seems completely randomly to me. Longer files likely just have bigger surface for errors.
- Sometimes after fiddling with the seeker it moves towards the beginning and AP seemingly thinks the song should be way longer than reality.

**Comment by AmonBune** [comment]
@mmatous Chrome works fine, I tried it also in Edge, and there the effects are pretty funny. When using the seek bar, some "X" icon duplicates itself like 20 times and then the playback crashes and the next track starts to play. It also hangs up randomly during a long song.

And regarding the 7 minute duration, it sometimes also happens on shorter tracks. Perhaps the filesize is more relevant. Oh and I personally use FLAC files. Perhaps also a good starting point.

**Comment by r4sas** [comment]
@AmonBune can you share info about your webserver and it configuration?

**Comment by Rello** [comment]
Hey all,

I am hoping for your help here. somehow I don´t become friend with FF on macOS. running mad at 100% CPU

**Comment by mmatous** [comment]
I will take a proper look at it eventually with more logging and stepping through the code. Right now I have some fun facts gained by trial and error:
- Updating soundmanager2 to 2017 version does not help
- Updating soundmanager2 to html5only HEAD does not help
- killpoints are present in the same spot regardless of user
- killpoints are present in the same spot regardless of device
- setting `debug = true` in soundmanager reveals that the audio is buffering normally up to 100% which suggests JS error rather than server config error

**Comment by Rello** [comment]
hey,
any update on this?

**Comment by Rello** [comment]
Hello,
i dropped soundmanager and bar-ui.
the next version will be html5 only. I will put a note here and then ask you for retest

**Comment by Rello** [comment]
Version 2.11.0 was released
