### ISSUE TITLE
Audio Player NC17 compatibility: EmptyFeaturePolicy

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#428]
@rullzer can you help me on your change you applied here?
`Add Feature-Policy header #16613`
https://github.com/nextcloud/server/pull/16613

This part of Audio Player breaks with NC17 beta 1
https://github.com/Rello/audioplayer/blob/master/lib/Http/ImageResponse.php

Error:
`"Exception":"TypeError","Message":"Return value of OCP\\AppFramework\\Http\\Response::getFeaturePolicy() must be an instance of OCP\\AppFramework\\Http\\EmptyFeaturePolicy, null returned"`

can you help me on what to do here?

thank you for your support

**Comment by rullzer** [comment]
You should call the default constructor. But let me add some hardning int he server so this doesn't break so hard.

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/16788

**Comment by Rello** [comment]
Thank you @rullzer
How do I need to „call the default constructor“?
How do I need to do it?

**Comment by rullzer** [comment]
See my PR.
But with beta2 it will be no longer needed

**Comment by Rello** [comment]
ok, that simple. I am continuing NC17 testing

thank you!

**Comment by Rello** [comment]
@rullzer your fix is not NC16 compatible.
so i need to remove it and wait for NC17.b2.

do you know when it is planned or if there is a way to get it working for both NCs?
thank you

**Comment by rullzer** [comment]
Beta 2 will be released tomorrow :)

**Comment by Rello** [comment]
sounds like a plan
