### ISSUE TITLE
Genre selection not working correctly when switching to different genre

### ISSUE THREAD

**Issue by connium** [Rello/audioplayer#43]
I use Nextcloud 9.0.53 with Audioplayer 1.0.3. OS is Ubuntu with Firefox and Chromium.

**Steps to reproduce**
1. Select a genre from the left sidebar
2. Click on a title to start playback (e.g. 2nd track)
3. Pause playback
4. Select a different genre
5. Click on a title to start playback (e.g. 3rd track)

**Expected behaviour**

The 3rd track of the currently selected genre is played.

**Actual behaviour**

The 3rd track of the previously selected genre is played.

**Comment by Rello** [comment]
Hello,
this is fixed with the upcoming 1.1.0
we in the final testing and it should be released this week.

thank you!

**Comment by connium** [comment]
Sounds great! :+1: 

Thank you for your fast response.

**Comment by Rello** [comment]
Check the appstore ;-)
