### ISSUE TITLE
Cover display under NC17.0.0.beta1

### ISSUE THREAD

**Issue by Larsene** [Rello/audioplayer#430]
### Expected behavior
The display of the covers

### Actual behavior
white covers (not loaded)

### Steps to reproduce the behavior
1. install or update to nextcloud 17.0.0 beta1
2. launch audioplayer
3. even after library reset, same thing.

### Additional information (optional)
Except that, audioplayer works good.

### Server configuration
**Operating system:**
Nextcloud 17.0.0.1

**Web server:**
apache

**Database:**
mariaDB

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.0 beta1

**Comment by Rello** [comment]
Hello

Will be fixed with todays NC17 beta2
https://github.com/Rello/audioplayer/issues/428

**Comment by Rello** [comment]
confirmed working again in beta2

**Comment by Larsene** [comment]
totally right. sorry about that.

**Comment by Rello** [comment]
no problem at all.
thank you for supporting the pre-testing of either NC and also AP!
