### ISSUE TITLE
Remove Dashboard Widget into separate add-on

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#431]
- [x] remove code from AP
- [ ] create new app

**Comment by Spartachetto** [comment]
Did you see this: https://github.com/nextcloud/server/issues/20930 ?

**Comment by Rello** [comment]
nice idea!
thank you. I like it. have to see how we can integrate non-file-topics in there, because an inline player e.g. is something different than a list item. NC is very list focused at the moment

**Comment by Rello** [comment]
no priority at the moment
