### ISSUE TITLE
Reduction of metadata transfer size

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#433]
`/gettracks`
does not include the full file link anymore. 
`/getaudiostream` now just requires the track-id and the rest is parsed in the MusicController

Test of all dependencies ongoing. but normal usage of the list should be fine...

@mmatous 
@psy-q could you make a test and check the filesize being transferred of "all titles" in list-view mode; Before this fix - after this fix?

**Comment by psy-q** [comment]
Seems to work, with "all titles" in list mode we went from 9.45 to 5.05 MB for a bit over 40000 tracks :)  

The query became faster from 26s to around 23s as well, but that could also be because the database was warmed up on the second request.

**Comment by Rello** [comment]
>45% improvement :-)
