### ISSUE TITLE
Provide option to export music to m3u file (playlist file for streaming with Winamp or VLC)

### ISSUE THREAD

**Issue by Sanookmakmak** [Rello/audioplayer#434]
https://help.nextcloud.com/t/which-missing-apps-and-features-do-you-want-in-nextcloud/28200/92

**Comment by Rello** [comment]
Hello,

what exactly do you want to do?
if you have a local playlist already with referential paths, Audio Player can process them.
what do you want to achieve?

**Comment by Sanookmakmak** [comment]
Hello Rello,

I would like to share some mp3 files in public for streaming them with Winamp or VLC, for those which don't have (and don't want) an account of my Nextcloud instance.

**Comment by Rello** [comment]
you can always share single MP3 files and access them via webdav.
problem would be to share playlist (which would need to contain several webdav file links) because the user won´t have access to them.
when you share one m3u does not mean that the user has access to the 10 files within this m3u

do you know what I mean?

**Comment by thefantas** [comment]
Ideally, you should use the folder sharing module to generate a file with the url's of all the media with their respective token that is not cookie-based . (downloadStartSecret).
https://nube.nextc.loud/index.php/s/oNdeGzEaiNDBqJg/download?path=%2F&files=01%20its%20my%20life.mp3&downloadStartSecret=c6iieyrmf5n

And with that one manages to generate the m3u.

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
