### ISSUE TITLE
PostgreSQL compatibility issue

### ISSUE THREAD

**Issue by beowulf14** [Rello/audioplayer#437]
### Expected behavior
Audioplayer should show and play audio files;)

### Actual behavior
It just stalled with the symbol rotating, but does not load anything
When you try to click the play button it does not do anything.

![audioplayer](https://user-images.githubusercontent.com/54770057/64077065-9ebb9900-cccc-11e9-9914-90c402861f91.png)

### Server configuration
**Operating system:**
Debian buster 
Kernel 4.19.0-5-amd64

**Web server:**
nginx/1.14.2

**Database:**
postgresql 11

**Nextcloud/ownCloud version:** (see `/status.php`)
16.0.4.1

**Audio Player version:** (see `/settings/apps`)
2.8.1

### Client configuration
**Browser:**
Firefox 60.8.0esr (64-Bit)
Chromium Version 76.0.3809.100

#### Nextcloud log
The important part is probably:

`SQLSTATE[42601]: Syntax error: 7 ERROR:  zero-length delimited identifier at or near 
`
[audioplayer_log.txt](https://github.com/Rello/audioplayer/files/3563511/audioplayer_log.txt)

**Comment by beowulf14** [comment]
I just noticed that in you get a HTML 500 response, when it tries to open
https://NEXTCLOUD_DOMAIN/index.php/apps/audioplayer/gettracks?category=Title&categoryId=0

**Comment by Rello** [comment]
Hello,
thank you for reporting back. it seems related to some PostgeSQL treatment which does not apply in the other DBs

https://github.com/Rello/audioplayer/blob/master/lib/Controller/CategoryController.php#L290
`(CASE  WHEN `AB`.`cover` IS NOT NULL THEN `AB`.`id` ELSE "" END)`
the double quote at the end might be the issue.

@beowulf14 would you have any chance to edit this one line in your setup to '' and report back?
if not, I will try to start up a postres on one of my test instances...

**Comment by Rello** [comment]
the select has to be changed to

> (CASE WHEN AB.cover IS NOT NULL THEN AB.id ELSE **NULL** END)

but additionally postgres is complaining about additional issues in the cover display

> ...muss in der GROUP-BY-Klausel erscheinen oder in einer Aggregatfunktion verwendet werden

**Comment by Rello** [comment]
fix was released

thank you for reporting!

**Comment by beowulf14** [comment]
update to 2.8.3 solved the issue
thanks for fixing it so fast!
