### ISSUE TITLE
Play icon in Cover View not starting the correct track

### ISSUE THREAD

**Issue by Thomas301263** [Rello/audioplayer#438]
### Expected behavior
All is working like before

### Actual behavior
Only one title can be played.

### Steps to reproduce the behavior
1. Open Music Player start a title all is fine
2. Try to start another title and the first one will end up in a look so it doesn't take the new chosen one.
3. That happend after the upgrade today morning

### Server configuration
**Operating system:**
Ubuntu Kernel 4.15.08

**Web server:**
Firefox

**Database:**
Mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
16.04

**Audio Player version:** (see `/settings/apps`)
2.8.3

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
not for music player

### Client configuration
**Operating system:**
Ubuntu 18.04.3

**Browser:**
Firefox

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>
To see what is going on I deleted the logs and start all new.
After reproduction of error the log was empty so no errors.

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
Thank you for the finding. I could reproduce it already and will check. 

For the moment, please use the „opening“ list in the Cover View or the List view

**Comment by Rello** [comment]
when an album in cover view is switched, the playlist in the background (`OCA.Audioplayer.UI.ActivePlaylist`) is not being updated, as the following check fails
https://github.com/Rello/audioplayer/blob/master/js/app.js#L699

The ID is set by the category selection which remains the same in case of the cover view

_...work in progress..._

**Comment by Rello** [comment]
@Thomas301263 
fix released

thank you
