### ISSUE TITLE
Error reading ID3 tags on most songs. No files imported.

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#439]
### Actual behavior
Songs are not imported to the library when doing `occ audioplayer:scan -v`

### Steps to reproduce the behavior
1.   run `occ audioplayer:scan -v --all` from the shell
2.   occ spits out many rows with `Error with getID3. Does not seem to be a valid audio file`
3.  No files are added to the media library.

### Additional information (optional)

The files have valid ID3v1, ID3v2 and APE tags set by `mp3tag` 
Output from the command line shows them:
```
id3info  -w -n /media/music/Music/The\ Smiths/The\ Queen\ Is\ Dead/08\ -\ The\ Smiths\ -\ Vicar\ In\ A\ Tutu.mp3

*** Tag information for /media/music/Music/The Smiths/The Queen Is Dead/08 - The Smiths - Vicar In A Tutu.mp3
=== TIT2 (Title/songname/content description): Vicar In A Tutu
=== TPE1 (Lead performer(s)/Soloist(s)): The Smiths
=== TALB (Album/Movie/Show title): The Queen Is Dead
=== TYER (Year): 1986
=== TRCK (Track number/Position in set): 8
```
Also Winamp output:
![image](https://user-images.githubusercontent.com/1469150/64313008-7a044180-cfaa-11e9-90fc-b00fe9a5dda5.png)

### Server configuration
**Operating system:**
Gentoo Linux.
Kernel 5.2.8

**Web server:**
`apache-2.4.41`

**Database:**
`mariadb-10.4.7-r1`

**Nextcloud version:** (see `/status.php`)
```json
{
	"installed":true,
	"maintenance":false,
	"needsDbUpgrade":false,
	"version":"16.0.4.1",
	"versionstring":"16.0.4",
	"edition":"",
	"productname":"Nextcloud"
}
```

**Audio Player version:** (see `/settings/apps`)
`audioplayer-2.8.4`

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
`local storage`

### Client configuration
**Browser:**

#### Nextcloud log
```
Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437		för 2 minuter sedan
Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437		för 2 minuter sedan
Debug	audioplayer	Error with getID3. Does not seem to be a valid audio file: /gatak/files/Music Library/The Smiths/The Queen Is Dead/08 - The Smiths - Vicar In A Tutu.mp3		för 2 minuter sedan
Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437		för 2 minuter sedan
Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437		för 2 minuter sedan
Debug	audioplayer	Error with getID3. Does not seem to be a valid audio file: /gatak/files/Music Library/The Smiths/The Queen Is Dead/07 - The Smiths - The Boy With The Thorn In His Side.mp3		för 2 minuter sedan
```

### The other "Music" app
The other "Music app" doesn't seem to have any issues with the files.
![image](https://user-images.githubusercontent.com/1469150/64313613-7ec9f500-cfac-11e9-96b3-ee7aaedcd603.png)

**Comment by ghost** [comment]
An update:

Apparently it works better to scan for new files from the browser. Though it is slow. Also, hard to schedule updates for many users this way. Some files still didn't open, but I know they play well.

![image](https://user-images.githubusercontent.com/1469150/64314442-4c6dc700-cfaf-11e9-8db1-2dec34152487.png)

**Comment by Rello** [comment]
Hello
The issue is the parallel activated music app. 

It is using a different implementation of getID3 and it seems to be implemented in a way that it is interfering other apps

Once you disable it you can scan your library. Afterwards you can enable music again to compare which app fits your needs the best

**Comment by ghost** [comment]
OK. Thank you. I will check and see. Did not realize the two apps would affect each other.

**Comment by Rello** [comment]
Problem is, that music uses a non-stock version of getID3. I still need to figure out why AP uses this wrong implementation on the first hand

**Comment by Rello** [comment]
https://github.com/owncloud/music/issues/715

**Comment by Rello** [comment]
https://github.com/nextcloud/server/issues/17027

**Comment by Rello** [comment]
@Gatak Music was just updated and should not interfere anymore.
please report back, in case the issue comes up again

**Comment by ghost** [comment]
Great! I can confirm it is now working as it shoushould :)
