### ISSUE TITLE
Feature request: more decent background for album view

### ISSUE THREAD

**Issue by connium** [Rello/audioplayer#44]
From the colors of the album cover the background color of the title listing (which is shown when you click on an album) is calculated.

For some albums the calculated color is rather annoying. Maybe it makes sense to have a decent background color that is the same for all albums (e.g. light grey).

![albumview](https://cloud.githubusercontent.com/assets/3909302/17906986/f7635fc0-6979-11e6-8f76-777bc0c3f4ae.png)

Another thing is that the background color of albums featuring a cover image is transparent (see image above). Unfortunately for the albums without a cover the background color is not transparent. Is there a chance to fix this?

**Comment by Rello** [comment]
thank you for the finding. there is indeed a transparency for some of them.
I removed it for now to correct this.
the colors will be looked at later

**Comment by ghost** [comment]
@connium Please take a look at the new uniform background and tracklist design. #59
