### ISSUE TITLE
Cant play any song

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [Rello/audioplayer#440]
Today I just wanted to hear some music like a few weeks ago. When I clicked on an Album, I was able to see the tracks. When I clicked on a Track to start listening Music it loaded, but the at the top in the player there was a black x infront of the Titel. It jumped to the next track in the album but this would couldnt be played neither. I tried 10 different albums, but none of them worked. 
Any idea what could cause such problem? 

The tracks are in a shared folder from another user. ()

**Comment by mmatous** [comment]
Could you post relevant fields requested in the "New issue" template? Most importantly the browser log. Was the app updated in the meanwhile?

**Comment by r4sas** [comment]
And please provide media information, like codecs which used in your audio.

**Comment by riparise** [comment]
Same issue. Audio files are also in a shared folder.
When I try to play a song, the song appears in the bar with an "X" before the name, and then it proceeds to try to play the next song, and so on.
When I try to play a song an error "OCP\Files\NotFoundException" is logged, follwed by "Exception: Call to a member function getPath() on null" for every song it subsequently tries to play and skip.

Here are the details of both errors:
[index] Error: OCP\Files\NotFoundException: /XXXXXX/files/Musics/Player at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 134
    OC\Files\Node\Root->get("/XXXXXX/files/Musics/Player")
 1. /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php line 469
    OC\Files\Node\Folder->get("/Musics/Player/")
 2. /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php line 825
    OCA\audioplayer\Controller\ScannerController->getAudioObjects(Symfony\Componen ... {})
 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\audioplayer\Controller\ScannerController->checkNewTracks()
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\audioplayer\ ... {}, "checkNewTracks")
 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "checkNewTracks")
 6. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\audioplaye ... r", "checkNewTracks", OC\AppFramework\ ... {}, {_route: "audiop ... "})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
 8. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
 9. /var/www/nextcloud/lib/base.php line 1000
    OC\Route\Router->match("/apps/audioplayer/checknewtracks")
10. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

POST /apps/audioplayer/checknewtracks
from XXX.XXX.XXX.XXX by XXXXXX at 2019-11-13T13:31:46+01:00


And the second error:

[index] Error: Exception: Call to a member function getPath() on null at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "getAudioStream")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\audioplaye ... r", "getAudioStream", OC\AppFramework\ ... {}, {_route: "audiop ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
4. /var/www/nextcloud/lib/base.php line 1000
   OC\Route\Router->match("/apps/audioplayer/getaudiostream")
5. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/audioplayer/getaudiostream?t=33732
from XXX.XXX.XXX.XXX by XXXXXX at 2019-11-13T13:32:08+01:00

**Comment by riparise** [comment]
I do not recall updating the player lately.

**Comment by riparise** [comment]
If I try to scan with occ, I receive the following error:
occ audioplayer:scan XXXXX -vvv                                                                             
Start scan for XXXXX 
Start processing of audio files
                                                                                                                                                                                        
In Root.php line 202:
                                 
  [OCP\Files\NotFoundException]  
  /XXXXX/files/Musics/Player  
                                 
                                                                                                                                                                                        
Exception trace:
 () at /var/www/nextcloud/lib/private/Files/Node/Root.php:202
 OC\Files\Node\Root->get() at /var/www/nextcloud/lib/private/Files/Node/Folder.php:134
 OC\Files\Node\Folder->get() at /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php:469
 OCA\audioplayer\Controller\ScannerController->getAudioObjects() at /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php:162
 OCA\audioplayer\Controller\ScannerController->scanForAudios() at /var/www/nextcloud/apps/audioplayer/lib/Command/Scan.php:75
 OCA\audioplayer\Command\Scan->execute() at /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:908
 Symfony\Component\Console\Application->doRunCommand() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:269
 Symfony\Component\Console\Application->doRun() at /var/www/nextcloud/3rdparty/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /var/www/nextcloud/lib/private/Console/Application.php:213
 OC\Console\Application->run() at /var/www/nextcloud/console.php:97
 require_once() at /var/www/nextcloud/occ:11
                                                                                                                                                                                        
audioplayer:scan [--all] [--] [<user_id>...]

**Comment by paranoiagu** [comment]
[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT  `AB`.`id` , `AB`.`name`, LOWER(`AB`.`name`) AS `lower` , `AA`.`id` AS `art`, (CASE  WHEN `AB`.`cover` IS NOT NULL THEN `AB`.`id` ELSE NULL END) AS `cid` FROM `oc_audioplayer_tracks` `AT` LEFT JOIN `oc_audioplayer_albums` `AB` ON `AB`.`id` = `AT`.`album_id` LEFT JOIN `oc_audioplayer_artists` `AA` ON `AA`.`id` = `AB`.`artist_id` WHERE `AT`.`user_id` = ? AND `AB`.`artist_id`= ? GROUP BY `AB`.`id`, `AA`.`id` ORDER BY LOWER(`AB`.`name`) ASC' with params ["382D302E-0945-45C4-A684-A5708BE0830A", "4288"]:

SQLSTATE[42000]: Syntax error or access violation: 1055 'nextcloud.AB.name' isn't in GROUP BY at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... Y", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... Y")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 162
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT  `AB`.`i ... C", {1: "382D302E-09 ... "})
 3. /var/www/html/custom_apps/audioplayer/lib/Controller/CategoryController.php line 200
    Doctrine\DBAL\Statement->execute(["382D302E-0945- ... "])
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\audioplayer\Controller\CategoryController->getCategoryItemCovers("Album Artist", "4288")
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 6. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\audioplaye ... r", "getCategoryItemCovers", OC\AppFramework\ ... {}, {_route: "audiop ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
 9. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
10. /var/www/html/lib/base.php line 1000
    OC\Route\Router->match("/apps/audioplayer/getcategoryitemcovers")
11. /var/www/html/index.php line 42
    OC::handleRequest()

GET /apps/audioplayer/getcategoryitemcovers?category=Album+Artist&categoryId=4288
from 114.92.117.60 by 382D302E-0945-45C4-A684-A5708BE0830A at 2019-12-21T02:21:14+00:00

**Comment by Rello** [comment]
Hello
Thats interesting. Which SQL version are you using?

**Comment by paranoiagu** [comment]
my database is: 10.1.41-MariaDB-1~bionic
with these sql_mode: 
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by Rello** [comment]
was solved already some releases ago
