### ISSUE TITLE
add random-tracks smart playlist

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#442]
add a smart playlist which generates a list of random 50 tracks

**Comment by mmeinesz** [comment]
that sounds a bit like my feature request. I have closed my request.
+1

**Comment by great-qwerty** [comment]
Hey guys, I've just submitted a PR #455  which kinda satisfies the requirements of this feature request. @Rello, could you please have a look?

**Comment by Rello** [comment]
Hello @great-qwerty 
I almost expected it already. there is an issue with RAND() as it is not compatible to Postgres for example.
I will see if I can find an alternative

**Comment by Rello** [comment]
Hello,
I will have to leave it out for now.
it does not seem possible across databases
nextcloud/server#18640 (comment)

**Comment by Rello** [comment]
solution was found
thank you @nickvergessen for your support

**Comment by Rello** [comment]
v 2.10.0 released
