### ISSUE TITLE
Audioplayer does not scan ID3v1 tags

### ISSUE THREAD

**Issue by lorinder** [Rello/audioplayer#443]
### Actual behavior
When importing my music collection into nextcloud, I got almost exclusively "unknown" tracks in "unknown" albums from "unknown" artists.  Digging into the documentation suggests this is because audioplayer supports only ID3v2 tags.  That is far from ideal; users shouldn't have to use specific types of tags. In fact users shouldn't be expected or required to even know that there are different versions of ID3 tags, or what an ID3 tag even is, for that matter.

### Steps to reproduce the behavior
1. Import a file with ID3v1 tags, but no ID3v2 tags.
2. Check in your music library.
3. Look for the "unknown" song in your library.

### Additional information

In my local version of the audio player, the following patch fixed things for me:

```
--- ./lib/Controller/ScannerController.php.orig 2019-10-02 04:09:12.000000000 +0000
+++ ./lib/Controller/ScannerController.php      2019-10-08 15:24:29.713664231 +0000
@@ -151,7 +151,7 @@
         }
         $getID3 = new getID3;
         $getID3->setOption(['encoding' => 'UTF-8',
-            'option_tag_id3v1' => false,
+            'option_tag_id3v1' => true,
             'option_tag_id3v2' => true,
             'option_tag_lyrics3' => false,
             'option_tag_apetag' => false,
```

I'm assuming there must be a reason why ID3v1 tags are disabled by default.  Digging in the audio player bug reports I only found a vague comment that this was so for "compatibility reasons".  I'd be interested in knowing more details; that might help coming up with generally acceptable fix, thus closing this issue.

One possible drawback of the above patch is that I'm not sure what happens when there are both ID3v1 and ID3v2 tags in a file; ideally, ID3v2 tags should take precedence over ID3v1 tags if both are present.

### Server configuration
**Operating system:**
ubuntu 19.04

**Web server:**
Apache 2.4.38

**Database:**
MariaDB 10.3.13

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.0.9

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
S3 object storage

### Client configuration
**Browser:**
Chromium 77.0.3865.120

**Comment by Rello** [comment]
Hello,
there was a reason in terms of formatting like UTF-8 if I am not wrong. also not all tags are delivered in v1 if I remember correctly

if the patch works locally for you, this might be the easiest
