### ISSUE TITLE
None of the controlling buttons are displaying

### ISSUE THREAD

**Issue by rarealphacat** [Rello/audioplayer#446]
### Actual behavior
Controlling buttons not showing up, including, prev, play, next, volume, repeat, shuffle. Not even incorrect link img is showing, only white. When I move the mouse over I can see the link of the controller like www.nextcloud.com/index.php/apps/audioplayer/#volume. It even does the action, only not displaying the icon.

### Steps to reproduce the behavior
1. open up audio player and no controlling buttons found
2. 
3. 

### Server configuration
**Operating system:**
Ubuntu 18

**Web server:**
Apache2.4

**Database:**
Mariadb

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0

**Audio Player version:** (see `/settings/apps`)
2.8.3

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
no

### Client configuration
**Browser:**
firefox, chrome

here's the permission info
drwxr-xr-x  2 www-data www-data  4096 Oct 11 01:31 .
drwxr-xr-x 10 www-data www-data  4096 Oct 11 01:31 ..
-rw-r--r--  1 www-data www-data  1178 Oct 11 01:31 albumplay.svg
-rw-r--r--  1 www-data www-data   605 Oct 11 01:31 albums.svg
-rw-r--r--  1 www-data www-data  1328 Oct 11 01:31 app-dark.svg
-rw-r--r--  1 www-data www-data  1356 Oct 11 01:31 app.svg
-rw-r--r--  1 www-data www-data  1150 Oct 11 01:31 favicon.ico
-rw-r--r--  1 www-data www-data 12314 Oct 11 01:31 favicon.png
-rw-r--r--  1 www-data www-data 12888 Oct 11 01:31 favicon-touch.png
-rw-r--r--  1 www-data www-data   703 Oct 11 01:31 list2.svg
-rw-r--r--  1 www-data www-data   658 Oct 11 01:31 next.svg
-rw-r--r--  1 www-data www-data   627 Oct 11 01:31 pause.svg
-rw-r--r--  1 www-data www-data   534 Oct 11 01:31 play.svg
-rw-r--r--  1 www-data www-data   653 Oct 11 01:31 previous.svg
-rw-r--r--  1 www-data www-data   539 Oct 11 01:31 repeat.svg
-rw-r--r--  1 www-data www-data   917 Oct 11 01:31 shuffle.svg
-rw-r--r--  1 www-data www-data  1682 Oct 11 01:31 spinner.svg
-rw-r--r--  1 www-data www-data   208 Oct 11 01:31 toggle-filelist.svg
-rw-r--r--  1 www-data www-data   348 Oct 11 01:31 toggle-pictures.svg
-rw-r--r--  1 www-data www-data   725 Oct 11 01:31 volume-down.svg
-rw-r--r--  1 www-data www-data   477 Oct 11 01:31 volume.svg
-rw-r--r--  1 www-data www-data   812 Oct 11 01:31 volume-up.svg

**Comment by r4sas** [comment]
Can you check what return your webserver when that images are requested via webconsole/devtools in browser?

**Comment by rarealphacat** [comment]
um, I'm not sure I know how to do that, webconsole says 
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).??

**Comment by Rello** [comment]
hello
sorry for the late reply.
no, the CSP is not the issue here. the icons are generated by NC and delivered via scss variables

is the error still there? only the icons on the right missing - but the ones on the left (play) are working?

let me know

**Comment by rarealphacat** [comment]
The error is gone and idk why, anyway I'm closing this.
