### ISSUE TITLE
Audioplayer fails integrity check

### ISSUE THREAD

**Issue by AmorbiaCacoa** [Rello/audioplayer#447]
### Actual behavior
Nextcloud displays a message in the admin settings that some files failed the integrity check. Clicking on the "list of invalid files"-link, it shows that the audioplayer file "css/bar-ui.css" has a different hash than expected.

### Additional information (optional)
The following is the output from the "list of invalid files"-link in nextcloud:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- audioplayer
	- INVALID_HASH
		- css/bar-ui.css

Raw output
==========
Array
(
    [audioplayer] => Array
        (
            [INVALID_HASH] => Array
                (
                    [css/bar-ui.css] => Array
                        (
                            [expected] => e2dbc17d2a7249d499dada33d53e4f787fc6dec702e176d0f677bb52a63f4aea79c565708ef63b7c3d0932140d647fc518e2390486bb28ca7cbdaf80432249a0
                            [current] => 36f17c8c7fc4c3efe4c96c5f2d1cdb111af68a13415e2357e352f2031ef8ab82156936dd8f4306861a7b2520781d96b784f5cef112d2979c7b17fe744ba7340d
                        )

                )

        )

)
```

### Server configuration
**Operating system:**
Raspian Buster

**Web server:**
Apache2 with php7.3-fpm

**Database:**
MySQL

**Nextcloud/ownCloud version:** (see `/status.php`)
currently 16.0.2 but the problem started with 16.0.0 (I think)

**Audio Player version:** (see `/settings/apps`)
2.8.4

### Client configuration
**Browser:**
Brave, Chrome, Firefox, does not matter

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
There are no information in the nextcloud log regarding this issue.
```

</details>

I also disabled and removed audioplayer. After re-installation the error persists.

**Comment by Rello** [comment]
Hello,
I can not explain this. Current version has many thousand usages and you are the only one reporting this. 

Are you planning to update your NC to a proper version soon?

**Comment by AmorbiaCacoa** [comment]
Sorry, the Version of Nextcloud was wrong in my report. I'm on the current 16.0.6

Edit:
I downloaded the .tar.gz from here and exchanged the css/bar-ui.css file in my folder. After a rescan of the files, the error is gone.
I don't know what was wrong and how the manual exchange is different from the automatic deletion/re-installation. 
I assume this can be closed.

Thanks for your quick reply!
