### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by snarffy1959** [Rello/audioplayer#449]
### Actual behavior
Nextcloud or some of the used apps recommended to use the latest version of PHP (at this moment 7.4) so i installed this version. After that I liked to download and install Audio Player but that was not possible anymore because of this "PHP with a version lower than 7.3 is required.".

### Steps to reproduce the behavior
1. Select Audio player in Nextcloud
2. 
3. 

### Additional information (optional)

Prerequisites |  
-- | --
Prerequisite Nextcloud versions | >=14.0.0,<18.0.0
Minimum Integer bits | 32
PHP | >=7.0.0,<7.4.0

### Server configuration
**Operating system:**

**Web server:**

**Database:**

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.1

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

### Client configuration
**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
I don´t have a 7.4 environment ready yet. do you have the possibility to maintain the info.xml manually to include 7.4 and let me know if AP still works?

**Comment by snarffy1959** [comment]
Hello Rello thanx for your reply, it took me a while (never add apps in nextcloud by hand). I think its working with FireFox in Edge the scanning for files seems a hell of a job (empty progress bar, if thats a progress bar) nothing happens there. The "ID editor" and "SONOS" i didn't download and enable, i'll do that soon (only the "ID editor" and when i can use "SONOS"also with my Yamaha WX010 that one too).

**Comment by Rello** [comment]
Hello @snarffy1959,
so did the scanner finish? can you play back all your files?

**Comment by snarffy1959** [comment]
Hello @Rello, yes when using FireFox the scan finished (Edge not).

**Comment by snarffy1959** [comment]
@Rello, i had only one file, but that could be play backed . Thnx again for your reply, soon i'll have more files (files are on another lan, must see how i get them from there).

**Comment by Rello** [comment]
Hello,
I just did a version check. ist seems the external getID3 library has some compatibility issues.
I will update everything and release a new version

**Comment by snarffy1959** [comment]
@Rello, then i wait. Is the new version "audioplayer_editor-0.1.1"?

**Comment by mmatous** [comment]
Running NC17 with PHP 7.4 is currently not officially supported. It's not listed [here](https://portal.nextcloud.com/article/supported-platforms-26.html) and support was added in [this](https://github.com/nextcloud/server/pull/18064) PR. 

The cron.php (or whatever it is called) will fail unless you manually modify ./lib/versioncheck.php.

I am personally running 7.4 and it seems fine otherwise, but downgrading to 7.3 should be the preferred option until another NC update.

**Comment by snarffy1959** [comment]
Thanx MMatous for your comment.
