### ISSUE TITLE
SQL group by exception

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#450]
[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT  `AB`.`id` , `AB`.`name`, LOWER(`AB`.`name`) AS `lower` , `AA`.`id` AS `art`, (CASE  WHEN `AB`.`cover` IS NOT NULL THEN `AB`.`id` ELSE NULL END) AS `cid` FROM `oc_audioplayer_tracks` `AT` LEFT JOIN `oc_audioplayer_albums` `AB` ON `AB`.`id` = `AT`.`album_id` LEFT JOIN `oc_audioplayer_artists` `AA` ON `AA`.`id` = `AB`.`artist_id` WHERE `AT`.`user_id` = ? AND `AB`.`artist_id`= ? GROUP BY `AB`.`id`, `AA`.`id` ORDER BY LOWER(`AB`.`name`) ASC' with params ["382D302E-0945-45C4-A684-A5708BE0830A", "4288"]:

SQLSTATE[42000]: Syntax error or access violation: 1055 'nextcloud.AB.name' isn't in GROUP BY at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... Y", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... Y")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 162
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT  `AB`.`i ... C", {1: "382D302E-09 ... "})
 3. /var/www/html/custom_apps/audioplayer/lib/Controller/CategoryController.php line 200
    Doctrine\DBAL\Statement->execute(["382D302E-0945- ... "])
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\audioplayer\Controller\CategoryController->getCategoryItemCovers("Album Artist", "4288")
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 6. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\audioplayer\ ... {}, "getCategoryItemCovers")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\audioplaye ... r", "getCategoryItemCovers", OC\AppFramework\ ... {}, {_route: "audiop ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "audiop ... "})
 9. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "audiop ... "})
10. /var/www/html/lib/base.php line 1000
    OC\Route\Router->match("/apps/audioplayer/getcategoryitemcovers")
11. /var/www/html/index.php line 42
    OC::handleRequest()

GET /apps/audioplayer/getcategoryitemcovers?category=Album+Artist&categoryId=4288
from 114.92.117.60 by 382D302E-0945-45C4-A684-A5708BE0830A at 2019-12-21T02:21:14+00:00

_Originally posted by @paranoiagu in https://github.com/Rello/audioplayer/issues/440#issuecomment-568145240_

**Comment by Rello** [comment]
thats interesting, because no one of the many 1000s users had this. even postgres which is normally more strict does not complain.
I will extend the group-by

**Comment by paranoiagu** [comment]
this exception will throw only when i set the sql mode ONLY_FULL_GROUP_BY .
