### ISSUE TITLE
[Bug] fast forwarding immediately causes player to skip song

### ISSUE THREAD

**Issue by SimplyCorbett** [Rello/audioplayer#451]
With shuffle on (big collection of flac) if I fastforward immediately after a song starts it skips the song and goes to the next one.

If I wait 2-4 seconds it will fast forward normally.

I'd say it's because I use S3 as primary which nextcloud has issues with in terms of seek support, however it plays the song before I fast forward so it should be fully loaded at that point.

If I drag instead of click it fast forwards normally without issue.

**Expected Behavior**

Even if the song isn't loaded the expected behavior should be that it waits until it is loaded to fast forward. It shouldn't just skip to the next song.

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Nginx

**Database:**
Mariadb

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.2.1

**Audio Player version:** (see `/settings/apps`)
Latest

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**
Firefox

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
{"reqId":"cWblankdZlL4","level":3,"time":"2019-12-26T15:04:17+00:00","remoteAddr":"172.16.2.20","user":"blank","app":"PHP","method":"GET","url":"\/apps\/audioplayer\/getaudiostream?t=3199","message":"fseek(): stream does not support seeking at \/var\/www\/html\/3rdparty\/icewind\/streams\/src\/Wrapper.php#82","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko\/20100101 Firefox\/71.0","version":"17.0.2.1"}
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
2019/12/26 07:04:18 [warn] 22202#22202: *199277 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/4/10/0000000104 while reading upstream, client: 172.16.2.20, server: blank, request: "GET /apps/audioplayer/getaudiostream?t=7388 HTTP/2.0", upstre$
```

</details>

**Comment by Rello** [comment]
Hello,
thank you for your report.
I will have a look. I assume it is exactly as you mentioned: when the title is not loaded/buffered already, the soundmanager does not recognize it as playing - yet.
let me check if I can catch this case

**Comment by SimplyCorbett** [comment]
This is what happens:

https://i.imgur.com/otsaZgB.gifv

It's not a big deal just annoying.

**Comment by Dragon988** [comment]
It's also freezing during playback. Not sure if I should file another bug report for that.

https://i.imgur.com/zBqvN8U.gifv

No errors in any logs. If I skip forward, works fine.

**Comment by Rello** [comment]
Hello,
the next release will have a reworked player.
I dropped the soundmanager/bar-ui plugin and switched to html5-standard.
I will update this issue when it is released and ask you for a retest then.

**Comment by Rello** [comment]
Version 2.11.0 was released
