### ISSUE TITLE
Download track via path in sidebar

### ISSUE THREAD

**Issue by beatandbyte** [Rello/audioplayer#453]
Hi,

how can I add or display the download button? I would like to share my own tracks, directly via the audioplayer?

**Comment by Rello** [comment]
Hello,
let me check. its a standard NC thing but we hided it for a reason

**Comment by beatandbyte** [comment]
Thx Rello 
and a Happy New Year :)

**Comment by Rello** [comment]
Hello,

it is working on my side. tested in NC16 and NC18
can you send your screenshot?
![Screenshot 2020-01-15 at 22 40 49](https://user-images.githubusercontent.com/13385119/72473943-17d50c00-37e8-11ea-98bd-5c89a52547a2.png)

**Comment by beatandbyte** [comment]
Hi Rello!
I meant this view:
![Beispiel1](https://user-images.githubusercontent.com/59344600/72549791-a81b5b80-3891-11ea-926c-4951e0202622.PNG)

**Comment by beatandbyte** [comment]
Close and reopen works... LOL

**Comment by Rello** [comment]
Hello,
when the user is seeing this view, he has access to the file itself.
so he can access the file in the files app

what is the need here?

**Comment by beatandbyte** [comment]
Hi,
the download via "files app" does work, this is not the problem.
I need the download function directly in the audio player app,
because then can i or my partners search for genre directly in the audio app and then download directly from this audio app without switching to the files app.
That would be much more practical and easier
...that would be awesome :)

**Comment by r4sas** [comment]
He wants collumn with button, which will start downloading tracks from playlist/folder/etc. list.

**Comment by Rello** [comment]
Hello @beatandbyte 
i don´t want to put up any new buttons somewhere because I don´t have a usefull idea where.

what I can offer: I enabled the path in the sidebar as a link. when you click on this, the file gets downloaded directly via its webdav-link.

does this work for you?
![Screenshot 2020-07-28 at 23 20 55](https://user-images.githubusercontent.com/13385119/88723490-4170d780-d129-11ea-9c72-23edab2ae2bb.png)

**Comment by beatandbyte** [comment]
Hello Rello :)

thank you very much for your efforts!
That would be fine for me.
It would also be great if the sidbar updated with the information of the currently playing song when it is open.
