### ISSUE TITLE
Album selection to show tracks and not the album art as default

### ISSUE THREAD

**Issue by dennorske** [Rello/audioplayer#454]
### Actual behavior
You go in the list of you albums in the left pane. Let's say I want to listen to Album A. I click on Album A, and instead of showing me all the tracks from this album in the main part of the screen, it shows me the album cover or album art. Then you have to again click this to reveal the tracks.

### Steps to reproduce the behavior
1. In the audio player dropdown, select albums
2. Click any album you have
3. See the album art show up on the right

### Additional information
So, what would be even more effective, is to show the list of tracks from that album directly. I imagine it could be like when you click a playlist. As it is right now, it is slightly cumbersome to click twice on one album to reveal the tracks. This extra click every time you switch album is not a big deal, but it makes the difference.
Also, thank you Rello for your continued development on the player. I truly appreciate it!

### Server configuration
**Operating system:**
Ubuntu Server 18.04 

**Web server:**
Apache2

**Database:**
Mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.2

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
not relevant in this context

### Client configuration
**Browser:**
Chrome, Firefox

**Comment by Rello** [comment]
Hi,

just to understand it: you are in the cover-view mode (not the list view; icon above the dropdown).
and for the special case, that you choose dropdown->Albums->select one Album, you have an overhead click

- do you need the tracklist? there is the little play icon on top of every album cover which starts the play directly
- you want to remain in cover mode and not use the list-view in general

is my understanding correct?

**Comment by dennorske** [comment]
my apologies Rello, yet again I assume it isn't possible - but the list view actually gave me exactly what I wanted. Thank you very much, your list view does exactly what I had hoped to see.

**Comment by Rello** [comment]
ok, perfect
