### ISSUE TITLE
absolute path and '../' in .m3u playlist files

### ISSUE THREAD

**Issue by rainer042** [Rello/audioplayer#457]
### Actual behavior
audioplayer detect .m3u playlists stored in nextcloud but is unable to play them. Clicking on any of the playlists found results in a window that does not show any songs files (.mp3).  Probably this is due to my directory structure which is as follows:

Music/                      # music basefolder
----00Playlists/       # directory with .m3u playlists
--------testplaylist.m3u
----myartist/
--------myalbum/
------------mysong.mp3     # mp3 file
----myartist2/
--------album2/
------------song2.mp3       # mp3 file

So a song is located eg here: 
Music/myartist/myalbum/mysong.mp3 

The testplaylist.m3u Playlist file can be found here:
Music/00Playlists/testplaylist.m3u

Now in the playlist that should contain relative paths compared to the playlists file directory I tried these variants:

File Music/00Playlists/testplaylist.m3u:
../myartist/myalbum/mysong.mp3
myartist/myalbum/mysong.mp3

None of these songs are displayed as part of the playlistfile testplaylist.m3u

Music is not a toplevel folder in my nextcloud if this is important.

### Steps to reproduce the behavior
1. create  a .m3u playlistfile and store it in a subfolder of your mp3 collection
2. 
3. 

### Additional information (optional)

I was able to get a working playlist only if I copied the playlistfile in the same directory like my "Music" folder containing all the mp3 files. But as soon as I ctreated a subfolder at this place and moved the playlistfile inside, modifying the song path inside the file by prepending a "../" to the songs path it did no longer work. 

### Server configuration
**Operating system:**
Linux, OpenSuSE Leap 15.1

**Web server:**
apache 2.4

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.1

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
could you please try with the full path
`Music/myartist/myalbum/mysong.mp3`

this worked on my side. I need to see how I fix the issue with the referential links. its a little tricky
https://github.com/Rello/audioplayer/blob/master/lib/Controller/CategoryController.php#L473-L477

**Comment by rainer042** [comment]
Sorry for the long delay. I tried the scheme you mentioned which actually is the only I am able to use eg on android and also with Linux mp3 players. So this would be my favorite however for me it does not workwith audioplayer. I tried this:

Playlistfile: "/Multimedia/Music/Playlists/testm3u.m3u":
Music/Harry Styles/Harry Styles/02 - Sign of the Times.mp3

In my nextcloud root the files are located like this:
/Multimedia/Music/Playlists/testm3u.m3u
/Multimedia/Music/Harry Styles/Harry Styles/02 - Sign of the Times.mp3

In audioplayer I can see the playlist testm3u but when I click on it its empty.
In the advance settings of AudioPlayer I defined /Multimedia/Music/ to be the folder where to scan for music in my nextcloud.

When scanning for autio files I see the real path on the device something like "/myaccount/files/Multimedia/Music/..." in the scan output, where "myaccount" is my user nextcloud account. Could this be the source of trouble?

**Comment by Rello** [comment]
Hello @rainer042 ,
i am currently looking at this.
The problem is, that the ../ does not work (even so I thought it does).
So if going for a referential path, it will start with the location of the playlist file. in your case, it would not work.
I am changing this to also work with absolute path. so in your case it would start with a /. so this would work 
`/Multimedia/Music/Harry Styles/Harry Styles/02 - Sign of the Times.mp3`
this would not work
`../Harry Styles/Harry Styles/02 - Sign of the Times.mp3`

do you think this is ok? would this be usable?

**Comment by Rello** [comment]
...ok,
i made changes to the parser. now absolute and relative path including (one) `../` will work

**Comment by Rello** [comment]
Version 2.11.0 was released
