### ISSUE TITLE
Nextcloud 18 support

### ISSUE THREAD

**Issue by elpraga** [Rello/audioplayer#458]
### Actual behavior

NC18 not supported ATM. It would be great to add the support at the release date of NC18 is very near.

### Steps to reproduce the behavior
1. 
2. 
3. 

### Server configuration
**Operating system:**

**Web server:**

**Database:**

**Nextcloud/ownCloud version:** (see `/status.php`)

**Audio Player version:** (see `/settings/apps`)

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

### Client configuration
**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
will be released on time
