### ISSUE TITLE
Feature request: Add .cue (cuesheet) playlist support

### ISSUE THREAD

**Issue by CarloApri** [Rello/audioplayer#459]
An entire multi-track audio CD may be ripped to a single audio file and a [cue sheet](https://en.wikipedia.org/wiki/Cue_sheet_(computing)#Examples), resulting in `cd.flac` and `cd.cue`. 
Softwares like foobar2000 can play the CD by using the .cue playlist file.
It would be great if we could do that too on nextcloud!

**Comment by Rello** [comment]
Hello,
I had a look. I think this playback is a little questionable here. you will result in a huge flac file plus and index file which basically just stores start-times within the big file.
the way the <audio> playback works is that this would create huge downloads in the background for buffering the whole x00MB file

As my time is limited, I have to park this request as I don´t see a real use case.
Thank you for initially coming back with the request
