### ISSUE TITLE
Cover from M4A-Tracks not shown

### ISSUE THREAD

**Issue by kangaroo72** [Rello/audioplayer#460]
I'm using audioplayer in Nextcloud 17.0.3
All tracks and covers are fine, but if you add m4a-files, the cover will not be listed ...

See screenshot

![nc_audioplayer_cover_bug_mp4](https://user-images.githubusercontent.com/6906390/74579141-ec853e80-4f98-11ea-8f7a-f7bf967d577a.jpg)

**Comment by r4sas** [comment]
Please provide more info about encoding, because m4a container is used by various encoders.

Maybe your tracks doesn't have included cover?
