### ISSUE TITLE
Playlist ends outside of visible part of page

### ISSUE THREAD

**Issue by r4sas** [Rello/audioplayer#461]
### Actual behavior
Playlist ends outside of visible part of page
![image](https://user-images.githubusercontent.com/7023612/74592532-5e11cb00-5033-11ea-804a-c8051d2d4aed.png)

### Steps to reproduce the behavior
Use playlist which does not fit on page

### Additional information (optional)
Investigation of the problem led to the CSS tag `#playlist-container` where I see `position: relative` style. If I change it to `absolute` page start work correctly.

### Server configuration
**Nextcloud/ownCloud version:** (see `/status.php`)
17.0.3

**Audio Player version:** (see `/settings/apps`)
2.9.0

### Client configuration
**Browser:**
Chromium 77.0.3865.120

**Comment by Rello** [comment]
Hey,
thank you for the finding.
does the playbar still work when you change this? I will also check on my side

**Comment by Rello** [comment]
I could not reproduce this issue in Chrome or Safari.
but changing your setting did also not make anything worse.
if it helps you, we can put it in

**Comment by r4sas** [comment]
> does the playbar still work when you change this?

Yes, without problems.

> I could not reproduce this issue in Chrome or Safari.

idk, but dropping cache doesnt make me trick. I checked this in dark and standart theme and got same issue. NC without any changes in stylish, themes, etc.

I see in devtools block structure, where playlist block bottom appears below page end.
![image](https://user-images.githubusercontent.com/7023612/74594865-3549ff80-504c-11ea-8403-186b8bc131d0.png)

With absolute it changes, but playlist shows all tracks:
![image](https://user-images.githubusercontent.com/7023612/74594851-121f5000-504c-11ea-8f37-3cd1cda81dad.png)

**Comment by Rello** [comment]
v 2.10.0 released

**Comment by r4sas** [comment]
I got new regression here, but now other type: white space at end of list.

![image](https://user-images.githubusercontent.com/7023612/89542511-72779900-d808-11ea-96a7-ea0e602911da.png)
![image](https://user-images.githubusercontent.com/7023612/89542624-963adf00-d808-11ea-9f49-01394f79bbba.png)

Fixable with changing https://github.com/Rello/audioplayer/blob/2753392f05b3fa8ef7941ff379b820aa0b832287/css/style.css#L335-L345
by replacing `top` to `padding-top` and adding `background-color: var(--color-main-background);`
Also, `60px` is a bit big amount, can be changed to `50px`.

![image](https://user-images.githubusercontent.com/7023612/89543807-0e55d480-d80a-11ea-9c2d-4e62c819e325.png)
![image](https://user-images.githubusercontent.com/7023612/89544075-5bd24180-d80a-11ea-91ed-fe26b284d222.png)
![image](https://user-images.githubusercontent.com/7023612/89543893-29c0df80-d80a-11ea-9523-ec17647e427e.png)
![image](https://user-images.githubusercontent.com/7023612/89543996-44935400-d80a-11ea-8248-b34ec90c369a.png)

**Comment by r4sas** [comment]
Please test if you can reproduce problem and possible solution.

**Comment by r4sas** [comment]
oops, wrong commit text issue mention :laughing:

**Comment by Rello** [comment]
ok, will check
...interesting mixup... :-)

**Comment by Rello** [comment]
Hi,
I could not reproduce the error on my side (chrome), but it looks like that nothing got worse.
I like the sidebar update

I will push it to the repo.
thank you!
