### ISSUE TITLE
Add setting for disable html5 audio to force using Flash player to support .m4a on chrome

### ISSUE THREAD

**Issue by c0710204** [Rello/audioplayer#463]
So since there is not html5 support in Chrome anymore, could we add a setting to force sm2 using flash to play the m4a through flash?

**Comment by Rello** [comment]
Hello,
SM2 has some flash output according to the documentation. I have no Idea if it is actually working. also the swf files are not shipped with AP because no one is using flash to my knowledge.

how many tracks are involved on your side to justify this effort?

**Comment by Rello** [comment]
Hello,
closing for now due to missing feedback
