### ISSUE TITLE
Bookmarking of long audio tracks

### ISSUE THREAD

**Issue by mcorrigan** [Rello/audioplayer#464]
It would be nice to add bookmarking or at least track position remembering for longer tracks like audio books. 

This could also tie into when you start a track in file view and then go to your player, so you don't have to start over.

**Comment by Rello** [comment]
Hallo,

thank you for your request.
Actually this request was prototyped already. the idea was even to auto-start the track at the same location when entering the next time. but this is not allowed by most browsers anymore.

At the moment I am caught up in my other app - Data Analytics - with important fixes.
I have to leave this request open for a while

**Comment by jarbus** [comment]
Also interested in this. Looking at using the audioplayer to listen to audiobooks, as there is no good way to sync playback history from linux to phone with existing solutions.

**Comment by Rello** [comment]
remember playback position between sessions #288

**Comment by Rello** [comment]
Hello,
I am looking at this for the upcoming release...

**Comment by Rello** [comment]
Version 2.11.0 was released
