### ISSUE TITLE
Can't show all albums as album covers after leaving view

### ISSUE THREAD

**Issue by craig24x** [Rello/audioplayer#465]
### Actual behavior
once you move off of this to say , list view, you can't go back to see all albums by pictures again.
instead i, navigation is limited to left hand pane.

### Steps to reproduce the behavior
1. Select List view
2. select artist from drop down
3. play a song
4. try to go back to see all albums by album picture , can't get back to the default view

### Server configuration
**Operating system:**
Debian (UCS)

**Web server:**

**Database:**

**Nextcloud/ownCloud version:** (see `/status.php`)
Owncloud 10.3.2

**Audio Player version:** (see `/settings/apps`)
2.8.4

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
no

### Client configuration
**Browser:**
Firefox
Safari
Edge

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
the switch between list an cover view uses the same filter in the categories. this was a change in 2.8.0 compared to before, when the cover view was always showing all albums.
now it behaves like the files app for example.

To see all covers, you need to select all titles (which would correspond to the "Titles" category dropdown).
currently you see only the covers for your artist selection

please try

**Comment by craig24x** [comment]
That was it. Sorry, I didn't realize filtering had changed in that way, thanks!
