### ISSUE TITLE
Does not play opus in safari iphone browser

### ISSUE THREAD

**Issue by PetrusVermaak** [Rello/audioplayer#467]
Does not play opus audio in safari iphone browser
iPhone XR IOS 13.4
Browser Safari

Steps to reproduce:
Try playing a shared opus file in the safari browser on the mobile phone. (works perfectly on android)

**Comment by PetrusVermaak** [comment]
Does not play opus in safari iphone browser
iPhone XR IOS 13.4
Browser Safari

Steps to reproduce:
Try playing a shared opus file in the safari browser on the mobile phone. (works perfectly on android)

**Comment by Rello** [comment]
Hello,
it is not compatible with Safari, unless it is packaged in some CAF file
https://caniuse.com/#feat=opus

**Comment by PetrusVermaak** [comment]
Sure, repackaged it as .caf using ffmpeg... But now the player does not recognize it to play?

**Comment by PetrusVermaak** [comment]
Yes, but then CAF takes my 4MB opus and turns it into a 220MB file. 

Ogg Opus files are supported on Safari with WebAssembly decoding:
    https://fetch-stream-audio.anthum.com/
    https://github.com/AnthumChris/fetch-stream-audio

**Comment by Rello** [comment]
Audioplayer is using the soundmanager plugin to process the audio. 
I did not fully understand the link. It requires backend/server/nginx configuration which is not possible with an NC app

**Comment by PetrusVermaak** [comment]
Understood, thanks for checking Rello. Not a programmer so had no idea.... opus is awesome, we use it at our college for student audio in online learning. It's small and the quality is great. CAF unfortunately is just too big to implement. On android we don't have any problems, but on ios of course it does not work in the browser.
