### ISSUE TITLE
Upgrade on nextcloud error

### ISSUE THREAD

**Issue by PrzemekSkw** [Rello/audioplayer#468]
### Actual behavior
Error when try to upgrade on Nextcloud server (Dietpi - Raspberry Pi4)
```
An exception occurred while executing 'CREATE TABLE `oc_audioplayer_artists` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `name` VARCHAR(256) DEFAULT NULL, INDEX artists_user_id_idx (`user_id`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`nextcloud`.`oc_audioplayer_artists`' exists. Please DISCARD the tablespace before IMPORT
```

### Steps to reproduce the behavior
1. Delete folder /var/www/nextcloud/apps/Audioplayer

### Additional information (optional)
I cannot login to my Nextcloud server because that error

Regards Przemek

**Comment by Rello** [comment]
Hi,
something went wrong in your instance.
the create is done on the first install of Audio Player. but here it seems that the table is already there.
was there an installation attempt which went wrong or was cancelled?

**Comment by r4sas** [comment]
He can temporary enable overwriting, but here is his own problem because of unexpected for NC deleting application directory.

https://github.com/Rello/audioplayer/blob/7ed830101525a9673df2cc9c18a9289f4bb05183/appinfo/database.xml#L5

**Comment by PrzemekSkw** [comment]
Hi, I click upgrade on nextcloud web and popup window for password appear. Then I need to go to my child and back later. Maybe I put password too late.

**Comment by r4sas** [comment]
Can you check all logs about deleting addon? Maybe here also nextcloud's bug?

**Comment by Rello** [comment]
Hello,

any news? 
we never got this issue with the 1000s of downloads yet

**Comment by PrzemekSkw** [comment]
@Rello Hi, Yesterday I try to upgrade Nextcloud and I have the same error. I must go to ssh and from Dietpi terminal I type `ncc upgrade`. Nextcloud upgrade correctly. But when I try to install Audio Player from Nextcloud App Store I still have error.
```
An exception occurred while executing 'CREATE TABLE `oc_audioplayer_artists` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `name` VARCHAR(256) DEFAULT NULL, INDEX artists_user_id_idx (`user_id`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`nextcloud`.`oc_audioplayer_artists`' exists. Please DISCARD the tablespace before IMPORT
```

**Comment by r4sas** [comment]
In that case I think better add to SQL `IF NOT EXISTS`

**Comment by Rello** [comment]
hello,
problem is, that the app does not have any influence there.
I tested yesterday again on several instances with installing/removing/updating. I could not reproduce the issue.

if its related to the manual deletion of the app-folder, then the app itself might still have the status of enabled.

@PrzemekSkw can you please try the occ command to disable the app?
`sudo -u www-data php occ app:disable audioplayer`

**Comment by PrzemekSkw** [comment]
@Rello Hi, I try that command and have:
```
Could not open input file: occ
```
the same with `ncc`.
Regards

**Comment by Rello** [comment]
Hello,
you need to execute the command within your nextcloud directory.
e.g.
`sudo -u www-data php /var/www/nextcloud/occ app:disable audioplayer`

**Comment by Rello** [comment]
did it work?

**Comment by PrzemekSkw** [comment]
@Rello  Hi, I try but:
```
root@Przemas82:/var/www/nextcloud# sudo -u www-data php /var/www/nextcloud/occ app:disable audioplayer
No such app enabled: audioplayer
```

**Comment by Rello** [comment]
ok, to sum it up:
- audioplayer is currently not enabled
- the tables were created somehow during a failed install?
- your NC must be running at the moment, you only can not enable/install audioplayer

is this correct?

**Comment by PrzemekSkw** [comment]
> ok, to sum it up:
> 
> * audioplayer is currently not enabled
> * the tables were created somehow during a failed install?
> * your NC must be running at the moment, you only can not enable/install audioplayer
> 
> is this correct?

Hi,
* Yes, it's not enabled
* I don't understand what do You mean "tables"
* I see `install/turn on`
when I click it I see
![Zrzut ekranu z 2020-04-30 16-52-36](https://user-images.githubusercontent.com/25219988/80726065-398ea080-8b04-11ea-8328-ddfc93ee7064.png)

and then:
![Zrzut ekranu z 2020-04-30 16-53-14](https://user-images.githubusercontent.com/25219988/80727197-b110ff80-8b05-11ea-92dd-e7d0b107b166.png)

when refresh browser there's 'delete/turn On' but also errors when I click it:
![Zrzut ekranu z 2020-04-30 16-53-32](https://user-images.githubusercontent.com/25219988/80727328-def64400-8b05-11ea-8359-2f986921e544.png)

Regards Przemek

**Comment by Rello** [comment]
Hello,
did you manage to repair your instance? I would not have an idea how to do it from here?!

**Comment by PrzemekSkw** [comment]
@Rello Hi, no I don't. But don't worry. I'm not using that audio on my nextcloud so I think I don't need it.
Thanks for Your time and Regards.
Przemek.
