### ISSUE TITLE
Version 1.1.0 doesn't work

### ISSUE THREAD

**Issue by sbr9150** [Rello/audioplayer#47]
error log :
`Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'SELECT id FROM oc_audioplayer_tracks WHERE`user_id`= ? AND`title`= ? AND`number`= ? AND`artist_id`= ? AND`album_id`= ? AND`length`= ? AND`bitrate`= ? AND`mimetype`= ? AND`genre_id`= ? AND`year`= ?' with params [\"sbr\", \"\\u4eca\\u5e74\\u590f\\u5929.mp3\", 0, 1828, 4124, \"3:37\", 128000, \"audio\\\/mpeg\", 447, 0]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'genre_id' in 'where clause'","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT id FROM ...', Array)\n#2 \/var\/www\/html\/owncloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/html\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(862): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/html\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(685): OCA\\audioplayer\\Controller\\ScannerController->writeTrackToDB(Array)\n#5 [internal function]: OCA\\audioplayer\\Controller\\ScannerController->scanForAudios()\n#6 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#8 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#9 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/html\/owncloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/audioplay...')\n#13 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":71}`

Then I downgrade to 1.0.3, reset music libary, upgrade to 1.1.0 again, scan music. Still get those error messages. Can play music on file browser.
nextcloud 9.0.53
php 7.0.8
mariaDB 10.1.16

**Comment by Rello** [comment]
Thats strange. 
As part of rhe upgrade of the version, the new DB field should have been created. 
Can you try to run the occ upgrade manually?
Can you check the versionnumber of audioplayer in the appconfig table?

**Comment by sbr9150** [comment]
I ran occ upgrade. It only told me my nextcloud is the latest version.
Audioplayer version shown in Web browser is 1.1.0, but I checked with occ app:list, it showed audioplayer 2.0.0.
By the way, My music files are all on external storage.

**Comment by Rello** [comment]
Hello,
this is strange. i checked the info.xml if there was some accident in there for a moment of time - but it was always correct.

I think the only workaround would be to deactivate the app; remove the entry in the _appconfig and drop the _audioplayer_ tables

**Comment by ghost** [comment]
… and remove the `audioplayer` app folder. Then try a fresh install.

**Comment by Rello** [comment]
Hey,
any news?

**Comment by Rello** [comment]
Hello,
Can you let us know if you could reset incorrect installation?
As we never got something similar, i would like to close this issue. 
Thank you

**Comment by sbr9150** [comment]
I'm facing a serious problem about my server and NC, I think that caused this error. I will try the new version after I fix my server. It may take some time. You can close this issue.
Keep up the good work,
