### ISSUE TITLE
It allows you to search a playlist by an album name, a title of a musical composition, an artist name

### ISSUE THREAD

**Issue by beniyas** [Rello/audioplayer#471]
It allows you to search a playlist by an album name, a title of a musical composition, an artist name

When collecting music increases, it becomes complicated to choose the music that I want to listen to

**Comment by beniyas** [comment]
When there is a problem in the state that Playlist was made and performs Rest library, Play list disappears at the same time, too.

In addition, I get used to being happy when I can enroll in Play List by an album unit as well as every music

**Comment by Rello** [comment]
Hello,
what is your question now?
I am not sure. I don´t understand your issue

**Comment by beniyas** [comment]
As I convert it into English from Japanese using translation software, it may become funny English.

There are two requests.
I want the option that Play list does not disappear even if the first carries out Rest library.
There are circumstances and must do Rest library, but re-registration of Play list is necessary even if I enroll in Play list through hardships as Play list disappears at the same time at time.
I want to evade it.

The registration to Play list is a musical piece unit now, but wants to register the second with this by artist or album unit by addition.
It means.

**Comment by Rello** [comment]
Hello,
I think I understand your problem. but it does not work.

the playlist saves the link to the audio track.
when you reset the library and do a new scan, the tracks get a new ID in the database (the database counts up incremental).
So the playlist does not match anymore.

...why do you need to reset the library so often? Perhaps we can solve this issue?

The alternative: you can create a playlist in a file. you can create m3u file and put in the file paths from your nextcloud folder. this is then not deleted as the playlist file is scanned every time again.
Is this possible?

**Comment by beniyas** [comment]
Thank you for your answer.
But I do not know how to make m3u files.

By the way, the reason that reset does is because I am not reflected well when I change a tag of mp3.

**Comment by Rello** [comment]
Hello,

create a file called e.g. "playlist.m3u" and put it in the root or in your music folder.
this file needs to include the path to the music files you like.
here is one example of the m3u with the file in the same folder

```
#EXTM3U
#EXTINF:321,Example Artist - Example title
Avicii – We Write The Story.mp3
Freeplay Music – Shopping Spree.mp3
```
then start the scan of the audioplayer. it will find the playlist in the "Playlists" dropdown section.
let me know if this works for you
