### ISSUE TITLE
Search result hidden behind playlist

### ISSUE THREAD

**Issue by hdp2101** [Rello/audioplayer#472]
### Steps to reproduce the behavior
Can you please produce search option in Audio Player app, because i have more then 500 songs, but if i want to listen particular song, then in that case i have to search the song from 500 songs, now there is no search option in audio player, so it's very difficult to find the songs from 500 songs.

Of course we have option to find the songs like from Playlist, Album, Artist, etc.... but if you have search option then this will be very easy .

If i have to give star then of course i will give you 5 star (If search option is included)

Thank you

### Server configuration
**Operating system:**
Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64

**Web server:**
Apache/2.4.39 (Unix) OpenSSL/1.0.2k-fips (fpm-fcgi)

**Database:**
mysql 10.1.44

**Nextcloud/ownCloud version:** (see `/status.php`)
Nextcloud version: 18.0.4 - 18.0.4.2

**Audio Player version:** (see `/settings/apps`)
audioplayer: 2.10.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**
Chrome

**Comment by Rello** [comment]
Hello,
Did you try the search in the top menu of nextcoud?
This is integrated and should show you the results right within AP

Can you try?

**Comment by hdp2101** [comment]
Please see i type search word "main" in search box.

But i see the search result not in the proper way.

now above is the example.

but when i have 500 song and when i search word "main" i see at lease
 60 to 70 songs, which will underlay the screen. so i couldn't see the song name properly.

also i suggest that if possible please show the search result on another page, like we select our option from drop down menu.

Thank you

![Ashampoo_Snap_2020 05 10_22h55m08s_002_](https://user-images.githubusercontent.com/13566445/81506195-43897e00-9312-11ea-8dd4-ad66ffd48888.png)

**Comment by hdp2101** [comment]
Hello Rello

       Sorry i forget to say thank you for making a superb app.

Thank you
Hemal

**Comment by hdp2101** [comment]
Please see this screenshot.

![Ashampoo_Snap_2020 05 10_23h19m14s_003_](https://user-images.githubusercontent.com/13566445/81506608-302be200-9315-11ea-814e-363802ecf18b.png)

**Comment by Rello** [comment]
Thank you for the details. 
i will check. This is definately a bug because the result has to be visible

**Comment by Rello** [comment]
Hello,
I found the issue. something changed in the NC css and I did not notice.
I could reproduce the issue in NC 18 and 19

**Comment by Rello** [comment]
OK,
the issue was introduced here
https://github.com/Rello/audioplayer/issues/461
@r4sas 
We will need to find another way. the relative->absolute change does not work with the search result anymore

**Comment by Rello** [comment]
@r4sas 
do you have the chance to test the fix in your envitionment?
I had to revert to the relative - but I put a padding at the button of the playlist. this should avoid that anything is lost

**Comment by hdp2101** [comment]
Hello Rello

        I don't know but let me try it out, and if i see any result i will share it with you.

Thank you
Hemal

**Comment by r4sas** [comment]
> @r4sas
> do you have the chance to test the fix in your envitionment?
> I had to revert to the relative - but I put a padding at the button of the playlist. this should avoid that anything is lost

I'll check in next few days, a bit overloaded with work.

**Comment by r4sas** [comment]
@Rello I'm checked just now, sorry for delay, everything works.
btw, seems like something again changed in NC's css, so that padding in not required... but I think with it better.

**Comment by hdp2101** [comment]
Hello

     Any update for search option.

**Comment by Rello** [comment]
yes. sorry for the delay. time was limited.
I will push another version

**Comment by hdp2101** [comment]
OK
Thank you

**Comment by Rello** [comment]
sorry for the delay.
I released the 2.10.1

**Comment by hdp2101** [comment]
Hello Rello

      Thank you so much for updating new version of Audio player. All the best.

Hemal Parikh

**Comment by hdp2101** [comment]
Hello Rello

      there is one more issue if possible to solve.

      While scanning the media in audio player, audio player scan the files from the user directory, but as i am an admin of nextcloud, then in that case can you give the access to scan the media files out of my directory path.

Thank you
Hemal Parikh
