### ISSUE TITLE
Ошибка при открытии audioplaye

### ISSUE THREAD

**Issue by conter86** [Rello/audioplayer#473]
Добрый день при открытии audioplaye в nextcloud вызывает ошибку 
Устанавливал с магазина 
![2020-05-21](https://user-images.githubusercontent.com/22930642/82544354-aa523700-9b5d-11ea-8525-3ebde21f8179.png)

{"reqId":"vKWMv5UBRAX8PZ1uSaa4","level":3,"time":"2020-05-21T09:12:42+00:00","remoteAddr":"188.32.110.81","user":"conter","app":"index","method":"GET","url":"/apps/audioplayer/","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create path","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php","line":84,"function":"newFile","class":"OC\\Files\\Node\\Folder","type":"->","args":["fcc9-5f3a-bar-ui.css"]},{"file":"/var/www/nextcloud/lib/private/Template/SCSSCacher.php","line":312,"function":"newFile","class":"OC\\Files\\SimpleFS\\SimpleFolder","type":"->","args":["fcc9-5f3a-bar-ui.css"]},{"file":"/var/www/nextcloud/lib/private/Template/SCSSCacher.php","line":182,"function":"cache","class":"OC\\Template\\SCSSCacher","type":"->","args":["/var/www/nextcloud/apps/audioplayer/css","fcc9-5f3a-bar-ui.css","bar-ui.scss",{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},"/apps/audioplayer/css"]},{"file":"/var/www/nextcloud/lib/private/Template/CSSResourceLocator.php","line":110,"function":"process","class":"OC\\Template\\SCSSCacher","type":"->","args":["/var/www/nextcloud/apps/audioplayer","css/bar-ui.scss","audioplayer"]},{"file":"/var/www/nextcloud/lib/private/Template/CSSResourceLocator.php","line":85,"function":"cacheAndAppendScssIfExist","class":"OC\\Template\\CSSResourceLocator","type":"->","args":["/var/www/nextcloud/apps/audioplayer","css/bar-ui.scss","audioplayer"]},{"file":"/var/www/nextcloud/lib/private/Template/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\CSSResourceLocator","type":"->","args":["css/bar-ui"]},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":310,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["css/server","css/css-variables","files_pdfviewer/css/style","notifications/css/styles","sociallogin/css/style","search/css/results","audioplayer/css/bar-ui","audioplayer/css/style","files/css/detailsView","audioplayer/css/3rdparty/fontello/css/fontello","audioplayer/css/3rdparty/fontello/css/animation"]]},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":215,"function":"findStylesheetFiles","class":"OC\\TemplateLayout","type":"::","args":[["css/server","css/css-variables","files_pdfviewer/css/style","notifications/css/styles","sociallogin/css/style","search/css/results","audioplayer/css/bar-ui","audioplayer/css/style","files/css/detailsView","audioplayer/css/3rdparty/fontello/css/fontello","audioplayer/css/3rdparty/fontello/css/animation"]]},{"file":"/var/www/nextcloud/lib/private/legacy/template.php","line":184,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["user","audioplayer"]},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":167,"function":"fetchPage","class":"OC_Template","type":"->","args":[{"audioplayer_navigationShown":"","audioplayer_view":"filelist","audioplayer_volume":"100","audioplayer_sonos":false,"audioplayer_notification":null}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\audioplayer\\Controller\\PageController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\audioplayer\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"audioplayer.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"audioplayer.page.index"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"audioplayer.page.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/audioplayer/"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","Line":185,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","version":"18.0.4.2","id":"5ec64623cc977"}

**Comment by r4sas** [comment]
Иссуи писать лучше на английском языке.

По делу - недостаточно прав на создание папки.
```
"function":"newFile"
"Message":"Could not create path"
```

Проверьте права доступа с учетом рекомендаций документации Nextcloud.

**Comment by conter86** [comment]
> Иссуи пишут лучше на английском языке.
> 
> По делу - недостаточно прав на создание папки.
> 
> ```
> "function":"newFile"
> "Message":"Could not create path"
> ```
> 
> Проверьте права доступа с учетом требований документации Nextcloud.

Дал на весь каталог nextcloud 777 и не чего не поменялось также ошибка появляется

![2020-05-21 (3)](https://user-images.githubusercontent.com/22930642/82562666-615eaa80-9b7e-11ea-8385-be2048a4f3de.png)

**Comment by r4sas** [comment]
Не самый лучший вариант. Проверьте владельца файлов, рекурсивно.

Поиск по иссуям привел только на тему 2017 года: https://github.com/nextcloud/server/issues/5129

**Comment by Rello** [comment]
NC tries to generate the dynamic css files which are collected; optimized; and delivered for better performance.
this does not work here

all other apps work?

**Comment by conter86** [comment]
> NC пытается генерировать динамические CSS-файлы, которые собираются; оптимизировано; и доставлены для лучшей производительности.
> это не работает здесь
> 
> все остальные приложения работают?

Не все кроме контактов они тоже в ошибку падают 
а целом ошибки не появляются

**Comment by conter86** [comment]
> Проверьте владельца файлов, рекурсивно.
> 
(https://github.com/nextcloud/server/issues/5129)

На папке были права но повторно дал права но не помогло 
chown -R www-data:www-data /var/www/nextcloud

**Comment by r4sas** [comment]
Значит проблема на стороне NextCloud.

**Comment by conter86** [comment]
> Значит проблема на стороне NextCloud.
А как мне ее решить хот в каком направлении копать

**Comment by r4sas** [comment]
Создать баг репорт в https://github.com/nextcloud/server/issues/ с описанием проблемы, поскольку если приложение "Контакты" тоже сбоит, то проблема в движке.

**Comment by Rello** [comment]
hey,
I don´t understand a word. is this topic still relevant?

**Comment by r4sas** [comment]
@Rello I think no, because no more replies from @conter86 since then.

**Comment by conter86** [comment]
Я решил вопрос с это проблемой путем переустановки nextcloud так как некто не смог помочь
