### ISSUE TITLE
Aif Aiff support 

### ISSUE THREAD

**Issue by astrocycles** [Rello/audioplayer#475]
Do you intend to add Aif Aiff support as full quality player ? 

many thanks 

### Steps to reproduce the behavior
1. 
2. 
3. 

### Server configuration
**Operating system:**

**Web server:**

**Database:**

**Nextcloud/ownCloud version:** (see `/status.php`)

**Audio Player version:** (see `/settings/apps`)

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`

### Client configuration
**Browser:**

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
I need to check if the plugin used can play this format...

**Comment by r4sas** [comment]
AIF/AIFF is not supported in common browsers, only in Safari.
http://www.jplayer.org/HTML5.Audio.Support/

**Comment by astrocycles** [comment]
So it could work in Safari ?

I have tones of Aiff :(

**Comment by Rello** [comment]
Hello @astrocycles 
good news, it was pretty easy to add the aif mime type!
I could successfully test it in my installation with Safari.

only prerequisite, you need to follow these instructions to add the x-aiff mime type to Nextcloud, as it is not supported out of the box
https://github.com/Rello/audioplayer/wiki/Audio-Files-and-MIME-Types

in the `mimetypemapping.json`, just enter the following content and follow the other steps of the instructions:
```
{
	"aif": ["audio/x-aiff"]
}
```

**Comment by Rello** [comment]
Version 2.11.0 was released
