### ISSUE TITLE
Feature request: Group by artists

### ISSUE THREAD

**Issue by TheDarkTron** [Rello/audioplayer#476]
I cant find the feature to group the library by artist. It would be nice if there would be a tab on the left top for this. Like with Album, Folders and Genres.

![image](https://user-images.githubusercontent.com/19347475/84410242-365ff780-ac0e-11ea-8e00-4c1c91e2e5a0.png)

**Comment by Rello** [comment]
Hello,

I think you are looking at the wrong tool. If I am not wrong, your screenshot is from the "Music" app. This has a different focus.

AP has all the filters (including cover or list display) available
![Screenshot 2020-06-12 at 12 05 34](https://user-images.githubusercontent.com/13385119/84491986-b9805c80-aca5-11ea-96f8-c8c3b0413cbb.png)
