### ISSUE TITLE
Need Lyrics column in option section.

### ISSUE THREAD

**Issue by hdp2101** [Rello/audioplayer#478]
### Steps to reproduce the behavior

1. Can you please produce any kind of notepad where i can add the Lyrics of the song in Audio Player app in the section of option, so i would like to show the Lyrics of every songs in my audio library.

Thank you

### Additional information (optional)
Operating system: Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64

Webserver: Apache/2.4.39 (Unix) OpenSSL/1.0.2k-fips (cgi-fcgi)

Database: mysql 10.1.45

PHP version: 7.3.18

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, standard, mysqlnd, pcntl, mysqli, PDO, PDO_Firebird, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, imagick, memcached, memcache, redis, mongodb, uploadprogress, sodium, mailparse, ssh2, yaz, sqlsrv, pdo_sqlsrv, apcu, inotify, OAuth, smbclient, mcrypt, libsmbclient, ionCube Loader, SourceGuardian, xdebug

Nextcloud version: 18.0.6 - 18.0.6.0

Enabled:
 
 - audioplayer: 2.10.1
 - audioplayer_editor: 0.2.2
 - audioplayer_sonos: 1.1.1

Are you using external storage? If yes, which one: local/smb/sftp/...
No

Client configuration
Browser:
Chrome

![Ashampoo_Snap_2020 06 27_17h46m01s_005_](https://user-images.githubusercontent.com/13566445/85922233-762a0e80-b89f-11ea-896f-5cc615237409.png)

**Comment by Rello** [comment]
Hello,
do you want to show the lyrics of a song as they are stored in their ID3 tag?
or do you want to add/enter the lyrics? the last one is not possible, because I don´t have an ID3 writer in place

**Comment by r4sas** [comment]
I think he about stored lyrics.

**Comment by Rello** [comment]
Hello,
I will close this topic for now due to limited ressources
