### ISSUE TITLE
Hardware media keys (MediaSession API)

### ISSUE THREAD

**Issue by mlietze** [Rello/audioplayer#479]
Hi,

it would be very cool, if the app would support media buttons. So you can hit ⏭ or ⏮ on your keyboard to control the playback. I think it should be a quick thing to implement. 🙈 

(working) Example:
```
navigator.mediaSession.setActionHandler('nexttrack', function() {
    OCA.Audioplayer.Core.Player.actions.next()
});
```

Thanks a lot for the app and all of your work! You are awesome! 🎉

**Comment by Rello** [comment]
Hey,
I like that idea. sounds pretty simple.
let me do some tests...

**Comment by Rello** [comment]
This implements hardware keys for play/pause/stop/next/previous depending on the browser availability
https://developer.mozilla.org/en-US/docs/Web/API/MediaSession#Browser_compatibility

The playlist can be controlled via hardware keys.
When working on a different tab, the playback information is shown in the music control of the browser

![Screenshot 2020-07-12 at 20 26 00](https://user-images.githubusercontent.com/13385119/87253762-f34bab00-c47d-11ea-93d8-f0dffeba046e.png)

**Comment by Rello** [comment]
Version 2.11.0 was released

**Comment by mlietze** [comment]
Works fantastic! Thank you!!
