### ISSUE TITLE
drop soundmanager2 and bar-ui for HTML5 audio

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#481]
the old and unmaintained soundmanager2 + bar-ui libraries will be removed.
Standard HTML5 <audio> will be used

**Comment by Rello** [comment]
@r4sas 
Did you upgrade AP already? Does everything work for you?

**Comment by r4sas** [comment]
> @r4sas
> Did you upgrade AP already? Does everything work for you?

Didn't checked for updates. When I checked in 8 hours after release, it wasn't available on NC. Will do againg later today.

**Comment by r4sas** [comment]
Works for me, but current progress bar is not usable with high resolution, huge dot like in previous variant is needed.
add: `endTime` evement also need some checks to prevent printing `NaN:NaN` while track loading.
add 2: one more thing here: seconds need to be parsed with prepending zero (when lesser then 10 seconds it prints `X:6` for six seconds).

**Comment by Rello** [comment]
Ok. Thank you!

What happens with the bar in your case? Too small? I read something about resolution scaling - but I have only HD

The others: ok. Little finetuning. Will take care
The rework was quite big - the codebase is now SO MUCH smaller/simpler. Thats why I could include so many pending features. 

Happy that it works in general. 
Will look at the details...

**Comment by r4sas** [comment]
![image](https://user-images.githubusercontent.com/7023612/88102045-75c71f80-cb8e-11ea-9c6e-e7db1034ddfd.png)

That's in chromium.

add: current track position saving code sending request four times instead one.

**Comment by r4sas** [comment]
https://github.com/Rello/audioplayer/commit/555f9b8a4de6fc93125fa3b1b6906cc7e8026c03#diff-783b03491a86df59900aedf1a46bce10R175-R183
Too wrong code... I think we can use `calculateCurrentValue` because it doing same thing...

https://stackoverflow.com/a/6313008

**Comment by r4sas** [comment]
Something like this:
```
    function formatSecondsToTime (seconds) {
        if (seconds <= 0) return "00:00";
        var hours = Math.floor(seconds / 3600),
            minutes = Math.floor(seconds / 60 % 60),
            seconds = (seconds % 60),
            time = (hours !== 0 ? String(hours).padStart(2, '0')+ ":" : "") + String(minutes).padStart(2, '0') + ":" + String(seconds).padStart(2, '0');
        return time;
    }
```

**Comment by r4sas** [comment]
Ah, also volume control is not visible and not works.

**Comment by Rello** [comment]
thank you for the pull requests. they look good. I like the idea with the rounded cover!

yes, volume control did not make it into the release. will have a look.
the question is, do you thing this is actually useful at all? I never used it

**Comment by r4sas** [comment]
Sometimes it useful if didn't want mess with system volume levels when few applications with sound output works at same time (example: voice conference and music).

**Comment by r4sas** [comment]
One more bug: track info is not updating in `audio` element, browsers always shows first track info.

**Comment by Rello** [comment]
> One more bug: track info is not updating in `audio` element, browsers always shows first track info.

got it. the currentTrackIndexUiChange() is only triggered when clicking on a title - not when the playback changes. will fix it

**Comment by Rello** [comment]
fyi: the player gets confused when the playlist is sorted. I am working on this

**Comment by Rello** [comment]
Hi,
I hope I got the issues fixed not. volume is still pending

**Comment by Rello** [comment]
volume is back.
for simplicity I switched to the standard slider. the old code was so huge...
not yet 100% perfect, but getting there

![Screenshot 2020-07-28 at 21 25 13](https://user-images.githubusercontent.com/13385119/88711679-d4554600-d118-11ea-9fdf-58e51ed8659a.png)

**Comment by Rello** [comment]
@r4sas hey, do you have the chance to test the current status? I think it should be complete now

**Comment by r4sas** [comment]
I'll check it later today.

**Comment by r4sas** [comment]
> add: current track position saving code sending request four times instead one.

Still exists. Problem in updating playback status 4 times in second (at least on my PC).

one more thing: If I'm starting playing track from saved state, I'm not able seek to track begining till switch to other track and return back.

![image](https://user-images.githubusercontent.com/7023612/88808027-e3cca180-d1a1-11ea-9323-eb330f0baaa8.png)
Is here any ability to change view of slider (volume regulation button)? Doesn't match the NC style.

**Comment by Rello** [comment]
> Still exists. Problem in updating playback status 4 times in second (at least on my PC).

I did not find a usefull other formular yet to trigger the timing only once. I need to connect to the timeupdate but this is fireing more often
https://github.com/Rello/audioplayer/blob/master/js/player.js#L235-L236

> one more thing: If I'm starting playing track from saved state, I'm not able seek to track begining till switch to other track and return back.

I did not find that one. let me check. **found it. thank you**

> Is here any ability to change view of slider (volume regulation button)? Doesn't match the NC style.

looks different on your browser. Safari/Chrome for me have the rounded one and look the same. whcih NC-Style are you referring to?

**Comment by r4sas** [comment]
> I did not find a usefull other formular yet to trigger the timing only once. I need to connect to the timeupdate but this is fireing more often
> https://github.com/Rello/audioplayer/blob/master/js/player.js#L235-L236

Make something like temporary variable where you will store latest update second on call, if it != current, update, otherwise ignore call.

> whcih NC-Style are you referring to?

I'm testing in chromium, about styling I mean that this is flat button, when other buttons ans NC using rounded dots, etc. See for `input[type=range]::` with `-webkit-slider-thumb`, `-moz-range-thumb` and `-ms-thumb`.

**Comment by r4sas** [comment]
Hm, I found that my browser messing with styles, investigating now...

add: `user agent stylesheet`, integrated in browser, overwriting any styles if no `input[type="range"]` is defined.

add2:
```
[Deprecation] '-webkit-appearance: sliderthumb-horizontal' for elements other than ::-webkit-slider-thumb and ::-webkit-media-slider-thumb is deprecated and will be removed in M79, around December 2019.
[Deprecation] '-webkit-appearance: sliderthumb-vertical' for elements other than ::-webkit-slider-thumb and ::-webkit-media-slider-thumb is deprecated and will be removed in M79, around December 2019
```
Testing on 78.0.3904.97.

add3:
```css
input[type=range].volume-slider {
  -webkit-appearance: none;
}

input[type=range].volume-slider::-webkit-slider-runnable-track {
  width: 100%;
  height: 8px;
  cursor: pointer;
  background: var(--color-background-dark);
  border-radius: var(--border-radius);
}

input[type=range].volume-slider::-webkit-slider-thumb {
  border: 1px solid var(--color-border-dark);
  height: 14px;
  width: 14px;
  border-radius: 7px;
  background: #ffffff;
  cursor: pointer;
  -webkit-appearance: none;
  margin-top: -3px;
}
```

![image](https://user-images.githubusercontent.com/7023612/88831537-002b0700-d1bf-11ea-9da7-f6577f7836e8.png)

**Comment by r4sas** [comment]
https://github.com/Rello/audioplayer/blob/67adb14842e27e5f4139648e1060668650f07047/js/app.js#L792
Extra space before `)`.

**Comment by r4sas** [comment]
> add3:

Good example for all browsers: https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

**Comment by Rello** [comment]
oh wow. going out for dinner; coming back; and seeing all this stuff!?
thank you for looking at this in this level of detail. 
I really appreciate your effort and support here!

**Comment by Rello** [comment]
it looks like this on my chrome now
![Screenshot 2020-07-29 at 21 14 11](https://user-images.githubusercontent.com/13385119/88842887-83108980-d1e0-11ea-8acf-e14ddd036d35.png)

**Comment by r4sas** [comment]
Yes, it must be like this, but I dont seen how remove transparancy when not hovered.

**Comment by Rello** [comment]
do you also have this blue frame after you clicked the slider - until you click somewhere else?

![Screenshot 2020-07-29 at 22 15 26](https://user-images.githubusercontent.com/13385119/88848616-046c1a00-d1e9-11ea-80bc-3b31e1ce5395.png)

**Comment by r4sas** [comment]
See #488, that was fixed here. Also try drop cache in your browser if you already applied it.

**Comment by Rello** [comment]
ah, now. I merged the pull via my phpStorm. 
I expected it to be clever enough to apply the patch also to my local files...
I updated everything. looks clean now!

**Comment by Rello** [comment]
what do you think?
are you happy now with this? you are the quality gate for the release :-)

**Comment by r4sas** [comment]
Is `bar-ui` styles still used? 
I'm now looking in Firefox and Edge CSSs

**Comment by Rello** [comment]
hello,
yes, the bar-header still uses the old ones. I did not want to start that work for now and put it on backlog.
i need to check which ones are really required and migrate them to the styles.css
for the moment I would suggest to live with it

**Comment by r4sas** [comment]
With #489 I'm ending row of changes. I think we can do that 2.11.1.

**Comment by Rello** [comment]
thank you. I also added you as contributor to the readme and authors.md
i hope its ok for you

**Comment by r4sas** [comment]
No problems.

**Comment by Rello** [comment]
hey,
I did not check it before the release. but for it looks like this now in chrome/safari
![Screenshot 2020-07-30 at 16 30 19](https://user-images.githubusercontent.com/13385119/88935452-0df59080-d282-11ea-9b10-1371181f0a8d.png)

**Comment by r4sas** [comment]
Yup, that's what I mention in #490

**Comment by Rello** [comment]
so I will push a .2 quickly

**Comment by Rello** [comment]
![Screenshot 2020-07-30 at 16 39 00](https://user-images.githubusercontent.com/13385119/88936407-2d40ed80-d283-11ea-938d-47568b278435.png)
can you check the dark-mode?
white mode looks good now

**Comment by r4sas** [comment]
ohh... That's strange... Let me check.
