### ISSUE TITLE
Track name/artist is not correctly recognized in EXTINF

### ISSUE THREAD

**Issue by r4sas** [Rello/audioplayer#485]
### Actual behavior
AP incorrectly detects track name/artist if commas present in EXTINF tag.

### Steps to reproduce the behavior
1. Create playlist with track info containing commas
2. Open it in AP

### Additional information (optional)
Example of incorrectly parsed track tag:
```m3u
#EXTINF:250,Kaori Sadohara, Ai Hirosaka, Mami Kosuga, Kaoru Mizuhara, Cho - Sakurai sensei no dokidoki seito shidou
Kaori Sadohara, Ai Hirosaka, Mami Kosuga, Kaoru Mizuhara, Cho - Sakurai Sensei No Dokidoki Seito Shidou.m4a
```

I think we must detect if we working with extended info tag and parse it in such order:
1. find `#EXTINF:` at line beggining, cut it
2. split row by first comma (get length)
3. find ` - ` (with spaces around)
4. resulting first and second part use as artist and title

### Server configuration
**Audio Player version:** (see `/settings/apps`)
2.11.0

**Comment by Rello** [comment]
Hi,
you are correct. the current setup was wrong. I corrected it
in the example, the 2 marked rows are found. the separation is now by " - " according to the M3U-Specification

one record of a valid file with EXTINF and one without
if EXTINF is given, the metadata from the AP database is overwritten in the displayed list

![Screenshot 2020-07-28 at 22 10 16](https://user-images.githubusercontent.com/13385119/88716372-43ce3400-d11f-11ea-801e-18b9a36e93bb.png)

**Comment by Rello** [comment]
sorry for the late comment here. 
I just noted that the message was sitting here in draft since 2 days. i hope it will still work as expected
