### ISSUE TITLE
theming issues

### ISSUE THREAD

**Issue by xchoice** [Rello/audioplayer#486]
When using nextcloud dark theme, the audio player controls are still black, so you end with black on black(lighter black, but still hard to see). Specially the volume, repeat and shuffle controls.

Here an image:
[https://imgur.com/a/NtfaTlw](url)

**Comment by xchoice** [comment]
Oh I did not realize there was an update, I took the screenshot using 2.10.
But now in 2.11, the volume control is gone, and the repeat control is still black.

**Comment by Rello** [comment]
Hello,
I will check. The volume was temporary disabled with the new release. Some fix is in progress

**Comment by Rello** [comment]
Hello,
repeat works. a little bug is still there. the single repeat shows a little "1" in the white theme. somehow this does not yet work.
volume is next...
