### ISSUE TITLE
Version 1.1.0 doesn't work error 15% scan

### ISSUE THREAD

**Issue by SparkYDevtk** [Rello/audioplayer#49]
Sunday Popcorn (Radio edit) - BANANAFOX 15% (74/465)

log

Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_audioplayer_genre` (`user_id`,`name`) SELECT ?,? FROM `oc_audioplayer_genre` WHERE `user_id` = ? AND `name` = ? HAVING COUNT(_) = 0' with params [\"SparkY\", \"\xff\xfe\", \"SparkY\", \"\xff\xfe\"]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xFF\xFE' for column 'name' at row 18","Code":0,"Trace":"#0 \/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\n#1 \/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/media\/Store\/www\/Cloud\/lib\/private\/DB\/Connection.php(209): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO`oc...', Array, Array)\n#3 \/media\/Store\/www\/Cloud\/lib\/private\/DB\/Adapter.php(113): OC\DB\Connection->executeUpdate('INSERT INTO `oc...', Array)\n#4 \/media\/Store\/www\/Cloud\/lib\/private\/DB\/Connection.php(247): OC\DB\Adapter->insertIfNotExist('_PREFIX_audiopl...', Array, Array)\n#5 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Db\/Db.php(149): OC\DB\Connection->insertIfNotExist('_PREFIX_audiopl...', Array, NULL)\n#6 \/media\/Store\/www\/Cloud\/apps\/audioplayer\/controller\/scannercontroller.php(780): OC\AppFramework\Db\Db->insertIfNotExist('_PREFIX*audiopl...', Array)\n#7 \/media\/Store\/www\/Cloud\/apps\/audioplayer\/controller\/scannercontroller.php(598): OCA\audioplayer\Controller\ScannerController->writeGenreToDB('\xFF\xFE')\n#8 [internal function]: OCA\audioplayer\Controller\ScannerController->scanForAudios()\n#9 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#10 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')\n#11 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/App.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')\n#12 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\AppFramework\App::main('ScannerControll...', 'scanForAudios', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\n#14 \/media\/Store\/www\/Cloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\n#15 \/media\/Store\/www\/Cloud\/lib\/base.php(891): OC\Route\Router->match('\/apps\/audioplay...')\n#16 \/media\/Store\/www\/Cloud\/index.php(39): OC::handleRequest()\n#17 {main}","File":"\/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}

**Comment by Rello** [comment]
Hello,
There is an issue with a special character combination in one of your files in the genre ID3, which is technically wrong. 

Can you check the file with an ID3 tool like iTunes or so and fix the genre?

I need to catch this exception somehow later, when i found a way

**Comment by Rello** [comment]
can you please provide the file causing the issue for debugging?

**Comment by Rello** [comment]
https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by xraMsamohT** [comment]
> ID3 tool like iTunes or so

[Mp3tag ](http://www.mp3tag.de/en/index.html)

**Comment by Rello** [comment]
Hello,

can you please locally test the code snippet postet here?
https://github.com/JamesHeinrich/getID3/issues/61#issuecomment-159636947

The error indicates an issue with the iconv implementation in your PHP installation.
these characters should be filtered out by the getID3 library when working correctly.

Let me know

**Comment by Rello** [comment]
Hey,
any news?

**Comment by Rello** [comment]
Hello,
Can you please let me know if you could validate your local installation?
I would like to process this issue. 
Thanks

**Comment by SparkYDevtk** [comment]
Hey. I'm sorry did not have time.
Can scan all files. If I delete all of the folders to the Trash. Next to restore by turns. And continue to scan.

That file and log an error when a full cloud scan MP3 files.
Milkshake (Radio Edit) - Dony Feat. Adena 36% (163/443)
file
http://sparkydev.tk:81/index.php/s/5h1yh9IWVS4rRsO
log

Exception: {"Exception":"BadMethodCallException","Message":"Not in batch","Code":0,"Trace":"#0 \/media\/Store\/www\/Cloud\/lib\/private\/Files\/Utils\/Scanner.php(143): OC\Files\Cache\Propagator->commitBatch()\n#1 \/media\/Store\/www\/Cloud\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php(87): OC\Files\Utils\Scanner->backgroundScan('')\n#2 \/media\/Store\/www\/Cloud\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php(111): OCA\Files\BackgroundJob\ScanFiles->runScanner(Object(OC\User\User))\n#3 \/media\/Store\/www\/Cloud\/lib\/private\/BackgroundJob\/Job.php(52): OCA\Files\BackgroundJob\ScanFiles->run(NULL)\n#4 \/media\/Store\/www\/Cloud\/lib\/private\/BackgroundJob\/TimedJob.php(53): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#5 \/media\/Store\/www\/Cloud\/cron.php(144): OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#6 {main}","File":"\/media\/Store\/www\/Cloud\/lib\/private\/Files\/Cache\/Propagator.php","Line":145} 
Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_audioplayer_albums` SET `year`= ?, `artist_id`= ? WHERE `id` = ? AND `user_id` = ?' with params [\"artMkiss 2012\", \"755\", \"340\", \"malice\"]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'artMkiss 2012' for column 'year' at row 1","Code":0,"Trace":"#0 \/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\n#1 \/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_audi...', Array)\n#2 \/media\/Store\/www\/Cloud\/lib\/private\/legacy\/db\/statementwrapper.php(73): Doctrine\DBAL\Statement->execute(Array)\n#3 \/media\/Store\/www\/Cloud\/apps\/audioplayer\/controller\/scannercontroller.php(752): OC_DB_StatementWrapper->execute(Array)\n#4 \/media\/Store\/www\/Cloud\/apps\/audioplayer\/controller\/scannercontroller.php(621): OCA\audioplayer\Controller\ScannerController->writeAlbumToDB('artMkiss 2012', 'artMkiss 2012', '755')\n#5 [internal function]: OCA\audioplayer\Controller\ScannerController->scanForAudios()\n#6 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')\n#8 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/App.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\audioplayer\Controller\ScannerController), 'scanForAudios')\n#9 \/media\/Store\/www\/Cloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\AppFramework\App::main('ScannerControll...', 'scanForAudios', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#10 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\n#11 \/media\/Store\/www\/Cloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\n#12 \/media\/Store\/www\/Cloud\/lib\/base.php(891): OC\Route\Router->match('\/apps\/audioplay...')\n#13 \/media\/Store\/www\/Cloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/media\/Store\/www\/Cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}

**Comment by SparkYDevtk** [comment]
If repeat scanning after errors, then it will succeed

**Comment by Rello** [comment]
Hello,
the scanner was adjusted to handle the wrong ID3 tag (non integer value) properly in future.
will be part of the next release
