### ISSUE TITLE
[Feature Request] Preload next track

### ISSUE THREAD

**Issue by r4sas** [Rello/audioplayer#494]
Requesting for next track preloading for smooth listening.

Some useful links:
https://stackoverflow.com/a/4138759
https://www.w3schools.com/tags/att_audio_preload.asp

**Comment by Rello** [comment]
Hi,
I am still thinking about this point. I think the added value would be quite big and a big selling feature.
"the other" player also has the request, but did not manage to implement this.

...the first link will be the right direction I think.
My idea is to use 2 permanent <audio> tags and jump the playback between both of them. lets see

**Comment by r4sas** [comment]
I think same way. Using JS update second one <audio> and start preload when left time is lesser that ~15 seconds, and after track end event switch to next one.

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.

**Comment by Rello** [comment]
fyi - this feature was recently added

https://github.com/Rello/audioplayer/issues/605
