### ISSUE TITLE
Multiple genre's not correctly filtered/attributed to track.

### ISSUE THREAD

**Issue by paddywaan** [Rello/audioplayer#496]
### Expected behaviour
When I enter multiple genre's to the ID3 tag for an audio file like so: `test1; test2; test3;`
![Rello Multi-genre](https://user-images.githubusercontent.com/70168382/91257687-74c37800-e762-11ea-8c2c-8072c56cc192.png)
I expect that when I filter by genre's, that the same track will appear in three different categories: `test1`, `test2`, and `test3`.

### Actual behavior
Only a single genre is attributed to the media:
![Rello ActualGenres](https://user-images.githubusercontent.com/70168382/91257931-fca98200-e762-11ea-97b2-a0dfede89f63.png)

### Steps to reproduce the behaviour
1. Edit ID3Tag of audo file with `Mp3Tag` or other audio software.
2. Assign multiple genre's, delimitered by a `;` followed with a space.
3. Sync the file to a nextcloud share.
4. clear the nextcloud Rello player of any previous files via "Reset Library".
5. Scan the library and find one file.
6. Observe a single genre attributed to a single file.

### Server configuration
**Operating system:**
Ubuntu 16.04

**Web server:**
nginx

**Database:**
MariaDB?

**Nextcloud/ownCloud version:** (see `/status.php`)
19.01

**Audio Player version:** (see `/settings/apps`)
2.11.2

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**
Webkit/Chrome/Brave

#### Nextcloud/ownCloud log
None submitted. N/A

#### Web server error log (optional)
None submitted. N/A

#### Browser log (optional)
Nolne submitted, N/A

**Comment by Rello** [comment]
Hello,
thank you for opening a request.
your finding is correct. due to its technical design, there can be only one genre per title as the database has a 1:1 track:genre mapping.

To change this would be significant rework of the app.
But as this request is very limited (never mentioned since all the years) I can not do the rework at the moment as the time is limited.

Sorry for that...
