### ISSUE TITLE
Problem to scan on SFTP external storage

### ISSUE THREAD

**Issue by Mimoza** [Rello/audioplayer#498]
### Actual behavior
Impossible to scan a collection on SFTP external storage, by web interface or CLI.

### Steps to reproduce the behavior
1. Configure «external storage support» with SFTP
2. Clear music librairy in «Audio Player» app
3. Start a new scan

### Additional information (optional)

- I've tried on CLI to see more information, here the result : 

<summary>CLI comand : $ su -s /bin/ksh www  -c 'php-7.3 /path to nexcloud/occ audioplayer:scan username'</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Start scan for username
Start processing of audio files
Scanned Folder: /<username>/files/Son
Total audio files: 14408
Checking audio files to be skipped
Final audio files to be processed: 14408
Total stream files: 73
Checking stream files to be skipped
Final stream files to be processed: 0
Start processing of audio files
Attention: Only slow indexing due to server config. See Audio Player wiki on GitHub for details.
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/ Tri Yann/Tri Yann - Abysses/Tri Yann - 15. Bonus Abysses.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/Jacques brel/Jacques Brel- Amsterdam.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/Ceux Qui Marchent Debout/Jackpot/CQMD-Just One More.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/F.F.F/Vivants- Live/FFF-Mauvais Garçon.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/Portishead/1997 - Portishead/03 - Undenied.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/Gainsbourg/Aux armes et caetera-vol8/08-Relax baby be cool.mp3
       Error with getID3. Does not seem to be a valid audio file
   /username/files/Son/Red Hot Chilli Pepper/1985 - Freaky Styley/14. Yertle The Turtle.mp3
[…]
   /username/files/Son/AC-DC/1986 - 13 - Who Made Who/1200-acdc-who_made_who-2001-sta.m3u
   /username/files/Son/AC-DC/1988 - 14 - Blow Up Your Video/1300-acdc-blow_up_your_video-2001-sta.m3u
   /username/files/Son/AC-DC/1990 - 15 - Razor's Edge/1400-acdc-the_razors_edge-2001-sta.m3u
   /username/files/Son/AC-DC/1995 - 17 - Ballbreaker/1600-acdc-ballbreaker-2001-sta.m3u

Audios found: 14481
Duplicates found: 0
Written to library: 73
Albums found: 0
Errors: 14408
```
It seem that the «Written to library: 73» are m3u files.

- I've also tried with the other «Music» app and the indexing work well

- i've tried with some copy of these files in other nextcloud folder (not external) and it's ok

I've seen the other issue [here](https://github.com/Rello/audioplayer/issues/448). Like the collection was on a normal folder before, i investigate if it's related to cache problem.

### Server configuration
**Operating system:**
OpenBSD 6.7

**Web server:**
Nginx

**Database:**
PostgreSQL 12

**Nextcloud/ownCloud version:** (see `/status.php`)
19.02

**Audio Player version:** (see `/settings/apps`)
2.11.2

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
SFTP

### Client configuration
**Browser:**
FireFox 80.0

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
did you find out anything more?
an external storage file is not any different to an internal file.
I just tried it with an SMB (first) and FTP (second) and both were indexed
```
/admin/files/FTP/ABBA – Happy New Year.mp3
/admin/files/music/formats/example M4A.m4a
```
did you go into the folder in the files app first, to make sure the filecache is up to date?

**Comment by christianaubry** [comment]
Hi,
  Also unable to scan from SFTP, I am getting this using cli
```
Start processing of audio files
Audios found: 5634
Duplicates found: 0
Written to library: 0
Albums found: 0
Errors: 5634
An unhandled exception has been thrown:
TypeError: Return value of "OCA\audioplayer\Command\Scan::execute()" must be of the type int, "null" returned. in /var/www/html/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#1 /var/www/html/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/html/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#3 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#4 /var/www/html/console.php(100): OC\Console\Application->run()
#5 /var/www/html/occ(11): require_once('/var/www/html/c...')
#6 {main}
```
What is the link with the mail app ?


NextCloud 20.0.2
Audio Player 3.0.0
Ubuntu 20.04.1

Hope it could help
Regards
Christian

**Comment by Rello** [comment]
hello,
is the issue still existing? the error is coming from mails - not AP
