### ISSUE TITLE
Jump display to current song

### ISSUE THREAD

**Issue by jimbolaya** [Rello/audioplayer#499]
### Actual behavior
Select "Titles" and "All Titles". Turn on "Shuffle Playlist" and hit Play.

The currently playing song shows at the top, but is not shown in the list of visible songs (whatever fits in the browser window). However, I have 3000+ songs and the song being played doesn't show up in this list of visible songs unless by chance.

If I want to star a song or see details, I have to search for it, either by Nextcloud or by the browser search.

### Additional information (optional)
This is probably a feature request, but it would be really nice for the list to show the currently playing song to populate in the visible part of the browser. 

### Server configuration
**Operating system:** Debian 10 Buster AMD64

**Web server:** Apache2

**Database:** MariaDB

**Nextcloud/ownCloud version:** 18.0.8.2

**Audio Player version:** 2.11.2

**Are you using external storage? If yes, which one:** `local`

### Client configuration
**Browser:** Firefox

**Comment by Rello** [comment]
Hello
thank you for the feedback.

do you mean that the list is so long, that the random song is somewhere outside and you expect the player to scroll to that position?

**Comment by jimbolaya** [comment]
I was hoping for that, I think it would be a cool feature.

**Comment by Rello** [comment]
ok, understood. I will check. 
I think it was in there already. will let you know

**Comment by Rello** [comment]
its solved with the next release

**Comment by jimbolaya** [comment]
Sweeet! Thank you.
