### ISSUE TITLE
Opus files not recognized in files app

### ISSUE THREAD

**Issue by poVoq** [Rello/audioplayer#500]
### Actual behavior
The instant playback of music in the files app seems to work fine for .mp3 files, but .opus files are not recognized. Playing .opus files in the audio player app itself works though.

### Server configuration
**Operating system:** Official docker image

**Database:** MySQL

**Nextcloud/ownCloud version:** (see `/status.php`) 19.03

**Audio Player version:** (see `/settings/apps`) latest

**Are you using external storage? If yes, which one:** `local/smb/sftp/...` no

### Client configuration
**Browser:** Firefox latest on Linux

**Comment by Rello** [comment]
just tried it. for me it works. 
is the issue still open?

Audioplayer App:
![Bildschirmfoto 2020-11-18 um 20 48 39](https://user-images.githubusercontent.com/13385119/99580125-70b09a80-29df-11eb-84e9-b77334ab572c.png)

Files App:
![Bildschirmfoto 2020-11-18 um 20 49 09](https://user-images.githubusercontent.com/13385119/99580225-832ad400-29df-11eb-94d1-46e080cdc67d.png)

**Comment by poVoq** [comment]
Odd, now it works. Not sure what changed since then.

**Comment by Rello** [comment]
good to know. 
thank you!
