### ISSUE TITLE
Limit Audio Player to specific user groups

### ISSUE THREAD

**Issue by essys** [Rello/audioplayer#501]
### Actual behavior
It is not possible to limit Audio Player to user groups.

### Steps to reproduce the behavior
1. Click on app Audio Player in app overview (admin frontend).
2. Try to limit to specific user groups
3. Error pop-up appears.

### Additional information (optional)
If it should not be possible then why is the functionality available?
![06 10-21-41](https://user-images.githubusercontent.com/7117619/95252073-c27cd700-081c-11eb-867f-de87cbf426d8.png)

### Server configuration
**Operating system:**
Linux

**Web server:**
Apache

**Database:**
MySQL

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.3

**Audio Player version:** (see `/settings/apps`)
2.12.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**
Firefox 80.0.1

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

```json
Insert your Nextcloud/ownCloud log here
```

</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>

```
Insert your web server log here
```

</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by essys** [comment]
Addendum:
After checking other stuff I came back to the app overview and realised the option to limit the app to groups is gone.

Could this be a bad behaviour of Nextcloud itself?

**Comment by Rello** [comment]
Hello,
the option should never be there. the app us using the filesystem as the backend. due to this, the app can not be limited and this option should never come up. must have been some kind of glitch

**Comment by essys** [comment]
@Rello thanks for the reply.
Yes I agree this is most probably a glitch in Nextcloud itself.
But it would be nice to limit this app to groups but I understand the limitations.

Issue can be closed.
