### ISSUE TITLE
Icons not visible with dark theme

### ISSUE THREAD

**Issue by Enhakiel** [Rello/audioplayer#502]
### Actual behavior
Icons are black with dark grey background (under firefox not with chrome)

### Steps to reproduce the behavior
1. Use firefox
2. Go to settings -> accessibility -> check dark theme
3. Go to media player

### Additional information (optional)
![icons](https://user-images.githubusercontent.com/6618150/95371097-0550b480-08da-11eb-9e8d-3050561ae97c.png)

### Server configuration
**Operating system:**
Debian

**Web server:**
Apache2

**Database:**
MySql

**Nextcloud/ownCloud version:** (see `/status.php`)
20.0.0

**Audio Player version:** (see `/settings/apps`)
 2.12.0

**Comment by Rello** [comment]
![Bildschirmfoto 2020-10-07 um 21 06 49](https://user-images.githubusercontent.com/13385119/95376193-0507e780-08e1-11eb-96da-702bf5746e61.png)

hi,
can you please refresh the page?
I had some occurrence where the icons came up after the second refresh. did not find out yet why it does not work on the very first start for everyone.

please let me know

**Comment by Enhakiel** [comment]
Hi,
I totally reinstall my server yesterday and now it's working on the first time. I didn't tried F5 but navigating from AudioPlayer to another app then back to the player didn't change it.

**Comment by Rello** [comment]
ok, good to hear that it is solved.
A assume it is related to the caching of the icons which is generated in NC. this is regenerated with every update so it might take a little longer than the first start of the app.
at the second start the old/incomplete is still cached. if you do a full refresh, the up to date version is loaded from the server

**Comment by Enhakiel** [comment]
Thanks for your reactivity

**Comment by Enhakiel** [comment]
Sorry, made a mistake, I restore a backup of nextcloud 19, after updating it to version 20 icons became black again, and refreshing the page doesn't change anything

**Comment by Rello** [comment]
let me check

**Comment by Enhakiel** [comment]
Solved!  I switched to regular theme, then the icons was white on white, but this time hitting refresh made them grey, switched back to dark theme and icons are ok.
This is more related to the update of nextcloud not your app, few other icons were not correct.
You can close it ;)
