### ISSUE TITLE
Duplicate entries.

### ISSUE THREAD

**Issue by ethancedwards8** [Rello/audioplayer#503]
# Actual behavior
Scanned a folder of audio files, then moved it and scanned it again but there are entries for both

### Steps to reproduce the behavior
1. Have an audio folder
2. Scan it
3. Move it
4. Scan it again

### Additional information (optional)
I'm on a Raspberry Pi

### Server configuration
**Operating system:**
Ubuntu 20.04 Rpi edition with Nextcloud inside of Docker

**Web server:**
Apache?

**Database:**
postgresql

**Nextcloud/ownCloud version:** (see `/status.php`)
20.0.0.9

**Audio Player version:** (see `/settings/apps`)
2.12.0

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No

### Client configuration
**Browser:**
Firefox 81

#### Nextcloud/ownCloud log
<details>
<summary>Nextcloud/ownCloud log (`/data/[nextcloud|owncloud].log`)</summary>

</details>

**Comment by ethancedwards8** [comment]
I fixed it, `sudo -u www-data ./occ audioplayer:reset --all`, closing.

**Comment by Rello** [comment]
Hello,
the reset can also be done within the UI.
in general, this topic is "expected". Audio Player is tracking deleted files, but not moved ones. would need to be implemented but I think the case is not that frequent

thank you for reporting and supporting the app

**Comment by ethancedwards8** [comment]
Okay, thank you, nice to know.
