### ISSUE TITLE
Feature request: 2x speed

### ISSUE THREAD

**Issue by ethancedwards8** [Rello/audioplayer#506]
Hi there,

I think a good feature for audioplayer would be a 2x audio speed. Maybe a button beside of the shuffle and repeat buttons.

**Comment by el-vishal** [comment]
A related request is already made here: #497

**Comment by Rello** [comment]
Hello,
I am thinking about the UI. technically its 2 lines of code. its a question on where to include this - even so the user base will be very limited for this.

one idea would be something like this behind a settings-icon. 
https://vimeo.zendesk.com/hc/article_attachments/115021525107/playback.png

But this would require a lot more programming and the time is limited.

A very quick - even so not so nice visual - would be to include a simple dropdown in the settings in the lower left.
What about your use case? would this help you if it can be implemented like this quicker?

![Bildschirmfoto 2020-11-18 um 12 25 50](https://user-images.githubusercontent.com/13385119/99524756-32908800-2999-11eb-8671-2a0e1ed080e9.png)

**Comment by Rello** [comment]
@martineizayaga lets continue here...

**Comment by r4sas** [comment]
But why not add button in player bar?

**Comment by Rello** [comment]
Hi,
because it needs to be flexible. 0.5, 1, 2 at least. so some kind of popup with a selection.
One more button will make the bar smaller again. and with 20.000 users, there seem to be 2 requests for this.
its a question of clean UI and reduce it to the minimum.

another idea would be to put also the other 2 controls on the right then into a popup behind a settings-wheel

**Comment by Torenga** [comment]
>there seem to be 2 requests for this.

3 requests. 🤗

IME speed adjustments are exclusively used for audiobooks, podcasts and other longer form spoken-word audio files. "a simple dropdown in the settings in the lower left" would keep it available but out of the way, sounds like a long-term solution to me.

So would a dedicated settings button in the player visuals as well but... My use case is AP exclusively for spoken word content, but without knowing any metrics I guess most people use it for music or mixed content. With that in mind, I don't think a speed adjustment button should be front and center.

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
