### ISSUE TITLE
Feature request: Search box

### ISSUE THREAD

**Issue by el-vishal** [Rello/audioplayer#507]
Hello

Is it possible to add a search box in the to-do features roadmap, to search for a specific song?

Thanks

**Comment by Rello** [comment]
Hello,
the standard search of Nextcloud (until 19) works also for the Audioplayer.
NC20 needs some tweak to support it.
can you try?

**Comment by el-vishal** [comment]
Hello @Rello I can confirm standard search working for NC (v20.0.1) but the search results redirects to Files

My feature request was to search it among the (cached?) audio list and play from there quickly.

Thanks

**Comment by Rello** [comment]
correct. NC20 changed the search box.
I will need to adjust the coding for NC20. NC19 did work integrated

**Comment by Rello** [comment]
done. part of next update
