### ISSUE TITLE
Use IIconSection instead of ISection for Nextcloud 21 compatibility

### ISSUE THREAD

**Issue by MorrisJobke** [Rello/audioplayer#508]
With NC 21 we will remove the interface `OCP\Settings\ISection` in favor of the `IIconSection` one that is available since NC 12. It only has one additional method that needs to be implemented: `getIcon()`.

@Rello Mind to update your app to continue working with Nextcloud 21?

See https://github.com/nextcloud/server/pull/23770

**Comment by Rello** [comment]
Hello @MorrisJobke 
thank you for the hint!
actually I am using the IIconSection already.
The leftover of ISection was in one file which I kept for owncloud compatibility. Did not know it was still there.
It is dropped now.

thank you for including me in this warning!

**Comment by MorrisJobke** [comment]
Thanks for fixing it that fast 👍
