### ISSUE TITLE
Resume-position not working

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#509]
Maybe this should be a separate issue, but it's directly related to this feature.

Remembering position and resuming doesn't work on my NC19.0.4 - Audio Player 2.12.0 setup. Tried on both FF/Chromium, with MP3 and OPUS. Unless there's a user error on my part ofc.

When exiting the AP and reopening, the player is empty

It's a great sounding feature that I hope I can get help to get working.

>current implementation workflow: The position is only stored for the LAST played title

If possible I would like per track position. I switch between several audiobooks (each book is a single file) and long-runtime podcasts, having a reset every time I switch isn't ideal for my use case.

_Originally posted by @Torenga in https://github.com/Rello/audioplayer/issues/288#issuecomment-727223226_

**Comment by Rello** [comment]
Hi @Torenga

thank you for reporting. there seems to be a bug. the position is stored, but not properly reused after restarting. 
let me have a look

**Comment by Rello** [comment]
Hello,
do you have some more details to reproduce the issue?
where do you exactly click?
I just tested again in NC19 and NC20 and it is working in all combinations

**Comment by Torenga** [comment]
>do you have some more details to reproduce the issue?

I did the exact same thing, but now it's working:

1. Create new browser profile to ensure no add-ons is the cause
2. Log in, open AP, start playing a single file, make sure it runs for more than 10 seconds
3. Close the browser, restart, log-in, open AP

AP 2.12:

4. Opens last viewed category/artists/album etc., not defaulting to a view of last played file. Playing previous single file restarts the track.

AP 2.13

4. Opens "Albums", marks last played track with a speaker icon, pressing the track resumes where I left off. Works as intended.

It seems to me splitting the codebase for 19 and 20 did something, but I'm not saying it's not PEBKAC... Thanks for trying to fix it, and definitively thanks for the great audio app!

**Comment by Rello** [comment]
really strange.
but nice that it works. thank you for reporting back
