### ISSUE TITLE
Ampache support

### ISSUE THREAD

**Issue by e-alfred** [Rello/audioplayer#51]
Hello,

do you intend to support Ampache like in the old Music app? This could be useful to not have to sync all the music on a device using the sync client, instead only those played back and the playlist.

Thank you

**Comment by Rello** [comment]
Hello,
Actually this was one of rhe main features - not to have any backends which require maintenance and make the app complicated. 

So to be honest, not on the planned features right now. 
Sorry

**Comment by michaelarlt** [comment]
Why you Guys not just using the plugin puplished over there?
https://github.com/owncloud/music/releases
it is an open plugin for owncloud and the far better nextcloud. This plugin is working flawlessly for me on my nextcloud server

**Comment by HLFH** [comment]
@michaelarlt Are you kidding? https://github.com/owncloud/music/issues/90 

It has been 4 years that the ownCloud Music plugin does not work.
