### ISSUE TITLE
 Audio player app corrupts the standard Nextcloud search function

### ISSUE THREAD

**Issue by brievenbusalex** [Rello/audioplayer#511]
### Actual behavior
When the audio player app is enable the standard Nextcloud search function does not work anymore.

The error log produces:
Exception: Argument 1 passed to OCA\audioplayer\Search\Provider::__construct() must implement interface OCP\IL10N, array given, called in /var/www/html/nextcloud/lib/private/Search.php on line 117

### Steps to reproduce the behavior
1. Enable Audioplayer app 2.13.0 in Nextcloud
2. Do a standard search for some text in the root of Nextcloud
3. Search stopped, hangs with message "search other places..."

### Server configuration
**Operating system:**
Centos 7

**Web server:**
Apache 2.4.6

**Database:**
Mariadb

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.5

**Audio Player version:** (see `/settings/apps`)
2.13.0

### Client configuration
**Browser:**
Chrome

**Comment by Rello** [comment]
will check.
thank you for the report

**Comment by Rello** [comment]
Hello @brievenbusalex 
do you have the possibility to test this fix, or are you using the standard appstore-updates?

**Comment by brievenbusalex** [comment]
Hello Rello,

I have tested the 2.13.1 in a test environment, and it's working fine now, the audioplayer works, aswell as the standard search is working again.

Thanks!
Alex

**Comment by Rello** [comment]
thank you!
will push the update today
