### ISSUE TITLE
Do not want yet another app tab at top

### ISSUE THREAD

**Issue by TurkeyMan** [Rello/audioplayer#512]
I'm not sure how nextcloud all fits together, but it has a serious problem with an app tab overload on the top nav bar.

What I want from the audio plugin, is to click on a file in the file browser, and it plays the thing... which does work, albeit with a pretty ugly UI experience; it places the little playing icon, and clicking again makes it stop, but don't click on the playing icon itself, otherwise instead, it will show the side panel with file properties... not the most polished experience, but the functionality is there.

What I also get is an audio player tab at the top to do things like album/playlist management. I do not want this; there are too many app tabs, and this one is not interesting to me.
Can I configure this app to only include the preview function?

I'm sure there are users who will appreciate the media player tab, but I'm focused in keeping my nextcloud instance slim and minimal, such that it doesn't overwhelm my non-tech-savvy users with noisy and confusing UI.

**Comment by kesselb** [comment]
> What I want from the audio plugin, is to click on a file in the file browser, and it plays the thing..

Nextcloud 21: https://github.com/nextcloud/viewer/pull/617

**Comment by TurkeyMan** [comment]
Oh wow, that's well timed.
Thanks!
