### ISSUE TITLE
Volume slider size

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#516]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
The control bar displaying the playback position and volume expands to about the width of the browser window, but the space is (in my personal opinion) not used ideally. On my screen (1366x768), the volume slider has a size of just about **2.5%** of the size of the playback position. It can be difficult to adjust, and I feel it would be more important to be precise with volume than with playback position.

### Additional information (optional)
![Control bar with small volume slider](https://user-images.githubusercontent.com/9149359/103768627-23d26300-5023-11eb-9519-04479ee1fbbe.png)

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
Hello,
all elements have the same width for cosmetically reasons.
did you try to use the keyboard keys (up/down) if you want to adjust the volume? does this work better for you?

**Comment by jojosoft** [comment]
I see, so that the volume slider just takes up as much space as (for example) the play, next and previous buttons? I personally would not recommend to design it like this, since the volume slider is used for much more interaction than just a button press or toggle. Maybe one could make it "three UI element widths" wide? I tried adjusting its value using the up and down keys, but for that to work, it needs focus first. (And because it's so small, it's hard to click and focus without completely changing the current song's volume...)

**Comment by Rello** [comment]
I set it to double width.
the key is a global listener. it will also work without focus. same as space(play/pause) and right/left(back/forward)

![Bildschirmfoto 2021-02-17 um 10 04 59](https://user-images.githubusercontent.com/13385119/108180962-a280ec80-7107-11eb-8c89-f6f5af2b70a2.png)

**Comment by jojosoft** [comment]
Thank you! Awesome. I first tried the up and down arrow keys, but they are not working for me, sorry. It's strange, the global listeners for play and pause (spacebar) and next and previous (left and right arrow keys) are both working! Only the volume does not change. Should I open a separate issue for that?

The only remaining thing about the volume slider would be having increments of 0.05 instead of 0.1, as mentioned in #517. Would you be up for also taking that one in? Thanks for looking into it..!
