### ISSUE TITLE
Remember playback volume

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#517]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
The volume slider starts at 1 by default (after reloading the site) and is configured to allow steps of 0.1 units. It's just a small detail, but it would probably increase most user's experience to have it start at 0.5 (or even remember the last value!) and also allow for steps of maybe 0.05. Most of modern music has been strongly compressed with regards to dynamics, so for those songs, users will usually only have a choice between 0.1, 0.2, 0.3 and 0.4 if they don't want to reduce the system volume for all applications in their operating system. (And want to keep their hearing. :wink:)

### Steps to reproduce the behavior
1. Open Audio Player, start playback of any song and adjust the volume
2. Wait a bit to make extra sure that no "delayed" AJAX request is lost
3. Close the tab in which Audio Player was loaded
4. Open Audio Player and see how the volume is back at 1 again

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
the volume is actually saved and reused during restart.
can you double check if it is really not working? I can check later on my side

**Comment by jojosoft** [comment]
Thank you! I have adjusted my description to contain the steps I follow to reproduce the behavior.
