### ISSUE TITLE
favorite star not showing

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#518]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
I like the star feature very much, so it was sad to see that the stars only get (loaded and (?)) displayed for an album if there is currently a track being played back from it. Since the star flag is probably just a boolean for each track, I would very much appreciate it if the star information would always be transferred together with the track name.

### Steps to reproduce the behavior
1. Play any track from a test album
2. Mark another track of the test album with a star
3. Play any track from any other album
4. See how the stars are only displayed for the album that currently has a track playing.

### Additional information (optional)
I never used the 5-star-system of iTunes because of the mental load that occurs if I am asked to specify why a song is a 3-star song instead of a 2-star song. It wouldn't be in my collection if I didn't like it. :thinking: However, the binary system in Audio Player made me actually mark the "very good" songs (binge-worthy) with a star! Hopefully this feature will always be there.

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
solved with the next release

**Comment by Rello** [comment]
@jojosoft 
did you upgrade to NC20 already? because the AP-Version for NC19 is not maintained due to double efforts

**Comment by jojosoft** [comment]
Good point. I tried to avoid Nextcloud 20 until now because so many things changed, so I'm still on version 19.0.7. I wasn't aware that there are separate versions of Audio Player for different Nextcloud releases. Maybe I should upgrade this month...

**Comment by Rello** [comment]
really? what don´t you like?
I went NC20 immediately with no issues

...they changed some underlaying basics in NC20 which are not backwards compatible.
to push the changes also in the NC19, I would need to rebase changes. but my spare time is a little limited there...

**Comment by jojosoft** [comment]
It just seemed like a huge change in direction, and some experienced members of the community seemed to see [some problems](https://help.nextcloud.com/t/any-assurance-that-the-code-wouldnt-be-as-bloated-and-buggy-as-microsoft-software/96220) with that. There were also quite many problem reports in the forum (maybe just my imagination that they were more when Nextcloud 20 was new), so I didn't want to spend time on it until now. From the outside it looks nice, so I might really just try upgrading now and test it a bit! Of course, you don't have to do a rebase for Nextcloud 19, I'm already extremely thankful for your main development efforts on Audio Player! Keep it up! :+1:

**Comment by Rello** [comment]
that sounds like a plan.
I also have to put time towards the Analytics app...
