### ISSUE TITLE
remove speaker icon to prioritize favorite star

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#519]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
I agree that the currently played track has to be marked in the track list somehow, but I think it would be enough if it was just the bold title. The problem with replacing the star ("favorite flag") in front of it is that user's cannot see or change the flag while the song in question is playing. Unfortunately, (at least for me) this is the most common use case. Since the little speaker symbol just replicates the information provided by the bold print, I would advise to remove it. I have seen that it also shows the play and pause state, but that's something we probably don't need a visual representation of if we're listening to music. :wink:

### Steps to reproduce the behavior
1. Open an album (while in album cover view) and play a track you have previously given a star
2. See how the star is replaced by a speaker symbol and can only be changed after playing another song.

### Additional information (optional)
![Screenshot_20210106_140854](https://user-images.githubusercontent.com/9149359/103771838-ca6d3280-5028-11eb-899d-2c0012f9babf.png)

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
there is one thing about it: bold is the currently marked track - speaker if its actually playing.
I will have a look

**Comment by jojosoft** [comment]
Yeah, that's what I referred to as "play and pause state", but in my logic, you will "hear" whether the song is currently being played back or not. :grin: And since the upper control bar is always visible, you will also always be able to "see" the state there. One thing I am maybe missing: Is it possible to mark a song without playing it? I thought that any song gets played immediately after clicking on it, but maybe I am not aware of a use case where that wouldn't happen...

**Comment by Rello** [comment]
speaker will be removed

**Comment by jojosoft** [comment]
Thank you so much..! This is really appreciated.
