### ISSUE TITLE
Incorrect placement of tracklist in album cover view

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#520]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
Since one of the more recent (2020) updates of Audio Player, the "songcontainer" is always placed a bit too high. This was not a problem about a year ago, so I guess it has to do with some later adjustments. (For example something similar to issue #461, but I don't know for sure!) On the right in the image below, I have manually changed the "top" value of the "songcontainer" to move it to the place where I would expect it. I am interested if other users experience this, too.

![Songcontainer](https://user-images.githubusercontent.com/9149359/103773375-42d4f300-502b-11eb-966a-568d8d041b59.png)

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
Hello,

in my side Chrome/Safari it is working better.
the issue seems to be different handling of the calculation `.offsetTop` between Firefox & Chrome
Will need to search for it. no idea yet

**Comment by alanswanson** [comment]
Have the same issue with Audio Player (2.13.1 on NC19 and still with 3.1.0 on NC20) under Firefox. Quick search gives (font of all misknowledge) Stackoverflow question [Firefox and Chrome give different values for offsetTop](https://stackoverflow.com/questions/1472842/firefox-and-chrome-give-different-values-for-offsettop) and might be Mozilla bug [1309247](https://bugzilla.mozilla.org/show_bug.cgi?id=1309427).

**Comment by Rello** [comment]
Hello,
do you still have the issue?

**Comment by jojosoft** [comment]
Unfortunately, yes! Also in Firefox 89.0.2 on my current system. If it's the bug referenced above, did the Mozilla developers not care to fix it for **5 years**?! However, I remember that Audio Player looked and worked fine back in 2019...

**Comment by Rello** [comment]
Hi,

interesting find. I just downloaded the newest firefox. now all 3 browsers behave the same for me (on macOS).

I changed the coding to the offset value from 210 to 260px and it looks correctly for me.
hope it also works for you

![Bildschirmfoto 2021-08-19 um 20 18 50](https://user-images.githubusercontent.com/13385119/130123023-2590d4ad-5c7d-4810-8b06-5d52565fd49b.png)

**Comment by jojosoft** [comment]
Wow, thank you so much! I think it's good that you include the poor fox in your target list, too. 🦊
It works great now, and some issues with the track list in cover view (I didn't yet talk about) have also been resolved in 3.2.0. 👍
