### ISSUE TITLE
Make tracklist in album cover view responsive

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#521]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
When the tracklist is shown in album cover mode and there are changes to the layout, its position is not updated accordingly. The most common case in which this happens is when using the three dots ("option") menu for a specific song in the currently opened album. The properties panel appears on the right, causing the albums to reorder and misplacing the tracklist until the panel is closed again.

### Steps to reproduce the behavior
1. Click on the three dots after the title of a song in album cover view
2. See how the appearing panel shifts the albums and misplaces the tracklist

### Additional information (optional)
The left part of the image shows the opened test album (marked with a bold arrow), the right part of the image shows how it looks like after the panel appeared. The tracklist is nowhere near the album it belongs to, which is probably because an old "top" value of "songcontainer" still contains its old absolute position.

![Shift of tracklist](https://user-images.githubusercontent.com/9149359/103782406-b5e46680-5037-11eb-9baf-d6882b1d237d.png)

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
Hello,
this is correct.

at the beginning of AP, every row was calculated on its own. there, the spacing could be adjusted, so it was always showing full rows.
But the issue was, that the calculation - especially for huge views - took a lot of time and the lazy loading did not work. All covers were requested by the browser at once. visible or not.

Then when the width changed and e.g. less covers were fitting into the space, the whole cover list had to be recalculated and regenerated.

I had to switch to one <div> container with all album covers inside. the browser does the regrouping and lazy loading on its own. without recalculating the WHOLE cover list again.

So in this case, its not alway perfect, but works as designed

**Comment by jojosoft** [comment]
Thank you for the explanation. However, I'm not sure if I was able to get the actual issue across. This issue is not related to the actual list of albums, which is a div called `coverrow`. (It is very good to keep all albums in one single container, I also think it is more elegant and less resource-intensive!) It concerns the div called `songcontainer`, displaying the list of songs of the currently selected album on top of the album view.

This is what currently happens in album cover view:
Click on album -> `songcontainer` is placed and shown -> width of `coverrow` changes -> nothing

This is what I would like to happen in album cover view:
Click on album -> `songcontainer` is placed and shown -> width of `coverrow` changes -> `songcontainer` is moved correctly

The "is moved correctly" part can actually be reproduced manually at the moment by clicking on the album that was open when the width of `coverrow` changed (e.g. by opening the right properties pane), which will close the song list, and then clicking on the album again to open it. Opening it will in some way use the current dimensions of `coverrow` to set the correct top-Value of `songcontainer` **once** depending on the selected album. I think you would just have to execute the same code whenever there is a change to the dimensions of `coverrow` to make it stay in the correct place. I hope that made it clear!
