### ISSUE TITLE
Only perform automatic scrolls if needed

### ISSUE THREAD

**Issue by jojosoft** [Rello/audioplayer#523]
Big thanks to @Rello for actively developing my favorite Nextcloud app! I was happy to dump iTunes and its weird (artificial) restrictions – it's like hosting your own free and privacy-respecting Spotify. However, over the last year, I noticed some things that got a little worse than before (mainly related UI), so I decided to open several smaller issues to address them.

### Actual behavior
I totally see how the auto-scroll feature for random playback came about through #499, but I am actually a little irritated by it. I wonder if it would be possible to only perform the jump while in random playback mode (_and_ the target track is outside of the current view)? :thinking:

### Additional information (optional)
I usually perform normal, album-oriented playback, so it is mostly giving me a hard time. But if I wanted to play tracks randomly _and_ the next track would really happen to be outside the view, I would be very thankful for the feature.

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
mysql

**Nextcloud/ownCloud version:** (see `/status.php`)
19.0.6

**Audio Player version:** (see `/settings/apps`)
2.13.1

**Are you using external storage? If yes, which one:** `local/smb/sftp/...`
No.

### Client configuration
**Browser:**
Firefox 84.0

**Comment by Rello** [comment]
Hello,
I don´t get what the issue is here.
if you have an album only - list view - it should not scroll that much I would guess.
if it scrolls, it gets the title into the center if possible.
can you let me know?

**Comment by jojosoft** [comment]
Well, it is not an issue relating to functional aspects of Audio Player, but more to its user experience. (At least personally) I think that it is very annoying if in album cover view, where (as you write) not much scrolling should be necessary anyway, the whole view constantly shifts up and down with every interaction you make. Coming from the previous version of Audio Player without the changes to solve #499, I got irritated by that behavior very much. Just adding a little condition to the auto-scroll would give the user freedom to have the view scrolled as they like – as long as the track in question is currently visible. I hope this made it a little clearer? It may sound strange, but for me, this is quite a crucial aspect of the user experience with Audio Player. :thinking: 

If it's too difficult to find out whether the song you "would" scroll to is currently already in the user's view or not, it might also be a good solution to just disable auto-scroll for the album cover view in general. Random playback will only jump within the album which is currently open, so the user will already know where to "find" the current song. In #499, the use case seemed to be list view anyway. Containing **all** titles in the collection! In that (but only that) situation, auto-scroll is really useful. :+1:

**Comment by Rello** [comment]
Hi,
lets get this topic sorted out :-)

I changed the random mode as it was giving issues.
Random only works in the list view (cover view does not make sense to me).
in the list if you press the random button, the list actually gets randomly mixed. from there, the player is going one by one. this should make the UI quiet and not jump around.

do you think this would fit your need?
I hope the description is clear somehow

**Comment by jojosoft** [comment]
I'm happy to help you sort it out, thanks so much for your answer! 😃

Well, in cover view, random mode could for example change the way the next song is selected within the currently played album. Current flow after a song ended: If not last song in the album, play next song, else stop playback. In random mode, this could become: If not all songs have been played since starting random mode, play random song from the set of songs not yet played, else stop playback.

But actually, my issue didn't have something to do with random mode. I just read my first comment again and noticed that it's not very well explained there, sorry for the confusion. 😅 So, my main argument was to basically undo #499. I personally found that there's no merit in centering the current title in album view. On the contrary, it really irritated me. However, I understood what the use case of the opener of #499 was. They had a problem finding randomly selected titles in a long list (in list view), but since you now changed it to "compile" the list randomly and then play it one by one, it should not be necessary anymore. Or, would you personally like to keep the jumping behavior?

Would **that** not be would be worth a UI switch? "Jump to currently played back title"..? 🙏😇🙏

**Comment by Rello** [comment]
Hi again,
but with the new 3.2 approach, in list mode it will always have the title centered. 
only if the list is longer than the screen, it will scroll. "half pages" can not be scrolled.

to how many lists does this apply on your side?
to have it visible makes sense to me. and a separate user parameter for this would be quite some effort for this small usecase (adapt js; extend user settings; translations). Due to the limited spare time, I don´t see a case at the moment. when looking at the other open topics, there can be more added value

**Comment by jojosoft** [comment]
I'm very sorry, but that's not what I meant. I barely use list mode, I am almost always in cover mode. And in cover mode, it **always** scrolls, no matter how few titles there are in an album. Although I see the whole list on my screen, it constantly performs useless shifts up and down every time a new title is played, basically destroying user experience.

If you don't see a problem with this, maybe it would help me already if you gave me a little hint as to where the scrolling is performed in code, so I can just delete this functionality on my end. It kind of drives me insane...

**Comment by Rello** [comment]
Hello,
thank you for this request. I understand the requirement, but the time invested in the app is currently limited due to other priorities.
