### ISSUE TITLE
Not available in Nextcloud Store

### ISSUE THREAD

**Issue by Schmidtjanroman** [Rello/audioplayer#524]
App doesn't show up in the Nextcloud Appstore, so it needs to be installed manually

**Comment by Rello** [comment]
Hi,
its available or NC20/21 in the current3.0 version ?!
https://apps.nextcloud.com/apps/audioplayer

**Comment by Schmidtjanroman** [comment]
Hi Rello,
your app is shows in the Nextcloud store on their website, but isn't available as plugin on my Nextcloud installation, which should imho reflect the available/advertised apps from the website.
So I found accidently your plugin via nextcloud homepage.

**Comment by Rello** [comment]
Hello,
its the first app in the multimedia category.
which NC version are you using?

![Bildschirmfoto 2021-01-24 um 09 54 28](https://user-images.githubusercontent.com/13385119/105625513-2823bc00-5e2a-11eb-8f50-afccf8158f77.png)

**Comment by Schmidtjanroman** [comment]
> Hello,
> its the first app in the multimedia category.
> which NC version are you using?

Looks good, but is and was not listed on my Nextcloud, maybe a bug from the Nextcloudpi?
As I said, ive downloaded and installed it via git in command line.
NC Version 20.0.5
NCP Version 1.34.7
![Unbenannt](https://user-images.githubusercontent.com/77236661/105625709-4e962700-5e2b-11eb-861f-7c805b56f047.JPG)

**Comment by Rello** [comment]
Hi,
what happens when you search for the pp in the menu bar?

**Comment by Schmidtjanroman** [comment]
Searchbar says "**No results**", also for your add-on "Audio Player - ID3 Editor (add-on)"

**Comment by Rello** [comment]
Hello,
thank you for the report. I forwarded the question to the NC team because it does not make any sense for me at the moment...

**Comment by Rello** [comment]
Hello,
there is a bug in NC with the php-version-compatibility check
https://help.nextcloud.com/t/i-cant-download/104916/11
