### ISSUE TITLE
aac support

### ISSUE THREAD

**Issue by Rothammel** [Rello/audioplayer#527]
please add aac support 😉

**Comment by r4sas** [comment]
That depends on your browser, not audioplayer.

**Comment by Rothammel** [comment]
But when I search for new audio files, ist sayes no new files found.

**Comment by r4sas** [comment]
Ah, that's different.
That can be found here: https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/lib/Controller/ScannerController.php#L471-L477

**Comment by Rothammel** [comment]
thank you,
i have added $audios_aac = $userView->searchByMime('audio/aac'); and also $audios_aac in the array_merge.
then I have created a mimetypemapping.json and add aac.

now the scanning shows an error:

Scan for audio files
Scanning finished!
Audios found: 2
Written to library: 0
Albums found: 0

Errors: 2
If rescan does not solve this problem the files are broken
/admin/files/Musik/Talstrasse 3-5 & Jason D3an - Henkersbaum.aac
/admin/files/Musik/Moguai & Graham Candy - A Little Bit Of Faith.aac

**Comment by r4sas** [comment]
https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/viewer/viewer.js#L55
https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/app.js#L47
https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/settings/personal.js#L61
https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/sharing/sharing.js#L17

idk if any more places needed to be checked.

**Comment by Rello** [comment]
Hi,
let me check.
in general, the getID3 library should be able to handle it...

**Comment by Rothammel** [comment]
> https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/viewer/viewer.js#L55
> 
> 
> https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/app.js#L47
> 
> 
> https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/settings/personal.js#L61
> 
> 
> https://github.com/Rello/audioplayer/blob/0986ec2a9349a3749fc3e2e72f04ec3b3ef672a5/js/sharing/sharing.js#L17
> 
> idk if any more places needed to be checked.

thank you very much, now I can play aac files

**Comment by Rello** [comment]
![Bildschirmfoto 2021-02-17 um 19 43 37](https://user-images.githubusercontent.com/13385119/108252037-76418c00-7158-11eb-8dfc-d9b82557a36a.png)

@r4sas thank you for the pre-analysis!

its added, but mimetype support might need to be added manually
https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types
