### ISSUE TITLE
[BUG] Download link of files shared via public link displayed also when 'hide download' option is enabled

### ISSUE THREAD

**Issue by fstorz** [Rello/audioplayer#529]
**Describe the bug**
When a single file is shared via a public link and the option to hide the download, the file can be download on the page displayed via the public link.

**To Reproduce**
1. Upload an audio file to Nextcloud
2. Click on the share icon for that file (in file view, not audio player)
3. Click on "Share Link"
4. Click on the 3 dots next to the entry "Share Link"
5. Enable the option "Hide download" in the popup
6. Open the copied link in a new tab
7. On the new tab, click on the 3 dots next to the "audio line"
8. Option to download the file is displayed

**Expected behavior**
When the option, to hide the download, is selected for a public link, it should not be possible to download the file.

**Screenshots**
***Create share link***
![image](https://user-images.githubusercontent.com/27813536/110921568-fbb2f900-831e-11eb-87e7-fc460d62ec91.png)
***Open Share link and download the file***
![image](https://user-images.githubusercontent.com/27813536/110921684-23a25c80-831f-11eb-9dcd-743e855ef64b.png)

**Versions:**
 - Nextcloud: 20.0.8
 - Audioplayer: 3.1.0

**Comment by Rello** [comment]
Hi,
the audio player is the standard HTML5 <audio> tag. This shareplayer was introduced by Nextcloud itself.
AP only adds meta data information if available. the player is not from AP.
I don´t know if the download can be hidden at all - but it would be a NC ticket
