### ISSUE TITLE
[BUG] make Audio Player 3.1.0 available on ownCloud Marketplace (atm 2.8.4)

### ISSUE THREAD

**Issue by mmattel** [Rello/audioplayer#531]
As the title says...

**Comment by Rello** [comment]
Hello,
I am not supporting ownCloud anymore.
on the one hand, the download numbers were very low. On the other hand, oC does not support 3rd party apps very well.
not even fixing download counter issues

sorry for that
Audio Player & Analytics are only available on Nextcloud

**Comment by mmattel** [comment]
These are sad news. I am really loving your app and it is a great piece of craftsmanship!

I tried using the newest version with a manual install, but as result, I needed to revert my DB to a former working state. It told me, that there is an app upgrade necessary and then it said it is upgrading to 10.6 which is already installed...

What can/should ownCloud do that you change your mind?

**Comment by Rello** [comment]
Hello,
problem is, that I am doing this in my spare time. The focus even shifted to the new Analytics.
Un-/fortunately oC and NC are evolving in technically different directions. before, both were the same and I could release the same app for both xClouds.
Now every app would have to be developed completely separate as classes & co are very different already.
As both of my apps are working with potential very big amounts of data, the coding has to be as optimized to the core as possible.

this is not possible for a single developer.
sorry
