### ISSUE TITLE
Deleted songs dont get removed

### ISSUE THREAD

**Issue by cfpwastaken** [Rello/audioplayer#533]
**Describe the bug**

If you delete an album or song from files and rescan for audios nothing will get removed.
In fact, if you didn't restart the server it will actually PLAY THE DELETED FILE?!?!?!?

**To Reproduce**
1. Go to Audio Player
2. Click on Scan for Audios
3. Remove one of the .mp3 files via the files tab
4. Go back to Audio Player
5. Rescan for Audios
6. See error

**Expected behavior**

It should remove the mp3 file from the list.

**Screenshots**

**Versions:**
 - Nextcloud: [e.g. 20.0.1] 21.0.0
 - Audioplayer [e.g. 2.1.0] Newest, just downloaded version from nextcloud app store
 
**Nextcloud log**

--

Edit: It doesn't happen all the time. But some do.

**Comment by Rello** [comment]
solved with next release
