### ISSUE TITLE
[BUG]  Player did not find any mp3 file

### ISSUE THREAD

**Issue by tiigaaa** [Rello/audioplayer#535]
Hello,

I cannot play any audio file because the player did not find it. :(

**PHP:**
> Version: 8.0.3
> Arbeitspeicher-Grenzwert: 7,8 GB
> Maximale Ausführungszeit: 3600
> Maximale Größe zum Hochladen: 16 GB

**Nextcloud**
> Version: 21.0.0

**Audioplayer**
> Version: 3.1.0

######################
root@cloud:/var/www/nextcloud# sudo -u www-data php occ files:scan Meister
Starting scan for user 1 out of 1 (Meister)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 545     | 33183 | 00:00:19     |
+---------+-------+--------------+
root@cloud:/var/www/nextcloud# sudo -u www-data php ./occ audioplayer:scan Meister -vv
Start scan for Meister
Start processing of audio files
Scanned Folder: /Meister/files
Total audio files: 10
Checking audio files to be skipped
Final audio files to be processed: 10
Total stream files: 0
Checking stream files to be skipped
Final stream files to be processed: 0
Cyrillic processing activated
Start processing of audio files
Audios found: 1
Duplicates found: 0
Written to library: 1
Albums found: 0
Errors: 0

**Music:**
root@cloud:/var/www/nextcloud# cd data/Meister/files/Musik/Mariah\ Carey/
root@cloud:/var/www/nextcloud/data/Meister/files/Musik/Mariah Carey# ls
'05 - Without You - Mariah Carey - Feel Blue.mp3'           'MARIAH CAREY-ALL I WANT FOR.MP3'
 AlbumArtSmall.jpg                                          "MARIAH CAREY-SANTA CLAUS IS COMIN' TO TOWN.MP3"
 AlbumArt_{C62FECF3-1133-4CAF-A5F8-996565314DEB}_Large.jpg  'Mariah Carey - All I Want For Christmas Is Yo.mp3'
 AlbumArt_{C62FECF3-1133-4CAF-A5F8-996565314DEB}_Small.jpg  'Mariah Carey - Its Like That (Main Version) - [wWw.Mp3.zAmBrOw.NeT].mp3'
'DON'\''T FORGET ABOUT US (TONY MORGAN MIX).MP3'            'Mariah Carey- Can I get your number.mp3'
 Folder.jpg                                                  Readme.md
'MARIAH CAREY - GET YOUR NUMBER (FEAT JERMAINE.MP3'         'Without You.Mp3'
'MARIAH CAREY - SAY SOMETHIN'\'' (FEAT. SNOOP DOGG).MP3'   

What kind of LOG do you need to help me out of that issue.

many thanks
KOAL

**Comment by tiigaaa** [comment]
HI,
no idea?
Now im on Nextcloud 21.0.1 but still not working.
![image](https://user-images.githubusercontent.com/52923848/114611565-7914b500-9ca1-11eb-8a52-6976abbab511.png)
![1](https://user-images.githubusercontent.com/52923848/114611592-7fa32c80-9ca1-11eb-89de-346890a163a2.JPG)
![2](https://user-images.githubusercontent.com/52923848/114611611-8336b380-9ca1-11eb-9341-ecf6fe73461c.JPG)

many thanks
KOAL

**Comment by r4sas** [comment]
Find nextcloud.log in data dir and check it for errors with audioplayer mention.

**Comment by tiigaaa** [comment]
Hi,
I cant see anything in the log but it seems for the player the folder is empty.
![1](https://user-images.githubusercontent.com/52923848/115143046-4d991e00-a045-11eb-89c7-42cbb97082c6.JPG)
![2](https://user-images.githubusercontent.com/52923848/115143047-4eca4b00-a045-11eb-8ccb-760c0c979f12.JPG)

**Comment by Rello** [comment]
Hello,
this is strange. I would expect something with the mimetypes to be wrong.
ist it a normal folder or a mounted external?

the screenshot from the folder-picker is correct. this is supposed to only show folders and no files itself

**Comment by tiigaaa** [comment]
HI,

this is a normal folder, nothing special :(
This is the mimetype file:
![grafik](https://user-images.githubusercontent.com/52923848/118878788-3cfff000-b8f0-11eb-87e1-bc9cef0fe202.png)

![grafik](https://user-images.githubusercontent.com/52923848/118879660-48075000-b8f1-11eb-9af8-11604b09c868.png)

**Comment by Rello** [comment]
Hello,
die you make any progress here?
I did a lot of testing for the new version in different scenarios and did not find any issues with the scanner

**Comment by tiigaaa** [comment]
Hello,

no i try this with every new Version, but never get any files. I think its my fault. But I dont have any idea how to fix this.

Maybe I try a test vm with a clean install.

**Comment by Rello** [comment]
Hello,
please get the nextcloud.log right after a scan.
There should be an indication whats wrong. I expect a faulty audio file which is causing the scanner to break

**Comment by rakekniven** [comment]
Hmmh, not sure if I hijacking this issue.
I used the audioplayer app a lot and after upgrading to the latest vxxx it does not find any song.
Unfortunately I cannot tell you the exact version being known to be ok.
Nothing changed on my NC config. I just told the app to scan again.

Log says:
"message":"Error while building library: PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"folder_id\" does not exist\nLINE 1: ..._albums\" WHERE \"user_id\" = $1 AND \"name\" = $2 AND \"folder_id...\n ^ in /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:82

Does this help?

**Comment by rakekniven** [comment]
Just did an update to NC v22.2.1 and still the same.
Tried with different users.
Audioplayer app is v3.2.2

**Comment by rakekniven** [comment]
Just did a new install with the latest VM of NC23 and it works out of the box.
I am pretty sure something is wrong with the db scheme.

**Comment by aPollO2k** [comment]
I'm facing the same issue:

`{"reqId":"xxxx","level":3,"time":"2021-12-25T21:33:46+00:00","remoteAddr":"","user":"--","app":"audioplayer","method":"","url":"--","message":"Error while building library: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'folder_id' in 'where clause' in /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:92\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(92): PDOStatement->execute(Array)\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php(189): Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(Array)\n#2 /var/www/nextcloud/lib/private/DB/PreparedStatement.php(87): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /var/www/nextcloud/apps/audioplayer/lib/Controller/DbController.php(297): OC\\DB\\PreparedStatement->execute(Array)\n#4 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(306): OCA\\audioplayer\\Controller\\DbController->writeAlbumToDB('xxx', 'xxx', xxx, NULL, 182500)\n#5 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(177): OCA\\audioplayer\\Controller\\ScannerController->scanAudio(Object(OC\\Files\\Node\\File), Object(getID3), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#6 /var/www/nextcloud/apps/audioplayer/lib/Command/Scan.php(75): OCA\\audioplayer\\Controller\\ScannerController->scanForAudios('xxx', Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\\audioplayer\\Command\\Scan->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(OCA\\audioplayer\\Command\\Scan), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/nextcloud/console.php(100): OC\\Console\\Application->run()\n#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')\n#14 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDO\\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'folder_id' in 'where clause' in /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php:26\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php(94): Doctrine\\DBAL\\Driver\\PDO\\Exception::new(Object(PDOException))\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php(189): Doctrine\\DBAL\\Driver\\PDO\\Statement->execute(Array)\n#2 /var/www/nextcloud/lib/private/DB/PreparedStatement.php(87): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /var/www/nextcloud/apps/audioplayer/lib/Controller/DbController.php(297): OC\\DB\\PreparedStatement->execute(Array)\n#4 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(306): OCA\\audioplayer\\Controller\\DbController->writeAlbumToDB('xxx', 'xxx', xxx, NULL, 182500)\n#5 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(177): OCA\\audioplayer\\Controller\\ScannerController->scanAudio(Object(OC\\Files\\Node\\File), Object(getID3), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#6 /var/www/nextcloud/apps/audioplayer/lib/Command/Scan.php(75): OCA\\audioplayer\\Controller\\ScannerController->scanForAudios('aPollO', Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\\audioplayer\\Command\\Scan->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(OCA\\audioplayer\\Command\\Scan), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/nextcloud/console.php(100): OC\\Console\\Application->run()\n#13 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')\n#14 {main}\n\nNext Doctrine\\DBAL\\Exception\\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'folder_id' in 'where clause' in /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:65\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1780): Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter->convert(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), Object(Doctrine\\DBAL\\Query))\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1719): Doctrine\\DBAL\\Connection->handleDriverException(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), Object(Doctrine\\DBAL\\Query))\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Statement.php(193): Doctrine\\DBAL\\Connection->convertExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'SELECT `id`, `a...', Array, Array)\n#3 /var/www/nextcloud/lib/private/DB/PreparedStatement.php(87): Doctrine\\DBAL\\Statement->execute(Array)\n#4 /var/www/nextcloud/apps/audioplayer/lib/Controller/DbController.php(297): OC\\DB\\PreparedStatement->execute(Array)\n#5 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(306): OCA\\audioplayer\\Controller\\DbController->writeAlbumToDB('xxx', 'xxx', xxx, NULL, 182500)\n#6 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(177): OCA\\audioplayer\\Controller\\ScannerController->scanAudio(Object(OC\\Files\\Node\\File), Object(getID3), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#7 /var/www/nextcloud/apps/audioplayer/lib/Command/Scan.php(75): OCA\\audioplayer\\Controller\\ScannerController->scanForAudios('xxx', Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\\audioplayer\\Command\\Scan->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(OCA\\audioplayer\\Command\\Scan), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /var/www/nextcloud/console.php(100): OC\\Console\\Application->run()\n#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')\n#15 {main}","userAgent":"--","version":"21.0.7.0"}
`

**Comment by Rello** [comment]
Hello,
I just released an update to AP which includes a repair step for the database. can you please try?

**Comment by aPollO2k** [comment]
Hi Rello,

I am very grateful to you for working on a fix. I'm sorry the test took a few days now.

Next column is missing when scanning for audio files:

`PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isrc' in 'field list' in /var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php:92`

For the complete error message please review the attached file.
[column_isrc_in_field_list.txt](https://github.com/Rello/audioplayer/files/7823976/column_isrc_in_field_list.txt)

My test environment is on NC 21 and audioplayer 3.2.4.

Best regards,
