### ISSUE TITLE
Track numbers limited to 2 digits

### ISSUE THREAD

**Issue by dennorske** [Rello/audioplayer#537]
**Describe the bug**
Track numbers above 100 shows incorrectly in album view & I can't scroll down to see the tracks overflowing my screen space.

**To Reproduce**
1. Load an album with 100 or more tracks.
2. Set it to be in Album view mode
3. See result as in screenshot below. I can't see all the tracks unless i go to List view.

**Expected behavior**
numbers over 100 to show more than 2 digits, and ability to scroll down when too many tracks listed in album view

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/3287543/118409243-b518ac80-b689-11eb-8bb6-77a3e0ad1b39.png)

**Versions:**
 - Nextcloud: 21.0.1
 - Audioplayer 3.1.0
 
**Nextcloud log**
None

**Comment by dennorske** [comment]
For better context, this is on a 2560x1440 screen with a normal browser window (maximized) 

![image](https://user-images.githubusercontent.com/3287543/118409387-77685380-b68a-11eb-8442-53ad10d8fcd5.png)

**Comment by r4sas** [comment]
Looks like fixed width causes that problem...

**Comment by Rello** [comment]
oh, nice finding. did not expect that many titles.
I wonder if extending the width or (also?) validating the cd-number makes sence here. because if you only have one, the "1-" is a waste anyway

**Comment by Rello** [comment]
Hello,
a conditional formatting will be applied. if all relates to the same disc, the disc number is now shown.

![Bildschirmfoto 2021-08-17 um 20 03 36](https://user-images.githubusercontent.com/13385119/129777562-6220b8d8-b3ea-4804-8ac8-bfa75e230e81.png)

![Bildschirmfoto 2021-08-17 um 20 02 31](https://user-images.githubusercontent.com/13385119/129777435-261a17cf-7540-409d-9c55-484ce9d7d472.png)
