### ISSUE TITLE
occ scan errors when scan folder is not available anymore

### ISSUE THREAD

**Issue by G33rt-hub** [Rello/audioplayer#539]
**Describe the bug**
An .occ audioplayer:scan -all stops scanning when a path is encountered which can't be accessed anymore. For example this can happen when the access to an external storage (in my case a local storage) has been removed for a user.

**To Reproduce**
1. User A gets access to a local external storage location from an admin
2. User A sets this location as prefered scan location on the Scanner Settings page
3. Admin has set .occ audioplayer:scan -all in a cron job
4. Admin removes access to the external storage location for User A
5. .occ audioplayer:scan -all gives a PHP error and doesn't continue

**Expected behavior**
skip the error and continue the scan for other users

**Versions:**
 - Nextcloud: 21.0.1
 - Audioplayer 3.1.0

**Comment by Rello** [comment]
Hello,
thank you for the report. I will need to look at the error handling. thats not good.

**Comment by Rello** [comment]
issue is solved with the next update. sorry for the delay
