### ISSUE TITLE
Loop playback states not remembered

### ISSUE THREAD

**Issue by gsantner** [Rello/audioplayer#541]
**Describe the bug**
The random playback & repeat playlist control states are not remembered. Not between nextcloud navigation (while logged in), logout&login again, and not even for simple (F5) reload of audioplayer.  
See video:  

![screenrecord2](https://user-images.githubusercontent.com/6735650/121211033-74711500-c87c-11eb-8ba3-eec12feda169.gif)

**To Reproduce**
1. Play some music
2. Click random and/or loop controls to enable them
3. Press F5/Reload, or close browser/login again.

**Expected behavior**
I expect that the state get stored at the point I pressed a random/loop button.  
When I come back to NextCloud audioplayer in whatever way, random and loop/repeat should be turned on still, like most recently set.  
Whatever album/playlist/tracks - I nearly always want random playback, and replay playlist when finished. This is tedious currently with this addon.

**Screenshots**
See video above.

**Versions:**
 - Nextcloud: Nextcloud 20.0.10
 - Audioplayer 	3.1.0

**Comment by Rello** [comment]
Hello,
the loop mode is persisted.
For random, I am not sure how this could be done. as changed in the other issue, it will shuffle the list on the fly.
to persist this does not really make sense.
what do you think?

https://user-images.githubusercontent.com/13385119/129750616-94f25140-d40d-43c2-b4c6-ba84f03c4b0f.mov
