### ISSUE TITLE
Previous track button when shuffle is enabled

### ISSUE THREAD

**Issue by gsantner** [Rello/audioplayer#542]
**Describe the bug**
When the random is enabled (control state highlighted), the previous track button does not work as expected.  
It just jumps to the track one up in the list, but not to the track previously played.

![screenrecord2](https://user-images.githubusercontent.com/6735650/121213426-7f2ca980-c87e-11eb-8efc-f5abfa0f5524.gif)

**To Reproduce**
1. Open audioplayer addon page
2. Click  random playback toggle to enable random playback
3. Play a track
4. Press next track button ~ 5 times
5. Press previous track button

**Expected behavior**
That the track is played that actually was before the current one. Not the track that happens to be above in the listview.

**Screenshots**  
See above.

**Versions:**
 - Nextcloud: Nextcloud 20.0.10
 - Audioplayer 3.1.0

**Comment by Rello** [comment]
Hi,
sorry for the late reply.
nice finding. I will check.

**Comment by Rello** [comment]
Hello,
the reasons is, that the shuffle only shuffles the next upcoming title by calculating a random index number.
I will change the procedure a little.
with a press on the shuffle button, the whole playlist will shuffle visually.
Then all standard coding can apply and everything will work

**Comment by gsantner** [comment]
yeah, I thought it was implemented this way :D
