### ISSUE TITLE
Please add compatibility with NC22

### ISSUE THREAD

**Issue by elpraga** [Rello/audioplayer#544]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rello** [comment]
will do shortly

**Comment by Rello** [comment]
added up to NC23

**Comment by jurgenhaas** [comment]
Sounds good, but the release doesn't show up on the app store at https://apps.nextcloud.com/apps/audioplayer yet.

**Comment by Rello** [comment]
yes - working on it 🤯
have to bundle some little changes into the next update
