### ISSUE TITLE
Download album cover art

### ISSUE THREAD

**Issue by spoorun** [Rello/audioplayer#55]
Where an album doesn't have a local picture, search for and download album cover art.
Where no album artwork is available, use photo of the artist (see #56 )
Images could be downloaded from DuckDuckGo, Google, Wikipedia, LastFM etc...
Perhaps use existing code from other open source projects to enable this.

**Comment by ghost** [comment]
Thanks for requesting this feature! There is not enough need for this feature at the moment.
We are looking forward to further feature requests.
