### ISSUE TITLE
dashboard style impact

### ISSUE THREAD

**Issue by Leprazoriy** [Rello/audioplayer#550]
**Describe the bug**
After updating the application to version 3.2.0, the dashboard page broke. The audio player widget is not included on the dashboard page.

**To Reproduce**
1. Update application to 3.2.0
2. Go to dashboard page

**Expected behavior**
Normal work.

**Screenshots**
![audioplayer1](https://user-images.githubusercontent.com/72513510/130228339-1b0fe28b-8d47-4ece-8488-ef54d0262c1f.jpg)
![audioplayer2](https://user-images.githubusercontent.com/72513510/130228950-af030970-a414-4ccc-b6e0-28947f4a91ff.jpg)

**Versions:**
 - Nextcloud: [e.g. 21.0.4]
 - Audioplayer [e.g. 3.2.0]
 
**Nextcloud log**

**Comment by Rello** [comment]
thank you for the report.
I could just reproduce it.
will fix it immediately

**Comment by Rello** [comment]
fix released.
thank you!

**Comment by Rello** [comment]
was the update already offered to your server?

**Comment by Leprazoriy** [comment]
Yes, I got an update on my server! The problem has been fixed, thanks!
