### ISSUE TITLE
[BUG]  Can't activate sonos plugin in admin interface

### ISSUE THREAD

**Issue by smCloudInTheSky** [Rello/audioplayer#551]
**Describe the bug**
Hi,

I've installed audioplayer and the sonos plugin.
In my Admin panel I can't activate the sonos plugin. I got this in the logs when I check the case "enable to all users":

OCP\AppFramework\QueryException: Could not resolve db! Class db does not exist

Is there a cmd I do have to run on my mysql to resolve this ? Do I need another plugin alongside to audioplay and audioplyer sonos plugin to make it work ?
Nextcloud has been installed using the truenas plugin.

Regards

**To Reproduce**
1. Go to admin panel
2. Click on 
3. Go to logging

**Expected behavior**
Sonos plugin being enabled to all users

**Screenshots**

**Versions:**
 - Nextcloud: 21.0.4
 - Audioplayer 3.2.1
 - Audioplayer sonos plugin : 1.2.0
 
**Nextcloud log**

Error | index | OCP\AppFramework\QueryException: Could not resolve db! Class db does not exist
/usr/local/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126: OC\AppFramework\Utility\SimpleContainer->resolve()
/usr/local/www/nextcloud/lib/private/ServerContainer.php - line 162: OC\AppFramework\Utility\SimpleContainer->query()
/usr/local/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 434: OC\ServerContainer->query()
/usr/local/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 96: OC\AppFramework\DependencyInjection\DIContainer->query()
<<closure>>OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
/usr/local/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 101: array_map()
/usr/local/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 109: OC\AppFramework\Utility\SimpleContainer->buildClass()
/usr/local/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 126: OC\AppFramework\Utility\SimpleContainer->resolve()
/usr/local/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 459: OC\AppFramework\Utility\SimpleContainer->query()
/usr/local/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 431: OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/usr/local/www/nextcloud/lib/private/AppFramework/App.php - line 144: OC\AppFramework\DependencyInjection\DIContainer->query()
/usr/local/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()
/usr/local/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()
/usr/local/www/nextcloud/index.php - line 37: OC::handleRequest()

**Comment by Rello** [comment]
Hi,
the tool is too outdated.
let me check. I think I need to move it over to NC21 compatibility

**Comment by Rello** [comment]
https://github.com/Rello/audioplayer_sonos/issues/3
