### ISSUE TITLE
Download and display artist photos

### ISSUE THREAD

**Issue by spoorun** [Rello/audioplayer#56]
For each artist, search for and download an image. Use online collections such as Wikipedia, Google, DuckDuckGo, LastFM. Perhaps use existing open source code to achieve this.
When user selects artist view, or when a  specific artist is selected, display image for each artist.

**Comment by ghost** [comment]
Thanks for requesting this feature! There is not enough need for this feature at the moment.
We are looking forward to further feature requests.
