### ISSUE TITLE
Scan is not being completed (50%) on a big library

### ISSUE THREAD

**Issue by sprnza** [Rello/audioplayer#57]
Hi there!
Thank you for the great app! But I'm facing with a very weird issue. My music library consist of >3500 mp3 files. And the app is hanging on 53% of scanning (1963 files)
### Expected behavior
1. Scan is being completed
### Actual behavior
1. Scan hangs on ~50%
### Steps to reproduce the behavior
1. Click "update library" button
### Server configuration

Linux 4.1.31-1
apache 2.4.23-1
mariadb 10.1.16-2
php 7.0.10-1
Nextcloud "version":"9.1.0.16","versionstring":"10.0"
Nextcloud updated from ownCloud 9
Audio Player installed from the appstore
no external storage
no encryption
### Client configuration

Linux manjaro 4.1.31-1-MANJARO
Firefox 48.0.2-1
### Log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
{"reqId":"PHovhdeA5u67OXBY6do1","remoteAddr":"MY_IP_HERE","app":"admin_audit","message":"Login attempt: \"Speranskiy\"","level":1,"time":"2016-09-12T08:50:34+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"--"}
{"reqId":"PHovhdeA5u67OXBY6do1","remoteAddr":"MY_IP_HERE","app":"admin_audit","message":"Login successful: \"Speranskiy\"","level":1,"time":"2016-09-12T08:50:34+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"PHovhdeA5u67OXBY6do1","remoteAddr":"MY_IP_HERE","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-09-12T08:50:34+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"Ct9FCxtR1tu6B\/fqeHEx","remoteAddr":"MY_IP_HERE","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-09-12T08:50:34+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"HfyPqfOMRnvgzafB0Ar2","remoteAddr":"MY_IP_HERE","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-09-12T08:50:46+00:00","method":"GET","url":"\/index.php\/apps\/audioplayer\/getimporttpl","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/Music\/MUSE\/2009 - The Resistance (Limited Edition Digipak) UK - (320 kbps)\/08. I Belong To You  Mon C?ur S'ouvre ? Ta Voix.mp3","level":0,"time":"2016-09-12T08:51:52+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#556","level":0,"time":"2016-09-12T08:52:48+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#556","level":0,"time":"2016-09-12T08:52:48+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#556","level":0,"time":"2016-09-12T08:52:48+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/Music\/\u0421\u043f\u043b\u0438\u043d (\u0421\u0430\u0448\u0430 \u0412\u0430\u0441\u0438\u043b\u044c\u0435\u0432)\/1998 - \u0413\u0440\u0430\u043d\u0430\u0442\u043e\u0432\u044b\u0439 \u0410\u043b\u044c\u0431\u043e\u043c (Navigator Records, NR 0708 CDp, 2008) [flac]\/.unwanted\/03. \u041e\u0440\u0431\u0438\u0442 \u0431\u0435\u0437 \u0441\u0430\u0445\u0430\u0440\u0430.mp3","level":0,"time":"2016-09-12T08:52:48+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"audioplayer","message":"Error with getID3. Does not seem to be a valid audio file: \/Music\/Robbie Williams - Discography\/Singles\/Robbie Williams - Advertising Space\/.unwanted\/(03) [Robbie Williams] Ouverture For Berlin.mp3","level":0,"time":"2016-09-12T08:53:09+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#556","level":0,"time":"2016-09-12T08:54:21+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#556","level":0,"time":"2016-09-12T08:54:21+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
{"reqId":"6EjsQy8lRItz6G+d+7lb","remoteAddr":"MY_IP_HERE","app":"PHP","message":"imagecreatefromstring(): gd-png: fatal libpng error: bad adaptive filter value\n at \/usr\/share\/webapps\/nextcloud\/lib\/private\/legacy\/image.php#598","level":3,"time":"2016-09-12T08:54:21+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}

```

</details>

**Comment by kbaegis** [comment]
+1

**Comment by kbaegis** [comment]
So I'm using PostgreSQL. The issue for me was the code doesn't gracefully handle duplicate keys and the fault it generates. In other words, if you have the same song in two different files on your cloud, this complete breaks this application. 

My workaround: 
1) make sure all files are unique
2) edit postgres database directly for all audioplayer fields (DELETE FROM <table>;)
3) rescan

**Comment by Rello** [comment]
Hello @kbaegis ,
thank you for your valuable help. I transferred your issue to #58 as it is not related to this issue here.

**Comment by Rello** [comment]
@sprnza 
thank you for your feedback:
It looks like you are using the special handling for cyrillic characters - **can you confirm**?

regarding your logfile:
is this the logfile of one scan-attempt? 
- it indicates that you have 3 corrupt files, where the ID3-Tags can not be processed
- it indicates that there are 5 files where the cyrillic conversion will not work (due to other characters)

But these errors should not break the scanner.
Can you please start the scan again, after it failed and see if you get more progress then?

**Comment by sprnza** [comment]
@Rello 
Hi! Yes, I do have the special handling for cyrillic characters enabled.
Yes, the log file is just for one scan-attempt. Next scans hang on the exact same amount of files/percentage.

**Comment by Rello** [comment]
Hello @sprnza 
so the last error in your log indicates a major issue which breaks the whole php-process (level":3).

The details:
Audioplayer  `scannercontroller => scanForAudios` calls `$image->loadFromdata($data)`, which is a NC standard function to transform the image data from your ID3 file info.

`lib/private/legacy/image.php` breaks at `$this->resource = @imagecreatefromstring($str);` with a fatal error because something is wrong with the image data.

Do you have any idea which file could be the one in question?
it has to be the one shown in the status screen (or the next one?).
anyway: something is wrong with the file. I need to check on an error-handler - but this will not solve the original issue

**Comment by sprnza** [comment]
Hi @Rello!
What's the status screen? I can't find any trace of the filename...

**Comment by Rello** [comment]
the screen where it shows the progress %-Values.
can this give any hints on where the issue might be?

**Comment by sprnza** [comment]
The screen looks like this
http://itmages.ru/image/view/4879401/356fc05e

**Comment by ghost** [comment]
@sprnza Is it possible that you run into a timeout, [as described in the wiki](https://github.com/rello/audioplayer/wiki/cyrillic-symbol-handling)?

**Comment by sprnza** [comment]
@xraMsamohT I suppose it's about 
default_socket_timeout = 60
if so, then no, it still hangs after I've increased it up to 180

**Comment by ghost** [comment]
What value is set for `max_execution_time` in `php.ini`? The default of 30 seconds isn't enough.

**Comment by sprnza** [comment]
@xraMsamohT I've set it to 180 with no luck unfortunately.

**Comment by ghost** [comment]
My setting is 360 and too short under some circumstances. I prefer a minimum of 300 seconds. ;-)

**Comment by sprnza** [comment]
I don't think it's a timeout issue, because scanning of these 50% of files takes around 3 minutes, so it definitely longe then 30 seconds. I've tested with 300 seconds though with no luck either.  I believe this is a problem
`
"app":"PHP","message":"imagecreatefromstring(): gd-png: fatal libpng error: bad adaptive filter value\n at \/usr\/share\/webapps\/nextcloud\/lib\/private\/legacy\/image.php#598","level":3,"time":"2016-09-21T09:30:52+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
`
But I have no idea how to find the corrupted file.

**Comment by Rello** [comment]
@sprnza 
sorry for the late reply. it took some time to figure out how to handle this.
I installed an error handler which will log the file in worst case to OC/NC.log for further analysis.

do you have the chance to manually download the modified file `controller/scannercontroller.php`
and give it a try in your installation?
the change is shown here: https://github.com/Rello/audioplayer/commit/ff776bec9188fabf31d7dbd0f0dbb7892a0166f2

thank you for your help

**Comment by sprnza** [comment]
Hi @Rello 
Seems like something went wrong. Here is the log: http://pastebin.com/5mkZLJ67
It ends up with tons of
`{"reqId":"kzx6oBfNNpgDM6LsUUhn","remoteAddr":"192.168.1.8","app":"PHP","message":"(Registered shutdown functions) Unable to call OCA\\audioplayer\\Controller\\ScannerController::shutDownFunction() - function does not exist at Unknown#0","level":0,"time":"2016-10-21T06:07:37+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}`
I've stripped down the log to fit pastebin limitations

**Comment by Rello** [comment]
Thank you. 
Pleas check the last rows of scannercontroller. 
Its the last function. Did it arrive correctly in your installation?

**Comment by sprnza** [comment]
Yep, it's absolutely[ the same](https://github.com/Rello/audioplayer/blob/master/controller/scannercontroller.php)

**Comment by Rello** [comment]
Hello @sprnza 
contratulations. you found a bug in PHP which should be solved since 5.6 - if I am not wrong.

anyway: I followed another approach and updated the behavior of the progress bar.
It will show the file currently being progressed. whenever the scanner stops, the file being shown should be the one making problems (logfile for the details of the problems).

could you give the updated scannercontroller another try?
thank you for your patience,
let me know

**Comment by sprnza** [comment]
Hi @Rello!
Haha! PHP devs are slow :)
Actually it doesn't show filenames for files that are being scanned for the second time and it does for ones that are being scanned for the first time. So I've found culprits, removed them and got the process finished! Thank you a lot! Do you want me to do some tests with these files to understand what's wrong with them? Or to share it with you?
After the second thousand the process becomes slower (probably because those files were being scanned for first time)
Some most frequent lines from the log file:
`{"reqId":"N88LKNo3qEoa4myzOlZs","remoteAddr":"128.68.102.114","app":"PHP","message":"rewinddir(): 5991 is not a valid Directory resource at \/usr\/share\/webapps\/nextcloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-10-22T18:20:28+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
`
and
`
{"reqId":"N88LKNo3qEoa4myzOlZs","remoteAddr":"128.68.102.114","app":"PHP","message":"iconv(): Detected an illegal character in input string at \/usr\/share\/webapps\/nextcloud\/apps\/audioplayer\/controller\/scannercontroller.php#558","level":0,"time":"2016-10-22T18:22:25+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"Speranskiy"}
`

**Comment by sprnza** [comment]
I've removed embedded images from those files and they've been scanned without a glitch.

**Comment by Rello** [comment]
nice!
So I will close the issue.
As it seems to be very rare (never reported before) I can not provide a special process for this, as I am focusing on the next features right now.
And the workaround with checking the logfile should be acceptable I would say.

thank you for your help.
the fix will be officially published with the next release...

**Comment by sprnza** [comment]
Here is the ![cover](https://cloud.githubusercontent.com/assets/1968839/19621899/698ae69c-98ad-11e6-9964-6af60547664f.png) which is even not being opened by an image viewer.

**Comment by Rello** [comment]
yes. definitely an issue with the file itself, which I cant really handle

**Comment by sprnza** [comment]
Cool! Thank you! :) I wish you the bugless release!

**Comment by sprnza** [comment]
Cool! Thank you! :) I wish you a bugless release!
