### ISSUE TITLE
double files are not handled correctly

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#58]
@kbaegis

> So I'm using PostgreSQL. The issue for me was the code doesn't gracefully handle duplicate keys and the fault it generates. In other words, if you have the same song in two different files on your cloud, this complete breaks this application.
> 
> My workaround: 
> 1) make sure all files are unique
> 2) edit postgres database directly for all audioplayer fields (DELETE FROM
> 
> ;)
> 3) rescan

**Comment by Rello** [comment]
thank you @kbaegis for the analysis.
there is indeed an error in the scanner because when adding a track to the DB, all information is validated in combination - but not including the file_id (from owncloud filecache).

will be fixed soon

**Comment by Rello** [comment]
@kbaegis can you please describe the issue more in detail?
I evaluated the scanner and the current process is on purpose: when a file with the same matching combination of the following fields is found, it is not added to the database again - because this would not make any sense.
- $aTrack['title'],
- $aTrack['number'],
- $aTrack['artist_id'],
- $aTrack['album_id'],
- $aTrack['length'],
- $aTrack['bitrate'],
- $aTrack['mimetype'],
- $aTrack['genre'],
- $aTrack['year']

This can be seen in the scanner when the numbers of "found" and "added" are different:
![screen shot 2016-09-12 at 21 56 56](https://cloud.githubusercontent.com/assets/13385119/18450567/e31c2e74-7933-11e6-83fc-f96e7adde7b1.png)

let me know

**Comment by kbaegis** [comment]
Here's the actual error I see from the owncloud log (sanitized): 
http://hastebin.com/piqonubuvo.xml
"duplicate key value violates unique constraint"

**Comment by Rello** [comment]
Hello,

the problem is alerted by index 

> aa_tracks_file_user_id_idx

which has to be unique for file_id & user_id (where file_id is the unique ID from the cloud filecache).
But this can only be the case if you have the actual same file twice in your collection - not the same song in 2 different files.

I don´t know how this can happen - but can you please analyze how?
Any Idea?
perhaps a file linked twice via a symlink on OS level?

**Comment by Rello** [comment]
Hello,
Can you please post the "title" of the song mentioned in the errorlog? Could it be longer than 256 digits?

Thank you...

**Comment by ghost** [comment]
Closed due to lack of info.
