### ISSUE TITLE
new visuals - cleaner colors

### ISSUE THREAD

**Issue by Rello** [Rello/audioplayer#59]
The automatic derivation of background colors for albums & titlelists did not really work.
either the colors were to bright or the contrast between background & fonts was not good.

It is reworked to a unique experience

**Comment by Rello** [comment]
![screen shot 2016-09-13 at 21 50 13](https://cloud.githubusercontent.com/assets/13385119/18489022/1828ba6a-79fc-11e6-8853-7d4d4b9aa0cf.png)

**Comment by connium** [comment]
Would prefer it a little brighter (e.g. same color as the dropdown in the left sidebar) to increase the contrast between background and font.

**Comment by ghost** [comment]
> Maybe it makes sense to have a decent background color that is the same for all albums (e.g. **light grey**).

This _is_ `Light Gray`. ;-)

The whole design – except the covers – in one color isn't a good choice, imho. Dropdown, covers/tracklist, and soundbar are in grayscales. Maybe it will be customizable in the future but not soon.
