### ISSUE TITLE
searching for titles

### ISSUE THREAD

**Issue by JustusDinera** [Rello/audioplayer#60]
### Expected behavior

The music libary should be filled with my upoaded music.
### Actual behavior

The popup with "searching for titles" coming up.
But if I click the button "start search" the progress bar is showing only a "0%" and nothing happend
### Steps to reproduce the behavior
1. open the app
2. click refresh library
3. click start search
4. nothing happend
### Server configuration

**Operating system**:
Debian 8.5 (Raspbian)

**Web server:**
Apache2 2.4

**Database:**
MySQL 14.14

**PHP version:**
PHP 5.6.22

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 9.0.51.0

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh installion

**Where did you install Audio Player from:**
directly out of the Nextcloud "Apps"

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
internal storage

**Are you using encryption:** yes/no
yes, of course
### Client configuration

**Operating system:**
Win 7 and Ubuntu 16.04

**Browser:**
Firefox in both operating systems
### Log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
Error   PHP     Cannot redeclare class getID3 at /var/www/html/nextcloud/apps/audioplayer/3rdparty/getid3/getid3.php#75     2016-09-14T14:41:09+00:00   dsadmin
Error   PHP     Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0   2016-09-14T14:34:38+00:00   dsadmin
```

</details>

**Comment by mantazzo** [comment]
If you have a problem with Searching at 0% (0/0) you should check if you have old MP3 Player and/or Music app installed. I had the same problem on ownCloud 9.1 and it fixed itself after I deleted MP3 Player old app and disabled Music app.

**Comment by JustusDinera** [comment]
Thanks a lot!
That was the Solution!

**Comment by ghost** [comment]
@mantazzo Thank you very much for this helpful hint. We will add this to our wiki.
