### ISSUE TITLE
Cover Image will not displayed

### ISSUE THREAD

**Issue by Mokkujin** [Rello/audioplayer#62]
Is there a way to display a cover.jpg or cover.png in the Dashboard from Audioplayer. All my Folders have an cover.jpg but the image will not displayed. I try to rename it to Cover,jpg and cover.png and Cover.png but the image will not be displayed

The Issue is on Nextcloud 10
![image](https://cloud.githubusercontent.com/assets/3368978/18577276/bd23b1c6-7be8-11e6-91ac-45db44940799.png)

**Comment by Rello** [comment]
Its similar to #24

Audioplayer currently only used the cover from the ID3 tag of the title. 
Additionally you can use the editor (little pen icon next to a song in the albums) to upload or select a new icon (ehich is then stored in the ID3)

To search for a cover file is on the to-do, but i need to implement some other parts first. 

Thank you for you patience

**Comment by Mokkujin** [comment]
ok thanks the little pen works fine but its a lot of work to configure each cover.jpg to an album.

**Comment by xraMsamohT** [comment]
Duplicate of #24
