### ISSUE TITLE
Search m3u Playlist

### ISSUE THREAD

**Issue by hitam4450** [Rello/audioplayer#64]
I copied a .m3u play list(holding the URl of an internet radio station) into the folder where .mp3 files are located.
Selecting Wiedergabelisten from the drop down menu I only could search for Album, but nit for .m3u play list.

regards, hitam4450

**Comment by xraMsamohT** [comment]
Duplicate of your request #31 .

No playlist support at the moment.

**Comment by xraMsamohT** [comment]
Duplicate of #31
