### ISSUE TITLE
Filter settings / specific folder for scan

### ISSUE THREAD

**Issue by Atanamo** [Rello/audioplayer#66]
Hi,
currently you can only press a button to start the scan for new audio files.
But what I am missing is any kind of setting to determine or filter the directories to scan.

The reason is: I have a bunch of stuff (like e.g. portable programs) in my cloud, which also contain audio files. But these files are neither music files nor do I want them to appear in the audio player.

Maybe you could add an optional selection to the scan dialog, which defines the directory to scan?

Thanks! :-)

**Comment by Rello** [comment]
Hello,
Thank you for the request. 
There is already a rought design idea in my head. 

I dont like the idea of one (or 2? Or 3) dedicated include/exclude folders. 
My aproach is to use the comments functionality where the scanner does not include folders when a special comment is set. 

But it still needs some design. 
I hope you have a little patience here ;-)

**Comment by ghost** [comment]
I prefer a folder setting as in the _Music_ app. Another solution would be a `.nomedia` file in excluded folders as in the _Gallery_ app.
_Comments_ are not a good idea (for many reasons). _Tags_ would be a better choice but this app isn't available in the ownCloud Community Edition.

**Comment by Rello** [comment]
followup in Roadmap;
will be reopened when work is started

**Comment by Rello** [comment]
Feel free to add your opinion to the survery here:
https://help.nextcloud.com/t/help-on-include-exclude-filters-for-file-search/4694

**Comment by Rello** [comment]
1.3 is in final testing and will be released soon
