### ISSUE TITLE
Trying to enable app: index a_artist_id_album_id_idx already exists

### ISSUE THREAD

**Issue by ghost** [Rello/audioplayer#67]
### Expected behavior

Tried to click "Enable" to enable the app
### Actual behavior

Produces the erorr:
An exception occurred while executing 'CREATE UNIQUE INDEX a_artist_id_album_id_idx ON "oc_audioplayer_album_artists" ("artist_id", "album_id")': SQLSTATE[HY000]: General error: 1 index a_artist_id_album_id_idx already exists
### Steps to reproduce the behavior
1. Go to apps/multimedia
2. Click Enable on audio player
### Possible solution

Clear old DB indexes for audio player? I don't know
### Server configuration

**Operating system**: Gentoo

**Web server:**

**Database:**
SQLite

**PHP version:**
5.6.26

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
older ownCloud (8.0.x -> 8.1.x -> 9.0.x -> 9.1.x ) -- but it didn't work before either

**Where did you install Audio Player from:**
The app button

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
yes
### Client configuration

**Operating system:**
gentoo

**Browser:**
chrome
### Log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```

Error   core    An exception occurred while executing 'CREATE UNIQUE INDEX a_artist_id_album_id_idx ON "oc_audioplayer_album_artists" ("artist_id", "album_id")': SQLSTATE[HY000]: General error: 1 index a_artist_id_album_id_idx already exists   2016-10-01T03:59:44+00:00
```

</details>

**Comment by Rello** [comment]
hello,
can you please have a look if you habe oc_audioplayer_\* tables in your database?
As a workaround, delete them and re-enable the app.

let me know if it works

**Comment by ghost** [comment]
Closed due to lack of info.
