### ISSUE TITLE
Documentation for occ commands

### ISSUE THREAD

**Issue by davygravy** [Rello/audioplayer#70]
### Steps to reproduce the behavior

Not applicable.
### Possible solution (optional)

Provide some documentation :) .
### Server configuration

**Operating system**: Linux

**Web server:**
nginx

**Database:**
postgresql

**PHP version:**
5.7

**ownCloud/Nextcloud version:** (see `/status.php`)
"version":"9.1.1.3"

**Updated from an older ownCloud/Nextcloud or fresh install:**
updated

**Where did you install Audio Player from:**
app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
not applicable

**Are you using encryption:** yes/no
no
### Client configuration

**Operating system:**
Linux, OS X El Capitan/Yosemite/others, Windows

**Browser:**
Safari, Chrome, Firefox
### Log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
Insert your ownCloud/Nextcloud log here
```

</details>

**Comment by ghost** [comment]
> Documentation regarding occ commands seems to be not present.

There are no occ commands implemented yet but this feature is on the to-do list. #39
