### ISSUE TITLE
Exclude Folders

### ISSUE THREAD

**Issue by 26op181** [Rello/audioplayer#71]
The ability to exclude folders in the scan function.

**Comment by Rello** [comment]
#39

**Comment by xraMsamohT** [comment]
Duplicate of #66

**Comment by Rello** [comment]
#39

**Comment by Rello** [comment]
Feel free to add your opinion to the survery here:
https://help.nextcloud.com/t/help-on-include-exclude-filters-for-file-search/4694

**Comment by xraMsamohT** [comment]
Duplicate of #66
