### ISSUE TITLE
Scanned audio files not added to library

### ISSUE THREAD

**Issue by Talw3g** [Rello/audioplayer#73]
### Expected behavior

When scanning files, found audio files should be stored in library and available for browsing and playing.
### Actual behavior

File scan does perform, but explicitly doesn't add the files to the library !
[files_scan](https://cloud.githubusercontent.com/assets/12981757/19628186/49a9eaf2-9958-11e6-9538-61b986a8878a.PNG)
### Steps to reproduce the behavior
1. Add some audio files in your owncloud home folder
2. Scan for new files in audioplayer
### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
SQLite

**PHP version:**
php 7.0.8

**ownCloud/Nextcloud version:** (see `/status.php`)
owncloud 9.1.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh install

**Where did you install Audio Player from:**
Owncloud app store

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Yes, local ext4 external HD

**Are you using encryption:** yes/no
no
### Client configuration

**Operating system:**
Windows 10

**Browser:**
Firefox and Chrome
#### ownCloud/Nextcloud log

<details>
<summary>

ownCloud log</summary>

```
[owncloud_log.txt](https://github.com/Rello/audioplayer/files/546519/owncloud_log.txt)
```

</details>

**Comment by JLagrue** [comment]
I get pretty much the same thing. The scan happens, but nothing is found nor added to the library.

Running on Raspbian on a Raspberry Pi

**Comment by peejoox** [comment]
I have the same problem, the songs are found but not added to the library. 
I use a Mac, tried on Safari, Firefox and Chrome, with owncloud 8.2.3 and fresh installation of 9.1.1

**Comment by peejoox** [comment]
After spending the half day with this, my last try was to use MySQL instead of SQLLite!
Now it works! Please, make a hint the installation manual to use MySQL for the owncloud installation.

**Comment by Rello** [comment]
@peejoox thank you very much for not giving up on this. 
Actually it should work with SQLLite and we never got any issues reported until now. 
I will try to setup a test-instance in this combination to evaluate

@JLagrue are you also using SQLite?

**Comment by nicomaha** [comment]
I have the same problem using MySQL!
But in my case everything works fine until I want to scan shared files.
If User A shares files with User B, User B is able to scan the files but they are not added to User B's library.
I'm using nextcloud 10.0.1.

**Comment by Rello** [comment]
@nicohauger @JLagrue can you please check the owncloud.log and post the errors?

**Comment by nicomaha** [comment]
I don't get any errors related to the audioplayer app...
I switched log level to all, logged into the user the files are shared with and scanned the library but I don't get anything in the logfiles...

**Comment by Rello** [comment]
Hello,

I just evaluated with the new 1.3. pre-version and everything workes fine.
I set up a new OC instance on sqlite and did index all files.
I would ask you to retest, once the new version is published. 
I will send you a not here (some time this week)

thank you
