### ISSUE TITLE
first search result row is partially hidden under the top menu

### ISSUE THREAD

**Issue by dassencio** [Rello/audioplayer#74]
### Expected behavior

First search result row is entirely visible.
### Actual behavior

First search result row is partially hidden under the top menu.
### Steps to reproduce the behavior
1. Type a string on the search box which matches the name of one or more songs in the music collection
2. Each matching song name is displayed as a row (to be specific, as a td element of class 'info')
3. The row containing the first song name is partially hidden under the top menu, and the song name itself (a div of class 'name result') appears to be directly touching the ownCloud top menu.
### Possible solution (optional)

Properly align the table containing the search results so that its first row does not partially hide under the top menu.
### Server configuration

**Operating system**:
Linux

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
7.0

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.0

**Updated from an older ownCloud/Nextcloud or fresh install:**
Fresh install

**Where did you install Audio Player from:**
Apps menu (as admin)

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
Yes
### Client configuration

**Operating system:**
Linux

**Browser:**
Firefox and Chrome
#### ownCloud/Nextcloud log

<details>
<summary>

ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
Insert your ownCloud/Nextcloud log here
```

</details>
#### Web server error log (optional)

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Browser log (optional)

<details>
<summary>

Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by dassencio** [comment]
After further investigation, I realized that the search box is not part of the Audio Player, but of ownCloud itself. However, this search box does not seem to properly interact with the Audio Player at all. It would be great if you could improve this, but if not, then just close this issue. Thank you very much!

**Comment by Rello** [comment]
Hello @dassencio 
I just tried to understand the issue. I could not replicate the problem.
could you post a screenshot please?

Even so I am not sure if I can influence it, because the api for handing over search-results is pretty straight forward, I would like to double check.

thank you

**Comment by dassencio** [comment]
Hi @Rello 

Please see the attached screenshot. Take a look at the very first row in the results: do you see that the row is partially hidden by the top menu?

Thank you very much!

![screenshot](https://cloud.githubusercontent.com/assets/4624617/20090210/ffeb0fd2-a58b-11e6-84fa-f6b6dbb82b50.png)

**Comment by Rello** [comment]
I found something strange on #searchresults within result.css of the search functionality.
I need to check if it related to Audio Player stylesheet

**Comment by Rello** [comment]
Issue located.
search result will be shown above album container now
![screen shot 2016-12-03 at 18 42 27](https://cloud.githubusercontent.com/assets/13385119/20861123/51120fcc-b988-11e6-8c97-b995f09061a9.png)
