### ISSUE TITLE
Song's being skipped in m4a format

### ISSUE THREAD

**Issue by jrtoman** [Rello/audioplayer#75]
### Expected behavior

Song should play since the format is listed as compatible.
### Actual behavior

Audio playr moves onto the next song and starts playing the first non m4a file format.
### Steps to reproduce the behavior
1. Upload a m4a song
2. Try to play it
3. 
### Possible solution (optional)

No Idea
### Server configuration

**Operating system**:
Ubuntu Server 16.04

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 10.0.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
Nextcloud 9

**Where did you install Audio Player from:**
Github

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
Https
### Client configuration

**Operating system:**
windows 7/android

**Browser:**
chrome
#### ownCloud/Nextcloud log

<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>

```
Insert your ownCloud/Nextcloud log here
```

</details>

#### Web server error log (optional)

<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```

</details>

#### Browser log (optional)

<details>
<summary>Browser log</summary>

```
Insert your browser log here
```

</details>

**Comment by Rello** [comment]
Hello,
You dont use an SMB connection, correct? Because these can cause issues. 

I have this issue myself when acessing OC via http and not https - but OC is expecting the last one

What are you using?

**Comment by xraMsamohT** [comment]
@Rello 
> **Are you using encryption:** yes/no
> Https

**Comment by Rello** [comment]
Yes. Correct. 
Please check if the browser is actually connected via https;
Also, is there a valis certificate in place?

**Comment by jrtoman** [comment]
No encryption

**Comment by jrtoman** [comment]
I am connected via https, with a self-generated https certificate. All songs play fine besides for the given format.

**Comment by Rello** [comment]
Hello @jrtoman 
sorry for the late reply. something is strange there.
please try the following: in the album view right-click on a m4a song and choose "open in new tab"

this will generate the core-streaming url with is being processed by your browser. something like
`https://server/owncloud/apps/audioplayer/getaudiostream?file=%2Ftest%2Ftestsong.mp3`

I hope your browser will tell you more details why it is not playing the format.
try one m4a and one mp3

**Comment by jrtoman** [comment]
No dice, it will not play and has the play button greyed out

**Comment by Rello** [comment]
Hello @jrtoman 
can you copy-paste a generated link like mine for verification that the syntax is correct?
`https://server/owncloud/apps/audioplayer/getaudiostream?file=%2Ftest%2Ftestsong.mp3`

If you don´t see anything in the logs - neither nextcloud.log or nginx or php - there seems to be an issue with the browser I can only imagine.
did you try another browser already?

**Comment by jrtoman** [comment]
I tried both chrome and firefox thus far

https://myserver.com/apps/audioplayer/getaudiostream?file=%2FMusic%2FAdele%2F25%2F02%20Send%20My%20Love%20%28To%20Your%20New%20Lover%29.m4a

**Comment by jrtoman** [comment]
Jut noticed that in firefox when I tab opene a song it says it can’t play the video because it is corrupt, but its’ audio only and plays fine when downloaded to a media player

**Comment by Rello** [comment]
Can you send the file to 
audioplayer "at" scherello "dot" de

**Comment by Rello** [comment]
Hello,
thank you for submitting the file.
the issue is with the fileencoding itself.
I could play it in Safari - Firefox complains with "cant be decoded".
Perhaps its related to the`ALAC (Apple Lossless Audio Codec)`which is used.

its definitely a file or browser issue on your side because Audio Player only "transmits" the file and the playing is done 1:1 by the HTML5 API in the frontend.

**Comment by seonghobae** [comment]
Huh, I experiencing like this issue with encoded with ALAC, I can not play them on Ubuntu Linux + Chrome.

**Comment by Rello** [comment]
hello
when it is skipped, the browser can not play this format.
did you try another one?

**Comment by r4sas** [comment]
ALAC is not supported by browsers by default.
You can check that by trying open that audio file in browser from local storage.
