### ISSUE TITLE
Limit Scan To Directory

### ISSUE THREAD

**Issue by thomaskonrad** [Rello/audioplayer#76]
Hi,

I have my music collection inside a directory called "Music" in my ownCloud account. Now I would like Audio Player to scan for music only inside that directory. Is that possible?

Thanks
Thomas

**Comment by xraMsamohT** [comment]
Duplicate of #66 
See #39

**Comment by Rello** [comment]
Feel free to add your opinion to the survery here:
https://help.nextcloud.com/t/help-on-include-exclude-filters-for-file-search/4694

**Comment by xraMsamohT** [comment]
Duplicate of #66
