### ISSUE TITLE
scanning often interrupted

### ISSUE THREAD

**Issue by sbr9150** [Rello/audioplayer#8]
When scan for audio files, often stop scanning after some files.
oc:9.0.2
php:7.0.4-7ubuntu2.1
mysql:5.7.12
owncloud log:
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE`oc_audios_albums`SET`year`= ?,`genre_id`= ? WHERE`id`= ? AND`user_id`= ?' with params ["", "4", "2340", "sbr"]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'year' at row 1
0. /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 116: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
1. /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 174: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE`oc_audi...', Array)
2. /var/www/html/owncloud/lib/private/db/statementwrapper.php - line 73:Doctrine\DBAL\Statement->execute(Array)
3. /var/www/html/owncloud/apps/audios/controller/scannercontroller.php - line 626:OC_DB_StatementWrapper->execute(Array)
4. /var/www/html/owncloud/apps/audios/controller/scannercontroller.php - line 494:OCA\Audios\Controller\ScannerController->writeAlbumToDB('Unplugged and O...', '', '4')
5. [internal function] OCA\Audios\Controller\ScannerController->scanForAudios()
6. /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php - line 159:call_user_func_array(Array, Array)
7. /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php - line 89:OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Audios\Controller\ScannerController), 'scanForAudios')
8. /var/www/html/owncloud/lib/private/appframework/app.php - line 110:OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Audios\Controller\ScannerController), 'scanForAudios')
9. /var/www/html/owncloud/lib/private/appframework/routing/routeactionhandler.php- line 45: OC\AppFramework\App main('ScannerControll...', 'scanForAudios', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
10. [internal function] OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
11. /var/www/html/owncloud/lib/private/route/router.php - line`

**Comment by Rello** [comment]
Hello,
are you using the current version here from git?

it says `Incorrect integer value: '' for column 'year'`
can you check the file with itunes if the year is maintained? I think we need to handle some exceptions here

**Comment by sbr9150** [comment]
I follow the readme to install this 1.3 version.
I had checked mp3 id tag, there are numbers in the year field.

**Comment by Rello** [comment]
I will have a look tomorrow. 
Yesterday i found an issue with the code using wrong getID3 libraries

**Comment by Rello** [comment]
Hello,
are you using NGINX by chance?

I found an issue with the fastcgi-timeout.
fastcgi_read_timeout of 120 (in my case) is too little for a big DB.
I implemented an error-handling & debug-logging & restart-ability.

Can you get the new /controller/scannercontroller.php and see what happens - and provide the log when it happens?

Commit: [b930b47](https://github.com/z000ao8q/audios2/commit/b930b4766788d439f75e45a6d944f9ab2f88dd0e)

**Comment by sbr9150** [comment]
Hi,
I use apache2.
Using new scannercontroller.php can scan audio files continuously from 0% to 100%. I think the problem is solved.
A question, I can scan flac files, but cannot play flac files. Any suggestion?

**Comment by Rello** [comment]
this will not work due to the used soundmanager2 js library.
perhaps we can look at others later - when we got this version working at least.

I corrected the filter to the supported files. FLAC should not be selected anymore
`$audios_mp3 = $userView->searchByMime('audio/mpeg');
        $audios_m4a = $userView->searchByMime('audio/mp4');
        $audios_ogg = $userView->searchByMime('audio/ogg');
        $audios_wav = $userView->searchByMime('audio/wav');`

**Comment by Rello** [comment]
would you have time to support me with the testing of the new - rebranded version?
https://github.com/z000ao8q/audios/tree/rebranding

it should be possible to run it in parallel to the old one - but disabling the old version might be on the save side.

let me know & thank you!
