### ISSUE TITLE
Turn auto-play-next-song off

### ISSUE THREAD

**Issue by coco65** [Rello/audioplayer#81]
### Expected behavior
Audio player halts playing after a song is over.

### Actual behavior
The payer automatically plays the next song in the album.

### Steps to reproduce the behavior
1. Play a song in an album with more then 1 song
2. wait until the song is over.

### Possible solution (optional)
a. An option in a configuration screen to turn auto-play-next-song on or off
b. Or a boolean in the source code that can easily tweaked, like
auto-play-next-song == true;

**Comment by Rello** [comment]
Hello,
thank you for the feedback.
I put it on the Roadmap already
https://github.com/Rello/audioplayer/issues/39

I will close this issue for the moment. when it is being developed, it will be reopened.

thank you
