### ISSUE TITLE
Ability to scan specific folder

### ISSUE THREAD

**Issue by Tomatoly** [Rello/audioplayer#82]
### Expected behavior
It would be nice to select a specific folder to scan for music or to exclude folders from scanning.

### Actual behavior
All folders are scanned for music.

### Steps to reproduce the behavior
1. Start a scan.
2. Watch the result when finished. All music files have been added to the library.

### Possible solution (optional)
a) Add a settings dialog where a user can either add specific folders or exclude specific folders for scanning.
b) Add a command line setting via occ for configuring which folders to include or exclude.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
sqlite (I think)

**PHP version:**

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.1

**Updated from an older ownCloud/Nextcloud or fresh install:**

**Where did you install Audio Player from:**
Ownclouds Administrator App widget

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Yes, local

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Windows 8.1

**Browser:**
Firefox

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by Tomatoly** [comment]
This is not a bug I just did not figure out how to make a feature request. I just found this owncloud app and I like it :)

**Comment by xraMsamohT** [comment]
Duplicate of #66 #71 #79

**Comment by xraMsamohT** [comment]
Duplicate of #66
