### ISSUE TITLE
Ampache backend support

### ISSUE THREAD

**Issue by HLFH** [Rello/audioplayer#83]
Hi,

I would love Ampache backend support so I would be able to use audioplayer with my smartphone easily.

**Comment by xraMsamohT** [comment]
Duplicate of #51

**Comment by HLFH** [comment]
@xraMsamohT

So, audioplayer is useless to at least 25% of the OC/NC users. I'll use Plex.

**Comment by Rello** [comment]
Hello @HLFH 
we are happy to take any knowledgeable support to develop this kind of backend.
It should not be developed into AP - but as an add-on for the app. So a perfect place for several developers to contribute.

and with many thousand users, AP does not seem that useless :-)

**Comment by ghost** [comment]
@HLFH If Audio Player is useful for up to 75% of *cloud users, we have achieved more than we had imagined or dreamed three months ago.

I agree with @Rello. Some features that a significant minority needs should be developed as an add-on rather than as part of the app.

**Comment by HLFH** [comment]
@xraMsamohT @Rello I hope so. You are the perfect app to listen to music on *cloud. I'm just frustrated we don't have since the beginning of *cloud a fully working music app. Ok. I'm noting that AP will gratefully accept an Ampache add-on if someone of the *cloud community has done it. Still, Ampache backend was one of the main features within the outdated *cloud Music app. I understand your dream team has a different strategy and I accept it :) Thank you for the nice answer and have a good continuation!

**Comment by michaelarlt** [comment]
Why you Guys not just using the plugin puplished over there?
https://github.com/owncloud/music/releases
it is an open plugin for owncloud and the far better nextcloud. This plugin is working flawlessly for me on my nextcloud server.

**Comment by HLFH** [comment]
@michaelarlt Are you kidding? https://github.com/owncloud/music/issues/90 

It has been 4 years that the ownCloud Music plugin does not work.

**Comment by Rello** [comment]
Hello,
There is no 'just'. It required deep integration into the backend and DB tables of AP. 

As mentioned: it will not happen within AP due to flexibility and maintainability. 

As mentioned: it would be the perfect showcase to implement a separate and clean Ampache App which connects to AP. 

if anyone with the dev knowledge could help with his own app, it would be great. 
Or put up a bugbounty to find one. 

For AP, onlinestreams or flac are much higher valued on the roadmap....

**Comment by xraMsamohT** [comment]
Duplicate of #51
