### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by PatrickePatate** [Rello/audioplayer#84]
The volume control button not working, when I click on it, nothing happens ..

Only #volume appears in the URL !

**Comment by ghost** [comment]
Thanks for reporting this issue! Please fill in the [issue template](https://github.com/rello/audioplayer/blob/master/.github/ISSUE_TEMPLATE.md) as complete as possible.

**Comment by coco65** [comment]
It works fine for me on Chrome and Edge. Just a visual thing: on Edge the first corner of the volume triangle stays blank when choosing 100% volume. See image
![volume](https://cloud.githubusercontent.com/assets/23413188/20296043/eab89c7e-ab08-11e6-82d4-f551346112a1.png)

**Comment by ghost** [comment]
Closed due to lack of info.
