### ISSUE TITLE
Cannot edit album title (because of ?)

### ISSUE THREAD

**Issue by himbeere** [Rello/audioplayer#87]
Hello.

First thanks for your work.

Here is my litte problem with version 1.3.0. 

I'm using nextcloud 10.0.1, php 7.0.13. Whenever i try to edit a albums title which has a "?" currently i get no response from audioplayer. Any idea what the reason could be?

![bildschirmfoto 2016-11-16 um 13 47 19](https://cloud.githubusercontent.com/assets/631865/20347931/9182c304-ac03-11e6-8600-39c421b5a6c0.png)

thanks and cheers

**Comment by Rello** [comment]
Hello,
Does the Album have a "?" In there originally?
Or is it a result of a unicode issue in the scanner and you try to correct it?

**Comment by ghost** [comment]
Hi Rello.

Thanks for your answer. The album does not have a question mark init. Here is how it looks like.

misc_music # mp3info 03\ -\ Men\ From\ The\ Nile\ -\ Watch\ Theme\ Come.mp3 
File: 03 - Men From The Nile - Watch Theme Come.mp3
Title:   Watch Theme Come               Track: 3
Artist:  Men From The Nile
Album:                                  Year:  
Comment:                                Genre:  [255]
misc_music #

**Comment by Rello** [comment]
hello @himbeere 
can you please send the file via mail to `audioplayer "at" scherello "dot" de`

**Comment by ghost** [comment]
Uah. That was quick. 1.3.1 works for me. Thanks. :-)

**Comment by ghost** [comment]
I guess i was to quick. Problem is still here. Seems the file audioplayer was able to adjust with 1.3.1 was the only one.

**Comment by ghost** [comment]
@himbeere v1.3.1 is a bugfix regarding PostgreSQL. ;-)

**Comment by Rello** [comment]
...file is being analyzed offline. Update will be posted...

**Comment by Rello** [comment]
Hello @himbeere 
your file has a wrong encoding (UTF-16), indicated by the characters %FF%FE in the Album.
this is not supposed to be the case and is creating complications.

please correct your file outside AP with a standard player/ID3 editor. then everything will work as normal.
As this is a very special case, a special handling is difficult within AP.

let me know if it worked...

**Comment by Rello** [comment]
...feel free to test the attached commit. it should make  the standard scanner working
