### ISSUE TITLE
Better display of albums with multiple discs

### ISSUE THREAD

**Issue by arnoldsuperstar** [Rello/audioplayer#88]
When displaying the tracks of an album, the disc number should also be considered. It should be displayed as follows, for instance:

Disc #1
-- Track #1
-- Track #2
-- Track #3
-- Track #4
Disc #2
-- Track #1
-- Track #2
-- Track #3

Currently, it will be displayed as follows:
-- Track #1
-- Track #1
-- Track #2
-- Track #2
-- Track #3
-- Track #3
-- Track #4

**Comment by Rello** [comment]
Thank you for the suggestion. 
We will have a look at the possibilities and release planning

**Comment by Rello** [comment]
#186
