### ISSUE TITLE
Problem with one of two wav files (does not play an ADPCM wav file)

### ISSUE THREAD

**Issue by Wikinaut** [Rello/audioplayer#89]
I have two wav files, one is less than 00:02 seconds and plays, the other file shows 00:16 and cannot be played.

What can be wrong here ?

**Comment by ghost** [comment]
These are very little information to help you. No info about your environment, **Audio Player version**, browser, and file. For such problems we created the issue template. ;-)

Can you post a link to the file?

**Comment by Wikinaut** [comment]
current up-to-date versions:
ja, ja...
- Nextcloud 10.0.1 (stable)
- Server debian 8 Jessie
- Audio Player 1.3.0
- Client: Firefox ESR 45.5.0 = (current debian version of today)

**Comment by Wikinaut** [comment]
I cannot post a link, because the file is a recording of a private telephone call.

**Comment by ghost** [comment]
For example, the codecs PCM S16 LE and PCM ALAW are supported. We can not guarantee that Audio Player supports all codecs with all sampling frequencies and bit rates.

Do the two files have different codecs?

**Comment by Wikinaut** [comment]
@xraMsamohT I will check this with mediainfo very soon.

Just another positive thing: the player is nice. Much better than what was available before. However, I would also suggest a "light" plugin which plays directly from the files list (in directory view), perhaps I will submit a PR.

**Comment by Wikinaut** [comment]
#### Not playing:

```
General                                                                                                                                                                                                            
Complete name                            : 10.06.16_17.42_Anruf Tanni.wav                                                                                                                               
Format                                   : Wave                                                                                                                                                                    
File size                                : 125 KiB                                                                                                                                                                 
Duration                                 : 15s 968ms                                                                                                                                                               
Overall bit rate mode                    : Constant                                                                                                                                                                
Overall bit rate                         : 64.0 Kbps                                                                                                                                                               

Audio                                                                                                                                                                                                              
Format                                   : ADPCM                                                                                                                                                                   
Format profile                           : A-Law                                                                                                                                                                   
Codec ID                                 : 6                                                                                                                                                                       
Codec ID/Hint                            : CCITT
Duration                                 : 15s 968ms
Bit rate mode                            : Constant
Bit rate                                 : 64.0 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 8 000 Hz
Bit depth                                : 8 bits
Stream size                              : 125 KiB (100%)
```

#### Playing:

```
General
Complete name                            : sure.wav
Format                                   : Wave
File size                                : 16.9 KiB
Duration                                 : 1s 555ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 88.8 Kbps
Writing application                      : Cool Edit v.1.31 by David Johnston

Audio
Format                                   : PCM
Format settings, Endianness              : Little
Format settings, Sign                    : Unsigned
Codec ID                                 : 1
Duration                                 : 1s 555ms
Bit rate mode                            : Constant
Bit rate                                 : 88.2 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 11.025 KHz
Bit depth                                : 8 bits
Stream size                              : 16.7 KiB (99%)
```

**Comment by Wikinaut** [comment]
Why not simply tagging wav files between `<audio> </audio>`  tags and playing in the browser ?

**Comment by Rello** [comment]
Hello @Wikinaut 

> However, I would also suggest a "light" plugin which plays directly from the files list (in directory view), perhaps I will submit a PR.

actually this one-click-play is available. after your issue we found a bug. if you try for the other formats like mp3 you will be able to play directly from the files browser. if you need this urgently, feel free to manually apply this tweak:
https://github.com/Rello/audioplayer/commit/63a9ba903ff1ec44d20aaca786b3b7cc7890b7f4

**Comment by Rello** [comment]
regarding your issue with the audio files, mozilla states that firefox can only play PCM wav files.
other formats - like your subformat ADPCM - seem not to be supported.
so its an firefox - not an AP issue

https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox

**Comment by Wikinaut** [comment]
I will check this too (I have a test suite for different file types). Later I will send you my jquery code (simple and efficient), which renders audio items on a page into `<audio>` tags, and adds the HTML5 player handles.

The one-click play you mentioned above is not active for me! (What can be the reason?) My browser offers to download the file, or to open a target program with it, this is what I call the "download" link.
I want to have a button or so, which when clicked, starts the HTML5 player.

**Comment by Rello** [comment]
Hello,
when you click on a supported file, the playback will start immediately.
a supported file is indicated by the play link on the options for the file (3-dot icon).
it will then look like that:
https://github.com/rello/screenshots/blob/master/audioplayer_actions.png

but as mentioned: I works for all but wav due to the bug mentioned. if you want to tweak your local code as mentioned above, then you can enable it also for WAV

**Comment by Wikinaut** [comment]
@Rello okay, now I see it. This is a bad GUI, when you "hide" the "Abspielen" in the file settings. I will come forward with a better solution. (Click onto file name should start playing, and/or a play triangle should be shown in the lower corner of the icon, whereas the "..." setting should then offer "download").

BTW, there is no handle to stop the player then.

**Comment by Wikinaut** [comment]
@Rello I confirm, that Firefox cannot play my ADPCM "wav" file, I double checked it here.

**Comment by Rello** [comment]
hey,
please try with an mp3. clicking on a file directly WILL start playing and a speaker icon will be overlayed to the icon
![screen shot 2016-11-17 at 19 40 55](https://cloud.githubusercontent.com/assets/13385119/20402649/ccde4a54-acfd-11e6-8ca4-e5dee94eccd3.png)

**Comment by Wikinaut** [comment]
I confirm that https://github.com/Rello/audioplayer/commit/63a9ba903ff1ec44d20aaca786b3b7cc7890b7f4 is at least an improvement, as it adds the "Abspielen" link for "wav" files !

**Comment by Wikinaut** [comment]
Arrrgh, on the SECOND click, baaaaah

**Comment by Wikinaut** [comment]
bad GUI

**Comment by Wikinaut** [comment]
I expect audio files playing on the first click. Double click: download !!

[updated]
Like with images, the first click already opens the image [media].

**Comment by Wikinaut** [comment]
and, how is playing be stopped ????

**Comment by Wikinaut** [comment]
@Rello here is my test code, you need only to add some audio files into /audio subdirectory

https://piratenpad.de/p/html5-audio

**Comment by Wikinaut** [comment]
How can I stop the audio player once it is fired ?

**Comment by Rello** [comment]
Click again and it is stopped. 

The player is based on the soundmanager2 plugin to ensure crossbrowser support and features like scrolling. 

...happy to get a PR with a better suggestion. But take care of the challenges with remote & encrypted files.

**Comment by Wikinaut** [comment]
@Rello click toggle, okay. ty. [Note to myself: To do: Add handle and a slider]
