### ISSUE TITLE
Upgrading to 1.3.0 breaks AudioPlayer (postgresql)

### ISSUE THREAD

**Issue by davygravy** [Rello/audioplayer#90]
### Expected behavior
When upgrading from 1.2.x to 1.3.0, user should be able to see albums, or to rescan perhaps, and then see the albums.

### Actual behavior
When upgrading from 1.2.x to 1.3.0, I can longer see albums my albums.   Rescanning seems to have no effect, scanning for media seems to not occur after pressing button.  Setting the media folder also seems to have no effect.   Deleting the music database has no apparent effect, either.

### Steps to reproduce the behavior
1.   Update the app from 1.2.2 (or the most recent version) to 1.3.0.
2.   Either leave the media folder undefined, or set it to the music folder.
3.   Notice that there are no longer any albums or music of any kind visible, in any view.
4.   Restarting either the webserver or the hardware has no effect.
5.   Scanning for media from the occ command-line interface has no effect, but registers an error.

### Possible solution (optional)
1.   Downgrade to 1.2.2 manually does renable function.  This is not really a solution.

### Server configuration
**Operating system**:
Debian Linux Stretch on 64-bit Atom

**Web server:**
nginx

**Database:**
postgresql

**PHP version:**
php 7.0

**ownCloud/Nextcloud version:** (see `/status.php`)
9.1.1.3

**Updated from an older ownCloud/Nextcloud or fresh install:**
Updated

**Where did you install Audio Player from:**
AppStore

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
No

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Linux, OS X, Windows

**Browser:**
Chrome, Safari, Firefox

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'select fileid from \"oc_filecache\" where parent in (SELECT parent FROM \"oc_filecache\" WHERE \"name\" = \".noAudio\" or \"name\" = \".noaudio\" ORDER BY \"fileid\" ASC)':\n\nSQLSTATE[42703]: Undefined column: 7 ERROR: column \".noAudio\" does not exist\nLINE 1: ...(SELECT parent FROM \"oc_filecache\" WHERE \"name\" = \".noAudio\"...\n ^","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'select fileid f...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/legacy\/db\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \/var\/www\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(891): OC_DB_StatementWrapper->execute()\n#4 \/var\/www\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(523): OCA\\audioplayer\\Controller\\ScannerController->getAudioObjects(NULL, NULL)\n#5 [internal function]: OCA\\audioplayer\\Controller\\ScannerController->scanForAudios(NULL, NULL, NULL)\n#6 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#8 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#9 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('OCA\\\\audioplayer...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/audioplay...')\n#13 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":72}	2016-11-16T06:48:16-06:00
Error	index	Exception: {"Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Message":"An exception occurred while executing 'select fileid from \"oc_filecache\" where parent in (SELECT parent FROM \"oc_filecache\" WHERE \"name\" = \".noAudio\" or \"name\" = \".noaudio\" ORDER BY \"fileid\" ASC)':\n\nSQLSTATE[42703]: Undefined column: 7 ERROR: column \".noAudio\" does not exist\nLINE 1: ...(SELECT parent FROM \"oc_filecache\" WHERE \"name\" = \".noAudio\"...\n ^","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'select fileid f...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/legacy\/db\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \/var\/www\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(891): OC_DB_StatementWrapper->execute()\n#4 \/var\/www\/owncloud\/apps\/audioplayer\/controller\/scannercontroller.php(523): OCA\\audioplayer\\Controller\\ScannerController->getAudioObjects(NULL, NULL)\n#5 [internal function]: OCA\\audioplayer\\Controller\\ScannerController->scanForAudios(NULL, NULL, NULL)\n#6 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#8 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\audioplayer\\Controller\\ScannerController), 'scanForAudios')\n#9 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('OCA\\\\audioplayer...', 'scanForAudios', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/audioplay...')\n#13 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":72}
Insert your ownCloud/Nextcloud log here
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
No errors

Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by davygravy** [comment]
Below is the output that is produced, showing an error when attempting to use the occ CLI to rescan the the music/audio database.  I am confident that this is related closely to the errors with the web interface functionality in AudioPlayer.

---

```
sudo -u www-data php occ audioplayer:scan adminuser

Start scan for adminuser

[Doctrine\DBAL\Exception\InvalidFieldNameException]
An exception occurred while executing 'select fileid from "oc_filecache" where parent in (SELECT parent FROM "oc_filecache" WHERE "name" = ".noAudio" or "name" = ".noaudio" ORDER BY "fileid" ASC)':
SQLSTATE[42703]: Undefined column: 7 ERROR:  column ".noAudio" does not exist
LINE 1: ...(SELECT parent FROM "oc_filecache" WHERE "name" = ".noAudio"...

[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[42703]: Undefined column: 7 ERROR:  column ".noAudio" does not exist
LINE 1: ...(SELECT parent FROM "oc_filecache" WHERE "name" = ".noAudio"...

[PDOException]
SQLSTATE[42703]: Undefined column: 7 ERROR:  column ".noAudio" does not exist
LINE 1: ...(SELECT parent FROM "oc_filecache" WHERE "name" = ".noAudio"...
```

**Comment by Rello** [comment]
Hello @davygravy ,
would you be able to test the fix on short notice https://github.com/Rello/audioplayer/commit/9fdda5f5e0780fd7eea04c191ab9a3cc58e6b0be by modifying the scannercontroller locally?

I had a typo with " and ' in the SQL statement. MySQL, MariaDB, SQLite did not complain but it was a valid finding.

thank you

**Comment by davygravy** [comment]
Confirming the patch works as expected, and in addition 1.3.1 from the appstore works as expected.

Thank you, Rello!
