### ISSUE TITLE
OCC commands don't work after update (php)

### ISSUE THREAD

**Issue by nicomaha** [Rello/audioplayer#91]
### Expected behavior
executing occ commands for nextcloud should work

### Actual behavior
error message
```
(uiserver):****:~/cloud$ php5.4-cli occ list
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /****/htdocs/cloud/apps/audioplayer/appinfo/register_command.php on line 30     
```  

### Steps to reproduce the behavior
1. update to audioplayer 1.3.0
2. enable app
3. try to run occ command

### Server configuration
**Operating system**:

**Web server:**

**Database:**
MySQL5.5.52

**PHP version:**
7.0.12

**ownCloud/Nextcloud version:** (see `/status.php`)
Nextcloud 10.0.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
Updated version

**Where did you install Audio Player from:**
github & appstore

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
no

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
OSX

**Browser:**
latest Chrome & Safari

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' at /****/htdocs/cloud/apps/audioplayer/appinfo/register_command.php#30
```
</details>

**Comment by Rello** [comment]
Hello @nicohauger 
i am confused regarding your php-versions.
you say you are using 7.0.12 - but your command-line shows the 5.4 version of the CLI.
is this on purpose?

AP is tested on current php and is working.
what does `php -v` give you

**Comment by nicomaha** [comment]
In my current hosting environment I can only use php5.4 via ssh...
If I use php -v I get PHP 4.4.9 :-O Don't know why!
If you think that's related to the problem, I'll check this with my hosting provider!

**Comment by nicomaha** [comment]
Problem solved! Using PHP5.5 was the solution!
