### ISSUE TITLE
occ audioplayer:scan unknown_user

### ISSUE THREAD

**Issue by eplusk** [Rello/audioplayer#93]
`root@ncserver:~# sudo -u www-data php /var/www/nextcloud/occ audioplayer:scan klaus`
Wrong user-name   klaus --> Klaus

### Expected behavior
 telling: unknown user,

### Actual behavior
 audioplayer tries to find the music and installed in nextcloud/data the default directories and the default files for the wrong user klaus

### Possible solution (optional)
first check if known user

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-1029-raspi2 armv7l)

**Web server:**
nginx_1.11.5-1~xenial_armhf

**Database:**
mariadb

**PHP version:**
php7.0

**ownCloud/Nextcloud version:** (see `/status.php`)
nextcloud 10.0.1

**Updated from an older ownCloud/Nextcloud or fresh install:**
fresh install

**Where did you install Audio Player from:**
audioplayer-1.3.0.tar.gz with wget 

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
yes local , system mounted CIFS filesystem

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
Kubuntu 16.4 LTS

**Browser:**
Firefox 50.0

**Comment by Rello** [comment]
a check for an existing user is missing 
`$this->userManager->userExists($user)`

**Comment by eplusk** [comment]
### Test after occ audioplayer:scan unknown_user and validate if user actually exists #93


**I manually included the patch and tested the occ audioplayer:scan**

```
root@ncserver:~# sudo -u www-data php /var/www/nextcloud/occ audioplayer:scan klaus --debug
Start scan for klaus
Scanned Folder: /klaus/files
Total audio files: 0
Checking all files whether they can be skipped
Final audio files to be processed: 0
Start processing of ID3s
Audios found: 0
Duplicates found: 0
Written to music library: 0
Albums found: 0
Errors: 0
root@ncserver:~# ll /var/nc_data/
total 700
drwxrwx--- 11 www-data www-data   4096 Nov 25 12:25 ./
drwxr-xr-x 15 root     root       4096 Oct 27 21:55 ../
drwxr-xr-x  2 www-data www-data   4096 Oct 28 17:10 files_external/
-rw-r--r--  1 root     www-data    284 Oct 28 14:24 .htaccess
-rw-r--r--  1 www-data www-data      0 Oct 28 14:24 index.html
drwxr-xr-x  3 www-data www-data   4096 Nov 25 12:25 klaus/
drwxr-xr-x  7 www-data www-data   4096 Nov 17 21:01 Klaus/
drwxr-xr-x  6 www-data www-data   4096 Nov 10 20:44 ncadmin/
-rw-r-----  1 www-data www-data 499139 Nov 24 21:23 nextcloud.log
-rw-r--r--  1 www-data www-data      0 Oct 28 14:24 .ocdata
-rw-r--r--  1 www-data www-data 162112 Nov  1 11:16 themedbackgroundlogo
```

**It seemes the error has not disappeared.**

**Then I tried to delete the wrong user**

`root@ncserver:~# sudo -u www-data php /var/www/nextcloud/occ user:delete klaus`
The specified user was deleted

```
root@ncserver:~# ll /var/nc_data/
total 696
drwxrwx--- 10 www-data www-data   4096 Nov 25 12:27 ./
drwxr-xr-x 15 root     root       4096 Oct 27 21:55 ../
drwxr-xr-x  2 www-data www-data   4096 Oct 28 17:10 files_external/
-rw-r--r--  1 root     www-data    284 Oct 28 14:24 .htaccess
-rw-r--r--  1 www-data www-data      0 Oct 28 14:24 index.html
drwxr-xr-x  3 www-data www-data   4096 Nov 25 12:25 klaus/
drwxr-xr-x  6 www-data www-data   4096 Nov 10 20:44 ncadmin/
-rw-r-----  1 www-data www-data 499139 Nov 24 21:23 nextcloud.log
-rw-r--r--  1 www-data www-data      0 Oct 28 14:24 .ocdata
-rw-r--r--  1 www-data www-data 162112 Nov  1 11:16 themedbackgroundlogo

```
**Again I tried to delete the non-existent user**
 
`root@ncserver:~# sudo -u www-data php /var/www/nextcloud/occ user:delete klaus`
User does not exist

**The default directories and the default files for the non-existent user klaus are in Nextcloud Data-directory.**
**But the real user Klaus and his data vanished.!!**

### Second test: really unknown user

`root@ncserver:~# sudo -u www-data php /var/www/nextcloud/occ audioplayer:scan blabla --debug`
Unknown user blabla

**Validation if user actually exists #93 was successful.**

### Conclusion: This new error looks like not distinguishing between Klaus and klaus and klauS.
**I think its an server problem, not an audioplayer problem.**

**Comment by ghost** [comment]
>  But the real user Klaus and his data vanished.!!

Because user **klaus** did not exist, **Klaus** was deleted. That's a bug in server, imo.

_"Login names may contain letters (a-z, A-Z), numbers (0-9), dashes (-), underscores (_), periods (.) and at signs (@)."_ ([Source](https://docs.nextcloud.com/server/11/admin_manual/configuration_user/user_configuration.html)) – No info about case sensitivity.

**Comment by Rello** [comment]
Issue for "userExists($user) not case sensitive"
https://github.com/owncloud/core/issues/26727

**Comment by Rello** [comment]
background: 
the creation of a folder for a mistyped user was introduced here
https://github.com/nextcloud/server/commit/fb88d668575562407edcaf392ec6f771cba55dba
