### ISSUE TITLE
Added translation for ukrainian language

### ISSUE THREAD

**Issue by BODYA7979** [Rello/audioplayer#94]
I did a translation to Ukrainian language. Simply unpack this files to l10n folder.
[l10n.zip](https://github.com/Rello/audioplayer/files/614849/l10n.zip)

**Comment by Rello** [comment]
Hello @BODYA7979 
thank you for your support. they will be included with the next release

**Comment by Rello** [comment]
@BODYA7979 
could I ask you for Input on the newly added language parts?
there are additions in the json an in the js were I would appreciate your help.

https://github.com/Rello/audioplayer/tree/1.4/l10n

thank you

**Comment by BODYA7979** [comment]
@Rello 
Sure,
https://github.com/Rello/audioplayer/compare/1.4...BODYA7979:patch-1
https://github.com/Rello/audioplayer/compare/1.4...BODYA7979:patch-2

**Comment by Rello** [comment]
@BODYA7979 
merged. thank you!!!

**Comment by ghost** [comment]
@BODYA7979 May we ask again to complete **and** correct both files? We have changed some strings due to code changes. Thanks in advance!

**Comment by BODYA7979** [comment]
@xraMsamohT, @Rello here updated translations https://github.com/Rello/audioplayer/pull/195
